package py.com.excelsis.sicca.seguridad.entity;

// Generated 14-sep-2011 13:12:06 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Properties;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.EntityBase;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * Funcion generated by hbm2java
 */
@Entity
@Table(name = "funcion", schema = "seguridad")
public class Funcion extends EntityBase {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2588244215916336493L;
	private Long idFuncion;
	private String descripcion;
	private String url;
	private String modulo;
	private Boolean adjuntable;
	private Set<RolFuncion> rolFuncions = new HashSet<RolFuncion>(0);

	public Funcion() {
	}

	public Funcion(Long idFuncion, String descripcion, String url) {
		this.idFuncion = idFuncion;
		this.descripcion = descripcion;
		this.url = url;
	}

	public Funcion(Long idFuncion, String descripcion, String url,
			Set<RolFuncion> rolFuncions) {
		this.idFuncion = idFuncion;
		this.descripcion = descripcion;
		this.url = url;
		this.rolFuncions = rolFuncions;
	}

	@Id
	@GeneratedValue(generator="FUNCION_GENERATOR")
	@SequenceGenerator(name="FUNCION_GENERATOR",sequenceName="seguridad.funcion_id_funcion_seq")
	@Column(name = "id_funcion", unique = true, nullable = false)
	public Long getIdFuncion() {
		return this.idFuncion;
	}

	public void setIdFuncion(Long idFuncion) {
		this.idFuncion = idFuncion;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "url", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcion")
	public Set<RolFuncion> getRolFuncions() {
		return this.rolFuncions;
	}

	public void setRolFuncions(Set<RolFuncion> rolFuncions) {
		this.rolFuncions = rolFuncions;
	}

	@Column(name = "modulo", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getModulo() {
		return modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}
	
	
	@Column(name = "adjuntable")
	public Boolean getAdjuntable() {
		return adjuntable;
	}

	public void setAdjuntable(Boolean adjuntable) {
		this.adjuntable = adjuntable;
	}

	@Transient
	public Long getId() {
		return idFuncion;
	}

	/**
	 * 
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.FUNCION_ID, getId());
		properties.put(SICCASessionParameters.FUNCION_DESCRIPCION,
				descripcion);

		return properties;
	}

	/**
	 * 
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}


}
