package py.com.excelsis.sicca.seguridad.entity;

// Generated 14-sep-2011 13:12:06 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "usuario_rol", schema = "seguridad")
public class UsuarioRol implements java.io.Serializable {

	private Long idUsuarioRol;
	private Rol rol;
	private Usuario usuario;

	public UsuarioRol() {
	}

	public UsuarioRol(Long idUsuarioRol, Rol rol, Usuario usuario) {
		this.idUsuarioRol = idUsuarioRol;
		this.rol = rol;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(generator="USUARIO_ROL_GENERATOR")
	@SequenceGenerator(name="USUARIO_ROL_GENERATOR",sequenceName="seguridad.usuario_rol_id_usuario_rol_seq")
	@Column(name = "id_usuario_rol", unique = true, nullable = false)
	public Long getIdUsuarioRol() {
		return this.idUsuarioRol;
	}

	public void setIdUsuarioRol(Long idUsuarioRol) {
		this.idUsuarioRol = idUsuarioRol;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_rol", nullable = false)
	@NotNull
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	@NotNull
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
