
UPDATE jbpm.jbpm_task
   SET name_='ASIGNAR_PROMOCION_SALARIAL' 
	WHERE NAME_ = 'FIRMAR_RESOLUCION_ADJUDICACION'
	AND PROCESSDEFINITION_ = (SELECT MAX(ID_) FROM JBPM.JBPM_PROCESSDEFINITION WHERE UPPER (NAME_) = 'PROMOCIONCIO');