package enums;

public enum ActividadEnum {

	CARGA_GRUPO(1, "CARGA POR GRUPO", "CARGA_GRUPO"), 
	//ENVIAR_HOMOLOGACION(2, "ENVIAR A HOMOLOGACION", "ENVIAR_HOMOLOGACION"),//MODIFICADO RV
	APROBAR_HOMOLOG_SFP(3, "APROBAR HOMOLOGACION SFP", "APROBAR_HOMOLOG_SFP"),
	HOMOLOGACION_OEE(4, "HOMOLOGACION OEE", "HOMOLOGACION_OEE"),
	//ELABORAR_DOC_HOMOLOG(5, "ELABORAR DOCOCUMENTO HOMOLOGACION", "ELABORAR_DOC_HOMOLOG"),
	FIRMA_RESOL_HOMOLOG(6, "FIRMA DE RESOLUCION DE HOMOLOGACIONES", "FIRMA_RESOL_HOMOLOG"),
	MODIFICAR_DATOS_CONCURSO(7, "MODIFICAR DATOS DEL CONCURSO", "MODIFICAR_DATOS_CONCURSO"),
	//SOLICITAR_PUBLICACION(8, "SOLICITAR PUBLICACION", "SOLICITAR_PUBLICACION"),
	//APROBAR_PUBLICACION(9, "APROBAR PUBLICACION", "APROBAR_PUBLICACION"),
	//REVISION_PUBLICACION_OEE(10, "REVISION DE PUBLICACION", "REVISION_PUBLICACION_OEE"),
	RECIBIR_POSTULACIONES(11, "RECIBIR POSTULACIONES", "RECIBIR_POSTULACIONES"),
	PRORROGAR_POSTULACION(12, "PRORROGAR POSTULACION", "PRORROGAR_POSTULACION"),
	EVALUACION_DOCUMENTAL(13, "EVALUACION DOCUMENTAL", "EVALUACION_DOCUMENTAL"),
	ELABORAR_PUBLICACION_LISTA_LARGA(14, "ELABORAR PUBLICACION LISTA LARGA", "ELABORAR_PUBLICACION_LISTA_LARGA"),
	TACHAS_RECLAMOS_MODIF(119, "TACHAS, RECLAMOS Y MODIFICACIONES","TACHAS_RECLAMOS_MODIF"),//Tiene el mismo id que proceso.actividad
	ASIGNAR_PROMOCION_SALARIAL(120, "ASIGNAR_PROMOCION_SALARIAL","ASIGNAR_PROMOCION_SALARIAL"),//Tiene el mismo id que proceso.actividad
	REALIZAR_EVALUACIONES(15, "REALIZAR EVALUACIONES", "REALIZAR_EVALUACIONES"),
	ELABORAR_PUBLICACION_LISTA_CORTA(16, "ELABORAR PUBLICACION LISTA CORTA", "ELABORAR_PUBLICACION_LISTA_CORTA"),
	REALIZAR_ENTREVISTA_FINAL(17, "REALIZAR ENTREVISTA FINAL", "REALIZAR_ENTREVISTA_FINAL"),
	VALIDAR_MATRIZ_DOCUMENTAL_ADJ(18, "VALIDAR MATRIZ DOCUMENT. ADJ. POR GRUPO", "VALIDAR_MATRIZ_DOCUMENTAL_ADJ"),
	PUBLICAR_ADJUDICADOS(19, "PUBLICAR ADJUDICADOS", "PUBLICAR_ADJUDICADOS"),
	//ELABORAR_RESOLUCION_ADJUDICACION(20, "ELABORAR RESOLUCION ADJUDICACION", "ELABORAR_RESOLUCION_ADJUDICACION"),
	FIRMAR_RESOLUCION_ADJUDICACION(21, "FIRMAR RESOLUCION ADJUDICACION", "FIRMAR_RESOLUCION_ADJUDICACION"),
	
	ELABORAR_DECRECTO_PRESIDENCIAL(22, "ELABORAR DECRECTO PRESIDENCIAL", "ELABORAR_DECRECTO_PRESIDENCIAL"),
	//EDITAR_DOC_PRESIDENCIA_REPUBLICA(23, "EDITAR DOCUMENTO EN PRESIDENCIA DE LA REPUBLICA", "EDITAR_DOC_PRESIDENCIA_REPUBLICA"),
	INGRESAR_POSTULANTE(24, "INGRESAR POSTULANTE", "INGRESAR_POSTULANTE"),
	//ELABORAR_RESOLUCION_NOMBRAMIENTO(25, "ELABORAR RESOLUCION NOMBRAMIENTO", "ELABORAR_RESOLUCION_NOMBRAMIENTO"),
	//FIRMAR_RESOLUCION_NOMBRAMIENTO(26, "FIRMAR RESOLUCION NOMBRAMIENTO", "FIRMAR_RESOLUCION_NOMBRAMIENTO"),
	
	REVISION_EMPATES(27, "REVISION DE EMPATES", "REVISION_EMPATES"),
	GESTION_INGRESOS(28, "GESTION DE INGRESOS", "GESTION_INGRESOS"),
	COMPLETAR_CARPETAS(113, "COMPLETAR CARPETAS", "COMPLETAR_CARPETAS"),
	
	
	
	/* EXCEPCIONES */
	EXCEP_APROBAR_SFP (100, "APROBAR SFP", "APROBAR_SFP"),
	EXCEP_REVISAR_OEE (101, "REVISAR OEE", "REVISAR_OEE"),
	EXCEP_ADJUNTAR_DOC_CANCELACION_AUTOMATICA (102, "ADJUNTAR DOC. DE CANCELACION AUTOMATICA", "ADJUNTAR_DOC_CANCELACION_AUTOMATICA"),
	
	/* CAPACITACIONES */
	CAPA_CARGAR_CAPACITACION_ENVIAR_APROB (103, "CARGAR DATOS CAPAC./ENVIO A APROBACION", "CARGAR_CAPACITACION_ENVIAR_APROB"),
	CAPA_APROBAR_CAPACITACION (104, "APROBACION DE CAPACITACION", "APROBAR_CAPACITACION"),
	CAPA_REVISAR_CAPACITACION(105, "REVISION DE CAPACITACION", "REVISAR_CAPACITACION"),
	CAPA_PUBLICAR_CAPACITACION(106, "PUBLICACION CAPACITACION", "PUBLICAR_CAPACITACION"),
	CAPA_RECEPCIONAR_POST_INSC(107, "RECEPCION DE POSTULACIONES/INSCRIPCIONES", "RECEPCIONAR_POST_INSC"),
	CAPA_REPROGRAMAR_CANCELAR_CAPAC(108, "REPROGRAMAR CANCELAR CAPACITACION", "REPROGRAMAR_CANCELAR_CAPAC"),
	CAPA_REGISTRAR_COMISION(109, "REGISTRAR COMISION", "REGISTRAR_COMISION"),
	CAPA_EVALUAR_POSTULANTES(110, "EVALUACION POSTULANTES", "EVALUAR_POSTULANTES"),
	CAPA_PUBLICAR_SELECCIONADOS(111, "PUBLICACION SELECCIONADOS", "PUBLICAR_SELECCIONADOS"),
	CAPA_INSCRIPCION_LISTA(112, "INSCRIPCION/LISTA", "INSCRIPCION_LISTA"),
	
	/*EVALUACION DE DESEMPEÑO*/
	EVAL_DESEM_ASIGNAR_PLANTILLA(113, "ASIGNAR PLANTILLA", "ASIGNAR_PLANTILLA"),
	EVAL_DESEM_GENERAR_RESOLUCION(114, "GENERAR RESOLUCION", "GENERAR_RESOLUCION"),
	EVAL_DESEM_APROBAR_EVALUACION(115, "APROBAR EVALUACION", "APROBAR_EVALUACION"),
	EVAL_DESEM_REVISAR_EVALUACION(116, "REVISAR EVALUACION", "REVISAR_EVALUACION"),
	EVAL_DESEM_ADJUNTAR_RESOLUCION_FIRMADA(117, "ADJUNTAR RESOLUCION FIRMADA", "ADJUNTAR_RESOLUCION_FIRMADA"),
	
	/*CIRCUITO CIO*/
	CIO_CARGA_GRUPO(1, "CARGA POR GRUPO", "CARGA_GRUPO"), 
	CIO_ENVIAR_HOMOLOGACION(2, "ENVIAR A HOMOLOGACION", "ENVIAR_HOMOLOGACION"),
	CIO_APROBAR_HOMOLOG_SFP(3, "APROBAR HOMOLOGACION SFP", "APROBAR_HOMOLOG_SFP"),
	CIO_HOMOLOGACION_OEE(4, "HOMOLOGACION OEE", "HOMOLOGACION_OEE"),
	CIO_ELABORAR_DOC_HOMOLOG(5, "ELABORAR DOCOCUMENTO HOMOLOGACION", "ELABORAR_DOC_HOMOLOG"),
	CIO_FIRMA_RESOL_HOMOLOG(6, "FIRMA DE RESOLUCION DE HOMOLOGACIONES", "FIRMA_RESOL_HOMOLOG"),
	CIO_MODIFICAR_DATOS_CONCURSO(7, "MODIFICAR DATOS DEL CONCURSO", "MODIFICAR_DATOS_CONCURSO"),
	CIO_SOLICITAR_PUBLICACION(8, "SOLICITAR PUBLICACION", "SOLICITAR_PUBLICACION"),
	CIO_APROBAR_PUBLICACION(9, "APROBAR PUBLICACION", "APROBAR_PUBLICACION"),
	CIO_REVISION_PUBLICACION_OEE(10, "REVISION DE PUBLICACION", "REVISION_PUBLICACION_OEE"),
	CIO_RECIBIR_POSTULACIONES(11, "RECIBIR POSTULACIONES", "RECIBIR_POSTULACIONES"),
	CIO_PRORROGAR_POSTULACION(12, "PRORROGAR POSTULACION", "PRORROGAR_POSTULACION"),
	CIO_EVALUACION_DOCUMENTAL(13, "EVALUACION DOCUMENTAL", "EVALUACION_DOCUMENTAL"),
	CIO_ELABORAR_PUBLICACION_LISTA_LARGA(14, "ELABORAR PUBLICACION LISTA LARGA", "ELABORAR_PUBLICACION_LISTA_LARGA"),
	CIO_REALIZAR_EVALUACIONES(15, "REALIZAR EVALUACIONES", "REALIZAR_EVALUACIONES"),
	CIO_ELABORAR_PUBLICACION_LISTA_CORTA(16, "ELABORAR PUBLICACION LISTA CORTA", "ELABORAR_PUBLICACION_LISTA_CORTA"),
	CIO_REALIZAR_ENTREVISTA_FINAL(17, "REALIZAR ENTREVISTA FINAL", "REALIZAR_ENTREVISTA_FINAL"),
	CIO_VALIDAR_MATRIZ_DOCUMENTAL_ADJ(18, "VALIDAR MATRIZ DOCUMENT. ADJ. POR GRUPO", "VALIDAR_MATRIZ_DOCUMENTAL_ADJ"),
	CIO_PUBLICAR_ADJUDICADOS(19, "PUBLICAR ADJUDICADOS", "PUBLICAR_ADJUDICADOS"),
	CIO_ELABORAR_RESOLUCION_ADJUDICACION(20, "ELABORAR RESOLUCION ADJUDICACION", "ELABORAR_RESOLUCION_ADJUDICACION"),
	CIO_FIRMAR_RESOLUCION_ADJUDICACION(21, "FIRMAR RESOLUCION ADJUDICACION", "FIRMAR_RESOLUCION_ADJUDICACION"),
	CIO_ELABORAR_DECRECTO_PRESIDENCIAL(22, "ELABORAR DECRECTO PRESIDENCIAL", "ELABORAR_DECRECTO_PRESIDENCIAL"),
	CIO_EDITAR_DOC_PRESIDENCIA_REPUBLICA(23, "EDITAR DOCUMENTO EN PRESIDENCIA DE LA REPUBLICA", "EDITAR_DOC_PRESIDENCIA_REPUBLICA"),
	CIO_INGRESAR_POSTULANTE(24, "INGRESAR POSTULANTE", "INGRESAR_POSTULANTE"),
	CIO_ELABORAR_RESOLUCION_NOMBRAMIENTO(25, "ELABORAR RESOLUCION NOMBRAMIENTO", "ELABORAR_RESOLUCION_NOMBRAMIENTO"),
	CIO_FIRMAR_RESOLUCION_NOMBRAMIENTO(26, "FIRMAR RESOLUCION NOMBRAMIENTO", "FIRMAR_RESOLUCION_NOMBRAMIENTO"),
	CIO_REVISION_EMPATES(27, "REVISION DE EMPATES", "REVISION_EMPATES"),
	
	/*CIRCUITO CSI*/
	CSI_CARGA_GRUPO(1, "CARGA POR GRUPO", "CARGA_GRUPO"), 
	CSI_ENVIAR_HOMOLOGACION(2, "ENVIAR A HOMOLOGACION", "ENVIAR_HOMOLOGACION"),
	CSI_APROBAR_HOMOLOG_SFP(3, "APROBAR HOMOLOGACION SFP", "APROBAR_HOMOLOG_SFP"),
	CSI_HOMOLOGACION_OEE(4, "HOMOLOGACION OEE", "HOMOLOGACION_OEE"),
	CSI_ELABORAR_DOC_HOMOLOG(5, "ELABORAR DOCOCUMENTO HOMOLOGACION", "ELABORAR_DOC_HOMOLOG"),
	CSI_FIRMA_RESOL_HOMOLOG(6, "FIRMA DE RESOLUCION DE HOMOLOGACIONES", "FIRMA_RESOL_HOMOLOG"),
	CSI_MODIFICAR_DATOS_CONCURSO(7, "MODIFICAR DATOS DEL CONCURSO", "MODIFICAR_DATOS_CONCURSO"),
	CSI_SOLICITAR_PUBLICACION(8, "SOLICITAR PUBLICACION", "SOLICITAR_PUBLICACION"),
	CSI_APROBAR_PUBLICACION(9, "APROBAR PUBLICACION", "APROBAR_PUBLICACION"),
	CSI_REVISION_PUBLICACION_OEE(10, "REVISION DE PUBLICACION", "REVISION_PUBLICACION_OEE"),
	CSI_RECIBIR_POSTULACIONES(11, "RECIBIR POSTULACIONES", "RECIBIR_POSTULACIONES"),
	CSI_PRORROGAR_POSTULACION(12, "PRORROGAR POSTULACION", "PRORROGAR_POSTULACION"),
	CSI_REALIZAR_SORTEO(13, "REALIZAR SORTEO", "SORTEO"),
	CSI_COMPLETAR_CARPETAS(14, "COMPLETAR CARPETAS", "COMPLETAR_CARPETAS"),
	CSI_REALIZAR_EVALUACIONES(15, "REALIZAR EVALUACIONES", "REALIZAR_EVALUACIONES"),
	CSI_ELABORAR_PUBLICACION_LISTA_CORTA(16, "ELABORAR PUBLICACION LISTA CORTA", "ELABORAR_PUBLICACION_LISTA_CORTA"),
	CSI_VALIDAR_MATRIZ_DOCUMENTAL_ADJ(17, "VALIDAR MATRIZ DOCUMENT. ADJ. POR GRUPO", "VALIDAR_MATRIZ_DOCUMENTAL_ADJ"),
	CSI_PUBLICAR_ADJUDICADOS(18, "PUBLICAR ADJUDICADOS", "PUBLICAR_ADJUDICADOS"),
	CSI_ELABORAR_RESOLUCION_ADJUDICACION(19, "ELABORAR RESOLUCION ADJUDICACION", "ELABORAR_RESOLUCION_ADJUDICACION"),
	CSI_FIRMAR_RESOLUCION_ADJUDICACION(20, "FIRMAR RESOLUCION ADJUDICACION", "FIRMAR_RESOLUCION_ADJUDICACION"),
	CSI_ELABORAR_DECRECTO_PRESIDENCIAL(21, "ELABORAR DECRECTO PRESIDENCIAL", "ELABORAR_DECRECTO_PRESIDENCIAL"),
	CSI_EDITAR_DOC_PRESIDENCIA_REPUBLICA(22, "EDITAR DOCUMENTO EN PRESIDENCIA DE LA REPUBLICA", "EDITAR_DOC_PRESIDENCIA_REPUBLICA"),
	CSI_INGRESAR_POSTULANTE(23, "INGRESAR POSTULANTE", "INGRESAR_POSTULANTE"),
	CSI_ELABORAR_RESOLUCION_NOMBRAMIENTO(24, "ELABORAR RESOLUCION NOMBRAMIENTO", "ELABORAR_RESOLUCION_NOMBRAMIENTO"),
	CSI_FIRMAR_RESOLUCION_NOMBRAMIENTO(25, "FIRMAR RESOLUCION NOMBRAMIENTO", "FIRMAR_RESOLUCION_NOMBRAMIENTO"),
	CSI_REVISION_EMPATES(26, "REVISION DE EMPATES", "REVISION_EMPATES"),
	
	/*MOVILIDAD*/
    /*MOV_REGISTRAR_TRANSLADO_CONCURSO(1, "REGISTRAR TRANSLADO CONCURSO", "regTraCon"),
    MOV_RESPONDER_SOLICITUD(2, "RESPONDER SOLICITUD", "resSol"),
    MOV_REVISAR_SOLICITUD_SFP(3, "REVISAR SOLICITUD SFP", "revSolSfp"),
    MOV_REGISTRAR_TRASLADO_TEMPORAL(4, "REGISTRAR TRASLADO TEMPORAL", "regTraTem"),
    MOV_REGISTRAR_TRASLADO_DEF_SIN_LINEA(5, "REGISTRAR TRASLADO DEF SIN_LINEA", "regTraDefSinLin"),
    MOV_REGISTRAR_TRASLADO_DEF_CON_LINEA(6, "REGISTRAR TRASLADO DEF CON LINEA", "regTraDefConLin");*/
	
    MOV_REGISTRAR_TRASLADADO_POR_CONCURSO(1, "REGISTRAR TRASLADADO POR CONCURSO", "REGISTRAR_TRASLADADO_POR_CONCURSO"),
    MOV_RESPONDER_TRASLADO(2, "RESPONDER TRASLADO", "RESPONDER_TRASLADO"),
    MOV_REVISAR_SOLICITUD_SFP(3, "REVISAR SOLICITUD SFP", "REVISAR_SOLICITUD_SFP"),
    MOV_REGISTRAR_TRASLADO_TEMPORAL(4, "REGISTRAR TRASLADO TEMPORAL", "REGISTRAR_TRASLADO_TEMPORAL"),
    MOV_REGISTRAR_TRASLADO_SIN_LINEA(5, "REGISTRAR TRASLADO SIN LINEA", "REGISTRAR_TRASLADO_SIN_LINEA"),
    MOV_REGISTRAR_TRASLADO_CON_LINEA(6, "REGISTRAR TRASLADO CON LINEA", "REGISTRAR_TRASLADO_CON_LINEA");
	
	private Integer id;
	private String descripcion;
	private String valor;
	
	
	private ActividadEnum(Integer id, String descripcion, String valor) {
		this.id = id;
		this.descripcion = descripcion;
		this.valor = valor;
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDescripcion() {
		return descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	public String getValor() {
		return valor;
	}
	public void setValor(String valor) {
		this.valor = valor;
	}
	
	public static ActividadEnum getById(String id) {
		for (ActividadEnum o : ActividadEnum.values()) {
			if (id.equals("" + o.getId())) {
				return o;
			}
		}
		return null;
	}
	
	public static ActividadEnum getPorValor(String valor) {
		for (ActividadEnum o : ActividadEnum.values()) {
			if (valor.equals("" + o.getValor())) {
				return o;
			}
		}
		return null;
	}
}
