
--TABLA POSTULACION_CAP, NUEVAS COLUMNAS PARA REFLEJO DE OEE Y UNIDAD ORGANIZATIVA EN FICHA DE INSCRIPCION
ALTER TABLE capacitacion.postulacion_cap
  ADD COLUMN oee character varying(100), -- CORRESPONDE A LA OEE DE LA PERSONA
  ADD COLUMN unidad_organizativa character varying(100); -- CORRESPONDE A LA UO DE LA PERSONA