
--TABLA REMUNERACIONES Y TABLA HISTORICO_REMUNERACIONES, NUEVA COLUMNA ID_CONFIGURACION_UO PARA REFLEJO DE LA UO_CAB EN CASOS DE RESPALDO HISTORICO DE VACANTES
ALTER TABLE remuneracion.remuneraciones
  ADD COLUMN id_configuracion_uo bigint; -- CORRESPONDE AL ID DE LA UO EN CONFIGURACION_UO_CAB
  ALTER TABLE remuneracion.historico_remuneraciones
  ADD COLUMN id_configuracion_uo bigint; -- CORRESPONDE AL ID DE LA UO EN CONFIGURACION_UO_CAB