insert into seguridad.funcion (descripcion, url, modulo)
values ('ADM USUARIOS PORTAL','usuarioList', 'SELECCION')
insert into seguridad.funcion (descripcion, url, modulo)
values ('CANTIDAD FUNCIONARIOS','rptCantFuncionarios', 'REMUNERACION')
insert into seguridad.funcion (descripcion, url, modulo)
values ('CANTIDAD FUNCIONARIOS PCD','rptCantPCDFuncionarios', 'REMUNERACION')
insert into seguridad.funcion (descripcion, url, modulo)
values ('CANTIDAD PERMANENTES POR CATEGORIA','rptCantFuncionariosCat', 'REMUNERACION')
insert into seguridad.funcion (descripcion, url, modulo)
values ('CANTIDAD PERMANENTES POR EDAD','rptCantFuncionariosEdad', 'REMUNERACION')
insert into seguridad.funcion (descripcion, url, modulo)
values ('CANTIDAD PERMANENTES POR NIVEL SALARIAL','rptCantFuncionariosPerm', 'REMUNERACION')

