package py.com.excelsis.sicca.entity;

// Generated 23-feb-2012 8:44:13 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AccionInconstDet generated by hbm2java
 */
@Entity
@Table(name = "accion_inconst_det", schema = "juridicos")
public class AccionInconstDet implements java.io.Serializable {

	private Long idAccionDet;
	private AccionInconstCab accionInconstCab;
	private DatosEspecificos datosEspecifLey;
	private String otraLey;
	private boolean artTodos;
	private String artEspecif;
	private Date fechaAlta;
	private String usuAlta;

	public AccionInconstDet() {
	}

	public AccionInconstDet(Long idAccionDet,
			AccionInconstCab accionInconstCab, boolean artTodos,
			Date fechaAlta, String usuAlta) {
		this.idAccionDet = idAccionDet;
		this.accionInconstCab = accionInconstCab;
		this.artTodos = artTodos;
		this.fechaAlta = fechaAlta;
		this.usuAlta = usuAlta;
	}

	public AccionInconstDet(Long idAccionDet,
			AccionInconstCab accionInconstCab, DatosEspecificos datosEspecifLey,
			String otraLey, boolean artTodos, String artEspecif,
			Date fechaAlta, String usuAlta) {
		this.idAccionDet = idAccionDet;
		this.accionInconstCab = accionInconstCab;
		this.datosEspecifLey = datosEspecifLey;
		this.otraLey = otraLey;
		this.artTodos = artTodos;
		this.artEspecif = artEspecif;
		this.fechaAlta = fechaAlta;
		this.usuAlta = usuAlta;
	}

	@Id
	@Column(name = "id_accion_det", unique = true, nullable = false)
	@GeneratedValue(generator="ACCION_INCONST_DET_GENERATOR")
	@SequenceGenerator(name="ACCION_INCONST_DET_GENERATOR", sequenceName="juridicos.accion_inconst_det_id_accion_det_seq")
	public Long getIdAccionDet() {
		return this.idAccionDet;
	}

	public void setIdAccionDet(Long idAccionDet) {
		this.idAccionDet = idAccionDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_accion_cab", nullable = false)
	@NotNull
	public AccionInconstCab getAccionInconstCab() {
		return this.accionInconstCab;
	}

	public void setAccionInconstCab(AccionInconstCab accionInconstCab) {
		this.accionInconstCab = accionInconstCab;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especif_ley")
	public DatosEspecificos getDatosEspecifLey() {
		return datosEspecifLey;
	}

	public void setDatosEspecifLey(DatosEspecificos datosEspecifLey) {
		this.datosEspecifLey = datosEspecifLey;
	}

	@Column(name = "otra_ley", length = 100)
	@Length(max = 100)
	public String getOtraLey() {
		return this.otraLey;
	}

	public void setOtraLey(String otraLey) {
		this.otraLey = otraLey;
	}

	@Column(name = "art_todos", nullable = false)
	public boolean isArtTodos() {
		return this.artTodos;
	}

	public void setArtTodos(boolean artTodos) {
		this.artTodos = artTodos;
	}

	@Column(name = "art_especif", length = 100)
	@Length(max = 100)
	public String getArtEspecif() {
		return this.artEspecif;
	}

	public void setArtEspecif(String artEspecif) {
		this.artEspecif = artEspecif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

}
