package py.com.excelsis.sicca.entity;

// Generated 03-nov-2011 17:17:28 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ActividadProceso generated by hbm2java
 */
@Entity
@Table(name = "actividad_proceso", schema = "proceso")
public class ActividadProceso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5521164809922664174L;
	private Long idActividadProceso;
	private Proceso proceso;
	private Actividad actividad;
	private BigDecimal plazoActividad;
	private String unidadPlazo;
	private String observacion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private List<ProcActividadRol> procActividadRols = new ArrayList<ProcActividadRol>(0);

	public ActividadProceso() {
	}


	@Id
	@Column(name = "id_actividad_proceso", unique = true, nullable = false)
	@GeneratedValue(generator="ACTIVIDAD_PROCESO_GENERATOR")
	@SequenceGenerator(name="ACTIVIDAD_PROCESO_GENERATOR", sequenceName="proceso.tbl_actividad_proceso_id_actividad_proceso_seq")
	public Long getIdActividadProceso() {
		return this.idActividadProceso;
	}

	public void setIdActividadProceso(Long idActividadProceso) {
		this.idActividadProceso = idActividadProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proceso", nullable = false)
	@NotNull
	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad", nullable = false)
	@NotNull
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	
	@Column(name = "plazo_actividad", nullable = false, precision = 6, scale = 2)
    @NotNull
    public BigDecimal getPlazoActividad() {
            return this.plazoActividad;
    }

    public void setPlazoActividad(BigDecimal plazoActividad) {
            this.plazoActividad = plazoActividad;
    }
	

	@Column(name = "unidad_plazo", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getUnidadPlazo() {
		return this.unidadPlazo;
	}

	public void setUnidadPlazo(String unidadPlazo) {
		this.unidadPlazo = unidadPlazo;
	}

	@Column(name = "observacion", length = 100)
	@Length(max = 100)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividadProceso")
	public List<ProcActividadRol> getProcActividadRols() {
		return this.procActividadRols;
	}

	public void setProcActividadRols(List<ProcActividadRol> procActividadRols) {
		this.procActividadRols = procActividadRols;
	}

}
