package py.com.excelsis.sicca.entity;

// Generated 03-nov-2011 17:17:28 by Hibernate Tools 3.4.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Properties;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.EntityBase;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "actividad", schema = "proceso")
public class Actividad extends EntityBase {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6143876571616097934L;
	private Long idActividad;
	private String descripcion;
	private String tipo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String codActividad;
	private String descripcionHistorial;
	private String nroActividad;
	private Boolean valor;
	
	private Set<ActividadProceso> actividadProcesos = new HashSet<ActividadProceso>(0);

	public Actividad() {
	}

	@Id
	@Column(name = "id_actividad", unique = true, nullable = false)
	@GeneratedValue(generator="ACTIVIDAD_GENERATOR")
	@SequenceGenerator(name="ACTIVIDAD_GENERATOR", sequenceName="proceso.tbl_actividad_id_actividad_seq")
	public Long getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(Long idActividad) {
		this.idActividad = idActividad;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	
	@Column(name = "cod_actividad", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getCodActividad() {
		return codActividad;
	}
	public void setCodActividad(String codActividad) {
		this.codActividad = codActividad;
	}
	
	
	@Column(name = "tipo", nullable = false, length = 20)
	@NotNull
	public String getTipo() {
		return tipo;
	}
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividad")
	public Set<ActividadProceso> getActividadProcesos() {
		return this.actividadProcesos;
	}

	public void setActividadProcesos(Set<ActividadProceso> actividadProcesos) {
		this.actividadProcesos = actividadProcesos;
	}
	
	
	@Column(name = "descripcion_historial", length = 200)
	@Length(max = 200)
	public String getDescripcionHistorial() {
		return descripcionHistorial;
	}
	public void setDescripcionHistorial(String descripcionHistorial) {
		this.descripcionHistorial = descripcionHistorial;
	}

	@Transient
	public Long getId() {
		return idActividad;
	}

	/**
	 * 
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.ACTIVIDAD_ID, getId());
		properties.put(SICCASessionParameters.ACTIVIDAD_DESCRIPCION,
				descripcion);

		return properties;
	}

	/**
	 * 
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}

	@Column(name = "nro_actividad", length = 10)
	@Length(max = 10)
	public String getNroActividad() {
		return nroActividad;
	}
	public void setNroActividad(String nroActividad) {
		this.nroActividad = nroActividad;
	}

	@Column(name = "valor")
	public Boolean getValor() {
		return valor;
	}

	public void setValor(Boolean valor) {
		this.valor = valor;
	}

	
	

}
