package py.com.excelsis.sicca.entity;

// Generated 10/11/2011 09:07:54 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AdjuntoDocPortal generated by hbm2java
 */
@Entity
@Table(name = "adjunto_doc_portal", schema = "seleccion")
public class AdjuntoDocPortal implements java.io.Serializable {

	private Long idAdjuntoDocPortal;
	private Documentos documentos;
	private Boolean activo;
	private Boolean publicado;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean portal;
	private Boolean cuentaUsuario;
	private Integer nroOrden;

	public AdjuntoDocPortal() {
	}

	public AdjuntoDocPortal(Long idAdjuntoDocPortal, Documentos documentos,
			Boolean activo, Boolean publicado, String usuAlta, Date fechaAlta,
			Boolean portal, Boolean cuentaUsuario) {
		this.idAdjuntoDocPortal = idAdjuntoDocPortal;
		this.documentos = documentos;
		this.activo = activo;
		this.publicado = publicado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.portal = portal;
		this.cuentaUsuario = cuentaUsuario;
	}

	public AdjuntoDocPortal(Long idAdjuntoDocPortal, Documentos documentos,
			Boolean activo, Boolean publicado, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod, Boolean portal, Boolean cuentaUsuario) {
		this.idAdjuntoDocPortal = idAdjuntoDocPortal;
		this.documentos = documentos;
		this.activo = activo;
		this.publicado = publicado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.portal = portal;
		this.cuentaUsuario = cuentaUsuario;
	}

	@Id
	@Column(name = "id_adjunto_doc_portal", unique = true, nullable = false)
	@GeneratedValue(generator="ADJUNTO_DOC_PORTAL_GENERATOR")
	@SequenceGenerator(name="ADJUNTO_DOC_PORTAL_GENERATOR",sequenceName="seleccion.adjunto_doc_portal_id_adjunto_doc_portal_seq")
	public Long getIdAdjuntoDocPortal() {
		return this.idAdjuntoDocPortal;
	}

	public void setIdAdjuntoDocPortal(Long idAdjuntoDocPortal) {
		this.idAdjuntoDocPortal = idAdjuntoDocPortal;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}


	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	
	@Column(name = "publicado", nullable = false)
	public Boolean getPublicado() {
		return publicado;
	}

	public void setPublicado(Boolean publicado) {
		this.publicado = publicado;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	
	
	@Column(name = "portal", nullable = false)
	public Boolean getPortal() {
		return portal;
	}

	public void setPortal(Boolean portal) {
		this.portal = portal;
	}

	
	@Column(name = "cuenta_usuario", nullable = false)
	public Boolean getCuentaUsuario() {
		return cuentaUsuario;
	}

	public void setCuentaUsuario(Boolean cuentaUsuario) {
		this.cuentaUsuario = cuentaUsuario;
	}

	@Column(name = "nro_orden")
	public Integer getNroOrden() {
		return nroOrden;
	}

	public void setNroOrden(Integer nroOrden) {
		this.nroOrden = nroOrden;
	}

	
	

}
