package py.com.excelsis.sicca.entity;

// Generated 28/10/2011 05:04:36 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AdjuntoDocPuestoAgr generated by hbm2java
 */
@Entity
@Table(name = "adjunto_doc_puesto_agr", schema = "seleccion")
public class AdjuntoDocPuestoAgr implements java.io.Serializable {

	private Long idAdjuntoDocPuestoAgr;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Long idDocumento;
	private boolean activo;
	private String usuMod;
	private String usuAlta;
	private Date fechaAlta;
	private Date fechaMod;

	public AdjuntoDocPuestoAgr() {
	}

	public AdjuntoDocPuestoAgr(Long idAdjuntoDocPuestoAgr,
			ConcursoPuestoAgr concursoPuestoAgr, Long idDocumento,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idAdjuntoDocPuestoAgr = idAdjuntoDocPuestoAgr;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.idDocumento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public AdjuntoDocPuestoAgr(Long idAdjuntoDocPuestoAgr,
			ConcursoPuestoAgr concursoPuestoAgr, Long idDocumento,
			boolean activo, String usuMod, String usuAlta, Date fechaAlta,
			Date fechaMod) {
		this.idAdjuntoDocPuestoAgr = idAdjuntoDocPuestoAgr;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.idDocumento = idDocumento;
		this.activo = activo;
		this.usuMod = usuMod;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="ADJ_DOC_PUESTO_AGR_GENERATOR")
	@SequenceGenerator(name="ADJ_DOC_PUESTO_AGR_GENERATOR",sequenceName="seleccion.adjunto_doc_puesto_agr_id_adjunto_doc_puesto_agr_seq")
	@Column(name = "id_adjunto_doc_puesto_agr", unique = true, nullable = false)
	public Long getIdAdjuntoDocPuestoAgr() {
		return this.idAdjuntoDocPuestoAgr;
	}

	public void setIdAdjuntoDocPuestoAgr(Long idAdjuntoDocPuestoAgr) {
		this.idAdjuntoDocPuestoAgr = idAdjuntoDocPuestoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr", nullable = false)
	@NotNull
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "id_documento", nullable = false)
	public Long getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(Long idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
