package py.com.excelsis.sicca.entity;

// Generated 27/09/2011 04:27:10 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;


/**
 * AgrupamientoCce generated by hbm2java
 */
@Entity
@Table(name = "agrupamiento_cce", schema = "planificacion")
public class AgrupamientoCce implements java.io.Serializable {

	private Long idAgrupamientoCce;
	private TipoCce tipoCce;
	private Integer numero;
	private String descripcion;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private boolean activo;
	private Set<GradoSalarial> gradoSalarials = new HashSet<GradoSalarial>(0);

	public AgrupamientoCce() {
	}

	public AgrupamientoCce(Long idAgrupamientoCce, TipoCce tipoCce, Integer numero,
			String descripcion, String usuAlta, Date fechaAlta, boolean activo) {
		this.idAgrupamientoCce = idAgrupamientoCce;
		this.tipoCce = tipoCce;
		this.numero = numero;
		this.descripcion = descripcion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
	}

	public AgrupamientoCce(Long idAgrupamientoCce, TipoCce tipoCce, Integer numero,
			String descripcion, String usuAlta, String usuMod, Date fechaMod,
			Date fechaAlta, boolean activo, Set<GradoSalarial> gradoSalarials) {
		this.idAgrupamientoCce = idAgrupamientoCce;
		this.tipoCce = tipoCce;
		this.numero = numero;
		this.descripcion = descripcion;
		this.usuAlta = usuAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.gradoSalarials = gradoSalarials;
	}

	@Id
	@Column(name = "id_agrupamiento_cce", unique = true, nullable = false)
	@GeneratedValue(generator="AGRUPAMIENTO_CCE_GENERATOR")
	@SequenceGenerator(name="AGRUPAMIENTO_CCE_GENERATOR",sequenceName="general.barrio_id_barrio_seq")
	public Long getIdAgrupamientoCce() {
		return this.idAgrupamientoCce;
	}

	public void setIdAgrupamientoCce(Long idAgrupamientoCce) {
		this.idAgrupamientoCce = idAgrupamientoCce;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cce", nullable = false)
	@NotNull
	public TipoCce getTipoCce() {
		return this.tipoCce;
	}

	public void setTipoCce(TipoCce tipoCce) {
		this.tipoCce = tipoCce;
	}

	@Column(name = "numero", nullable = false)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrupamientoCce")
	public Set<GradoSalarial> getGradoSalarials() {
		return this.gradoSalarials;
	}

	public void setGradoSalarials(Set<GradoSalarial> gradoSalarials) {
		this.gradoSalarials = gradoSalarials;
	}

}
