package py.com.excelsis.sicca.entity;

// Generated 01-oct-2012 15:29:48 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AlertasEval generated by hbm2java
 */
@Entity
@Table(name = "alertas_eval", schema = "eval_desempeno")
public class AlertasEval implements java.io.Serializable {

	private Long idAlertasEval;
	private ConfiguracionUoCab configuracionUoCab;
	private Long periodo;
	private Boolean activarAlerta;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<AlertasEvalDet> alertasEvalDets = new HashSet<AlertasEvalDet>(0);

	public AlertasEval() {
	}

	public AlertasEval(Long idAlertasEval, ConfiguracionUoCab configuracionUoCab,
			Long periodo, Boolean activarAlerta, Boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idAlertasEval = idAlertasEval;
		this.configuracionUoCab = configuracionUoCab;
		this.periodo = periodo;
		this.activarAlerta = activarAlerta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public AlertasEval(Long idAlertasEval, ConfiguracionUoCab configuracionUoCab,
			long periodo, Boolean activarAlerta, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<AlertasEvalDet> alertasEvalDets) {
		this.idAlertasEval = idAlertasEval;
		this.configuracionUoCab = configuracionUoCab;
		this.periodo = periodo;
		this.activarAlerta = activarAlerta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.alertasEvalDets = alertasEvalDets;
	}

	@Id
	@GeneratedValue(generator="ALERTAS_EVAL_GENERATOR")
	@SequenceGenerator(name="ALERTAS_EVAL_GENERATOR",sequenceName="eval_desempeno.alertas_eval_id_alertas_eval_seq")
	@Column(name = "id_alertas_eval", unique = true, nullable = false)
	public Long getIdAlertasEval() {
		return this.idAlertasEval;
	}

	public void setIdAlertasEval(Long idAlertasEval) {
		this.idAlertasEval = idAlertasEval;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	@NotNull
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "periodo", nullable = false)
	public Long getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Long periodo) {
		this.periodo = periodo;
	}

	@Column(name = "activar_alerta", nullable = false)
	public Boolean getActivarAlerta() {
		return activarAlerta;
	}

	public void setActivarAlerta(Boolean activarAlerta) {
		this.activarAlerta = activarAlerta;
	}

	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}


	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alertasEval")
	public Set<AlertasEvalDet> getAlertasEvalDets() {
		return this.alertasEvalDets;
	}

	public void setAlertasEvalDets(Set<AlertasEvalDet> alertasEvalDets) {
		this.alertasEvalDets = alertasEvalDets;
	}

}
