package py.com.excelsis.sicca.entity;

// Generated 11-nov-2011 17:02:48 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AntecedenteGrupo generated by hbm2java
 */
@Entity
@Table(name = "antecedente_grupo", schema = "seleccion")
public class AntecedenteGrupo implements java.io.Serializable {

	private Long idAntecedenteGrupo;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private String descripcion;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean activo;
	private String tipo;
	
	public AntecedenteGrupo() {
	}

	public AntecedenteGrupo(Long idAntecedenteGrupo,
			ConcursoPuestoAgr concursoPuestoAgr, String descripcion,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idAntecedenteGrupo = idAntecedenteGrupo;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.descripcion = descripcion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="ANTECEDENTE_GRUPO_GENERATOR")
	@SequenceGenerator(name="ANTECEDENTE_GRUPO_GENERATOR",sequenceName="seleccion.antecedente_grupo_id_antecedente_grupo_seq")
	@Column(name = "id_antecedente_grupo", unique = true, nullable = false)
	public Long getIdAntecedenteGrupo() {
		return this.idAntecedenteGrupo;
	}

	public void setIdAntecedenteGrupo(Long idAntecedenteGrupo) {
		this.idAntecedenteGrupo = idAntecedenteGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr", nullable = false)
	@NotNull
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "usu_alta", nullable = false)
	public String getUsuAlta() {
		return usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}


	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	

}
