package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * Asignacion generated by Generality
 */
@Entity
@Table(name = "asignacion", schema = "planificacion")
public class Asignacion implements java.io.Serializable {
	private Long idAsignacion;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Date fecha2;
	private Integer valor;
	private TblPuestoCategoria tblPuestoCategoria;
	private Boolean activo;

	public Asignacion() {
	}

	public Asignacion(Long idAsignacion) {
		this.idAsignacion = idAsignacion;
	}

	@Id
	@GeneratedValue(generator="ASIGNACION_GENERATOR")
	@SequenceGenerator(name="ASIGNACION_GENERATOR",sequenceName="planificacion.asignacion_id_asignacion_seq")

	@Column(name = "id_asignacion")
	public Long getIdAsignacion() {
		return this.idAsignacion;
	}

	public void setIdAsignacion(Long idAsignacion) {
		this.idAsignacion = idAsignacion;
	}
	

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha")
	public Date getFecha2() {
		return this.fecha2;
	}

	public void setFecha2(Date fecha2) {
		this.fecha2 = fecha2;
	}
	

	@Column(name = "valor")
	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_puesto_categoria")
	public TblPuestoCategoria getTblPuestoCategoria() {
		return this.tblPuestoCategoria;
	}

	public void setTblPuestoCategoria(TblPuestoCategoria tblPuestoCategoria) {
		this.tblPuestoCategoria = tblPuestoCategoria;
	}
	

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idAsignacion == null) ? 0 : idAsignacion.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Asignacion other = (Asignacion) obj;
		if (idAsignacion == null) {
			if (other.idAsignacion != null)
				return false;
		} else if (!idAsignacion.equals(other.idAsignacion))
			return false;
		return true;
	}
}
