package py.com.excelsis.sicca.entity;

// Generated 15-oct-2012 15:52:09 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Transactional;

/**
 * AuditLegajoDet generated by hbm2java
 */
@Entity
@Table(name = "audit_legajo_det", schema = "legajo")
public class AuditLegajoDet implements java.io.Serializable {

	private Long idAuditLegajoDet;
	private AuditLegajo auditLegajo;
	private String tabla;
	private String campo;
	private String accion;
	private String anterior;
	private String nuevo;
	private Integer estado;
	private String usuAlta;
	private Date fechaAlta;
	private Long idPersonaFamiliar;
	private String usuMod;
	private Date fechaMod;
	private Boolean check = false;

	public AuditLegajoDet() {
	}

	public AuditLegajoDet(Long idAuditLegajoDet, AuditLegajo auditLegajo,
			String accion, Integer estado, String usuAlta, Date fechaAlta) {
		this.idAuditLegajoDet = idAuditLegajoDet;
		this.auditLegajo = auditLegajo;
		this.accion = accion;
		this.estado = estado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public AuditLegajoDet(Long idAuditLegajoDet, AuditLegajo auditLegajo,
			String tabla, String campo, String accion, String anterior,
			String nuevo, Integer estado, String usuAlta, Date fechaAlta,
			Long idPersonaFamiliar, String usuMod, Date fechaMod) {
		this.idAuditLegajoDet = idAuditLegajoDet;
		this.auditLegajo = auditLegajo;
		this.tabla = tabla;
		this.campo = campo;
		this.accion = accion;
		this.anterior = anterior;
		this.nuevo = nuevo;
		this.estado = estado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.idPersonaFamiliar = idPersonaFamiliar;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "AUDIT_LEGAJO_DET_GENERATOR")
	@SequenceGenerator(name = "AUDIT_LEGAJO_DET_GENERATOR", sequenceName = "legajo.audit_legajo_det_id_audit_legajo_det_seq")
	@Column(name = "id_audit_legajo_det", unique = true, nullable = false)
	public Long getIdAuditLegajoDet() {
		return this.idAuditLegajoDet;
	}

	public void setIdAuditLegajoDet(Long idAuditLegajoDet) {
		this.idAuditLegajoDet = idAuditLegajoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "audit_legajo", nullable = false)
	@NotNull
	public AuditLegajo getAuditLegajo() {
		return this.auditLegajo;
	}

	public void setAuditLegajo(AuditLegajo auditLegajo) {
		this.auditLegajo = auditLegajo;
	}

	@Column(name = "tabla")
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "campo")
	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	@Column(name = "accion", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "anterior")
	public String getAnterior() {
		return this.anterior;
	}

	public void setAnterior(String anterior) {
		this.anterior = anterior;
	}

	@Column(name = "nuevo")
	public String getNuevo() {
		return this.nuevo;
	}

	public void setNuevo(String nuevo) {
		this.nuevo = nuevo;
	}

	@Column(name = "estado", nullable = false)
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "id_persona_familiar")
	public Long getIdPersonaFamiliar() {
		return this.idPersonaFamiliar;
	}

	public void setIdPersonaFamiliar(Long idPersonaFamiliar) {
		this.idPersonaFamiliar = idPersonaFamiliar;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Transient
	public Boolean getCheck() {
		return check;
	}

	public void setCheck(Boolean check) {
		this.check = check;
	}
	
	

}
