package py.com.excelsis.sicca.entity;

// Generated 15-oct-2012 15:52:09 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AuditLegajoObs generated by hbm2java
 */
@Entity
@Table(name = "audit_legajo_obs", schema = "legajo")
public class AuditLegajoObs implements java.io.Serializable {

	private Long idAuditLegajoObs;
	private AuditLegajo auditLegajo;
	private Long ficha;
	private String observacion;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public AuditLegajoObs() {
	}

	public AuditLegajoObs(Long idAuditLegajoObs, AuditLegajo auditLegajo,
			Long ficha, String usuAlta, Date fechaAlta) {
		this.idAuditLegajoObs = idAuditLegajoObs;
		this.auditLegajo = auditLegajo;
		this.ficha = ficha;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public AuditLegajoObs(Long idAuditLegajoObs, AuditLegajo auditLegajo,
			Long ficha, String observacion, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idAuditLegajoObs = idAuditLegajoObs;
		this.auditLegajo = auditLegajo;
		this.ficha = ficha;
		this.observacion = observacion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "AUDIT_LEGAJO_OBS_GENERATOR")
	@SequenceGenerator(name = "AUDIT_LEGAJO_OBS_GENERATOR", sequenceName = "legajo.audit_legajo_obs_id_audit_legajo_obs_seq")
	@Column(name = "id_audit_legajo_obs", unique = true, nullable = false)
	public Long getIdAuditLegajoObs() {
		return this.idAuditLegajoObs;
	}

	public void setIdAuditLegajoObs(Long idAuditLegajoObs) {
		this.idAuditLegajoObs = idAuditLegajoObs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "audit_legajo", nullable = false)
	@NotNull
	public AuditLegajo getAuditLegajo() {
		return this.auditLegajo;
	}

	public void setAuditLegajo(AuditLegajo auditLegajo) {
		this.auditLegajo = auditLegajo;
	}

	@Column(name = "ficha", nullable = false)
	public Long getFicha() {
		return this.ficha;
	}

	public void setFicha(Long ficha) {
		this.ficha = ficha;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
