package py.com.excelsis.sicca.entity;

// Generated 20-nov-2012 10:31:26 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Query;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.jboss.seam.annotations.In;

/**
 * BandejaTraslado generated by hbm2java
 */
@Entity
@Table(name = "bandeja_traslado", schema = "movilidad")
public class BandejaTraslado implements java.io.Serializable {
	
	@In(value = "entityManager")
	EntityManager em;
	
	private Long idSolicitudTrasladoCab;
	private Long idPersona;
	private String nombres;
	private String apellidos;
	private Long idOeeOrigen;
	private String oeeOrigen;
	private Integer ordenOrigen;
	private Long idOeeDestino;
	private Integer ordenDestino;
	private String oeeDestino;
	private String tipoTraslado;
	private String estado;
	private Byte nenCodigo;
	private Short entCodigo;
	private String entNombre;
	private Byte nivelCod;
	private String nivelNombre;
	private String actividad;
	private String usuario;
	private Date fechaRecepcion;
	private Date fechaInicio;
	private Integer diasCreacion;
	private Integer diasInicio;
	private BigDecimal atraso;
	private Long idActividad;
	private Long idEntidad;
	private Long idSinNivelEntidad;
	private Long idTaskinstance;
	private Long idProcessInstance;
	private String codActividad;
	private Long idProceso;
	private ActividadProceso actividadProceso;
	private String tipoActividad;
	private Long idSinEntidad;
	
	public BandejaTraslado() {
	}

	public BandejaTraslado(Long idSolicitudTrasladoCab, 
			String oeeOrigen, Integer ordenOrigen, 
			Integer ordenDestino, String oeeDestino, String tipoTraslado,
			String estado, Byte nenCodigo, Short entCodigo, String entNombre,
			Byte nivelCod, String nivelNombre, String actividad,
			String usuario, Date fechaRecepcion, Date fechaInicio,
			Integer diasCreacion, Integer diasInicio, BigDecimal atraso,
			Long idActividad, Long idEntidad, Long idSinNivelEntidad,
			Long idTaskinstance, Long idProcessInstance, String codActividad,
			Long idProceso, ActividadProceso actividadProceso, String tipoActividad,
			Long idSinEntidad, String nombres, String apellidos) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
	
		this.oeeOrigen = oeeOrigen;
		this.ordenOrigen = ordenOrigen;
		
		this.ordenDestino = ordenDestino;
		this.oeeDestino = oeeDestino;
		this.tipoTraslado = tipoTraslado;
		this.estado = estado;
		this.nenCodigo = nenCodigo;
		this.entCodigo = entCodigo;
		this.entNombre = entNombre;
		this.nivelCod = nivelCod;
		this.nivelNombre = nivelNombre;
		this.actividad = actividad;
		this.usuario = usuario;
		this.fechaRecepcion = fechaRecepcion;
		this.fechaInicio = fechaInicio;
		this.diasCreacion = diasCreacion;
		this.diasInicio = diasInicio;
		this.atraso = atraso;
		this.idActividad = idActividad;
		this.idEntidad = idEntidad;
		this.idSinNivelEntidad = idSinNivelEntidad;
		this.idTaskinstance = idTaskinstance;
		this.idProcessInstance = idProcessInstance;
		this.codActividad = codActividad;
		this.idProceso = idProceso;
		this.actividadProceso = actividadProceso;
		this.tipoActividad = tipoActividad;
		this.idSinEntidad = idSinEntidad;
		this.nombres = nombres;
		this.apellidos = apellidos;
	}

	@Column(name = "id_solicitud_traslado_cab")
	public Long getIdSolicitudTrasladoCab() {
		return this.idSolicitudTrasladoCab;
	}

	public void setIdSolicitudTrasladoCab(Long idSolicitudTrasladoCab) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
	}
	
	@Column(name = "id_oee_origen")
	public Long getIdOeeOrigen() {
		return idOeeOrigen;
	}

	public void setIdOeeOrigen(Long idOeeOrigen) {
		this.idOeeOrigen = idOeeOrigen;
	}

	@Column(name = "id_oee_destino")
	public Long getIdOeeDestino() {
		return idOeeDestino;
	}

	public void setIdOeeDestino(Long idOeeDestino) {
		this.idOeeDestino = idOeeDestino;
	}

	
	@Column(name = "oee_origen", length = 100)
	@Length(max = 100)
	public String getOeeOrigen() {
		return this.oeeOrigen;
	}

	public void setOeeOrigen(String oeeOrigen) {
		this.oeeOrigen = oeeOrigen;
	}

	@Column(name = "orden_origen")
	public Integer getOrdenOrigen() {
		return this.ordenOrigen;
	}

	public void setOrdenOrigen(Integer ordenOrigen) {
		this.ordenOrigen = ordenOrigen;
	}

	
	@Column(name = "orden_destino")
	public Integer getOrdenDestino() {
		return this.ordenDestino;
	}

	public void setOrdenDestino(Integer ordenDestino) {
		this.ordenDestino = ordenDestino;
	}

	@Column(name = "oee_destino", length = 100)
	@Length(max = 100)
	public String getOeeDestino() {
		return this.oeeDestino;
	}

	public void setOeeDestino(String oeeDestino) {
		this.oeeDestino = oeeDestino;
	}

	@Column(name = "tipo_traslado", length = 500)
	@Length(max = 500)
	public String getTipoTraslado() {
		return this.tipoTraslado;
	}

	public void setTipoTraslado(String tipoTraslado) {
		this.tipoTraslado = tipoTraslado;
	}

	@Column(name = "estado", length = 500)
	@Length(max = 500)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "nen_codigo", precision = 2, scale = 0)
	public Byte getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(Byte nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo", precision = 3, scale = 0)
	public Short getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Short entCodigo) {
		this.entCodigo = entCodigo;
	}

	@Column(name = "ent_nombre", length = 60)
	@Length(max = 60)
	public String getEntNombre() {
		return this.entNombre;
	}

	public void setEntNombre(String entNombre) {
		this.entNombre = entNombre;
	}

	@Column(name = "nivel_cod", precision = 2, scale = 0)
	public Byte getNivelCod() {
		return this.nivelCod;
	}

	public void setNivelCod(Byte nivelCod) {
		this.nivelCod = nivelCod;
	}

	@Column(name = "nivel_nombre", length = 60)
	@Length(max = 60)
	public String getNivelNombre() {
		return this.nivelNombre;
	}

	public void setNivelNombre(String nivelNombre) {
		this.nivelNombre = nivelNombre;
	}

	@Column(name = "actividad", length = 200)
	@Length(max = 200)
	public String getActividad() {
		return this.actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

	@Column(name = "usuario")
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
	
	@Column(name = "id_persona")
	public Long getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Long idPersona) {
		this.idPersona = idPersona;
	}
	
	@Column(name = "nombres")
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}
	
	@Column(name = "apellidos")
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "fecha_recepcion", length = 29)
	public Date getFechaRecepcion() {
		return this.fechaRecepcion;
	}

	public void setFechaRecepcion(Date fechaRecepcion) {
		this.fechaRecepcion = fechaRecepcion;
	}

	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "dias_creacion")
	public Integer getDiasCreacion() {
		return this.diasCreacion;
	}

	public void setDiasCreacion(Integer diasCreacion) {
		this.diasCreacion = diasCreacion;
	}

	@Column(name = "dias_inicio")
	public Integer getDiasInicio() {
		return this.diasInicio;
	}

	public void setDiasInicio(Integer diasInicio) {
		this.diasInicio = diasInicio;
	}

	@Column(name = "atraso", precision = 131089, scale = 0)
	public BigDecimal getAtraso() {
		return this.atraso;
	}

	public void setAtraso(BigDecimal atraso) {
		this.atraso = atraso;
	}

	@Column(name = "id_actividad")
	public Long getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(Long idActividad) {
		this.idActividad = idActividad;
	}

	@Column(name = "id_entidad")
	public Long getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Column(name = "id_sin_nivel_entidad")
	public Long getIdSinNivelEntidad() {
		return this.idSinNivelEntidad;
	}

	public void setIdSinNivelEntidad(Long idSinNivelEntidad) {
		this.idSinNivelEntidad = idSinNivelEntidad;
	}

	@Id 
	@Column(name = "id_taskinstance")
	public Long getIdTaskinstance() {
		return this.idTaskinstance;
	}

	public void setIdTaskinstance(Long idTaskinstance) {
		this.idTaskinstance = idTaskinstance;
	}

	@Column(name = "id_process_instance")
	public Long getIdProcessInstance() {
		return this.idProcessInstance;
	}

	public void setIdProcessInstance(Long idProcessInstance) {
		this.idProcessInstance = idProcessInstance;
	}

	@Column(name = "cod_actividad", length = 50)
	@Length(max = 50)
	public String getCodActividad() {
		return this.codActividad;
	}

	public void setCodActividad(String codActividad) {
		this.codActividad = codActividad;
	}

	@Column(name = "id_proceso")
	public Long getIdProceso() {
		return this.idProceso;
	}

	public void setIdProceso(Long idProceso) {
		this.idProceso = idProceso;
	}

		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad_proceso")
	public ActividadProceso getActividadProceso() {
		return actividadProceso;
	}

	public void setActividadProceso(ActividadProceso actividadProceso) {
		this.actividadProceso = actividadProceso;
	}

	@Column(name = "tipo_actividad", length = 20)
	@Length(max = 20)
	public String getTipoActividad() {
		return this.tipoActividad;
	}

	public void setTipoActividad(String tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	@Column(name = "id_sin_entidad")
	public Long getIdSinEntidad() {
		return this.idSinEntidad;
	}

	public void setIdSinEntidad(Long idSinEntidad) {
		this.idSinEntidad = idSinEntidad;
	}

	

	
	

}
