package py.com.excelsis.sicca.entity;

//Generated 08-nov-2011 15:14:45 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
* BandejaEntrada generated by hbm2java
*/
@Entity
@Table(name = "bandeja_entrada_csi", schema = "proceso")
public class BandejaEntradaCsi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3196484403509795547L;

	private Long id;
	
	private Long idConcurso;
	private String nombreConcurso;
	private Integer ordenConfiguracion;
	private String denominacionUnidadCab;
	private Byte nenCodigo;
	private Short entCodigo;
	private String entNombre;
	private String descripcionGrupo;
	private Byte nivelCod;
	private String nivelNombre;
	private String usuario;
	private Date fechaRecepcion;
	private Date fechaInicio;
	private Integer diasCreacion;
	private Integer diasInicio;
	private BigDecimal atraso;
	private Long idEntidad;
	private Long idSinNivelEntidad;
	private Long idSinEntidad;
	private Long idConcursoPuestoAgr; //id_concurso_puesto_agr
	private Long idProcessInstance; //id_process_instance
	private String codActividad;
	private Proceso proceso;
	private Actividad actividad;
	private ActividadProceso actividadProceso;
	private ConfiguracionUoCab configuracionUoCab;
	private String tipoActividad;

	public BandejaEntradaCsi(){
		
	}
	
	@Id 
	@Column(name = "id_taskinstance", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "id_concurso")
	public Long getIdConcurso() {
		return this.idConcurso;
	}

	public void setIdConcurso(Long idConcurso) {
		this.idConcurso = idConcurso;
	}

	@Column(name = "nombre_concurso", length = 100)
	@Length(max = 100)
	public String getNombreConcurso() {
		return this.nombreConcurso;
	}

	public void setNombreConcurso(String nombreConcurso) {
		this.nombreConcurso = nombreConcurso;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "orden_configuracion")
	public Integer getOrdenConfiguracion() {
		return this.ordenConfiguracion;
	}

	public void setOrdenConfiguracion(Integer ordenConfiguracion) {
		this.ordenConfiguracion = ordenConfiguracion;
	}

	@Column(name = "denominacion_unidad_cab", length = 100)
	@Length(max = 100)
	public String getDenominacionUnidadCab() {
		return this.denominacionUnidadCab;
	}

	public void setDenominacionUnidadCab(String denominacionUnidadCab) {
		this.denominacionUnidadCab = denominacionUnidadCab;
	}

	@Column(name = "nen_codigo", precision = 2, scale = 0)
	public Byte getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(Byte nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo", precision = 3, scale = 0)
	public Short getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Short entCodigo) {
		this.entCodigo = entCodigo;
	}

	@Column(name = "ent_nombre", length = 60)
	@Length(max = 60)
	public String getEntNombre() {
		return this.entNombre;
	}

	public void setEntNombre(String entNombre) {
		this.entNombre = entNombre;
	}

	@Column(name = "descripcion_grupo", length = 100)
	@Length(max = 100)
	public String getDescripcionGrupo() {
		return this.descripcionGrupo;
	}

	public void setDescripcionGrupo(String descripcionGrupo) {
		this.descripcionGrupo = descripcionGrupo;
	}
	
	
	@Column(name = "cod_actividad", length = 50)
	@Length(max = 50)
	public String getCodActividad() {
		return codActividad;
	}
	public void setCodActividad(String codActividad) {
		this.codActividad = codActividad;
	}
	

	@Column(name = "nivel_cod", precision = 2, scale = 0)
	public Byte getNivelCod() {
		return this.nivelCod;
	}

	public void setNivelCod(Byte nivelCod) {
		this.nivelCod = nivelCod;
	}

	@Column(name = "nivel_nombre", length = 60)
	@Length(max = 60)
	public String getNivelNombre() {
		return this.nivelNombre;
	}

	public void setNivelNombre(String nivelNombre) {
		this.nivelNombre = nivelNombre;
	}

	@Column(name = "usuario")
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "fecha_recepcion", length = 29)
	public Date getFechaRecepcion() {
		return this.fechaRecepcion;
	}

	public void setFechaRecepcion(Date fechaRecepcion) {
		this.fechaRecepcion = fechaRecepcion;
	}

	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "dias_creacion")
	public Integer getDiasCreacion() {
		return this.diasCreacion;
	}

	public void setDiasCreacion(Integer diasCreacion) {
		this.diasCreacion = diasCreacion;
	}

	@Column(name = "dias_inicio")
	public Integer getDiasInicio() {
		return this.diasInicio;
	}

	public void setDiasInicio(Integer diasInicio) {
		this.diasInicio = diasInicio;
	}

	@Column(name = "atraso")
	public BigDecimal getAtraso() {
		return this.atraso;
	}

	public void setAtraso(BigDecimal atraso) {
		this.atraso = atraso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad", nullable = false)
	@NotNull
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@Column(name = "id_entidad")
	public Long getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Column(name = "id_sin_nivel_entidad")
	public Long getIdSinNivelEntidad() {
		return this.idSinNivelEntidad;
	}

	public void setIdSinNivelEntidad(Long idSinNivelEntidad) {
		this.idSinNivelEntidad = idSinNivelEntidad;
	}
	
	
	@Column(name = "id_concurso_puesto_agr")
	public Long getIdConcursoPuestoAgr() {
		return idConcursoPuestoAgr;
	}
	public void setIdConcursoPuestoAgr(Long idConcursoPuestoAgr) {
		this.idConcursoPuestoAgr = idConcursoPuestoAgr;
	}

	@Column(name = "id_process_instance")
	public Long getIdProcessInstance() {
		return idProcessInstance;
	}
	public void setIdProcessInstance(Long idProcessInstance) {
		this.idProcessInstance = idProcessInstance;
	}
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BandejaEntradaCsi))
			return false;
		BandejaEntradaCsi castOther = (BandejaEntradaCsi) other;

		return ((this.getIdConcurso() == castOther.getIdConcurso()) || (this
				.getIdConcurso() != null && castOther.getIdConcurso() != null && this
				.getIdConcurso().equals(castOther.getIdConcurso())))
				&& ((this.getNombreConcurso() == castOther.getNombreConcurso()) || (this
						.getNombreConcurso() != null
						&& castOther.getNombreConcurso() != null && this
						.getNombreConcurso().equals(
								castOther.getNombreConcurso())))
				&& ((this.getOrdenConfiguracion() == castOther
						.getOrdenConfiguracion()) || (this
						.getOrdenConfiguracion() != null
						&& castOther.getOrdenConfiguracion() != null && this
						.getOrdenConfiguracion().equals(
								castOther.getOrdenConfiguracion())))
				&& ((this.getDenominacionUnidadCab() == castOther
						.getDenominacionUnidadCab()) || (this
						.getDenominacionUnidadCab() != null
						&& castOther.getDenominacionUnidadCab() != null && this
						.getDenominacionUnidadCab().equals(
								castOther.getDenominacionUnidadCab())))
				&& ((this.getNenCodigo() == castOther.getNenCodigo()) || (this
						.getNenCodigo() != null
						&& castOther.getNenCodigo() != null && this
						.getNenCodigo().equals(castOther.getNenCodigo())))
				&& ((this.getEntCodigo() == castOther.getEntCodigo()) || (this
						.getEntCodigo() != null
						&& castOther.getEntCodigo() != null && this
						.getEntCodigo().equals(castOther.getEntCodigo())))
				&& ((this.getEntNombre() == castOther.getEntNombre()) || (this
						.getEntNombre() != null
						&& castOther.getEntNombre() != null && this
						.getEntNombre().equals(castOther.getEntNombre())))
				&& ((this.getDescripcionGrupo() == castOther
						.getDescripcionGrupo()) || (this.getDescripcionGrupo() != null
						&& castOther.getDescripcionGrupo() != null && this
						.getDescripcionGrupo().equals(
								castOther.getDescripcionGrupo())))
				&& ((this.getNivelCod() == castOther.getNivelCod()) || (this
						.getNivelCod() != null
						&& castOther.getNivelCod() != null && this
						.getNivelCod().equals(castOther.getNivelCod())))
				&& ((this.getNivelNombre() == castOther.getNivelNombre()) || (this
						.getNivelNombre() != null
						&& castOther.getNivelNombre() != null && this
						.getNivelNombre().equals(castOther.getNivelNombre())))
				&& ((this.getActividad() == castOther.getActividad()) || (this
						.getActividad() != null
						&& castOther.getActividad() != null && this
						.getActividad().equals(castOther.getActividad())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null && castOther.getUsuario() != null && this
						.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getFechaRecepcion() == castOther.getFechaRecepcion()) || (this
						.getFechaRecepcion() != null
						&& castOther.getFechaRecepcion() != null && this
						.getFechaRecepcion().equals(
								castOther.getFechaRecepcion())))
				&& ((this.getFechaInicio() == castOther.getFechaInicio()) || (this
						.getFechaInicio() != null
						&& castOther.getFechaInicio() != null && this
						.getFechaInicio().equals(castOther.getFechaInicio())))
				&& ((this.getDiasCreacion() == castOther.getDiasCreacion()) || (this
						.getDiasCreacion() != null
						&& castOther.getDiasCreacion() != null && this
						.getDiasCreacion().equals(castOther.getDiasCreacion())))
				&& ((this.getDiasInicio() == castOther.getDiasInicio()) || (this
						.getDiasInicio() != null
						&& castOther.getDiasInicio() != null && this
						.getDiasInicio().equals(castOther.getDiasInicio())))
				&& ((this.getAtraso() == castOther.getAtraso()) || (this
						.getAtraso() != null && castOther.getAtraso() != null && this
						.getAtraso().equals(castOther.getAtraso())))
				&& ((this.getIdEntidad() == castOther.getIdEntidad()) || (this
						.getIdEntidad() != null
						&& castOther.getIdEntidad() != null && this
						.getIdEntidad().equals(castOther.getIdEntidad())))
				&& ((this.getIdSinNivelEntidad() == castOther
						.getIdSinNivelEntidad()) || (this
						.getIdSinNivelEntidad() != null
						&& castOther.getIdSinNivelEntidad() != null && this
						.getIdSinNivelEntidad().equals(
								castOther.getIdSinNivelEntidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdConcurso() == null ? 0 : this.getIdConcurso()
						.hashCode());
		result = 37
				* result
				+ (getNombreConcurso() == null ? 0 : this.getNombreConcurso()
						.hashCode());
		result = 37
				* result
				+ (getOrdenConfiguracion() == null ? 0 : this
						.getOrdenConfiguracion().hashCode());
		result = 37
				* result
				+ (getDenominacionUnidadCab() == null ? 0 : this
						.getDenominacionUnidadCab().hashCode());
		result = 37 * result
				+ (getNenCodigo() == null ? 0 : this.getNenCodigo().hashCode());
		result = 37 * result
				+ (getEntCodigo() == null ? 0 : this.getEntCodigo().hashCode());
		result = 37 * result
				+ (getEntNombre() == null ? 0 : this.getEntNombre().hashCode());
		result = 37
				* result
				+ (getDescripcionGrupo() == null ? 0 : this
						.getDescripcionGrupo().hashCode());
		result = 37 * result
				+ (getNivelCod() == null ? 0 : this.getNivelCod().hashCode());
		result = 37
				* result
				+ (getNivelNombre() == null ? 0 : this.getNivelNombre()
						.hashCode());
		result = 37 * result
				+ (getActividad() == null ? 0 : this.getActividad().hashCode());
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37
				* result
				+ (getFechaRecepcion() == null ? 0 : this.getFechaRecepcion()
						.hashCode());
		result = 37
				* result
				+ (getFechaInicio() == null ? 0 : this.getFechaInicio()
						.hashCode());
		result = 37
				* result
				+ (getDiasCreacion() == null ? 0 : this.getDiasCreacion()
						.hashCode());
		result = 37
				* result
				+ (getDiasInicio() == null ? 0 : this.getDiasInicio()
						.hashCode());
		result = 37 * result
				+ (getAtraso() == null ? 0 : this.getAtraso().hashCode());
		result = 37 * result
				+ (getIdEntidad() == null ? 0 : this.getIdEntidad().hashCode());
		result = 37
				* result
				+ (getIdSinNivelEntidad() == null ? 0 : this
						.getIdSinNivelEntidad().hashCode());
		return result;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proceso", nullable = false)
	public Proceso getProceso() {
		return this.proceso;
	}
	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad_proceso", nullable = false)
	public ActividadProceso getActividadProceso() {
		return actividadProceso;
	}
	public void setActividadProceso(ActividadProceso actividadProceso) {
		this.actividadProceso = actividadProceso;
	}

	@Column(name = "tipo_actividad", nullable = false, length = 20)
	@NotNull
	public String getTipoActividad() {
		return tipoActividad;
	}
	public void setTipoActividad(String tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	@Column(name = "id_sin_entidad")
	public Long getIdSinEntidad() {
		return idSinEntidad;
	}
	public void setIdSinEntidad(Long idSinEntidad) {
		this.idSinEntidad = idSinEntidad;
	}
	
}

