package py.com.excelsis.sicca.entity;

// Generated 11/12/2012 03:21:42 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * CabeceraHistoricoMovilidad generated by hbm2java
 */
@Entity
@Table(name = "cabecera_historico_movilidad", schema = "movilidad")
public class CabeceraHistoricoMovilidad implements java.io.Serializable {

	private Long idSolicitudTrasladoCab;
	private Long idOeeOrigen;
	private Date fechaAlta;
	private String usuAlta;
	private String oeeOrigen;
	private Integer ordenOrigen;
	private String tipoTraslado;
	private String estado;
	private Byte nenCodigo;
	private Short entCodigo;
	private String entNombre;
	private Byte nivelCod;
	private String nivelNombre;
	private String funcionario;

	public CabeceraHistoricoMovilidad() {
	}

	public CabeceraHistoricoMovilidad(Long idSolicitudTrasladoCab,
			Long idOeeOrigen, Date fechaAlta, String usuAlta, String oeeOrigen,
			Integer ordenOrigen, String tipoTraslado, String estado,
			Byte nenCodigo, Short entCodigo, String entNombre, Byte nivelCod,
			String nivelNombre, String funcionario) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
		this.idOeeOrigen = idOeeOrigen;
		this.fechaAlta = fechaAlta;
		this.usuAlta = usuAlta;
		this.oeeOrigen = oeeOrigen;
		this.ordenOrigen = ordenOrigen;
		this.tipoTraslado = tipoTraslado;
		this.estado = estado;
		this.nenCodigo = nenCodigo;
		this.entCodigo = entCodigo;
		this.entNombre = entNombre;
		this.nivelCod = nivelCod;
		this.nivelNombre = nivelNombre;
		this.funcionario = funcionario;
	}

	@Id
	@Column(name = "id_solicitud_traslado_cab")
	public Long getIdSolicitudTrasladoCab() {
		return this.idSolicitudTrasladoCab;
	}

	public void setIdSolicitudTrasladoCab(Long idSolicitudTrasladoCab) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
	}

	@Column(name = "id_oee_origen")
	public Long getIdOeeOrigen() {
		return this.idOeeOrigen;
	}

	public void setIdOeeOrigen(Long idOeeOrigen) {
		this.idOeeOrigen = idOeeOrigen;
	}

	@Column(name = "fecha_alta", length = 29)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_alta", length = 50)
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "oee_origen", length = 100)
	@Length(max = 100)
	public String getOeeOrigen() {
		return this.oeeOrigen;
	}

	public void setOeeOrigen(String oeeOrigen) {
		this.oeeOrigen = oeeOrigen;
	}

	@Column(name = "orden_origen")
	public Integer getOrdenOrigen() {
		return this.ordenOrigen;
	}

	public void setOrdenOrigen(Integer ordenOrigen) {
		this.ordenOrigen = ordenOrigen;
	}

	@Column(name = "tipo_traslado", length = 500)
	@Length(max = 500)
	public String getTipoTraslado() {
		return this.tipoTraslado;
	}

	public void setTipoTraslado(String tipoTraslado) {
		this.tipoTraslado = tipoTraslado;
	}

	@Column(name = "estado", length = 500)
	@Length(max = 500)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "nen_codigo", precision = 2, scale = 0)
	public Byte getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(Byte nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo", precision = 3, scale = 0)
	public Short getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Short entCodigo) {
		this.entCodigo = entCodigo;
	}

	@Column(name = "ent_nombre", length = 60)
	@Length(max = 60)
	public String getEntNombre() {
		return this.entNombre;
	}

	public void setEntNombre(String entNombre) {
		this.entNombre = entNombre;
	}

	@Column(name = "nivel_cod", precision = 2, scale = 0)
	public Byte getNivelCod() {
		return this.nivelCod;
	}

	public void setNivelCod(Byte nivelCod) {
		this.nivelCod = nivelCod;
	}

	@Column(name = "nivel_nombre", length = 60)
	@Length(max = 60)
	public String getNivelNombre() {
		return this.nivelNombre;
	}

	public void setNivelNombre(String nivelNombre) {
		this.nivelNombre = nivelNombre;
	}

	@Column(name = "funcionario")
	public String getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(String funcionario) {
		this.funcionario = funcionario;
	}


}
