package py.com.excelsis.sicca.entity;

// Generated 22-ago-2012 15:32:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CabValidacionOee generated by hbm2java
 */
@Entity
@Table(name = "cab_validacion_oee", schema = "general")
public class CabValidacionOee implements java.io.Serializable {

	private Long idCabValidacionOee;
	private ConfiguracionUoCab configuracionUoCab;
	private String nombreGrupoValidacion;
	private Boolean activo;
	private String justifEstado;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<DetValidacionOee> detValidacionOees = new HashSet<DetValidacionOee>(
			0);

	public CabValidacionOee() {
	}

	public CabValidacionOee(Long idCabValidacionOee, ConfiguracionUoCab configuracionUoCab,
			String nombreGrupoValidacion, String usuAlta, Date fechaAlta) {
		this.idCabValidacionOee = idCabValidacionOee;
		this.configuracionUoCab = configuracionUoCab;
		this.nombreGrupoValidacion = nombreGrupoValidacion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CabValidacionOee(Long idCabValidacionOee, ConfiguracionUoCab configuracionUoCab,
			String nombreGrupoValidacion, Boolean activo, String justifEstado,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<DetValidacionOee> detValidacionOees) {
		this.idCabValidacionOee = idCabValidacionOee;
		this.configuracionUoCab = configuracionUoCab;
		this.nombreGrupoValidacion = nombreGrupoValidacion;
		this.activo = activo;
		this.justifEstado = justifEstado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.detValidacionOees = detValidacionOees;
	}

	@Id
	@GeneratedValue(generator="CAB_VALIDACION_OEE_GENERATOR")
	@SequenceGenerator(name="CAB_VALIDACION_OEE_GENERATOR",sequenceName="general.cab_validacion_oee_id_cab_validacion_oee_seq")
	@Column(name = "id_cab_validacion_oee", unique = true, nullable = false)
	public Long getIdCabValidacionOee() {
		return this.idCabValidacionOee;
	}

	public void setIdCabValidacionOee(Long idCabValidacionOee) {
		this.idCabValidacionOee = idCabValidacionOee;
	}

	
	@Column(name = "nombre_grupo_validacion", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getNombreGrupoValidacion() {
		return this.nombreGrupoValidacion;
	}

	public void setNombreGrupoValidacion(String nombreGrupoValidacion) {
		this.nombreGrupoValidacion = nombreGrupoValidacion;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "justif_estado")
	public String getJustifEstado() {
		return this.justifEstado;
	}

	public void setJustifEstado(String justifEstado) {
		this.justifEstado = justifEstado;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 22)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 22)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cabValidacionOee")
	public Set<DetValidacionOee> getDetValidacionOees() {
		return this.detValidacionOees;
	}

	public void setDetValidacionOees(Set<DetValidacionOee> detValidacionOees) {
		this.detValidacionOees = detValidacionOees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}
	
	

}
