package py.com.excelsis.sicca.entity;

// Generated 22-ago-2012 15:32:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CabValidacion generated by hbm2java
 */
@Entity
@Table(name = "cab_validacion", schema = "general")
public class CabValidacion implements java.io.Serializable {

	private Long idCabValidacion;
	private String nombreGrupoValidacion;
	private Boolean activo;
	private String justifEstado;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<DetValidacion> detValidacions = new HashSet<DetValidacion>(0);

	public CabValidacion() {
	}

	public CabValidacion(Long idCabValidacion, String nombreGrupoValidacion,
			String usuAlta, Date fechaAlta) {
		this.idCabValidacion = idCabValidacion;
		this.nombreGrupoValidacion = nombreGrupoValidacion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CabValidacion(Long idCabValidacion, String nombreGrupoValidacion,
			Boolean activo, String justifEstado, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod,
			Set<DetValidacion> detValidacions) {
		this.idCabValidacion = idCabValidacion;
		this.nombreGrupoValidacion = nombreGrupoValidacion;
		this.activo = activo;
		this.justifEstado = justifEstado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.detValidacions = detValidacions;
	}

	@Id
	@GeneratedValue(generator="CAB_VALIDACION_GENERATOR")
	@SequenceGenerator(name="CAB_VALIDACION_GENERATOR",sequenceName="general.cab_validacion_id_cab_validacion_seq")
	@Column(name = "id_cab_validacion", unique = true, nullable = false)
	public Long getIdCabValidacion() {
		return this.idCabValidacion;
	}

	public void setIdCabValidacion(Long idCabValidacion) {
		this.idCabValidacion = idCabValidacion;
	}

	@Column(name = "nombre_grupo_validacion", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getNombreGrupoValidacion() {
		return this.nombreGrupoValidacion;
	}

	public void setNombreGrupoValidacion(String nombreGrupoValidacion) {
		this.nombreGrupoValidacion = nombreGrupoValidacion;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "justif_estado")
	public String getJustifEstado() {
		return this.justifEstado;
	}

	public void setJustifEstado(String justifEstado) {
		this.justifEstado = justifEstado;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 22)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 22)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cabValidacion")
	public Set<DetValidacion> getDetValidacions() {
		return this.detValidacions;
	}

	public void setDetValidacions(Set<DetValidacion> detValidacions) {
		this.detValidacions = detValidacions;
	}

}
