package py.com.excelsis.sicca.entity;

// Generated 09-nov-2011 15:20:12 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CalendarioOeeDet generated by hbm2java
 */
@Entity
@Table(name = "calendario_oee_det", schema = "seleccion")
public class CalendarioOeeDet implements java.io.Serializable {

	private Long idCalendarioOeeDet;
	private CalendarioOeeCab calendarioOeeCab;
	private String descripcion;
	private Date fechaFestiva;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public CalendarioOeeDet() {
	}

	public CalendarioOeeDet(Long idCalendarioOeeDet,
			CalendarioOeeCab calendarioOeeCab, String descripcion,
			Date fechaFestiva, boolean activo, String usuAlta, Date fechaAlta) {
		this.idCalendarioOeeDet = idCalendarioOeeDet;
		this.calendarioOeeCab = calendarioOeeCab;
		this.descripcion = descripcion;
		this.fechaFestiva = fechaFestiva;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CalendarioOeeDet(Long idCalendarioOeeDet,
			CalendarioOeeCab calendarioOeeCab, String descripcion,
			Date fechaFestiva, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idCalendarioOeeDet = idCalendarioOeeDet;
		this.calendarioOeeCab = calendarioOeeCab;
		this.descripcion = descripcion;
		this.fechaFestiva = fechaFestiva;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "CALENDARIO_OEE_DET_GENERATOR")
	@SequenceGenerator(name = "CALENDARIO_OEE_DET_GENERATOR", sequenceName = "seleccion.calendario_oee_det_id_calendario_oee_det_seq")
	@Column(name = "id_calendario_oee_det", unique = true, nullable = false)
	public Long getIdCalendarioOeeDet() {
		return this.idCalendarioOeeDet;
	}

	public void setIdCalendarioOeeDet(Long idCalendarioOeeDet) {
		this.idCalendarioOeeDet = idCalendarioOeeDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_calendario_oee_cab", nullable = false)
	@NotNull
	public CalendarioOeeCab getCalendarioOeeCab() {
		return this.calendarioOeeCab;
	}

	public void setCalendarioOeeCab(CalendarioOeeCab calendarioOeeCab) {
		this.calendarioOeeCab = calendarioOeeCab;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_festiva", nullable = false, length = 13)
	@NotNull
	public Date getFechaFestiva() {
		return this.fechaFestiva;
	}

	public void setFechaFestiva(Date fechaFestiva) {
		this.fechaFestiva = fechaFestiva;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
