package py.com.excelsis.sicca.entity;

// Generated 09-nov-2011 15:20:12 by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CalendarioOeeCab generated by hbm2java
 */
@Entity
@Table(name = "calendario_oee_cab", schema = "seleccion")
public class CalendarioOeeCab implements java.io.Serializable {

	private Long idCalendarioOeeCab;
	private ConfiguracionUoCab configuracionUoCab;
	private Integer anho;
	private Date lunHoraDesde;
	private Date lunHoraHasta;
	private Date marHoraDesde;
	private Date marHoraHasta;
	private Date mieHoraDesde;
	private Date mieHoraHasta;
	private Date jueHoraDesde;
	private Date jueHoraHasta;
	private Date vieHoraDesde;
	private Date vieHoraHasta;
	private Date sabHoraDesde;
	private Date sabHoraHasta;
	private Date domHoraDesde;
	private Date domHoraHasta;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private List<CalendarioOeeDet> calendarioOeeDets = new ArrayList<CalendarioOeeDet>();

	public CalendarioOeeCab() {
	}

	public CalendarioOeeCab(Long idCalendarioOeeCab, ConfiguracionUoCab idConfiguracionUo,
			Integer anho, String usuAlta, Date fechaAlta) {
		this.idCalendarioOeeCab = idCalendarioOeeCab;
		this.configuracionUoCab = idConfiguracionUo;
		this.anho = anho;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CalendarioOeeCab(Long idCalendarioOeeCab, ConfiguracionUoCab idConfiguracionUo,
			Integer anho, Date lunHoraDesde, Date lunHoraHasta, Date marHoraDesde,
			Date marHoraHasta, Date mieHoraDesde, Date mieHoraHasta,
			Date jueHoraDesde, Date jueHoraHasta, Date vieHoraDesde,
			Date vieHoraHasta, Date sabHoraDesde, Date sabHoraHasta,
			Date domHoraDesde, Date domHoraHasta, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod,
			List<CalendarioOeeDet> calendarioOeeDets) {
		this.idCalendarioOeeCab = idCalendarioOeeCab;
		this.configuracionUoCab = idConfiguracionUo;
		this.anho = anho;
		this.lunHoraDesde = lunHoraDesde;
		this.lunHoraHasta = lunHoraHasta;
		this.marHoraDesde = marHoraDesde;
		this.marHoraHasta = marHoraHasta;
		this.mieHoraDesde = mieHoraDesde;
		this.mieHoraHasta = mieHoraHasta;
		this.jueHoraDesde = jueHoraDesde;
		this.jueHoraHasta = jueHoraHasta;
		this.vieHoraDesde = vieHoraDesde;
		this.vieHoraHasta = vieHoraHasta;
		this.sabHoraDesde = sabHoraDesde;
		this.sabHoraHasta = sabHoraHasta;
		this.domHoraDesde = domHoraDesde;
		this.domHoraHasta = domHoraHasta;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.calendarioOeeDets = calendarioOeeDets;
	}

	@Id
	@GeneratedValue(generator = "CALENDARIO_OEE_CAB_GENERATOR")
	@SequenceGenerator(name = "CALENDARIO_OEE_CAB_GENERATOR", sequenceName = "seleccion.calendario_oee_cab_id_calendario_oee_cab_seq")
	@Column(name = "id_calendario_oee_cab", unique = true, nullable = false)
	public Long getIdCalendarioOeeCab() {
		return this.idCalendarioOeeCab;
	}

	public void setIdCalendarioOeeCab(Long idCalendarioOeeCab) {
		this.idCalendarioOeeCab = idCalendarioOeeCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	@NotNull
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "anho", nullable = false)
	public Integer getAnho() {
		return this.anho;
	}

	

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "lun_hora_desde", length = 15)
	public Date getLunHoraDesde() {
		return this.lunHoraDesde;
	}

	public void setLunHoraDesde(Date lunHoraDesde) {
		this.lunHoraDesde = lunHoraDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "lun_hora_hasta", length = 15)
	public Date getLunHoraHasta() {
		return this.lunHoraHasta;
	}

	public void setLunHoraHasta(Date lunHoraHasta) {
		this.lunHoraHasta = lunHoraHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "mar_hora_desde", length = 15)
	public Date getMarHoraDesde() {
		return this.marHoraDesde;
	}

	public void setMarHoraDesde(Date marHoraDesde) {
		this.marHoraDesde = marHoraDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "mar_hora_hasta", length = 15)
	public Date getMarHoraHasta() {
		return this.marHoraHasta;
	}

	public void setMarHoraHasta(Date marHoraHasta) {
		this.marHoraHasta = marHoraHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "mie_hora_desde", length = 15)
	public Date getMieHoraDesde() {
		return this.mieHoraDesde;
	}

	public void setMieHoraDesde(Date mieHoraDesde) {
		this.mieHoraDesde = mieHoraDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "mie_hora_hasta", length = 15)
	public Date getMieHoraHasta() {
		return this.mieHoraHasta;
	}

	public void setMieHoraHasta(Date mieHoraHasta) {
		this.mieHoraHasta = mieHoraHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "jue_hora_desde", length = 15)
	public Date getJueHoraDesde() {
		return this.jueHoraDesde;
	}

	public void setJueHoraDesde(Date jueHoraDesde) {
		this.jueHoraDesde = jueHoraDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "jue_hora_hasta", length = 15)
	public Date getJueHoraHasta() {
		return this.jueHoraHasta;
	}

	public void setJueHoraHasta(Date jueHoraHasta) {
		this.jueHoraHasta = jueHoraHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "vie_hora_desde", length = 15)
	public Date getVieHoraDesde() {
		return this.vieHoraDesde;
	}

	public void setVieHoraDesde(Date vieHoraDesde) {
		this.vieHoraDesde = vieHoraDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "vie_hora_hasta", length = 15)
	public Date getVieHoraHasta() {
		return this.vieHoraHasta;
	}

	public void setVieHoraHasta(Date vieHoraHasta) {
		this.vieHoraHasta = vieHoraHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "sab_hora_desde", length = 15)
	public Date getSabHoraDesde() {
		return this.sabHoraDesde;
	}

	public void setSabHoraDesde(Date sabHoraDesde) {
		this.sabHoraDesde = sabHoraDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "sab_hora_hasta", length = 15)
	public Date getSabHoraHasta() {
		return this.sabHoraHasta;
	}

	public void setSabHoraHasta(Date sabHoraHasta) {
		this.sabHoraHasta = sabHoraHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "dom_hora_desde", length = 15)
	public Date getDomHoraDesde() {
		return this.domHoraDesde;
	}

	public void setDomHoraDesde(Date domHoraDesde) {
		this.domHoraDesde = domHoraDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "dom_hora_hasta", length = 15)
	public Date getDomHoraHasta() {
		return this.domHoraHasta;
	}

	public void setDomHoraHasta(Date domHoraHasta) {
		this.domHoraHasta = domHoraHasta;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendarioOeeCab")
	public List<CalendarioOeeDet> getCalendarioOeeDets() {
		return this.calendarioOeeDets;
	}

	public void setCalendarioOeeDets(List<CalendarioOeeDet> calendarioOeeDets) {
		this.calendarioOeeDets = calendarioOeeDets;
	}

}
