package py.com.excelsis.sicca.entity;

// Generated 26/06/2012 10:48:30 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;

/**
 * CapacitacionFinalizada generated by hbm2java
 */
@Entity
@Table(name = "capacitacion_finalizada", schema = "capacitacion")
public class CapacitacionFinalizada implements java.io.Serializable {

	private Long idCapacitacion;
	private String denominacionUnidad;
	private String nombre;
	private String descripcion;
	private String modalidalidadDesc;
	private String modalidalidad;
	private Date fechaPubDesde;
	private Date fechaPubHasta;
	private Ciudad ciudad;
	private Date fechaInicio;
	private Date fechaFin;
	private DatosEspecificos datosEspecificos;

	public CapacitacionFinalizada() {
	}

	public CapacitacionFinalizada(Long idCapacitacion,
			String denominacionUnidad, String nombre, String descripcion,
			String modalidalidadDesc, String modalidalidad, Date fechaPubDesde,
			Date fechaPubHasta, Ciudad idCiudad,Departamento idDepartamento, Pais idPais) {
		this.idCapacitacion = idCapacitacion;
		this.denominacionUnidad = denominacionUnidad;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.modalidalidadDesc = modalidalidadDesc;
		this.modalidalidad = modalidalidad;
		this.fechaPubDesde = fechaPubDesde;
		this.fechaPubHasta = fechaPubHasta;
		this.ciudad = idCiudad;
		
	}
	@Id
	@Column(name = "id_capacitacion")
	public Long getIdCapacitacion() {
		return this.idCapacitacion;
	}

	public void setIdCapacitacion(Long idCapacitacion) {
		this.idCapacitacion = idCapacitacion;
	}

	@Column(name = "denominacion_unidad", length = 100)
	@Length(max = 100)
	public String getDenominacionUnidad() {
		return this.denominacionUnidad;
	}

	public void setDenominacionUnidad(String denominacionUnidad) {
		this.denominacionUnidad = denominacionUnidad;
	}

	@Column(name = "nombre", length = 300)
	@Length(max = 300)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "modalidalidad_desc")
	public String getModalidalidadDesc() {
		return this.modalidalidadDesc;
	}

	public void setModalidalidadDesc(String modalidalidadDesc) {
		this.modalidalidadDesc = modalidalidadDesc;
	}

	@Column(name = "modalidalidad", length = 1)
	@Length(max = 1)
	public String getModalidalidad() {
		return this.modalidalidad;
	}

	public void setModalidalidad(String modalidalidad) {
		this.modalidalidad = modalidalidad;
	}

	@Column(name = "fecha_pub_desde", length = 29)
	public Date getFechaPubDesde() {
		return this.fechaPubDesde;
	}

	public void setFechaPubDesde(Date fechaPubDesde) {
		this.fechaPubDesde = fechaPubDesde;
	}

	@Column(name = "fecha_pub_hasta", length = 29)
	public Date getFechaPubHasta() {
		return this.fechaPubHasta;
	}

	public void setFechaPubHasta(Date fechaPubHasta) {
		this.fechaPubHasta = fechaPubHasta;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciudad")
	public Ciudad getCiudad() {
		return ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos")
	public DatosEspecificos getDatosEspecificos() {
		return datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio",  length = 29)
	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin",  length = 29)
	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
	

	

}
