package py.com.excelsis.sicca.entity;

// Generated 29/05/2012 10:38:34 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Capacitaciones generated by hbm2java
 */
@Entity
@Table(name = "capacitaciones", schema = "capacitacion")
public class Capacitaciones implements java.io.Serializable {

	private Long idCapacitacion;
	private String tipo;
	private ConfiguracionUoCab configuracionUoCab;
	private ConfiguracionUoDet configuracionUoDet;
	private String nombre;
	private DatosEspecificos datosEspecificosTipoCap;
	private String observacion;
	private String tipoSeleccion;
	private String modalidad;
	private Boolean recepcionPostulacion;
	private Boolean requiereComision;
	private String sede;
	private Ciudad ciudad;
	private String direccion;
	private Date fechaInicio;
	private Date fechaFin;
	private Float costo;
	private Long credito;
	private Long cupoMinino;
	private Long cupoMaximo;
	private Long cargaHoraria;
	private String fuenteFinanciacion;
	private String destinadoA;
	private Integer estado;
	private Long idProcessInstance;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String motivoCancelacion;
	private String usuCancelacion;
	private String fechaCancelacion;
	private Documentos documentos;
	private Date fechaRecepDesde;
	private Date fechaRecepHasta;
	private Date fechaPubHasta;
	private Date fechaPubDesde;
	private String estadoPublic;
	private String tituloPublic;
	private String tipoCosto;
	private ConfiguracionUoCab configuracionUoCabOeeDicta;
	private DatosEspecificos datosEspecificosInstDicta;
	private InstitucionEducativa institucionEducativa;

	private Set<CapacitacionFinanciacion> capacitacionFinanciacions =
		new HashSet<CapacitacionFinanciacion>(0);
	private Set<CapacitacionCerrada> capacitacionCerradas = new HashSet<CapacitacionCerrada>(0);
	private Set<ComisionCapacEval> comisionCapacEvals = new HashSet<ComisionCapacEval>(0);
	private Set<Instructores> instructoreses = new HashSet<Instructores>(0);
	private Set<EvaluacionTipo> evaluacionTipos = new HashSet<EvaluacionTipo>(0);
	private Set<ProrrogaCap> prorrogaCaps = new HashSet<ProrrogaCap>(0);

	public Capacitaciones() {
	}

	public Capacitaciones(
			Long idCapacitacion, String tipo, ConfiguracionUoCab idConfiguracionUo, String nombre,
			DatosEspecificos idDatosEspecificosTipoCap, Date fechaInicio, Date fechaFin,
			Float costo, Integer estado, Boolean activo, String usuAlta, Date fechaAlta) {
		this.idCapacitacion = idCapacitacion;
		this.tipo = tipo;
		this.configuracionUoCab = idConfiguracionUo;
		this.nombre = nombre;
		this.datosEspecificosTipoCap = idDatosEspecificosTipoCap;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.costo = costo;
		this.estado = estado;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public Capacitaciones(
			Long idCapacitacion, String tipo, ConfiguracionUoCab idConfiguracionUo,
			ConfiguracionUoDet idConfiguracionUoDet, String nombre,
			DatosEspecificos idDatosEspecificosTipoCap, String observacion, String tipoSeleccion,
			String modalidad, Boolean recepcionPostulacion, Boolean requiereComision, String sede,
			Ciudad idCiudad, String direccion, Date fechaInicio, Date fechaFin, Float costo,
			Long credito, Long cupoMinimo, Long cupoMaximo, Long cargaHoraria, String fuenteFinanciacion,
			String destinadoA, Integer estado, Long idProcessInstance, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod, String motivoCancelacion,
			String usuCancelacion, String fechaCancelacion,
			Set<CapacitacionFinanciacion> capacitacionFinanciacions,
			Set<CapacitacionCerrada> capacitacionCerradas,
			Set<ComisionCapacEval> comisionCapacEvals, Set<Instructores> instructoreses) {
		this.idCapacitacion = idCapacitacion;
		this.tipo = tipo;
		this.configuracionUoCab = idConfiguracionUo;
		this.configuracionUoDet = idConfiguracionUoDet;
		this.nombre = nombre;
		this.datosEspecificosTipoCap = idDatosEspecificosTipoCap;
		this.observacion = observacion;
		this.tipoSeleccion = tipoSeleccion;
		this.modalidad = modalidad;
		this.recepcionPostulacion = recepcionPostulacion;
		this.requiereComision = requiereComision;
		this.sede = sede;
		this.ciudad = idCiudad;
		this.direccion = direccion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.costo = costo;
		this.credito = credito;
		this.cupoMinino = cupoMinimo;
		this.cupoMaximo = cupoMaximo;
		this.cargaHoraria = cargaHoraria;
		this.fuenteFinanciacion = fuenteFinanciacion;
		this.destinadoA = destinadoA;
		this.estado = estado;
		this.idProcessInstance = idProcessInstance;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.motivoCancelacion = motivoCancelacion;
		this.usuCancelacion = usuCancelacion;
		this.fechaCancelacion = fechaCancelacion;
		this.capacitacionFinanciacions = capacitacionFinanciacions;
		this.capacitacionCerradas = capacitacionCerradas;
		this.comisionCapacEvals = comisionCapacEvals;
		this.instructoreses = instructoreses;
	}

	@Id
	@Column(name = "id_capacitacion", unique = true, nullable = false)
	@GeneratedValue(generator = "CAPACITACIONES_GENERATOR")
	@SequenceGenerator(name = "CAPACITACIONES_GENERATOR", sequenceName = "capacitacion.capacitaciones_id_capacitacion_seq")
	public Long getIdCapacitacion() {
		return this.idCapacitacion;
	}

	public void setIdCapacitacion(Long idCapacitacion) {
		this.idCapacitacion = idCapacitacion;
	}

	@Column(name = "tipo", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_det", nullable = false)
	public ConfiguracionUoDet getConfiguracionUoDet() {
		return configuracionUoDet;
	}

	public void setConfiguracionUoDet(ConfiguracionUoDet configuracionUoDet) {
		this.configuracionUoDet = configuracionUoDet;
	}

	@Column(name = "nombre", nullable = false, length = 300)
	@NotNull
	@Length(max = 300)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_cap", nullable = false)
	public DatosEspecificos getDatosEspecificosTipoCap() {
		return datosEspecificosTipoCap;
	}

	public void setDatosEspecificosTipoCap(DatosEspecificos datosEspecificosTipoCap) {
		this.datosEspecificosTipoCap = datosEspecificosTipoCap;
	}

	@Column(name = "observacion", length = 1000)
	@Length(max = 1000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "tipo_seleccion", length = 1)
	@Length(max = 1)
	public String getTipoSeleccion() {
		return this.tipoSeleccion;
	}

	public void setTipoSeleccion(String tipoSeleccion) {
		this.tipoSeleccion = tipoSeleccion;
	}

	@Column(name = "modalidad", length = 1)
	@Length(max = 1)
	public String getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(String modalidad) {
		this.modalidad = modalidad;
	}

	@Column(name = "recepcion_postulacion")
	public Boolean getRecepcionPostulacion() {
		return this.recepcionPostulacion;
	}

	public void setRecepcionPostulacion(Boolean recepcionPostulacion) {
		this.recepcionPostulacion = recepcionPostulacion;
	}

	@Column(name = "requiere_comision")
	public Boolean getRequiereComision() {
		return this.requiereComision;
	}

	public void setRequiereComision(Boolean requiereComision) {
		this.requiereComision = requiereComision;
	}

	@Column(name = "sede", length = 500)
	@Length(max = 500)
	public String getSede() {
		return this.sede;
	}

	public void setSede(String sede) {
		this.sede = sede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciudad")
	public Ciudad getCiudad() {
		return ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "direccion", length = 500)
	@Length(max = 500)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "costo", precision = 16, scale = 8)
	public Float getCosto() {
		return this.costo;
	}

	public void setCosto(Float costo) {
		this.costo = costo;
	}

	@Column(name = "credito")
	public Long getCredito() {
		return this.credito;
	}

	public void setCredito(Long credito) {
		this.credito = credito;
	}

	//@Column(name = "cupo_minimo", nullable = false)
	//@NotNull
	@Column(name = "cupo_minimo")
	public Long getCupoMinimo() {
		return this.cupoMinino;
	}

	public void setCupoMinimo(Long cupoMinimo) {
		this.cupoMinino = cupoMinimo;
	}
	
	//@Column(name = "cupo_maximo", nullable = false)
	//@NotNull
	@Column(name = "cupo_maximo")
	public Long getCupoMaximo() {
		return this.cupoMaximo;
	}

	public void setCupoMaximo(Long cupoMaximo) {
		this.cupoMaximo = cupoMaximo;
	}

	@Column(name = "carga_horaria")
	public Long getCargaHoraria() {
		return this.cargaHoraria;
	}

	public void setCargaHoraria(Long cargaHoraria) {
		this.cargaHoraria = cargaHoraria;
	}

	@Column(name = "fuente_financiacion", length = 500)
	@Length(max = 500)
	public String getFuenteFinanciacion() {
		return this.fuenteFinanciacion;
	}

	public void setFuenteFinanciacion(String fuenteFinanciacion) {
		this.fuenteFinanciacion = fuenteFinanciacion;
	}

	@Column(name = "destinado_a", length = 1)
	@Length(max = 1)
	public String getDestinadoA() {
		return this.destinadoA;
	}

	public void setDestinadoA(String destinadoA) {
		this.destinadoA = destinadoA;
	}

	@Column(name = "estado", nullable = false)
	@NotNull
	public Integer getEstado() {
		return estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "id_process_instance")
	public Long getIdProcessInstance() {
		return this.idProcessInstance;
	}

	public void setIdProcessInstance(Long idProcessInstance) {
		this.idProcessInstance = idProcessInstance;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "motivo_cancelacion", length = 1000)
	@Length(max = 1000)
	public String getMotivoCancelacion() {
		return this.motivoCancelacion;
	}

	public void setMotivoCancelacion(String motivoCancelacion) {
		this.motivoCancelacion = motivoCancelacion;
	}

	@Column(name = "usu_cancelacion", length = 50)
	@Length(max = 50)
	public String getUsuCancelacion() {
		return this.usuCancelacion;
	}

	public void setUsuCancelacion(String usuCancelacion) {
		this.usuCancelacion = usuCancelacion;
	}

	@Column(name = "fecha_cancelacion")
	public String getFechaCancelacion() {
		return this.fechaCancelacion;
	}

	public void setFechaCancelacion(String fechaCancelacion) {
		this.fechaCancelacion = fechaCancelacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capacitaciones")
	public Set<CapacitacionFinanciacion> getCapacitacionFinanciacions() {
		return this.capacitacionFinanciacions;
	}

	public void setCapacitacionFinanciacions(Set<CapacitacionFinanciacion> capacitacionFinanciacions) {
		this.capacitacionFinanciacions = capacitacionFinanciacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capacitaciones")
	public Set<CapacitacionCerrada> getCapacitacionCerradas() {
		return this.capacitacionCerradas;
	}

	public void setCapacitacionCerradas(Set<CapacitacionCerrada> capacitacionCerradas) {
		this.capacitacionCerradas = capacitacionCerradas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capacitaciones")
	public Set<ComisionCapacEval> getComisionCapacEvals() {
		return this.comisionCapacEvals;
	}

	public void setComisionCapacEvals(Set<ComisionCapacEval> comisionCapacEvals) {
		this.comisionCapacEvals = comisionCapacEvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capacitaciones")
	public Set<Instructores> getInstructoreses() {
		return this.instructoreses;
	}

	public void setInstructoreses(Set<Instructores> instructoreses) {
		this.instructoreses = instructoreses;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_recep_desde", length = 29)
	public Date getFechaRecepDesde() {
		return fechaRecepDesde;
	}

	public void setFechaRecepDesde(Date fechaRecepDesde) {
		this.fechaRecepDesde = fechaRecepDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_recep_hasta", length = 29)
	public Date getFechaRecepHasta() {
		return fechaRecepHasta;
	}

	public void setFechaRecepHasta(Date fechaRecepHasta) {
		this.fechaRecepHasta = fechaRecepHasta;
	}

	@Column(name = "estado_public", length = 15)
	@Length(max = 15)
	public String getEstadoPublic() {
		return estadoPublic;
	}

	public void setEstadoPublic(String estadoPublic) {
		this.estadoPublic = estadoPublic;
	}

	@Column(name = "titulo_public", length = 1000)
	@Length(max = 1000)
	public String getTituloPublic() {
		return tituloPublic;
	}

	public void setTituloPublic(String tituloPublic) {
		this.tituloPublic = tituloPublic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pub_desde", length = 29)
	public Date getFechaPubDesde() {
		return fechaPubDesde;
	}

	public void setFechaPubDesde(Date fechaPubDesde) {
		this.fechaPubDesde = fechaPubDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pub_hasta", length = 29)
	public Date getFechaPubHasta() {
		return fechaPubHasta;
	}

	public void setFechaPubHasta(Date fechaPubHasta) {
		this.fechaPubHasta = fechaPubHasta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capacitaciones")
	public Set<EvaluacionTipo> getEvaluacionTipos() {
		return this.evaluacionTipos;
	}

	public void setEvaluacionTipos(Set<EvaluacionTipo> evaluacionTipos) {
		this.evaluacionTipos = evaluacionTipos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capacitaciones")
	public Set<ProrrogaCap> getProrrogaCaps() {
		return this.prorrogaCaps;
	}

	public void setProrrogaCaps(Set<ProrrogaCap> prorrogaCaps) {
		this.prorrogaCaps = prorrogaCaps;
	}
	@Column(name = "tipo_costo", length = 1)
	@Length(max = 1)
	public String getTipoCosto() {
		return tipoCosto;
	}

	public void setTipoCosto(String tipoCosto) {
		this.tipoCosto = tipoCosto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oee_dicta")
	public ConfiguracionUoCab getConfiguracionUoCabOeeDicta() {
		return configuracionUoCabOeeDicta;
	}

	public void setConfiguracionUoCabOeeDicta(
			ConfiguracionUoCab configuracionUoCabOeeDicta) {
		this.configuracionUoCabOeeDicta = configuracionUoCabOeeDicta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_inst_dicta")
	public DatosEspecificos getDatosEspecificosInstDicta() {
		return datosEspecificosInstDicta;
	}

	public void setDatosEspecificosInstDicta(
			DatosEspecificos datosEspecificosInstDicta) {
		this.datosEspecificosInstDicta = datosEspecificosInstDicta;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inst_educativa")
	public InstitucionEducativa getInstitucionEducativa() {
		return institucionEducativa;
	}

	public void setInstitucionEducativa(InstitucionEducativa institucionEducativa) {
		this.institucionEducativa = institucionEducativa;
	}
	
	
}
