package py.com.excelsis.sicca.entity;
// Generated 26/06/2012 10:48:30 AM by Hibernate Tools 3.4.0.Beta1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;

/**
 * CapacitacionEnProceso generated by hbm2java
 */
@Entity
@Table(name = "capacitacion_en_proceso", schema = "capacitacion")
public class CapacitacionEnProceso implements java.io.Serializable {


     private Long idCapacitacion;
     private String denominacionUnidad;
     private String nombre;
     private String descripcion;
     private String modalidadDesc;
     private String modalidad;
     private Date fechaPubDesde;
     private Date fechaPubHasta;
     private Ciudad ciudad;
     private DatosEspecificos datosEspecificos;
     private Date fechaInicio;
     private Date fechaFin;
     

    public CapacitacionEnProceso() {
    }

    public CapacitacionEnProceso(Long idCapacitacion, String denominacionUnidad, String nombre, String descripcion, String modalidadDesc, String modalidad, Date fechaPubDesde, Date fechaPubHasta, Ciudad idCiudad, Departamento idDepartamento, Pais idPais) {
       this.idCapacitacion = idCapacitacion;
       this.denominacionUnidad = denominacionUnidad;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.modalidadDesc = modalidadDesc;
       this.modalidad = modalidad;
       this.fechaPubDesde = fechaPubDesde;
       this.fechaPubHasta = fechaPubHasta;
       this.ciudad = idCiudad;
     
    }
   

    @Id
    @Column(name="id_capacitacion")
    public Long getIdCapacitacion() {
        return this.idCapacitacion;
    }
    
    public void setIdCapacitacion(Long idCapacitacion) {
        this.idCapacitacion = idCapacitacion;
    }


    @Column(name="denominacion_unidad", length=100)
    @Length(max=100)
    public String getDenominacionUnidad() {
        return this.denominacionUnidad;
    }
    
    public void setDenominacionUnidad(String denominacionUnidad) {
        this.denominacionUnidad = denominacionUnidad;
    }


    @Column(name="nombre", length=300)
    @Length(max=300)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    @Column(name="descripcion", length=500)
    @Length(max=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    @Column(name="modalidad_desc")
    public String getModalidadDesc() {
        return this.modalidadDesc;
    }
    
    public void setModalidadDesc(String modalidadDesc) {
        this.modalidadDesc = modalidadDesc;
    }


    @Column(name="modalidad", length=1)
    @Length(max=1)
    public String getModalidad() {
        return this.modalidad;
    }
    
    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_pub_desde", length=29)
    public Date getFechaPubDesde() {
        return this.fechaPubDesde;
    }
    
    public void setFechaPubDesde(Date fechaPubDesde) {
        this.fechaPubDesde = fechaPubDesde;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_pub_hasta", length=29)
    public Date getFechaPubHasta() {
        return this.fechaPubHasta;
    }
    
    public void setFechaPubHasta(Date fechaPubHasta) {
        this.fechaPubHasta = fechaPubHasta;
    }


  
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciudad")
	public Ciudad getCiudad() {
		return ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos")
	public DatosEspecificos getDatosEspecificos() {
		return datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio",  length = 29)
	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin",  length = 29)
	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	

  

}


