package py.com.excelsis.sicca.entity;

// Generated 29/05/2012 10:38:34 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CapacitacionCerrada generated by hbm2java
 */
@Entity
@Table(name = "capacitacion_cerrada", schema = "capacitacion")
public class CapacitacionCerrada implements java.io.Serializable {

	private Long idCapacitacionCerrada;
	private Capacitaciones capacitaciones;
	private ConfiguracionUoCab configuracionUo;
	private Long cupo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private ConfiguracionUoDet configuracionUoDet;

	public CapacitacionCerrada() {
	}

	public CapacitacionCerrada(Long idCapacitacionCerrada,
			Capacitaciones capacitaciones, ConfiguracionUoCab idConfiguracionUo, Long cupo,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idCapacitacionCerrada = idCapacitacionCerrada;
		this.capacitaciones = capacitaciones;
		this.configuracionUo = idConfiguracionUo;
		this.cupo = cupo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CapacitacionCerrada(Long idCapacitacionCerrada,
			Capacitaciones capacitaciones, ConfiguracionUoCab idConfiguracionUo, Long cupo,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idCapacitacionCerrada = idCapacitacionCerrada;
		this.capacitaciones = capacitaciones;
		this.configuracionUo = idConfiguracionUo;
		this.cupo = cupo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_capacitacion_cerrada", unique = true, nullable = false)
	@GeneratedValue(generator="CAPACITACION_CERRADA_GENERATOR")
	@SequenceGenerator(name="CAPACITACION_CERRADA_GENERATOR",sequenceName="capacitacion.capacitacion_cerrada_id_capacitacion_cerrada_seq")
	public Long getIdCapacitacionCerrada() {
		return this.idCapacitacionCerrada;
	}

	public void setIdCapacitacionCerrada(Long idCapacitacionCerrada) {
		this.idCapacitacionCerrada = idCapacitacionCerrada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion", nullable = false)
	@NotNull
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	public ConfiguracionUoCab getConfiguracionUo() {
		return configuracionUo;
	}

	public void setConfiguracionUo(ConfiguracionUoCab configuracionUo) {
		this.configuracionUo = configuracionUo;
	}
	
	
	@Column(name = "cupo")
	public Long getCupo() {
		return this.cupo;
	}

	

	public void setCupo(Long cupo) {
		this.cupo = cupo;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_det")
	public ConfiguracionUoDet getConfiguracionUoDet() {
		return configuracionUoDet;
	}

	public void setConfiguracionUoDet(ConfiguracionUoDet configuracionUoDet) {
		this.configuracionUoDet = configuracionUoDet;
	}
	
	

}
