package py.com.excelsis.sicca.entity;

// Generated 29/05/2012 10:38:34 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CapacitacionFinanciacion generated by hbm2java
 */
@Entity
@Table(name = "capacitacion_financiacion", schema = "capacitacion")
public class CapacitacionFinanciacion implements java.io.Serializable {

	private Long idCapacitacionFinanciacion;
	private Capacitaciones capacitaciones;
	private DatosEspecificos datosEspecificosInst;
	private ConfiguracionUoCab configuracionUo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String fuenteFinanciacion;

	public CapacitacionFinanciacion() {
	}

	public CapacitacionFinanciacion(Long idCapacitacionFinanciacion,
			Capacitaciones capacitaciones, Boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idCapacitacionFinanciacion = idCapacitacionFinanciacion;
		this.capacitaciones = capacitaciones;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CapacitacionFinanciacion(Long idCapacitacionFinanciacion,
			Capacitaciones capacitaciones, DatosEspecificos idDatosEspecificosInst,
			ConfiguracionUoCab idConfiguracionUo, Boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idCapacitacionFinanciacion = idCapacitacionFinanciacion;
		this.capacitaciones = capacitaciones;
		this.datosEspecificosInst = idDatosEspecificosInst;
		this.configuracionUo = idConfiguracionUo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_capacitacion_financiacion", unique = true, nullable = false)
	@GeneratedValue(generator="CAPACITACION_FINANCIACION_GENERATOR")
	@SequenceGenerator(name="CAPACITACION_FINANCIACION_GENERATOR",sequenceName="capacitacion.capacitacion_financiacion_id_capacitacion_financiacion_seq")
	public Long getIdCapacitacionFinanciacion() {
		return this.idCapacitacionFinanciacion;
	}

	public void setIdCapacitacionFinanciacion(Long idCapacitacionFinanciacion) {
		this.idCapacitacionFinanciacion = idCapacitacionFinanciacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion", nullable = false)
	@NotNull
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_inst")
	public DatosEspecificos getDatosEspecificosInst() {
		return datosEspecificosInst;
	}

	public void setDatosEspecificosInst(DatosEspecificos datosEspecificosInst) {
		this.datosEspecificosInst = datosEspecificosInst;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUo() {
		return configuracionUo;
	}

	public void setConfiguracionUo(ConfiguracionUoCab configuracionUo) {
		this.configuracionUo = configuracionUo;
	}
	
	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}


	public void setActivo(Boolean activo) {
		this.activo = activo;
	}


	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	
	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "fuente_financiacion")
	public String getFuenteFinanciacion() {
		return fuenteFinanciacion;
	}

	public void setFuenteFinanciacion(String fuenteFinanciacion) {
		this.fuenteFinanciacion = fuenteFinanciacion;
	}
	
	

}
