package py.com.excelsis.sicca.entity;

// Generated 09/11/2012 10:32:07 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CapacitacionesPersona generated by hbm2java
 */
@Entity
@Table(name = "capacitaciones_persona", schema = "movilidad")
public class CapacitacionesPersona implements java.io.Serializable {

	private String curso;
	private Long cargaHoraria;
	private String origen;
	private Documentos documento;
	private Long idPersona;
	private String idEstudiosRealizados;
	private Capacitaciones capacitacion;
	private boolean seleccionar;

	public CapacitacionesPersona() {
	}

	public CapacitacionesPersona(String curso, Long cargaHoraria,
			String origen, Documentos documento, Long idPersona,
			String idEstudiosRealizados, Capacitaciones idCapacitacion) {
		this.curso = curso;
		this.cargaHoraria = cargaHoraria;
		this.origen = origen;
		this.documento = documento;
		this.idPersona = idPersona;
		this.idEstudiosRealizados = idEstudiosRealizados;
		this.capacitacion = idCapacitacion;
	}

	@Column(name = "curso")
	public String getCurso() {
		return this.curso;
	}

	public void setCurso(String curso) {
		this.curso = curso;
	}

	@Column(name = "carga_horaria")
	public Long getCargaHoraria() {
		return this.cargaHoraria;
	}

	public void setCargaHoraria(Long cargaHoraria) {
		this.cargaHoraria = cargaHoraria;
	}

	@Column(name = "origen")
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	
	

	@Column(name = "id_persona")
	@Id
	public Long getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Long idPersona) {
		this.idPersona = idPersona;
	}

	@Column(name = "id_estudios_realizados")
	public String getIdEstudiosRealizados() {
		return this.idEstudiosRealizados;
	}

	public void setIdEstudiosRealizados(String idEstudiosRealizados) {
		this.idEstudiosRealizados = idEstudiosRealizados;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion")
	public Capacitaciones getCapacitacion() {
		return capacitacion;
	}

	public void setCapacitacion(Capacitaciones capacitacion) {
		this.capacitacion = capacitacion;
	}

	@Transient
	public boolean isSeleccionar() {
		return seleccionar;
	}

	public void setSeleccionar(boolean seleccionar) {
		this.seleccionar = seleccionar;
	}
		
	

}
