package py.com.excelsis.sicca.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ciudad generated by Generality
 */
@Entity
@Table(name = "ciudad", schema = "general")
public class Ciudad implements java.io.Serializable {
	private Long idCiudad;
	private String descripcion;
	private Departamento departamento;
	private Integer ciuCodigoSinarh;
	private Boolean activo;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Set<EmprTercerizada> emprTercerizadas = new HashSet<EmprTercerizada>(0);
	private Set<OrganizacionDiscapacitados> organizacionDiscapacitadoses =
		new HashSet<OrganizacionDiscapacitados>(0);

	public Ciudad() {
	}

	public Ciudad(Long idCiudad) {
		this.idCiudad = idCiudad;
	}

	@Id
	@GeneratedValue(generator = "CIUDAD_GENERATOR")
	@SequenceGenerator(name = "CIUDAD_GENERATOR", sequenceName = "general.ciudad_id_ciudad_seq")
	@Column(name = "id_ciudad")
	public Long getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(Long idCiudad) {
		this.idCiudad = idCiudad;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "ciu_codigo_sinarh")
	public Integer getCiuCodigoSinarh() {
		return this.ciuCodigoSinarh;
	}

	public void setCiuCodigoSinarh(Integer ciuCodigoSinarh) {
		this.ciuCodigoSinarh = ciuCodigoSinarh;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<EmprTercerizada> getEmprTercerizadas() {
		return this.emprTercerizadas;
	}

	public void setEmprTercerizadas(Set<EmprTercerizada> emprTercerizadas) {
		this.emprTercerizadas = emprTercerizadas;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idCiudad == null) ? 0 : idCiudad.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Ciudad other = (Ciudad) obj;
		if (idCiudad == null) {
			if (other.idCiudad != null)
				return false;
		} else if (!idCiudad.equals(other.idCiudad))
			return false;
		return true;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<OrganizacionDiscapacitados> getOrganizacionDiscapacitadoses() {
		return this.organizacionDiscapacitadoses;
	}

	public void setOrganizacionDiscapacitadoses(Set<OrganizacionDiscapacitados> organizacionDiscapacitadoses) {
		this.organizacionDiscapacitadoses = organizacionDiscapacitadoses;
	}
}
