package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Properties;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * ClasificadorUoRequisito generated by Generality
 */
@Entity
@Table(name = "clasificador_uo_requisito", schema = "planificacion")
public class ClasificadorUoRequisito implements java.io.Serializable {
	private Long idClasificadorUoRequisito;
	private RequisitoMinimoCuo requisitoMinimoCuo;
	private ClasificadorUo clasificadorUo;
	private String descripcion;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ClasificadorUoRequisito() {
	}

	public ClasificadorUoRequisito(Long idClasificadorUoRequisito) {
		this.idClasificadorUoRequisito = idClasificadorUoRequisito;
	}

	@Id
	@GeneratedValue(generator="CLASIFICADOR_UO_REQUISITO_GENERATOR")
	@SequenceGenerator(name="CLASIFICADOR_UO_REQUISITO_GENERATOR",sequenceName="planificacion.clasificador_uo_requisito_id_clasificador_uo_requisito_seq")

	@Column(name = "id_clasificador_uo_requisito")
	public Long getIdClasificadorUoRequisito() {
		return this.idClasificadorUoRequisito;
	}

	public void setIdClasificadorUoRequisito(Long idClasificadorUoRequisito) {
		this.idClasificadorUoRequisito = idClasificadorUoRequisito;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_requisito_minimo_cuo")
	public RequisitoMinimoCuo getRequisitoMinimoCuo() {
		return this.requisitoMinimoCuo;
	}

	public void setRequisitoMinimoCuo(RequisitoMinimoCuo requisitoMinimoCuo) {
		this.requisitoMinimoCuo = requisitoMinimoCuo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_clasificador_uo")
	public ClasificadorUo getClasificadorUo() {
		return this.clasificadorUo;
	}

	public void setClasificadorUo(ClasificadorUo clasificadorUo) {
		this.clasificadorUo = clasificadorUo;
	}
	

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Transient
	public Long getId() {
		return idClasificadorUoRequisito;
	}

	/**
	 * 
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.CLASIFICADOR_UO_REQUISITO_ID, getId());
		properties.put(SICCASessionParameters.CLASIFICADOR_UO_REQUISITO_DESCRIPCION,
				descripcion);

		return properties;
	}

	/**
	 * 
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}
}
