package py.com.excelsis.sicca.entity;

// Generated 12-sep-2012 9:08:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ComisionEval generated by hbm2java
 */
@Entity
@Table(name = "comision_eval", schema = "eval_desempeno")
public class ComisionEval implements java.io.Serializable {

	private Long idComisionEval;
	private EvaluacionDesempeno evaluacionDesempeno;
	private String nombre;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<GruposEvaluacion> gruposEvaluacions = new HashSet<GruposEvaluacion>(0);

	public ComisionEval() {
	}

	public ComisionEval(
			Long idComisionEval, EvaluacionDesempeno evaluacionDesempeno, String nombre,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idComisionEval = idComisionEval;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.nombre = nombre;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ComisionEval(
			Long idComisionEval, EvaluacionDesempeno evaluacionDesempeno, String nombre,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<GruposEvaluacion> gruposEvaluacions) {
		this.idComisionEval = idComisionEval;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.nombre = nombre;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.gruposEvaluacions = gruposEvaluacions;
	}

	@Id
	@GeneratedValue(generator = "COMISION_EVAL_GENERATOR")
	@SequenceGenerator(name = "COMISION_EVAL_GENERATOR", sequenceName = "eval_desempeno.comision_eval_id_comision_eval_seq")
	@Column(name = "id_comision_eval", unique = true, nullable = false)
	public Long getIdComisionEval() {
		return this.idComisionEval;
	}

	public void setIdComisionEval(Long idComisionEval) {
		this.idComisionEval = idComisionEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno", nullable = false)
	@NotNull
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return this.evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comisionEval")
	public Set<GruposEvaluacion> getGruposEvaluacions() {
		return this.gruposEvaluacions;
	}

	public void setGruposEvaluacions(Set<GruposEvaluacion> gruposEvaluacions) {
		this.gruposEvaluacions = gruposEvaluacions;
	}

}
