package py.com.excelsis.sicca.entity;

// Generated 29/05/2012 10:38:34 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ComisionCapacEval generated by hbm2java
 */
@Entity
@Table(name = "comision_capac_eval", schema = "capacitacion", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_persona", "id_capacitacion" ,"activo"}))
public class ComisionCapacEval implements java.io.Serializable {

	private Long idComision;
	private Capacitaciones capacitaciones;
	private Persona persona;
	private ConfiguracionUoCab configuracionUo;
	private String tipo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String puesto;
	private ComisionEval comisionEval;
	private Set<ResultadoEvalComision> resultadoEvalComisions = new HashSet<ResultadoEvalComision>(
			0);

	public ComisionCapacEval() {
	}

	public ComisionCapacEval(Long idComision, Capacitaciones capacitaciones,
			Persona idPersona, ConfiguracionUoCab idConfiguracionUo, String tipo,
			String equipoTecnico, String titularSuplente, Long idRol,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idComision = idComision;
		this.capacitaciones = capacitaciones;
		this.persona = idPersona;
		this.configuracionUo = idConfiguracionUo;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ComisionCapacEval(Long idComision, Capacitaciones capacitaciones,
			Persona idPersona, ConfiguracionUoCab idConfiguracionUo, String tipo,
			String equipoTecnico, String titularSuplente, Long idRol,
			Long idDocumento, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod,
			String puesto, Set<ResultadoEvalComision> resultadoEvalComisions) {
		this.idComision = idComision;
		this.capacitaciones = capacitaciones;
		this.persona = idPersona;
		this.configuracionUo = idConfiguracionUo;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.resultadoEvalComisions = resultadoEvalComisions;
	}

	@Id
	@Column(name = "id_comision", unique = true, nullable = false)
	@GeneratedValue(generator="COMISION_CAP_EVAL_GENERATOR")
	@SequenceGenerator(name="COMISION_CAP_EVAL_GENERATOR",sequenceName="capacitacion.comision_capac_eval_id_comision_capacitacion_seq")
	public Long getIdComision() {
		return this.idComision;
	}

	public void setIdComision(Long idComision) {
		this.idComision = idComision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion")
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	@NotNull
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUo() {
		return configuracionUo;
	}

	public void setConfiguracionUo(ConfiguracionUoCab configuracionUo) {
		this.configuracionUo = configuracionUo;
	}
	
	

	@Column(name = "tipo", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getTipo() {
		return this.tipo;
	}

	

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "puesto", length = 200)
	@Length(max =200)
	public String getPuesto() {
		return puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comision_eval")
	public ComisionEval getComisionEval() {
		return comisionEval;
	}

	public void setComisionEval(ComisionEval comisionEval) {
		this.comisionEval = comisionEval;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comisionCapacEval")
	public Set<ResultadoEvalComision> getResultadoEvalComisions() {
		return this.resultadoEvalComisions;
	}

	public void setResultadoEvalComisions(
			Set<ResultadoEvalComision> resultadoEvalComisions) {
		this.resultadoEvalComisions = resultadoEvalComisions;
	}	
	
}
