package py.com.excelsis.sicca.entity;

// Generated 17-nov-2011 17:00:10 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ComisionGrupo generated by hbm2java
 */
@Entity
@Table(name = "comision_grupo", schema = "seleccion")
public class ComisionGrupo implements java.io.Serializable {

	private Long idComisionGrupo;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private ComisionSeleccionCab comisionSeleccionCab;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ComisionGrupo() {
	}

	public ComisionGrupo(Long idComisionGrupo,
			ConcursoPuestoAgr concursoPuestoAgr,
			ComisionSeleccionCab comisionSeleccionCab, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idComisionGrupo = idComisionGrupo;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.comisionSeleccionCab = comisionSeleccionCab;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ComisionGrupo(Long idComisionGrupo,
			ConcursoPuestoAgr concursoPuestoAgr,
			ComisionSeleccionCab comisionSeleccionCab, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idComisionGrupo = idComisionGrupo;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.comisionSeleccionCab = comisionSeleccionCab;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="COMISION_GRUPO_GENERATOR")
	@SequenceGenerator(name="COMISION_GRUPO_GENERATOR",sequenceName="seleccion.comision_grupo_id_comision_grupo_seq")
	@Column(name = "id_comision_grupo", unique = true, nullable = false)
	public Long getIdComisionGrupo() {
		return this.idComisionGrupo;
	}

	public void setIdComisionGrupo(Long idComisionGrupo) {
		this.idComisionGrupo = idComisionGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr", nullable = false)
	@NotNull
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comision_cab", nullable = false)
	@NotNull
	public ComisionSeleccionCab getComisionSeleccionCab() {
		return this.comisionSeleccionCab;
	}

	public void setComisionSeleccionCab(
			ComisionSeleccionCab comisionSeleccionCab) {
		this.comisionSeleccionCab = comisionSeleccionCab;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
