package py.com.excelsis.sicca.entity;

// Generated 08/10/2012 02:33:08 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConcursoPuestoAgrExc generated by hbm2java
 */
@Entity
@Table(name = "concurso_puesto_agr_exc", schema = "seleccion")
public class ConcursoPuestoAgrExc implements java.io.Serializable {

	private Long idConcursoPuestoAgrExc;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Excepcion excepcion;
	private String estado;
	private Date fechaAdjudicacion;
	private Resolucion decreto;
	private Resolucion resolucionAdjudicacion;
	private Resolucion resolucionNombramiento;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean nombramiento;

	public ConcursoPuestoAgrExc() {
	}

	public ConcursoPuestoAgrExc(
			Long idConcursoPuestoAgrExc, ConcursoPuestoAgr idConcursoPuestoAgr,
			Excepcion idExcepcion, boolean activo, String usuAlta, Date fechaAlta) {
		this.idConcursoPuestoAgrExc = idConcursoPuestoAgrExc;
		this.concursoPuestoAgr = idConcursoPuestoAgr;
		this.excepcion = idExcepcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ConcursoPuestoAgrExc(
			Long idConcursoPuestoAgrExc, ConcursoPuestoAgr idConcursoPuestoAgr,
			Excepcion idExcepcion, String estado, Date fechaAdjudicacion, Resolucion idDecreto,
			Resolucion idResolucionAdjudicacion, Resolucion idResolucionNombramiento,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Boolean nombramiento) {
		this.idConcursoPuestoAgrExc = idConcursoPuestoAgrExc;
		this.concursoPuestoAgr = idConcursoPuestoAgr;
		this.excepcion = idExcepcion;
		this.estado = estado;
		this.fechaAdjudicacion = fechaAdjudicacion;
		this.decreto = idDecreto;
		this.resolucionAdjudicacion = idResolucionAdjudicacion;
		this.resolucionNombramiento = idResolucionNombramiento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.nombramiento = nombramiento;
	}

	@Id
	@Column(name = "id_concurso_puesto_agr_exc", unique = true, nullable = false)
	@GeneratedValue(generator = "CONCURSOPUESTOAGREXC_GENERATOR")
	@SequenceGenerator(name = "CONCURSOPUESTOAGREXC_GENERATOR", sequenceName = "seleccion.concurso_puesto_agr_exc_id_concurso_puesto_agr_exc_seq")
	public Long getIdConcursoPuestoAgrExc() {
		return this.idConcursoPuestoAgrExc;
	}

	public void setIdConcursoPuestoAgrExc(Long idConcursoPuestoAgrExc) {
		this.idConcursoPuestoAgrExc = idConcursoPuestoAgrExc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_excepcion")
	@NotNull
	public Excepcion getExcepcion() {
		return excepcion;
	}

	public void setExcepcion(Excepcion excepcion) {
		this.excepcion = excepcion;
	}

	@Column(name = "estado", length = 30)
	@Length(max = 30)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adjudicacion", length = 29)
	public Date getFechaAdjudicacion() {
		return this.fechaAdjudicacion;
	}

	public void setFechaAdjudicacion(Date fechaAdjudicacion) {
		this.fechaAdjudicacion = fechaAdjudicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_decreto")
	public Resolucion getDecreto() {
		return decreto;
	}

	public void setDecreto(Resolucion decreto) {
		this.decreto = decreto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion_adjudicacion")
	public Resolucion getResolucionAdjudicacion() {
		return resolucionAdjudicacion;
	}

	public void setResolucionAdjudicacion(Resolucion resolucionAdjudicacion) {
		this.resolucionAdjudicacion = resolucionAdjudicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion_nombramiento")
	public Resolucion getResolucionNombramiento() {
		return resolucionNombramiento;
	}

	public void setResolucionNombramiento(Resolucion resolucionNombramiento) {
		this.resolucionNombramiento = resolucionNombramiento;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "nombramiento")
	public Boolean getNombramiento() {
		return this.nombramiento;
	}

	public void setNombramiento(Boolean nombramiento) {
		this.nombramiento = nombramiento;
	}

}
