package py.com.excelsis.sicca.entity;

// Generated 28/10/2011 05:04:36 PM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.core.SeamResourceBundle;

import py.com.excelsis.sicca.seguridad.entity.Usuario;

/**
 * ConcursoPuestoAgr generated by hbm2java
 */
@Entity
@Table(name = "concurso_puesto_agr", schema = "seleccion")
public class ConcursoPuestoAgr implements java.io.Serializable {

	private Long idConcursoPuestoAgr;
	private String codGrupo;
	private Concurso concurso;
	private String descripcionGrupo;
	private Integer nroOrden;
	private Integer cantidadPuestos;
	private String observacion;
	private Long idProcessInstance;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;

	private String usuMod;
	private Date fechaMod;
	private Resolucion resolucionHomologacion;
	private NotaHomologacion notaHomologacion;
	private MemoHomologacion memoHomologacion;
	private Integer estado;
	private Date fechaAdjudicacion;
	private Date fechaEvalDocDesde;
	private Date fechaEvalDocHasta;
	private Date fechaEvalRefDesde;
	private Date fechaEvalRefHasta;

	private String postHabilitados;
	private String postNoHabilitados;
	private String otrosBeneficios;
	private String fuenteFinanciacion;
	private Boolean seleccionado;

	private String objetivo;
	private String mision;
	private String contacto;
	private String lugar;
	private Date fechaLimite;
	private String condLaborales;
	private String otrasInf;
	private String remuneracion;
	private String otrasRemuneraciones;
	private String modalidad;
	private String misionEspecifica;
	private String documentos;
	private String horario;
	private Resolucion resolucionAdjudicacion;
	private Resolucion decreto;
	private Resolucion resolucionNombramiento;
	private Boolean homologar;
	private HomologacionPerfilMatriz homologacionPerfilMatriz;
	private ConcursoPuestoAgr concursoPuestoAgrOrigen;
	private Boolean permanente;
	private Boolean contratado;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	private Boolean nombramiento;
	private Boolean carpeta;//MODIFICADO RV
	private Integer prorrogaNum;//AGREGADO POR JD 
	
	
	private Set<AdjuntoDocPuestoAgr> adjuntoDocPuestoAgrs = new HashSet<AdjuntoDocPuestoAgr>(0);
	private List<ConcursoPuestoDet> concursoPuestoDets = new ArrayList<ConcursoPuestoDet>(0);
	private List<PromocionConcursoAgr> promocionConcursoAgr = new ArrayList<PromocionConcursoAgr>(0);
	private Set<FechasGrupoPuesto> fechasGrupoPuestos = new HashSet<FechasGrupoPuesto>(0);
	private Set<EmpleadoPuesto> empleadoPuestos = new HashSet<EmpleadoPuesto>(0);

	private Set<ExcepcionGrPuesto> excepcionGrPuestos = new HashSet<ExcepcionGrPuesto>(0);
	private Set<HomologacionPerfilMatriz> homologacionPerfilMatrizs =
		new HashSet<HomologacionPerfilMatriz>(0);
	private Set<PublicacionPortal> publicacionPortals = new HashSet<PublicacionPortal>(0);

	private Set<Excepcion> excepcions = new HashSet<Excepcion>(0);

	public ConcursoPuestoAgr() {
	}

	public ConcursoPuestoAgr(
			Long idConcursoPuestoAgr, Concurso concurso, String codGrupo, String descripcionGrupo,
			Integer nroOrden, boolean activo, String usuAlta, Date fechaAlta) {
		this.idConcursoPuestoAgr = idConcursoPuestoAgr;
		this.concurso = concurso;
		this.codGrupo = codGrupo;
		this.descripcionGrupo = descripcionGrupo;
		this.nroOrden = nroOrden;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ConcursoPuestoAgr(
			Long idConcursoPuestoAgr, Concurso concurso, String codGrupo, String descripcionGrupo,
			Integer nroOrden, String observacion, Long idProcessInstance, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<AdjuntoDocPuestoAgr> adjuntoDocPuestoAgrs,
			List<ConcursoPuestoDet> concursoPuestoDets, Set<FechasGrupoPuesto> fechasGrupoPuestos) {
		super();
		this.idConcursoPuestoAgr = idConcursoPuestoAgr;
		this.concurso = concurso;
		this.codGrupo = codGrupo;
		this.descripcionGrupo = descripcionGrupo;
		this.nroOrden = nroOrden;
		this.observacion = observacion;
		this.idProcessInstance = idProcessInstance;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.adjuntoDocPuestoAgrs = adjuntoDocPuestoAgrs;
		this.concursoPuestoDets = concursoPuestoDets;
		this.fechasGrupoPuestos = fechasGrupoPuestos;
	}

	public ConcursoPuestoAgr(
			Long idConcursoPuestoAgr, Concurso concurso, String codGrupo, String descripcionGrupo,
			Integer nroOrden, String observacion, Long idProcessInstance, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<AdjuntoDocPuestoAgr> adjuntoDocPuestoAgrs,
			List<ConcursoPuestoDet> concursoPuestoDets) {
		this.idConcursoPuestoAgr = idConcursoPuestoAgr;
		this.concurso = concurso;
		this.codGrupo = codGrupo;
		this.descripcionGrupo = descripcionGrupo;
		this.nroOrden = nroOrden;
		this.observacion = observacion;
		this.idProcessInstance = idProcessInstance;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.adjuntoDocPuestoAgrs = adjuntoDocPuestoAgrs;
		this.concursoPuestoDets = concursoPuestoDets;
	}

	@Id
	@GeneratedValue(generator = "CONCURSO_PUESTO_AGR_GENERATOR")
	@SequenceGenerator(name = "CONCURSO_PUESTO_AGR_GENERATOR", sequenceName = "seleccion.concurso_puesto_agr_id_concurso_puesto_agr_seq")
	@Column(name = "id_concurso_puesto_agr", unique = true, nullable = false)
	public Long getIdConcursoPuestoAgr() {
		return this.idConcursoPuestoAgr;
	}

	public void setIdConcursoPuestoAgr(Long idConcursoPuestoAgr) {
		this.idConcursoPuestoAgr = idConcursoPuestoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso", nullable = false)
	@NotNull
	public Concurso getConcurso() {
		return this.concurso;
	}

	public void setConcurso(Concurso concurso) {
		this.concurso = concurso;
	}

	@Column(name = "cod_grupo", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(String codGrupo) {
		this.codGrupo = codGrupo;
	}

	@Column(name = "descripcion_grupo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcionGrupo() {
		return this.descripcionGrupo;
	}

	public void setDescripcionGrupo(String descripcionGrupo) {
		this.descripcionGrupo = descripcionGrupo;
	}

	@Column(name = "nro_orden", nullable = false)
	public Integer getNroOrden() {
		return this.nroOrden;
	}

	public void setNroOrden(Integer nroOrden) {
		this.nroOrden = nroOrden;
	}
	
	@Column(name = "cantidad_puestos")
	public Integer getCantidadPuestos() {
		return this.cantidadPuestos;
	}

	public void setCantidadPuestos(Integer cant) {
		this.cantidadPuestos = cant;
	}

	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "id_process_instance")
	public Long getIdProcessInstance() {
		return this.idProcessInstance;
	}

	public void setIdProcessInstance(Long idProcessInstance) {
		this.idProcessInstance = idProcessInstance;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public Set<AdjuntoDocPuestoAgr> getAdjuntoDocPuestoAgrs() {
		return this.adjuntoDocPuestoAgrs;
	}

	public void setAdjuntoDocPuestoAgrs(Set<AdjuntoDocPuestoAgr> adjuntoDocPuestoAgrs) {
		this.adjuntoDocPuestoAgrs = adjuntoDocPuestoAgrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public List<ConcursoPuestoDet> getConcursoPuestoDets() {
		return this.concursoPuestoDets;
	}

	public void setConcursoPuestoDets(List<ConcursoPuestoDet> concursoPuestoDets) {
		this.concursoPuestoDets = concursoPuestoDets;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public List<PromocionConcursoAgr> getPromocionConcursoAgrs() {
		return this.promocionConcursoAgr;
	}

	public void setPromocionConcursoAgrs(List<PromocionConcursoAgr> promocionConcursoAgr) {
		this.promocionConcursoAgr = promocionConcursoAgr;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "concursoPuestoAgr")
	public Set<FechasGrupoPuesto> getFechasGrupoPuestos() {
		return this.fechasGrupoPuestos;
	}

	public void setFechasGrupoPuestos(Set<FechasGrupoPuesto> fechasGrupoPuestos) {
		this.fechasGrupoPuestos = fechasGrupoPuestos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion_homologacion")
	public Resolucion getResolucionHomologacion() {
		return resolucionHomologacion;
	}

	public void setResolucionHomologacion(Resolucion resolucionHomologacion) {
		this.resolucionHomologacion = resolucionHomologacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nota_homologacion")
	public NotaHomologacion getNotaHomologacion() {
		return notaHomologacion;
	}

	public void setNotaHomologacion(NotaHomologacion notaHomologacion) {
		this.notaHomologacion = notaHomologacion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public Set<HomologacionPerfilMatriz> getHomologacionPerfilMatrizs() {
		return this.homologacionPerfilMatrizs;
	}

	public void setHomologacionPerfilMatrizs(Set<HomologacionPerfilMatriz> homologacionPerfilMatrizs) {
		this.homologacionPerfilMatrizs = homologacionPerfilMatrizs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_memo_homologacion")
	public MemoHomologacion getMemoHomologacion() {
		return memoHomologacion;
	}

	public void setMemoHomologacion(MemoHomologacion memoHomologacion) {
		this.memoHomologacion = memoHomologacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adjudicacion", length = 29)
	public Date getFechaAdjudicacion() {
		return this.fechaAdjudicacion;
	}

	public void setFechaAdjudicacion(Date fechaAdjudicacion) {
		this.fechaAdjudicacion = fechaAdjudicacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eval_doc_desde", length = 29)
	public Date getFechaEvalDocDesde() {
		return this.fechaEvalDocDesde;
	}

	public void setFechaEvalDocDesde(Date fechaEvalDocDesde) {
		this.fechaEvalDocDesde = fechaEvalDocDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eval_doc_hasta", length = 29)
	public Date getFechaEvalDocHasta() {
		return this.fechaEvalDocHasta;
	}

	public void setFechaEvalDocHasta(Date fechaEvalDocHasta) {
		this.fechaEvalDocHasta = fechaEvalDocHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eval_ref_desde", length = 29)
	public Date getFechaEvalRefDesde() {
		return this.fechaEvalRefDesde;
	}

	public void setFechaEvalRefDesde(Date fechaEvalRefDesde) {
		this.fechaEvalRefDesde = fechaEvalRefDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eval_ref_hasta", length = 29)
	public Date getFechaEvalRefHasta() {
		return this.fechaEvalRefHasta;
	}

	public void setFechaEvalRefHasta(Date fechaEvalRefHasta) {
		this.fechaEvalRefHasta = fechaEvalRefHasta;
	}

	@Transient
	public Boolean getSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(Boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

	@Column(name = "fuente_financiacion", length = 150)
	@Length(max = 150)
	public String getFuenteFinanciacion() {
		return fuenteFinanciacion;
	}

	public void setFuenteFinanciacion(String fuenteFinanciacion) {
		this.fuenteFinanciacion = fuenteFinanciacion;
	}

	@Column(name = "otros_beneficios", length = 500)
	@Length(max = 500)
	public String getOtrosBeneficios() {
		return otrosBeneficios;
	}

	public void setOtrosBeneficios(String otrosBeneficios) {
		this.otrosBeneficios = otrosBeneficios;
	}

	@Column(name = "post_habilitados", length = 500)
	@Length(max = 500)
	public String getPostHabilitados() {
		return postHabilitados;
	}

	public void setPostHabilitados(String postHabilitados) {
		this.postHabilitados = postHabilitados;
	}

	@Column(name = "post_no_habilitados", length = 500)
	@Length(max = 500)
	public String getPostNoHabilitados() {
		return postNoHabilitados;
	}

	public void setPostNoHabilitados(String postNoHabilitados) {
		this.postNoHabilitados = postNoHabilitados;
	}

	@Column(name = "objetivo", length = 500)
	@Length(max = 500)
	public String getObjetivo() {
		return this.objetivo;
	}

	public void setObjetivo(String objetivo) {
		this.objetivo = objetivo;
	}

	@Column(name = "mision", length = 500)
	@Length(max = 500)
	public String getMision() {
		return this.mision;
	}

	public void setMision(String mision) {
		this.mision = mision;
	}

	@Column(name = "contacto", length = 500)
	@Length(max = 500)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "lugar", length = 500)
	@Length(max = 500)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_limite", length = 13)
	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	@Column(name = "cond_laborales", length = 500)
	@Length(max = 500)
	public String getCondLaborales() {
		return this.condLaborales;
	}

	public void setCondLaborales(String condLaborales) {
		this.condLaborales = condLaborales;
	}

	@Column(name = "otras_inf", length = 500)
	@Length(max = 500)
	public String getOtrasInf() {
		return this.otrasInf;
	}

	public void setOtrasInf(String otrasInf) {
		this.otrasInf = otrasInf;
	}

	@Column(name = "remuneracion")
	public String getRemuneracion() {
		return this.remuneracion;
	}

	public void setRemuneracion(String remuneracion) {
		this.remuneracion = remuneracion;
	}
	
	@Column(name = "otras_remuneraciones")
	public String getOtrasRemuneraciones() {
		return this.otrasRemuneraciones;
	}

	public void setOtrasRemuneraciones(String otrasRemuneraciones) {
		this.otrasRemuneraciones = otrasRemuneraciones;
	}

	@Column(name = "modalidad", length = 50)
	@Length(max = 50)
	public String getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(String modalidad) {
		this.modalidad = modalidad;
	}

	@Column(name = "mision_especifica", length = 500)
	@Length(max = 500)
	public String getMisionEspecifica() {
		return this.misionEspecifica;
	}

	public void setMisionEspecifica(String misionEspecifica) {
		this.misionEspecifica = misionEspecifica;
	}

	@Column(name = "documentos", length = 500)
	@Length(max = 500)
	public String getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(String documentos) {
		this.documentos = documentos;
	}

	@Column(name = "horario", length = 250)
	@Length(max = 250)
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion_adjudicacion")
	public Resolucion getResolucionAdjudicacion() {
		return resolucionAdjudicacion;
	}

	public void setResolucionAdjudicacion(Resolucion resolucionAdjudicacion) {
		this.resolucionAdjudicacion = resolucionAdjudicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_decreto")
	public Resolucion getDecreto() {
		return decreto;
	}

	public void setDecreto(Resolucion decreto) {
		this.decreto = decreto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resolucion_nombramiento")
	public Resolucion getResolucionNombramiento() {
		return resolucionNombramiento;
	}

	public void setResolucionNombramiento(Resolucion resolucionNombramiento) {
		this.resolucionNombramiento = resolucionNombramiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_homologacion")
	public HomologacionPerfilMatriz getHomologacionPerfilMatriz() {
		return homologacionPerfilMatriz;
	}

	public void setHomologacionPerfilMatriz(HomologacionPerfilMatriz homologacionPerfilMatriz) {
		this.homologacionPerfilMatriz = homologacionPerfilMatriz;
	}

	@Column(name = "homologar")
	public Boolean getHomologar() {
		return homologar;
	}

	public void setHomologar(Boolean homologar) {
		this.homologar = homologar;
	}

	@Column(name = "carpeta")
	public Boolean getCarpeta() {
		return carpeta;
	}

	public void setCarpeta(Boolean carpeta) {
		this.carpeta = carpeta;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public Set<Excepcion> getExcepcions() {
		return this.excepcions;
	}

	public void setExcepcions(Set<Excepcion> excepcions) {
		this.excepcions = excepcions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public Set<ExcepcionGrPuesto> getExcepcionGrPuestos() {
		return this.excepcionGrPuestos;
	}

	public void setExcepcionGrPuestos(Set<ExcepcionGrPuesto> excepcionGrPuestos) {
		this.excepcionGrPuestos = excepcionGrPuestos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr_origen")
	public ConcursoPuestoAgr getConcursoPuestoAgrOrigen() {
		return concursoPuestoAgrOrigen;
	}

	public void setConcursoPuestoAgrOrigen(ConcursoPuestoAgr concursoPuestoAgrOrigen) {
		this.concursoPuestoAgrOrigen = concursoPuestoAgrOrigen;
	}
	@Column(name = "nombramiento")
	public Boolean getNombramiento() {
		return nombramiento;
	}

	public void setNombramiento(Boolean nombramiento) {
		this.nombramiento = nombramiento;
	}

	
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public Set<PublicacionPortal> getPublicacionPortals() {
		return this.publicacionPortals;
	}

	public void setPublicacionPortals(Set<PublicacionPortal> publicacionPortals) {
		this.publicacionPortals = publicacionPortals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concursoPuestoAgr")
	public Set<EmpleadoPuesto> getEmpleadoPuestos() {
		return empleadoPuestos;
	}

	public void setEmpleadoPuestos(Set<EmpleadoPuesto> empleadoPuestos) {
		this.empleadoPuestos = empleadoPuestos;
	}

	@Column(name = "permanente")
	public Boolean getPermanente() {
		return permanente;
	}

	public void setPermanente(Boolean permanente) {
		this.permanente = permanente;
	}

	@Column(name = "contratado")
	public Boolean getContratado() {
		return contratado;
	}

	public void setContratado(Boolean contratado) {
		this.contratado = contratado;
	}
	@Column(name = "prorroga_num")
	public Integer getProrrogaNum() {
		return prorrogaNum;
	}

	public void setProrrogaNum(Integer prorrogaNum) {
		this.prorrogaNum = prorrogaNum;
	}

	//Agregado por Santiago
	//(es este el lugar correcto para poner estos metodos?)
	public String dondePostularse() {
		if(this.paraPublicacion())
			return SeamResourceBundle.getBundle().getString(
					"postularse_en_entidad");
		else
			if(this.carpeta!=null && this.carpeta)
				return SeamResourceBundle.getBundle().getString(
						"postularse_ambos");
			else
				return SeamResourceBundle.getBundle().getString(
						"postularse_sicca");
	}
	
	public boolean paraPublicacion(){
		return this.estado == 1000;
	}
}
