package py.com.excelsis.sicca.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import py.com.excelsis.sicca.seguridad.entity.Usuario;

/**
 * ConfiguracionUoCab generated by Generality
 */
@Entity
@Table(name = "configuracion_uo_cab", schema = "planificacion")
public class ConfiguracionUoCab implements java.io.Serializable {

	private Long idConfiguracionUo;
	private Date vigenciaDesde;
	private Date vigenciaHasta;
	private String mision;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Boolean activo;
	private String denominacionUnidad;
	private String telefono;
	private String direccion;
	private Integer orden;
	private String codigoSinarh;
	private Entidad entidad;
	private String descripcionCorta;
	private Integer anho;
	private String url;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private List<Oficina> oficinas = new ArrayList<Oficina>(0);
	private List<ConfiguracionUoDet> configuracionUoDets = new ArrayList<ConfiguracionUoDet>(0);
	private Set<FuncionarioOee> funcionarioOees = new HashSet<FuncionarioOee>(0);
	private Set<Familiares> familiares = new HashSet<Familiares>(0);
	private Set<RedCapacitacion> redCapacitacions = new HashSet<RedCapacitacion>(0);
	private Set<RemunConfig> remunConfigs = new HashSet<RemunConfig>(0);
	private Set<Importacion> importacions = new HashSet<Importacion>(0);
	private Date vigenciaDesdeRemuneraciones;

	public ConfiguracionUoCab() {
	}

	public ConfiguracionUoCab(
			Long idConfiguracionUo, Date vigenciaDesde, Date vigenciaHasta, String mision,
			String usuAlta, Date fechaAlta, Boolean activo, String denominacionUnidad) {
		this.idConfiguracionUo = idConfiguracionUo;
		this.vigenciaDesde = vigenciaDesde;
		this.vigenciaHasta = vigenciaHasta;
		this.mision = mision;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.denominacionUnidad = denominacionUnidad;
	}

	public ConfiguracionUoCab(
			Long idConfiguracionUo, Entidad entidad, Date vigenciaDesde, Date vigenciaHasta,
			String mision, String usuAlta, String usuMod, Date fechaMod, Date fechaAlta,
			Boolean activo, String denominacionUnidad, String telefono, String direccion,
			String codigoSinarh, Integer orden, String descripcionCorta, Integer anho,
			List<Oficina> oficinas, List<ConfiguracionUoDet> configuracionUoDets,
			Set<RemunConfig> remunConfigs, Set<Importacion> importacions) {
		this.idConfiguracionUo = idConfiguracionUo;
		this.entidad = entidad;
		this.vigenciaDesde = vigenciaDesde;
		this.vigenciaHasta = vigenciaHasta;
		this.mision = mision;
		this.usuAlta = usuAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.denominacionUnidad = denominacionUnidad;
		this.telefono = telefono;
		this.direccion = direccion;
		this.codigoSinarh = codigoSinarh;
		this.orden = orden;
		this.descripcionCorta = descripcionCorta;
		this.anho = anho;
		this.oficinas = oficinas;
		this.configuracionUoDets = configuracionUoDets;
		this.importacions = importacions;
		this.remunConfigs = remunConfigs;
	}

	public ConfiguracionUoCab(Long idConfiguracionUo) {
		this.idConfiguracionUo = idConfiguracionUo;
	}

	@Id
	@GeneratedValue(generator = "CONFIGURACION_UO_CAB_GENERATOR")
	@SequenceGenerator(name = "CONFIGURACION_UO_CAB_GENERATOR", sequenceName = "planificacion.configuracion_uo_cab_id_configuracion_uo_seq")
	@Column(name = "id_configuracion_uo")
	public Long getIdConfiguracionUo() {
		return this.idConfiguracionUo;
	}

	public void setIdConfiguracionUo(Long idConfiguracionUo) {
		this.idConfiguracionUo = idConfiguracionUo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vigencia_desde")
	public Date getVigenciaDesde() {
		return this.vigenciaDesde;
	}

	public void setVigenciaDesde(Date vigenciaDesde) {
		this.vigenciaDesde = vigenciaDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vigencia_hasta")
	public Date getVigenciaHasta() {
		return this.vigenciaHasta;
	}

	public void setVigenciaHasta(Date vigenciaHasta) {
		this.vigenciaHasta = vigenciaHasta;
	}

	@Column(name = "mision")
	public String getMision() {
		return this.mision;
	}

	public void setMision(String mision) {
		this.mision = mision;
	}

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "denominacion_unidad", nullable = false, length = 256)
	@NotNull
	@Length(max = 256)
	public String getDenominacionUnidad() {
		return denominacionUnidad;
	}

	public void setDenominacionUnidad(String denominacionUnidad) {
		this.denominacionUnidad = denominacionUnidad;
	}

	@Column(name = "telefono", length = 50)
	@Length(max = 50)
	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	//SE AGREGA CAMPO URL - MP 28-12-2015
	@Column(name = "url", length = 50)
	@Length(max = 50)
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "direccion", length = 150)
	@Length(max = 150)
	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "codigo_sinarh", length = 100)
	@Length(max = 100)
	public String getCodigoSinarh() {
		return codigoSinarh;
	}

	public void setCodigoSinarh(String codigoSinarh) {
		this.codigoSinarh = codigoSinarh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "descripcion_corta", length = 50)
	@Length(max = 50)
	public String getDescripcionCorta() {
		return descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}

	@Column(name = "anho")
	public Integer getAnho() {
		return anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public List<Oficina> getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(List<Oficina> oficinas) {
		this.oficinas = oficinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public List<ConfiguracionUoDet> getConfiguracionUoDets() {
		return this.configuracionUoDets;
	}

	public void setConfiguracionUoDets(List<ConfiguracionUoDet> configuracionUoDets) {
		this.configuracionUoDets = configuracionUoDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public Set<FuncionarioOee> getFuncionarioOees() {
		return this.funcionarioOees;
	}

	public void setFuncionarioOees(Set<FuncionarioOee> funcionarioOees) {
		this.funcionarioOees = funcionarioOees;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idConfiguracionUo == null) ? 0 : idConfiguracionUo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ConfiguracionUoCab other = (ConfiguracionUoCab) obj;
		if (idConfiguracionUo == null) {
			if (other.idConfiguracionUo != null)
				return false;
		} else if (!idConfiguracionUo.equals(other.idConfiguracionUo))
			return false;
		return true;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public Set<RedCapacitacion> getRedCapacitacions() {
		return this.redCapacitacions;
	}

	public void setRedCapacitacions(Set<RedCapacitacion> redCapacitacions) {
		this.redCapacitacions = redCapacitacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public Set<Familiares> getFamiliares() {
		return familiares;
	}

	public void setFamiliares(Set<Familiares> familiares) {
		this.familiares = familiares;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public Set<RemunConfig> getRemunConfigs() {
		return this.remunConfigs;
	}

	public void setRemunConfigs(Set<RemunConfig> remunConfigs) {
		this.remunConfigs = remunConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoCab")
	public Set<Importacion> getImportacions() {
		return this.importacions;
	}

	public void setImportacions(Set<Importacion> importacions) {
		this.importacions = importacions;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "vigencia_desde_remuneraciones")
	public Date getVigenciaDesdeAyB() {
		return this.vigenciaDesdeRemuneraciones;
	}

	public void setVigenciaDesdeAyB(Date vigenciaDesdeAyB) {
		this.vigenciaDesdeRemuneraciones = vigenciaDesdeAyB;
	}

}
