package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * Configuracion generated by Generality
 */
@Entity
@Table(name = "configuracion", schema = "sistema")
public class Configuracion implements java.io.Serializable {
	private Integer idConfiguracion;
	private String descIdentVac;
	private Integer tiempoIdentVac;
	private String undMedIdentVac;
	private String descConfComite;
	private Integer tiempoConfComite;
	private String unidMedConfComite;

	public Configuracion() {
	}

	public Configuracion(Integer idConfiguracion) {
		this.idConfiguracion = idConfiguracion;
	}

	@Id
	@GeneratedValue(generator="CONFIGURACION_GENERATOR")
	@SequenceGenerator(name="CONFIGURACION_GENERATOR",sequenceName="sistema.configuracion_id_configuracion_seq")

	@Column(name = "id_configuracion")
	public Integer getIdConfiguracion() {
		return this.idConfiguracion;
	}

	public void setIdConfiguracion(Integer idConfiguracion) {
		this.idConfiguracion = idConfiguracion;
	}
	

	@Column(name = "desc_ident_vac")
	public String getDescIdentVac() {
		return this.descIdentVac;
	}

	public void setDescIdentVac(String descIdentVac) {
		this.descIdentVac = descIdentVac;
	}
	

	@Column(name = "tiempo_ident_vac")
	public Integer getTiempoIdentVac() {
		return this.tiempoIdentVac;
	}

	public void setTiempoIdentVac(Integer tiempoIdentVac) {
		this.tiempoIdentVac = tiempoIdentVac;
	}
	

	@Column(name = "und_med_ident_vac")
	public String getUndMedIdentVac() {
		return this.undMedIdentVac;
	}

	public void setUndMedIdentVac(String undMedIdentVac) {
		this.undMedIdentVac = undMedIdentVac;
	}
	

	@Column(name = "desc_conf_comite")
	public String getDescConfComite() {
		return this.descConfComite;
	}

	public void setDescConfComite(String descConfComite) {
		this.descConfComite = descConfComite;
	}
	

	@Column(name = "tiempo_conf_comite")
	public Integer getTiempoConfComite() {
		return this.tiempoConfComite;
	}

	public void setTiempoConfComite(Integer tiempoConfComite) {
		this.tiempoConfComite = tiempoConfComite;
	}
	

	@Column(name = "unid_med_conf_comite")
	public String getUnidMedConfComite() {
		return this.unidMedConfComite;
	}

	public void setUnidMedConfComite(String unidMedConfComite) {
		this.unidMedConfComite = unidMedConfComite;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idConfiguracion == null) ? 0 : idConfiguracion.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Configuracion other = (Configuracion) obj;
		if (idConfiguracion == null) {
			if (other.idConfiguracion != null)
				return false;
		} else if (!idConfiguracion.equals(other.idConfiguracion))
			return false;
		return true;
	}
}
