package py.com.excelsis.sicca.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import py.com.excelsis.sicca.seguridad.entity.Usuario;

/**
 * ConfiguracionUoDet generated by Generality
 */
@Entity
@Table(name = "configuracion_uo_det", schema = "planificacion")
public class ConfiguracionUoDet implements java.io.Serializable, Comparable {
	private Long idConfiguracionUoDet;
	private String descripcionCorta;
	private Integer orden;
	private String denominacionUnidad;
	private Integer condPolitica;
	private Integer prodAdmPublica;
	private Integer prodSociedad;
	private Integer interno;
	private String descripcionFinalidad;
	private String direccion;
	private String telefono;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Boolean activo;
	private ConfiguracionUoDet configuracionUoDet;
	private ClasificadorUo clasificadorUo;
	private ConfiguracionUoCab configuracionUoCab;
	private String estadoAnterior;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private List<ConfiguracionUoDet> configuracionUoDets = new ArrayList<ConfiguracionUoDet>(0);
	private List<ProcesoGestion> procesoGestions = new ArrayList<ProcesoGestion>(0);
	private List<PlantaCargoDet> plantaCargoDets = new ArrayList<PlantaCargoDet>(0);
	private Boolean selected = false;
	private String codigoUo;

	public ConfiguracionUoDet() {
	}

	public ConfiguracionUoDet(
			Long idConfiguracionUoDet, ConfiguracionUoCab configuracionUoCab, Integer orden,
			String denominacionUnidad, Date fechaAlta, Boolean activo) {
		this.idConfiguracionUoDet = idConfiguracionUoDet;
		this.configuracionUoCab = configuracionUoCab;
		this.orden = orden;
		this.denominacionUnidad = denominacionUnidad;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
	}

	public ConfiguracionUoDet(
			Long idConfiguracionUoDet, ConfiguracionUoDet configuracionUoDet,
			ClasificadorUo clasificadorUo, ConfiguracionUoCab configuracionUoCab,
			String descripcionCorta, Integer orden, String denominacionUnidad,
			Integer condPolitica, Integer prodAdmPublica, Integer prodSociedad, Integer interno,
			String descripcionFinalidad, String direccion, String telefono, String usuAlta,
			String usuMod, Date fechaMod, Date fechaAlta, Boolean activo, String estadoAnterior,
			List<ConfiguracionUoDet> configuracionUoDets, List<ProcesoGestion> procesoGestions,
			List<PlantaCargoDet> plantaCargoDets) {
		this.idConfiguracionUoDet = idConfiguracionUoDet;
		this.configuracionUoDet = configuracionUoDet;
		this.clasificadorUo = clasificadorUo;
		this.configuracionUoCab = configuracionUoCab;
		this.descripcionCorta = descripcionCorta;
		this.orden = orden;
		this.denominacionUnidad = denominacionUnidad;
		this.condPolitica = condPolitica;
		this.prodAdmPublica = prodAdmPublica;
		this.prodSociedad = prodSociedad;
		this.interno = interno;
		this.descripcionFinalidad = descripcionFinalidad;
		this.direccion = direccion;
		this.telefono = telefono;
		this.usuAlta = usuAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.estadoAnterior = estadoAnterior;
		this.configuracionUoDets = configuracionUoDets;
		this.procesoGestions = procesoGestions;
		this.plantaCargoDets = plantaCargoDets;
	}

	@Id
	@GeneratedValue(generator = "CONFIGURACION_UO_DET_GENERATOR")
	@SequenceGenerator(name = "CONFIGURACION_UO_DET_GENERATOR", sequenceName = "planificacion.configuracion_uo_det_id_configuracion_uo_det_seq")
	@Column(name = "id_configuracion_uo_det")
	public Long getIdConfiguracionUoDet() {
		return this.idConfiguracionUoDet;
	}

	public void setIdConfiguracionUoDet(Long idConfiguracionUoDet) {
		this.idConfiguracionUoDet = idConfiguracionUoDet;
	}

	@Column(name = "descripcion_corta")
	public String getDescripcionCorta() {
		return this.descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "denominacion_unidad")
	public String getDenominacionUnidad() {
		return this.denominacionUnidad;
	}

	public void setDenominacionUnidad(String denominacionUnidad) {
		this.denominacionUnidad = denominacionUnidad;
	}

	@Column(name = "cond_politica")
	public Integer getCondPolitica() {
		return this.condPolitica;
	}

	public void setCondPolitica(Integer condPolitica) {
		this.condPolitica = condPolitica;
	}

	@Column(name = "prod_adm_publica")
	public Integer getProdAdmPublica() {
		return this.prodAdmPublica;
	}

	public void setProdAdmPublica(Integer prodAdmPublica) {
		this.prodAdmPublica = prodAdmPublica;
	}

	@Column(name = "prod_sociedad")
	public Integer getProdSociedad() {
		return this.prodSociedad;
	}

	public void setProdSociedad(Integer prodSociedad) {
		this.prodSociedad = prodSociedad;
	}

	@Column(name = "interno")
	public Integer getInterno() {
		return this.interno;
	}

	public void setInterno(Integer interno) {
		this.interno = interno;
	}

	@Column(name = "descripcion_finalidad")
	public String getDescripcionFinalidad() {
		return this.descripcionFinalidad;
	}

	public void setDescripcionFinalidad(String descripcionFinalidad) {
		this.descripcionFinalidad = descripcionFinalidad;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_det_padre")
	public ConfiguracionUoDet getConfiguracionUoDet() {
		return this.configuracionUoDet;
	}

	public void setConfiguracionUoDet(ConfiguracionUoDet configuracionUoDet) {
		this.configuracionUoDet = configuracionUoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_clasificador_uo")
	public ClasificadorUo getClasificadorUo() {
		return this.clasificadorUo;
	}

	public void setClasificadorUo(ClasificadorUo clasificadorUo) {
		this.clasificadorUo = clasificadorUo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "estado_anterior")
	public String getEstadoAnterior() {
		return estadoAnterior;
	}

	public void setEstadoAnterior(String estadoAnterior) {
		this.estadoAnterior = estadoAnterior;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoDet")
	public List<ConfiguracionUoDet> getConfiguracionUoDets() {
		return this.configuracionUoDets;
	}

	public void setConfiguracionUoDets(List<ConfiguracionUoDet> configuracionUoDets) {
		this.configuracionUoDets = configuracionUoDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoDet")
	public List<ProcesoGestion> getProcesoGestions() {
		return this.procesoGestions;
	}

	public void setProcesoGestions(List<ProcesoGestion> procesoGestions) {
		this.procesoGestions = procesoGestions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoDet")
	public List<PlantaCargoDet> getPlantaCargoDets() {
		return this.plantaCargoDets;
	}

	public void setPlantaCargoDets(List<PlantaCargoDet> plantaCargoDets) {
		this.plantaCargoDets = plantaCargoDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUoDet")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result =
			prime * result + ((idConfiguracionUoDet == null) ? 0 : idConfiguracionUoDet.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ConfiguracionUoDet other = (ConfiguracionUoDet) obj;
		if (idConfiguracionUoDet == null) {
			if (other.idConfiguracionUoDet != null)
				return false;
		} else if (!idConfiguracionUoDet.equals(other.idConfiguracionUoDet))
			return false;
		return true;
	}

	public int compareTo(Object o) {
		ConfiguracionUoDet configuracionUoDet = (ConfiguracionUoDet) o;
		return this.orden.compareTo(configuracionUoDet.getOrden());
	}

	@Transient
	public Boolean getSelected() {
		return selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

	@Column(name = "codigo_uo")
	public String getCodigoUo() {
		return codigoUo;
	}

	public void setCodigoUo(String codigoUo) {
		this.codigoUo = codigoUo;
	}

}
