package py.com.excelsis.sicca.entity;

// Generated 21-jun-2012 8:24:32 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConsultasCapacitacion generated by hbm2java
 */
@Entity
@Table(name = "consultas_capacitacion", schema = "capacitacion")
public class ConsultasCapacitacion implements java.io.Serializable {

	private Long idConsultas;
	private Capacitaciones capacitaciones;
	private String lugar;
	private String direccion;
	private String telefono;
	private String email;
	private Date horaDesde;
	private Date horaHasta;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ConsultasCapacitacion() {
	}

	public ConsultasCapacitacion(Long idConsultas,
			Capacitaciones capacitaciones, String lugar, String direccion,
			Date horaDesde, Date horaHasta, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idConsultas = idConsultas;
		this.capacitaciones = capacitaciones;
		this.lugar = lugar;
		this.direccion = direccion;
		this.horaDesde = horaDesde;
		this.horaHasta = horaHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ConsultasCapacitacion(Long idConsultas,
			Capacitaciones capacitaciones, String lugar, String direccion,
			String telefono, String email, Date horaDesde, Date horaHasta,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idConsultas = idConsultas;
		this.capacitaciones = capacitaciones;
		this.lugar = lugar;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.horaDesde = horaDesde;
		this.horaHasta = horaHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="CONSULTAS_CAPACITACION_GENERATOR")
	@SequenceGenerator(name="CONSULTAS_CAPACITACION_GENERATOR", sequenceName="capacitacion.consultas_capacitacion_id_consultas_seq")
	@Column(name = "id_consultas", unique = true, nullable = false)
	public Long getIdConsultas() {
		return this.idConsultas;
	}

	public void setIdConsultas(Long idConsultas) {
		this.idConsultas = idConsultas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion", nullable = false)
	@NotNull
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}

	@Column(name = "lugar", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "direccion", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 500)
	@Length(max = 500)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email", length = 500)
	@Length(max = 500)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_desde", nullable = false, length = 15)
	@NotNull
	public Date getHoraDesde() {
		return this.horaDesde;
	}

	public void setHoraDesde(Date horaDesde) {
		this.horaDesde = horaDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHoraHasta() {
		return this.horaHasta;
	}

	public void setHoraHasta(Date horaHasta) {
		this.horaHasta = horaHasta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
