package py.com.excelsis.sicca.entity;

// Generated 05/11/2012 03:13:42 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Remuneraciones generated by hbm2java
 */
@Entity
@Table(name = "control_remuneraciones_tmp", schema = "remuneracion")
public class ControlRemuneracionesTmp implements java.io.Serializable {

	private Long idControlRemuneracion;
	private Integer anho;
	private Integer mes;
	private Long idConfiguracionUoCab;
	private Integer cantLineas;
	private Integer ultimaLineaProcesada;
	private Date fechaUpdate;
	private String estadoProceso;
    private Boolean insercionExitosa;
    private String usuario;
    private Date fechaInicio;
    private Date fechaFin;
    
    private Persona persona;

	public ControlRemuneracionesTmp() {
	}

	public ControlRemuneracionesTmp(Long idControlRemuneracion, Integer anho, Integer mes, Long idConfiguracionUoCab, Integer cantLineas,
			Integer ultimaLineaProcesada, Date fechaUpdate, String estadoProceso, Boolean insercionExitosa, String usuario, Date fechaInicio, Date fechaFin) {
		
		this.idControlRemuneracion = idControlRemuneracion;
		this.anho = anho;
		this.mes = mes;
		this.idConfiguracionUoCab = idConfiguracionUoCab;
		this.cantLineas = cantLineas;
		this.ultimaLineaProcesada = ultimaLineaProcesada;
		this.fechaUpdate = fechaUpdate;
		this.estadoProceso = estadoProceso;
		this.insercionExitosa = insercionExitosa;
		this.usuario = usuario;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	@Id
	@Column(name = "id_control_remuneracion_tmp", unique = true, nullable = false)
	@GeneratedValue(generator="REMUNERACION_TMP_GENERATOR")
	@SequenceGenerator(name="REMUNERACION_TMP_GENERATOR",sequenceName="remuneracion.control_remuneraciones_tmp_id_control_remuneracion_tmp_seq")
	public Long getIdControlRemuneracion() {
		return this.idControlRemuneracion;
	}

	public void setIdControlRemuneracion(Long idControlRemuneracion) {
		this.idControlRemuneracion = idControlRemuneracion;
	}
	
	@Column(name = "anho")
	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}
	
	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}
	
	@Column(name = "id_configuracion_uo")
	public Long getIdConfiguracionUoCab() {
		return idConfiguracionUoCab;
	}

	public void setIdConfiguracionUoCab(Long idConfiguracionUoCab) {
		this.idConfiguracionUoCab = idConfiguracionUoCab;
	}
	
	@Column(name = "cant_lineas")
	public Integer getCantLineas() {
		return this.cantLineas;
	}

	public void setCantLineas(Integer cantLineas) {
		this.cantLineas = cantLineas;
	}
	
	@Column(name = "ultima_linea_procesada")
	public Integer getUltimaLineaProcesada() {
		return this.ultimaLineaProcesada;
	}

	public void setUltimaLineaProcesada(Integer ultimaLineaProcesada) {
		this.ultimaLineaProcesada = ultimaLineaProcesada;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_update", length = 29)
	public Date getFechaUpdate() {
		return this.fechaUpdate;
	}

	public void setFechaUpdate(Date fechaUpdate) {
		this.fechaUpdate = fechaUpdate;
	}
	
	@Column(name = "estado_proceso", length = 10)
	@Length(max = 10)
	public String getEstadoProceso() {
		return estadoProceso;
	}

	public void setEstadoProceso(String estadoProceso) {
		this.estadoProceso = estadoProceso;
	}
	
	@Column(name = "insercion_exitosa")
	public Boolean getInsercionExitosa() {
		return insercionExitosa;
	}

	public void setInsercionExitosa(Boolean insercionExitosa) {
		this.insercionExitosa = insercionExitosa;
	}

	@Column(name = "usuario", length = 50)
	@Length(max = 50)
	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
}
