package py.com.excelsis.sicca.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.EntityBase;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * Cpt generated by Generality
 */
@Entity
@Table(name = "cpt", schema = "planificacion")
public class Cpt extends EntityBase {
	/**
	 * 
	 */
	private static final long serialVersionUID = -1200372212885777991L;
	private Long idCpt;
	private Integer nivel;
	private TipoCpt tipoCpt;
	private GradoSalarial gradoSalarialMin;
	private GradoSalarial gradoSalarialMax;
	private Integer numero;
	private String denominacion;
	private String estadoHomologacion;
	private Boolean jefatura;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Boolean activo;
	private Integer nroEspecifico;
	private Cpt cptPadre;
	private ConfiguracionUoCab configuracionUoCab;
	private Date fechaSolicitudHomologacion;
	private Date fechaHomologacion;
	private String usuHomologacion;
	

	public static final String ESTADO_NO_HOMOLOGADO = "NO HOMOLOGADO";
	public static final String ESTADO_PARA_HOMOLOGACION = "PARA HOMOLOGACIÓN";
	public static final String ESTADO_HOMOLOGADO = "HOMOLOGADO";
	
	private Set<HomologacionPerfilMatriz> homologacionPerfilMatrizs = new HashSet<HomologacionPerfilMatriz>(0);

	public Cpt() {
	}

	
	@Id
	@GeneratedValue(generator="CPT_GENERATOR")
	@SequenceGenerator(name="CPT_GENERATOR",sequenceName="planificacion.cpt_id_cpt_seq")

	@Column(name = "id_cpt")
	public Long getIdCpt() {
		return this.idCpt;
	}

	public void setIdCpt(Long idCpt) {
		this.idCpt = idCpt;
	}
	

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cpt")
	public TipoCpt getTipoCpt() {
		return this.tipoCpt;
	}

	public void setTipoCpt(TipoCpt tipoCpt) {
		this.tipoCpt = tipoCpt;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grado_salarial_min")
	public GradoSalarial getGradoSalarialMin() {
		return gradoSalarialMin;
	}

	public void setGradoSalarialMin(GradoSalarial gradoSalarialMin) {
		this.gradoSalarialMin = gradoSalarialMin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grado_salarial_max")
	public GradoSalarial getGradoSalarialMax() {
		return gradoSalarialMax;
	}

	public void setGradoSalarialMax(GradoSalarial gradoSalarialMax) {
		this.gradoSalarialMax = gradoSalarialMax;
	}
	

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}
	

	@Column(name = "denominacion")
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}
	
	@Column(name = "estado_homologacion")
	public String getEstadoHomologacion() {
		return estadoHomologacion;
	}


	public void setEstadoHomologacion(String estadoHomologacion) {
		this.estadoHomologacion = estadoHomologacion;
	}
	

	@Column(name = "jefatura")
	public Boolean getJefatura() {
		return this.jefatura;
	}

	public void setJefatura(Boolean jefatura) {
		this.jefatura = jefatura;
	}
	

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Column(name = "usu_homologacion")
	public String getUsuHomologacion() {
		return usuHomologacion;
	}


	public void setUsuHomologacion(String usuHomologacion) {
		this.usuHomologacion = usuHomologacion;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	
	@Column(name = "nro_especifico")
	public Integer getNroEspecifico() {
		return nroEspecifico;
	}


	public void setNroEspecifico(Integer nroEspecifico) {
		this.nroEspecifico = nroEspecifico;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cpt_padre")
	public Cpt getCptPadre() {
		return cptPadre;
	}


	public void setCptPadre(Cpt cptPadre) {
		this.cptPadre = cptPadre;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_cab")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}


	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cpt")
	public Set<HomologacionPerfilMatriz> getHomologacionPerfilMatrizs() {
		return this.homologacionPerfilMatrizs;
	}

	public void setHomologacionPerfilMatrizs(
			Set<HomologacionPerfilMatriz> homologacionPerfilMatrizs) {
		this.homologacionPerfilMatrizs = homologacionPerfilMatrizs;
	}


	@Transient
	public Long getId() {
		return idCpt;
	}

	/**
	 * 
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.CPT_ID, getId());
		properties.put(SICCASessionParameters.CPT_DENOMINACION,
				denominacion);

		return properties;
	}

	/**
	 * 
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}

	@Column(name = "fecha_solicitud_homologacion")
	public Date getFechaSolicitudHomologacion() {
		return fechaSolicitudHomologacion;
	}


	public void setFechaSolicitudHomologacion(Date fechaSolicitudHomologacion) {
		this.fechaSolicitudHomologacion = fechaSolicitudHomologacion;
	}

	@Column(name = "fecha_homologacion")
	public Date getFechaHomologacion() {
		return fechaHomologacion;
	}


	public void setFechaHomologacion(Date fechaHomologacion) {
		this.fechaHomologacion = fechaHomologacion;
	}

}
