package py.com.excelsis.sicca.entity;

// Generated 07/11/2011 11:58:24 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CronogramaConcDet generated by hbm2java
 */
@Entity
@Table(name = "cronograma_conc_det", schema = "seleccion")
public class CronogramaConcDet implements java.io.Serializable {

	private Long idCronogramaConcDet;
	private DatosEspecificos datosEspecificos;
	private CronogramaConcCab cronogramaConcCab;
	private String lugar;
	private Date fecha;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaHasta;
	private Date horaDesde;
	private Date horaHasta;

	@Transient
	private String actividad;

	public CronogramaConcDet() {
	}

	public CronogramaConcDet(
			Long idCronogramaConcDet, CronogramaConcCab cronogramaConcCab,
			DatosEspecificos datosEspecificos, Date fecha, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idCronogramaConcDet = idCronogramaConcDet;
		this.cronogramaConcCab = cronogramaConcCab;
		this.datosEspecificos = datosEspecificos;
		this.fecha = fecha;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CronogramaConcDet(
			Long idCronogramaConcDet, CronogramaConcCab cronogramaConcCab,
			DatosEspecificos datosEspecificos, String lugar, Date fecha, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idCronogramaConcDet = idCronogramaConcDet;
		this.cronogramaConcCab = cronogramaConcCab;
		this.datosEspecificos = datosEspecificos;
		this.lugar = lugar;
		this.fecha = fecha;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "CRONOGRAMA_CONC_DET")
	@SequenceGenerator(name = "CRONOGRAMA_CONC_DET", sequenceName = "seleccion.cronograma_conc_det_id_cronograma_conc_det_seq")
	@Column(name = "id_cronograma_conc_det", unique = true, nullable = false)
	public Long getIdCronogramaConcDet() {
		return this.idCronogramaConcDet;
	}

	public void setIdCronogramaConcDet(Long idCronogramaConcDet) {
		this.idCronogramaConcDet = idCronogramaConcDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cronograma_conc_cab", nullable = false)
	@NotNull
	public CronogramaConcCab getCronogramaConcCab() {
		return this.cronogramaConcCab;
	}

	public void setCronogramaConcCab(CronogramaConcCab cronogramaConcCab) {
		this.cronogramaConcCab = cronogramaConcCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_acti", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@Column(name = "lugar", length = 200)
	@Length(max = 200)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public String getActividad() {
		return actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hasta", length = 29)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_desde", length = 15)
	public Date getHoraDesde() {
		return this.horaDesde;
	}

	public void setHoraDesde(Date horaDesde) {
		this.horaDesde = horaDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_hasta", length = 15)
	public Date getHoraHasta() {
		return this.horaHasta;
	}

	public void setHoraHasta(Date horaHasta) {
		this.horaHasta = horaHasta;
	}
}
