 
package py.com.excelsis.sicca.entity;

// Generated 07/11/2011 11:58:24 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CronogramaConcCab generated by hbm2java
 */
@Entity
@Table(name = "cronograma_conc_cab", schema = "seleccion")
public class CronogramaConcCab implements java.io.Serializable {

	private Long idCronogramaConcCab;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Concurso concurso;
	private int nroCronograma;
	private String descripcion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<CronogramaConcDet> cronogramaConcDets = new HashSet<CronogramaConcDet>(
			0);
	private Set<SolicProrrogaCab> solicProrrogaCabs = new HashSet<SolicProrrogaCab>(
			0);

	public CronogramaConcCab() {
	}

	public CronogramaConcCab(Long idCronogramaConcCab,
			ConcursoPuestoAgr concursoPuestoAgr, int nroCronograma,
			String descripcion, boolean activo, String usuAlta, Date fechaAlta) {
		this.idCronogramaConcCab = idCronogramaConcCab;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.nroCronograma = nroCronograma;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public CronogramaConcCab(Long idCronogramaConcCab,
			ConcursoPuestoAgr concursoPuestoAgr, int nroCronograma,
			String descripcion, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod,
			Set<CronogramaConcDet> cronogramaConcDets) {
		this.idCronogramaConcCab = idCronogramaConcCab;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.nroCronograma = nroCronograma;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.cronogramaConcDets = cronogramaConcDets;
	}

	@Id
	@GeneratedValue(generator="CRONOGRAMA_CONC_CAB")
	@SequenceGenerator(name="CRONOGRAMA_CONC_CAB",sequenceName="seleccion.cronograma_conc_cab_id_cronograma_conc_cab_seq")
	@Column(name = "id_cronograma_conc_cab", unique = true, nullable = false)
	public Long getIdCronogramaConcCab() {
		return this.idCronogramaConcCab;
	}

	public void setIdCronogramaConcCab(Long idCronogramaConcCab) {
		this.idCronogramaConcCab = idCronogramaConcCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr"  )
	 
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "nro_cronograma", nullable = false)
	public int getNroCronograma() {
		return this.nroCronograma;
	}

	public void setNroCronograma(int nroCronograma) {
		this.nroCronograma = nroCronograma;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso")
	public Concurso getConcurso() {
		return this.concurso;
	}

	public void setConcurso(Concurso concurso) {
		this.concurso = concurso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cronogramaConcCab")
	public Set<CronogramaConcDet> getCronogramaConcDets() {
		return this.cronogramaConcDets;
	}

	public void setCronogramaConcDets(Set<CronogramaConcDet> cronogramaConcDets) {
		this.cronogramaConcDets = cronogramaConcDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cronogramaConcCab")
	public Set<SolicProrrogaCab> getSolicProrrogaCabs() {
		return this.solicProrrogaCabs;
	}

	public void setSolicProrrogaCabs(Set<SolicProrrogaCab> solicProrrogaCabs) {
		this.solicProrrogaCabs = solicProrrogaCabs;
	}
}
