package py.com.excelsis.sicca.entity;

// Generated 15/10/2012 11:05:00 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DatosPremio generated by hbm2java
 */
@Entity
@Table(name = "datos_premio", schema = "legajo")
public class DatosPremio implements java.io.Serializable {

	private Long idDatosPremio;
	private Persona persona;
	private String obsPremio;
	private Integer nroActo;
	private Date fechaActo;
	private Documentos documento;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public DatosPremio() {
	}

	public DatosPremio(Long idDatosPremio, Boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idDatosPremio = idDatosPremio;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public DatosPremio(Long idDatosPremio, Persona idPersona, String obsPremio,
			Integer nroActo, Date fechaActo, Documentos idDocumento, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idDatosPremio = idDatosPremio;
		this.persona = idPersona;
		this.obsPremio = obsPremio;
		this.nroActo = nroActo;
		this.fechaActo = fechaActo;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_datos_premio", unique = true, nullable = false)
	@GeneratedValue(generator = "DATOS_PREMIO_GENERATOR")
	@SequenceGenerator(name = "DATOS_PREMIO_GENERATOR", sequenceName = "legajo.datos_premio_id_datos_premio_seq")

	public Long getIdDatosPremio() {
		return this.idDatosPremio;
	}

	public void setIdDatosPremio(Long idDatosPremio) {
		this.idDatosPremio = idDatosPremio;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	
	

	@Column(name = "obs_premio", length = 250)
	@Length(max = 250)
	public String getObsPremio() {
		return this.obsPremio;
	}

	public void setObsPremio(String obsPremio) {
		this.obsPremio = obsPremio;
	}

	@Column(name = "nro_acto")
	public Integer getNroActo() {
		return this.nroActo;
	}

	public void setNroActo(Integer nroActo) {
		this.nroActo = nroActo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_acto", length = 13)
	public Date getFechaActo() {
		return this.fechaActo;
	}

	public void setFechaActo(Date fechaActo) {
		this.fechaActo = fechaActo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	
	
	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
