package py.com.excelsis.sicca.entity;

// Generated 15-oct-2012 15:52:09 by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Query;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.In;



/**
 * DatosEnfermedad generated by hbm2java
 */
@Entity
@Table(name = "datos_enfermedad", schema = "legajo")
public class DatosEnfermedad implements java.io.Serializable {
	private List<DatosEnfermedad> listaEnfermedades = new ArrayList<DatosEnfermedad>();
	private Long idDatosEnfermedad;
	private Persona persona;
	private String obsEnfermedad;
	private Documentos documento;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	

	public DatosEnfermedad() {
	}

	public DatosEnfermedad(Long idDatosEnfermedad, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idDatosEnfermedad = idDatosEnfermedad;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}
	public DatosEnfermedad(Long idDatosEnfermedad, Persona persona, String obsEnfermedad, Documentos documento,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		
		this.idDatosEnfermedad = idDatosEnfermedad;
		this.persona = persona;
		this.obsEnfermedad = obsEnfermedad;
		this.documento = documento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="DATOS_ENFERMEDAD_GENERATOR")
	@SequenceGenerator(name="DATOS_ENFERMEDAD_GENERATOR",sequenceName="legajo.datos_enfermedad_id_datos_enfermedad_seq")
	@Column(name = "id_datos_enfermedad", unique = true, nullable = false)
	public Long getIdDatosEnfermedad() {
		return this.idDatosEnfermedad;
	}

	public void setIdDatosEnfermedad(Long idDatosEnfermedad) {
		this.idDatosEnfermedad = idDatosEnfermedad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}


	@Column(name = "obs_enfermedad", length = 250)
	@Length(max = 250)
	public String getObsEnfermedad() {
		return this.obsEnfermedad;
	}

	public void setObsEnfermedad(String obsEnfermedad) {
		this.obsEnfermedad = obsEnfermedad;
	}


	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	
}
