package py.com.excelsis.sicca.entity;

// Generated 18/10/2012 01:18:55 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DatosAmonestacion generated by hbm2java
 */
@Entity
@Table(name = "datos_amonestacion", schema = "legajo")
public class DatosAmonestacion implements java.io.Serializable {

	private Long idDatosAmonestacion;
	private Persona persona;
	// private DatosEspecificos datosEspMotivoAmonestacion;
	private String obsAmonestacion;
	private Integer nroActo;
	private Date fechaActo;
	private Documentos documento;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String motivo;
	private DatosEspecificos datosEspTipoSancion;

	public DatosAmonestacion() {
	}

	public DatosAmonestacion(Long idDatosAmonestacion,
			DatosEspecificos idDatosEspMotivoAmonestacion, Boolean activo, String usuAlta,
			Date fechaAlta, DatosEspecificos idDatosEspTipoSancion) {
		this.idDatosAmonestacion = idDatosAmonestacion;
		// this.datosEspMotivoAmonestacion = idDatosEspMotivoAmonestacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.datosEspTipoSancion = idDatosEspTipoSancion;
	}

	public DatosAmonestacion(Long idDatosAmonestacion, Persona persona,
			DatosEspecificos idDatosEspMotivoAmonestacion, String obsAmonestacion,
			Integer nroActo, Date fechaActo, Documentos idDocumento, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod, String motivo, 
			DatosEspecificos idDatosEspTipoSancion) {
		this.idDatosAmonestacion = idDatosAmonestacion;
		this.persona = persona;
		// this.datosEspMotivoAmonestacion = idDatosEspMotivoAmonestacion;
		this.obsAmonestacion = obsAmonestacion;
		this.nroActo = nroActo;
		this.fechaActo = fechaActo;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.motivo = motivo;
		this.datosEspTipoSancion = idDatosEspTipoSancion;
	}

	@Id
	@Column(name = "id_datos_amonestacion", unique = true, nullable = false)
	@GeneratedValue(generator = "DATOS_AMONESTACION_GENERATOR")
	@SequenceGenerator(name = "DATOS_AMONESTACION_GENERATOR", sequenceName = "legajo.datos_amonestacion_id_datos_amonestacion_seq")
	public Long getIdDatosAmonestacion() {
		return this.idDatosAmonestacion;
	}

	public void setIdDatosAmonestacion(Long idDatosAmonestacion) {
		this.idDatosAmonestacion = idDatosAmonestacion;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	
	/*
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_motivo_amonestacion")
	@NotNull
	public DatosEspecificos getDatosEspMotivoAmonestacion() {
		return datosEspMotivoAmonestacion;
	}

	public void setDatosEspMotivoAmonestacion(
			DatosEspecificos datosEspMotivoAmonestacion) {
		this.datosEspMotivoAmonestacion = datosEspMotivoAmonestacion;
	}
	*/
	

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_tipo_sancion")
	@NotNull
	public DatosEspecificos getDatosEspTipoSancion() {
		return datosEspTipoSancion;
	}

	public void setDatosEspTipoSancion(
			DatosEspecificos datosEspTipoSancion) {
		this.datosEspTipoSancion = datosEspTipoSancion;
	}
	
	

	@Column(name = "obs_amonestacion", length = 250)
	@Length(max = 250)
	public String getObsAmonestacion() {
		return this.obsAmonestacion;
	}

	public void setObsAmonestacion(String obsAmonestacion) {
		this.obsAmonestacion = obsAmonestacion;
	}

	@Column(name = "nro_acto")
	public Integer getNroActo() {
		return this.nroActo;
	}

	public void setNroActo(Integer nroActo) {
		this.nroActo = nroActo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_acto", length = 13)
	public Date getFechaActo() {
		return this.fechaActo;
	}

	public void setFechaActo(Date fechaActo) {
		this.fechaActo = fechaActo;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Column(name = "motivo", length = 100)
	@Length(max = 100)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

}
