package py.com.excelsis.sicca.entity;

// Generated 05/10/2011 11:41:21 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DatosGenerales generated by hbm2java
 */
@Entity
@Table(name = "datos_generales", schema = "seleccion")
public class DatosGenerales implements java.io.Serializable {

	private Long idDatosGenerales;
	private String descripcion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<DatosEspecificos> datosEspecificoses = new HashSet<DatosEspecificos>(
			0);

	public DatosGenerales() {
	}

	public DatosGenerales(Long idDatosGenerales, String descripcion,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idDatosGenerales = idDatosGenerales;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public DatosGenerales(Long idDatosGenerales, String descripcion,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Set<DatosEspecificos> datosEspecificoses) {
		this.idDatosGenerales = idDatosGenerales;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.datosEspecificoses = datosEspecificoses;
	}

	@Id
	@GeneratedValue(generator="DATOS_GENERALES_GENERATOR")
	@SequenceGenerator(name="DATOS_GENERALES_GENERATOR",sequenceName="seleccion.sel_datos_generales_id_datos_generales_seq")
	@Column(name = "id_datos_generales", unique = true, nullable = false)
	public Long getIdDatosGenerales() {
		return this.idDatosGenerales;
	}

	public void setIdDatosGenerales(Long idDatosGenerales) {
		this.idDatosGenerales = idDatosGenerales;
	}

	@Column(name = "descripcion", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosGenerales")
	public Set<DatosEspecificos> getDatosEspecificoses() {
		return this.datosEspecificoses;
	}

	public void setDatosEspecificoses(Set<DatosEspecificos> datosEspecificoses) {
		this.datosEspecificoses = datosEspecificoses;
	}

}
