package py.com.excelsis.sicca.entity;

// Generated 15-oct-2012 15:52:09 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DatosSeguroMedico generated by hbm2java
 */
@Entity
@Table(name = "datos_seguro_medico", schema = "legajo")
public class DatosSeguroMedico implements java.io.Serializable {

	private Long idDatosSeguroMedico;
	private Persona persona;
	private DatosEspecificos datosEspSeguroMedico;
	private String planSeguroMedico;
	private String nombreAsegurador;
	private Date fechaIngreso;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	String telefonoSeguro;

	public DatosSeguroMedico() {
	}

	public DatosSeguroMedico(Long idDatosSeguroMedico,
			DatosEspecificos datosEspSeguroMedico, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idDatosSeguroMedico = idDatosSeguroMedico;
		this.datosEspSeguroMedico = datosEspSeguroMedico;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public DatosSeguroMedico(Long idDatosSeguroMedico, Persona persona,
			DatosEspecificos datosEspSeguroMedico, String planSeguroMedico,
			String nombreAsegurador, Date fechaIngreso, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod, String telefonoSeguro) {
		this.idDatosSeguroMedico = idDatosSeguroMedico;
		this.persona = persona;
		this.datosEspSeguroMedico = datosEspSeguroMedico;
		this.planSeguroMedico = planSeguroMedico;
		this.nombreAsegurador = nombreAsegurador;
		this.fechaIngreso = fechaIngreso;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.telefonoSeguro = telefonoSeguro;
	}

	@Id
	@GeneratedValue(generator="DATOS_SEG_MEDICO_GENERATOR")
	@SequenceGenerator(name="DATOS_SEG_MEDICO_GENERATOR",sequenceName="legajo.datos_seguro_medico_id_datos_seguro_medico_seq")
	@Column(name = "id_datos_seguro_medico", unique = true, nullable = false)
	public Long getIdDatosSeguroMedico() {
		return this.idDatosSeguroMedico;
	}

	public void setIdDatosSeguroMedico(Long idDatosSeguroMedico) {
		this.idDatosSeguroMedico = idDatosSeguroMedico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_seguro_medico")
	public DatosEspecificos getDatosEspSeguroMedico() {
		return datosEspSeguroMedico;
	}

	public void setDatosEspSeguroMedico(DatosEspecificos datosEspSeguroMedico) {
		this.datosEspSeguroMedico = datosEspSeguroMedico;
	}

	@Column(name = "plan_seguro_medico", length = 50)
	@Length(max = 50)
	public String getPlanSeguroMedico() {
		return this.planSeguroMedico;
	}

	public void setPlanSeguroMedico(String planSeguroMedico) {
		this.planSeguroMedico = planSeguroMedico;
	}

	@Column(name = "nombre_asegurador", length = 100)
	@Length(max = 100)
	public String getNombreAsegurador() {
		return this.nombreAsegurador;
	}

	public void setNombreAsegurador(String nombreAsegurador) {
		this.nombreAsegurador = nombreAsegurador;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Column(name = "telefono_seguro", length = 20)
	@Length(max = 20)
	public String getTelefonoSeguro() {
		return this.telefonoSeguro;
	}

	public void setTelefonoSeguro(String telefonoSeguro) {
		this.telefonoSeguro = telefonoSeguro;
	}

}
