package py.com.excelsis.sicca.entity;

// Generated 23-oct-2012 17:25:57 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DatosPermiso generated by hbm2java
 */
@Entity
@Table(name = "datos_permiso", schema = "legajo")
public class DatosPermiso implements java.io.Serializable {

	private Long idDatosPermiso;
	private Persona persona;
	private Date fechaInicio;
	private Date fechaFin;
	private Date horaInicio;
	private Date horaFin;
	private DatosEspecificos datosEspMotivoPermiso;
	private String obsPermiso;
	private DatosEspecificos datosEspEstadoPermiso;
	private Integer nroActo;
	private Date fechaActo;
	private Documentos documentos;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public DatosPermiso() {
	}

	public DatosPermiso(
			Long idDatosPermiso, Date fechaInicio, Date fechaFin,
			DatosEspecificos datosEspMotivoPermiso, boolean activo, String usuAlta, Date fechaAlta) {
		this.idDatosPermiso = idDatosPermiso;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.datosEspEstadoPermiso = datosEspMotivoPermiso;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public DatosPermiso(
			Long idDatosPermiso, Persona persona, Date fechaInicio, Date fechaFin, Date horaInicio,
			Date horaFin, DatosEspecificos datosEspMotivoPermiso, String obsPermiso,
			DatosEspecificos datosEspEstadoPermiso, Integer nroActo, Date fechaActo,
			Documentos documentos, boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idDatosPermiso = idDatosPermiso;
		this.persona = persona;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.datosEspMotivoPermiso = datosEspMotivoPermiso;
		this.obsPermiso = obsPermiso;
		this.datosEspEstadoPermiso = datosEspEstadoPermiso;
		this.nroActo = nroActo;
		this.fechaActo = fechaActo;
		this.documentos = documentos;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "DATOS_PERMISO_GENERATOR")
	@SequenceGenerator(name = "DATOS_PERMISO_GENERATOR", sequenceName = "legajo.datos_permiso_id_datos_permiso_seq")
	@Column(name = "id_datos_permiso", unique = true, nullable = false)
	public Long getIdDatosPermiso() {
		return this.idDatosPermiso;
	}

	public void setIdDatosPermiso(Long idDatosPermiso) {
		this.idDatosPermiso = idDatosPermiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_motivo_permiso")
	public DatosEspecificos getDatosEspMotivoPermiso() {
		return datosEspMotivoPermiso;
	}

	public void setDatosEspMotivoPermiso(DatosEspecificos datosEspMotivoPermiso) {
		this.datosEspMotivoPermiso = datosEspMotivoPermiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_estado_permiso")
	public DatosEspecificos getDatosEspEstadoPermiso() {
		return datosEspEstadoPermiso;
	}

	public void setDatosEspEstadoPermiso(DatosEspecificos datosEspEstadoPermiso) {
		this.datosEspEstadoPermiso = datosEspEstadoPermiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	@NotNull
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 13)
	@NotNull
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 15)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", length = 15)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "obs_permiso", length = 500)
	@Length(max = 500)
	public String getObsPermiso() {
		return this.obsPermiso;
	}

	public void setObsPermiso(String obsPermiso) {
		this.obsPermiso = obsPermiso;
	}

	@Column(name = "nro_acto")
	public Integer getNroActo() {
		return this.nroActo;
	}

	public void setNroActo(Integer nroActo) {
		this.nroActo = nroActo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_acto", length = 13)
	public Date getFechaActo() {
		return this.fechaActo;
	}

	public void setFechaActo(Date fechaActo) {
		this.fechaActo = fechaActo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
