package py.com.excelsis.sicca.entity;

// Generated 15-oct-2012 15:52:09 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DeclaracionJurada generated by hbm2java
 */
@Entity
@Table(name = "declaracion_jurada", schema = "legajo")
public class DeclaracionJurada implements java.io.Serializable {

	private Long idDeclaracionJurada;
	private Documentos documento;
	private Persona persona;
	private Date fechaPresentacion;
	private String comentario;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public DeclaracionJurada() {
	}

	public DeclaracionJurada(Long idDeclaracionJurada, Persona persona,
			Date fechaPresentacion, String comentario, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idDeclaracionJurada = idDeclaracionJurada;
		this.persona = persona;
		this.fechaPresentacion = fechaPresentacion;
		this.comentario = comentario;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public DeclaracionJurada(Long idDeclaracionJurada, Documentos documento,
			Persona persona, Date fechaPresentacion, String comentario,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idDeclaracionJurada = idDeclaracionJurada;
		this.documento = documento;
		this.persona = persona;
		this.fechaPresentacion = fechaPresentacion;
		this.comentario = comentario;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="DECLARACION_JURADA_GENERATOR")
	@SequenceGenerator(name="DECLARACION_JURADA_GENERATOR",sequenceName="legajo.declaracion_jurada_id_declaracion_jurada_seq")
	@Column(name = "id_declaracion_jurada", unique = true, nullable = false)
	public Long getIdDeclaracionJurada() {
		return this.idDeclaracionJurada;
	}

	public void setIdDeclaracionJurada(Long idDeclaracionJurada) {
		this.idDeclaracionJurada = idDeclaracionJurada;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_presentacion", nullable = false, length = 29)
	@NotNull
	public Date getFechaPresentacion() {
		return this.fechaPresentacion;
	}

	public void setFechaPresentacion(Date fechaPresentacion) {
		this.fechaPresentacion = fechaPresentacion;
	}

	@Column(name = "comentario", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
