package py.com.excelsis.sicca.entity;

// Generated 10-feb-2012 9:53:04 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Desvinculacion generated by hbm2java
 */
@Entity
@Table(name = "desvinculacion", schema = "desvinculacion")
public class Desvinculacion implements java.io.Serializable {

	private Long idDesvinculacion;
	private EmpleadoPuesto empleadoPuesto;
	private DatosEspecificos datosEspecifMotivo;
	private BigDecimal montoLiquidacion;
	private String observacion;
	private String concepto;
	private String usuAlta;
	private Date fechaAlta;
	private Date fechaDesvinculacion;
	private Desvinculacion desvinculacion;
	
	public Desvinculacion() {
	}

	public Desvinculacion(Long idDesvinculacion, EmpleadoPuesto empleadoPuesto,
			DatosEspecificos datosEspecifMotivo, String usuAlta, Date fechaAlta) {
		this.idDesvinculacion = idDesvinculacion;
		this.empleadoPuesto = empleadoPuesto;
		this.datosEspecifMotivo = datosEspecifMotivo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public Desvinculacion(Long idDesvinculacion, EmpleadoPuesto empleadoPuesto,
			DatosEspecificos datosEspecifMotivo, BigDecimal montoLiquidacion,
			String observacion, String concepto, String usuAlta, Date fechaAlta) {
		this.idDesvinculacion = idDesvinculacion;
		this.empleadoPuesto = empleadoPuesto;
		this.datosEspecifMotivo = datosEspecifMotivo;
		this.montoLiquidacion = montoLiquidacion;
		this.observacion = observacion;
		this.concepto = concepto;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	@Id
	@GeneratedValue(generator="DESVINCULACION_GENERATOR")
	@SequenceGenerator(name="DESVINCULACION_GENERATOR",sequenceName="desvinculacion.desvinculacion_id_desvinculacion_seq")
	@Column(name = "id_desvinculacion", unique = true, nullable = false)
	public Long getIdDesvinculacion() {
		return this.idDesvinculacion;
	}

	public void setIdDesvinculacion(Long idDesvinculacion) {
		this.idDesvinculacion = idDesvinculacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto", nullable = false)
	@NotNull
	public EmpleadoPuesto getEmpleadoPuesto() {
		return this.empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especif_motivo", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecifMotivo() {
		return datosEspecifMotivo;
	}

	public void setDatosEspecifMotivo(DatosEspecificos datosEspecifMotivo) {
		this.datosEspecifMotivo = datosEspecifMotivo;
	}
	

	@Column(name = "monto_liquidacion", precision = 131089, scale = 0)
	public BigDecimal getMontoLiquidacion() {
		return this.montoLiquidacion;
	}

	

	public void setMontoLiquidacion(BigDecimal montoLiquidacion) {
		this.montoLiquidacion = montoLiquidacion;
	}

	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "concepto", length = 200)
	@Length(max = 200)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_desvinculacion", length = 29)
	public Date getFechaDesvinculacion() {
		return fechaDesvinculacion;
	}

	public void setFechaDesvinculacion(Date fechaDesvinculacion) {
		this.fechaDesvinculacion = fechaDesvinculacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_desvinculacion_padre")
	public Desvinculacion getDesvinculacion() {
		return desvinculacion;
	}

	public void setDesvinculacion(Desvinculacion desvinculacion) {
		this.desvinculacion = desvinculacion;
	}

	
	

}
