package py.com.excelsis.sicca.entity;

// Generated 15-sep-2011 8:16:18 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import com.sun.org.apache.xpath.internal.operations.Bool;

/**
 * DetCondicionTrabajo generated by hbm2java
 */
@Entity
@Table(name = "det_condicion_trabajo", schema = "planificacion")
public class DetCondicionTrabajo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3072786776457641259L;
	private Long idDetCondiconTrabajo;
	private PlantaCargoDet plantaCargoDet;
	private Cpt cpt;
	private CondicionTrabajo condicionTrabajo;
	private String tipo;
	private Float puntajeCondTrab;
	private Boolean activo;
	private ConcursoPuestoAgr concursoPuestoAgr;

	public DetCondicionTrabajo() {
	}

	@Id
	@GeneratedValue(generator="DET_CONDICION_TRABAJO_GENERATOR")
	@SequenceGenerator(name="DET_CONDICION_TRABAJO_GENERATOR",sequenceName="planificacion.det_condicion_trabajo_id_det_condicon_trabajo_seq")
	@Column(name = "id_det_condicon_trabajo", unique = true, nullable = false)
	public Long getIdDetCondiconTrabajo() {
		return this.idDetCondiconTrabajo;
	}

	public void setIdDetCondiconTrabajo(Long idDetCondiconTrabajo) {
		this.idDetCondiconTrabajo = idDetCondiconTrabajo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_planta_cargo_det")
	public PlantaCargoDet getPlantaCargoDet() {
		return this.plantaCargoDet;
	}

	public void setPlantaCargoDet(PlantaCargoDet plantaCargoDet) {
		this.plantaCargoDet = plantaCargoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cpt")
	public Cpt getCpt() {
		return this.cpt;
	}

	public void setCpt(Cpt cpt) {
		this.cpt = cpt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_condicion_trabajo", nullable = false)
	@NotNull
	public CondicionTrabajo getCondicionTrabajo() {
		return this.condicionTrabajo;
	}

	public void setCondicionTrabajo(CondicionTrabajo condicionTrabajo) {
		this.condicionTrabajo = condicionTrabajo;
	}

	@Column(name = "tipo", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "puntaje_cond_trab", nullable = false, precision = 8, scale = 8)
	public Float getPuntajeCondTrab() {
		return this.puntajeCondTrab;
	}

	public void setPuntajeCondTrab(Float puntajeCondTrab) {
		this.puntajeCondTrab = puntajeCondTrab;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

}
