package py.com.excelsis.sicca.entity;

// Generated 30/08/2012 01:05:43 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DetListaElegibles generated by hbm2java
 */
@Entity
@Table(name = "det_lista_elegibles", schema = "seleccion")
public class DetListaElegibles implements java.io.Serializable {

	private long idDetListaElegible;
	private ListaElegibles listaElegibles;
	private DatosEspecificos datosEspecificos;
	private Postulacion postulacion;
	private String obsEstado;
	private Boolean seleccionado;
	private long usuAlta;
	private Date fechaAlta;
	private Long idDocumento;

	public DetListaElegibles() {
	}

	public DetListaElegibles(long idDetListaElegible,
			ListaElegibles listaElegibles, Postulacion postulacion,
			long usuAlta, Date fechaAlta) {
		this.idDetListaElegible = idDetListaElegible;
		this.listaElegibles = listaElegibles;
		this.postulacion = postulacion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public DetListaElegibles(long idDetListaElegible,
			ListaElegibles listaElegibles, DatosEspecificos datosEspecificos,
			Postulacion postulacion, String obsEstado, Boolean seleccionado,
			long usuAlta, Date fechaAlta, Long idDocumento) {
		this.idDetListaElegible = idDetListaElegible;
		this.listaElegibles = listaElegibles;
		this.datosEspecificos = datosEspecificos;
		this.postulacion = postulacion;
		this.obsEstado = obsEstado;
		this.seleccionado = seleccionado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.idDocumento = idDocumento;
	}

	@Id
	@Column(name = "id_det_lista_elegible", unique = true, nullable = false)
	public long getIdDetListaElegible() {
		return this.idDetListaElegible;
	}

	public void setIdDetListaElegible(long idDetListaElegible) {
		this.idDetListaElegible = idDetListaElegible;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_lista_elegible", nullable = false)
	@NotNull
	public ListaElegibles getListaElegibles() {
		return this.listaElegibles;
	}

	public void setListaElegibles(ListaElegibles listaElegibles) {
		this.listaElegibles = listaElegibles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_estado_elegible")
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@Column(name = "obs_estado", length = 250)
	@Length(max = 250)
	public String getObsEstado() {
		return this.obsEstado;
	}

	public void setObsEstado(String obsEstado) {
		this.obsEstado = obsEstado;
	}

	@Column(name = "seleccionado")
	public Boolean getSeleccionado() {
		return this.seleccionado;
	}

	public void setSeleccionado(Boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

	@Column(name = "usu_alta", nullable = false)
	public long getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(long usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "id_documento")
	public Long getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(Long idDocumento) {
		this.idDocumento = idDocumento;
	}

}
