package py.com.excelsis.sicca.entity;

// Generated 15-sep-2011 8:16:18 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DetOpcionesConvenientes generated by hbm2java
 */
@Entity
@Table(name = "det_opciones_convenientes", schema = "planificacion")
public class DetOpcionesConvenientes implements java.io.Serializable {

	private Long idDetOpcionesConvenientes;
	private DetReqMin detReqMin;
	private String opcConvenientes;
	private Boolean activo;
	protected boolean selected = false;

	public DetOpcionesConvenientes() {
	}

	public DetOpcionesConvenientes(Long idDetOpcionesConvenientes,
			String opcConvenientes, Boolean activo) {
		this.idDetOpcionesConvenientes = idDetOpcionesConvenientes;
		this.opcConvenientes = opcConvenientes;
		this.activo = activo;
	}

	public DetOpcionesConvenientes(Long idDetOpcionesConvenientes,
			DetReqMin detReqMin, String opcConvenientes, Boolean activo) {
		this.idDetOpcionesConvenientes = idDetOpcionesConvenientes;
		this.detReqMin = detReqMin;
		this.opcConvenientes = opcConvenientes;
		this.activo = activo;
	}

	@Id
	@GeneratedValue(generator="DET_OPCIONES_CONVENIENTES_GENERATOR")
	@SequenceGenerator(name="DET_OPCIONES_CONVENIENTES_GENERATOR",sequenceName="planificacion.det_opciones_convenientes_id_det_opciones_convenientes_seq")
	@Column(name = "id_det_opciones_convenientes", unique = true, nullable = false)
	public Long getIdDetOpcionesConvenientes() {
		return this.idDetOpcionesConvenientes;
	}

	public void setIdDetOpcionesConvenientes(Long idDetOpcionesConvenientes) {
		this.idDetOpcionesConvenientes = idDetOpcionesConvenientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_det_req_min")
	public DetReqMin getDetReqMin() {
		return this.detReqMin;
	}

	public void setDetReqMin(DetReqMin detReqMin) {
		this.detReqMin = detReqMin;
	}

	@Column(name = "opc_convenientes", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getOpcConvenientes() {
		return this.opcConvenientes;
	}

	public void setOpcConvenientes(String opcConvenientes) {
		this.opcConvenientes = opcConvenientes;
	}

	

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
    @Transient
    public boolean isSelected() 
    {
        return selected;
    }
    
    public void setSelected(boolean selected) 
    {
        this.selected = selected;
    }
}
