package py.com.excelsis.sicca.entity;

// Generated 15/10/2012 11:05:00 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DiscapacidadApoyos generated by hbm2java
 */
@Entity
@Table(name = "discapacidad_apoyos", schema = "legajo")
public class DiscapacidadApoyos implements java.io.Serializable {

	private Long idDiscapacidadApoyos;
	private Persona persona;
	private Boolean instRehab;
	private Boolean centroSal;
	private Boolean particular;
	private Boolean entrenamiento;
	private Boolean otroApoyo;
	private String comentario;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean ninguno;

	public DiscapacidadApoyos() {
	}

	public DiscapacidadApoyos(Long idDiscapacidadApoyos, Persona idPersona,
			Boolean instRehab, Boolean centroSal, Boolean particular,
			Boolean entrenamiento, Boolean otroApoyo, Boolean activo,
			String usuAlta, Date fechaAlta, Boolean ninguno) {
		this.idDiscapacidadApoyos = idDiscapacidadApoyos;
		this.persona = idPersona;
		this.instRehab = instRehab;
		this.centroSal = centroSal;
		this.particular = particular;
		this.entrenamiento = entrenamiento;
		this.otroApoyo = otroApoyo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.ninguno = ninguno;
	}

	public DiscapacidadApoyos(Long idDiscapacidadApoyos, Persona idPersona,
			Boolean instRehab, Boolean centroSal, Boolean particular,
			Boolean entrenamiento, Boolean otroApoyo, String comentario,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Boolean ninguno) {
		this.idDiscapacidadApoyos = idDiscapacidadApoyos;
		this.persona = idPersona;
		this.instRehab = instRehab;
		this.centroSal = centroSal;
		this.particular = particular;
		this.entrenamiento = entrenamiento;
		this.otroApoyo = otroApoyo;
		this.comentario = comentario;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.ninguno = ninguno;
	}

	@Id
	@Column(name = "id_discapacidad_apoyos", unique = true, nullable = false)
	@GeneratedValue(generator = "DISCAPACIDAD_APOYOS_GENERATOR")
	@SequenceGenerator(name = "DISCAPACIDAD_APOYOS_GENERATOR", sequenceName = "legajo.discapacidad_apoyos_id_discapacidad_apoyos_seq")
	public Long getIdDiscapacidadApoyos() {
		return this.idDiscapacidadApoyos;
	}

	public void setIdDiscapacidadApoyos(Long idDiscapacidadApoyos) {
		this.idDiscapacidadApoyos = idDiscapacidadApoyos;
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	@NotNull
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	
	
	@Column(name = "inst_rehab", nullable = false)
	public Boolean getInstRehab() {
		return instRehab;
	}

	public void setInstRehab(Boolean instRehab) {
		this.instRehab = instRehab;
	}

	


	@Column(name = "centro_sal", nullable = false)
	public Boolean getCentroSal() {
		return centroSal;
	}

	public void setCentroSal(Boolean centroSal) {
		this.centroSal = centroSal;
	}

	
	
	@Column(name = "particular", nullable = false)
	public Boolean getParticular() {
		return particular;
	}

	public void setParticular(Boolean particular) {
		this.particular = particular;
	}

	
	@Column(name = "entrenamiento", nullable = false)
	public Boolean getEntrenamiento() {
		return entrenamiento;
	}

	public void setEntrenamiento(Boolean entrenamiento) {
		this.entrenamiento = entrenamiento;
	}

	
	
	@Column(name = "otro_apoyo", nullable = false)
	public Boolean getOtroApoyo() {
		return otroApoyo;
	}

	public void setOtroApoyo(Boolean otroApoyo) {
		this.otroApoyo = otroApoyo;
	}

	
	

	@Column(name = "comentario", length = 250)
	@Length(max = 250)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	
	@Column(name = "ninguno", nullable = false)
	public Boolean getNinguno() {
		return ninguno;
	}

	public void setNinguno(Boolean ninguno) {
		this.ninguno = ninguno;
	}


	

}
