package py.com.excelsis.sicca.entity;

// Generated 15-oct-2012 15:52:09 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DocumentosPersona generated by hbm2java
 */
@Entity
@Table(name = "documentos_persona", schema = "legajo")
public class DocumentosPersona implements java.io.Serializable {

	private Long idDocumentosPersona;
	private Persona persona;
	private Integer tipoDocumento;
	private String documentoNro;
	private String otroDato;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public DocumentosPersona() {
	}

	public DocumentosPersona(Long idDocumentosPersona, Persona persona,
			Integer tipoDocumento, String usuAlta, Date fechaAlta) {
		this.idDocumentosPersona = idDocumentosPersona;
		this.persona = persona;
		this.tipoDocumento = tipoDocumento;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public DocumentosPersona(Long idDocumentosPersona, Persona persona,
			Integer tipoDocumento, String documentoNro, String otroDato,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idDocumentosPersona = idDocumentosPersona;
		this.persona = persona;
		this.tipoDocumento = tipoDocumento;
		this.documentoNro = documentoNro;
		this.otroDato = otroDato;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "DOCUMENTOS_PERSONA_GENERATOR")
	@SequenceGenerator(name = "DOCUMENTOS_PERSONA_GENERATOR", sequenceName = "legajo.documentos_persona_id_documentos_persona_seq")
	@Column(name = "id_documentos_persona", unique = true, nullable = false)
	public Long getIdDocumentosPersona() {
		return this.idDocumentosPersona;
	}

	public void setIdDocumentosPersona(Long idDocumentosPersona) {
		this.idDocumentosPersona = idDocumentosPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "tipo_documento")
	public Integer getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(Integer tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "documento_nro", length = 14)
	@Length(max = 14)
	public String getDocumentoNro() {
		return this.documentoNro;
	}

	public void setDocumentoNro(String documentoNro) {
		this.documentoNro = documentoNro;
	}

	@Column(name = "otro_dato", length = 50)
	@Length(max = 50)
	public String getOtroDato() {
		return this.otroDato;
	}

	public void setOtroDato(String otroDato) {
		this.otroDato = otroDato;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
