package py.com.excelsis.sicca.entity;

// Generated 22/12/2011 04:46:20 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EmpleadoPuesto generated by hbm2java
 */
@Entity
@Table(name = "empleado_puesto", schema = "general")
public class EmpleadoPuesto implements java.io.Serializable {

	private Long idEmpleadoPuesto;
	private PlantaCargoDet plantaCargoDet;
	private TipoNombramiento tipoNombramiento;
	private Persona persona;
	private int lineaPresupuestaria;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private boolean activo;
	private Integer nroContrato;
	private Integer discapacitado;
	private String categoria;
	private boolean actual;
	private Boolean contratado;
	private Date fechaInicio;
	private Date fechaFin;
	private Date fechaFirmaContrato;
	private Date fechaFinContrato;
	private String pin;
	private String observacion;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Set<EmpleadoConceptoPago> empleadoConceptoPagos = new HashSet<EmpleadoConceptoPago>(0);
	private DatosEspecificos datosEspecificosByIdDatosEspTipoIngresoMovilidad;
	private DatosEspecificos datosEspecificosByIdDatosEspEstado;
	private DatosEspecificos datosEspecificosByIdDatosEspTipoRegistro;
	private DatosEspecificos datosEspecificosByIdDatosEspSituacion;
	private Set<SumarioCab> sumarioCabs = new HashSet<SumarioCab>(0);
	private boolean selecciono;
	private boolean selecciono2;
	private Boolean incidenAntiguedad = true;
	private String descPuestoHistorico;
	private String descOeeHistorico;
	private Set<Importacion> importacions = new HashSet<Importacion>(0);
	private Set<HistoricoRemuneraciones> historicoRemuneracioneses =
		new HashSet<HistoricoRemuneraciones>(0);
	private Set<Remuneraciones> remuneracioneses = new HashSet<Remuneraciones>(0);
	private String encabezadoActoAdministrativo;
	private String descripcionFunciones;
	private String descUoHistorico;
	
	public EmpleadoPuesto() {
	}

	public EmpleadoPuesto(
			Long idEmpleadoPuesto, PlantaCargoDet plantaCargoDet, int lineaPresupuestaria,
			String usuAlta, Date fechaAlta, boolean activo, boolean actual, Boolean contratado,
			Date fechaInicio, DatosEspecificos idDatosEspTipoVinculacion, String encabezadoActoAdministrativo) {
		this.idEmpleadoPuesto = idEmpleadoPuesto;
		this.plantaCargoDet = plantaCargoDet;
		this.lineaPresupuestaria = lineaPresupuestaria;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.actual = actual;
		this.contratado = contratado;
		this.fechaInicio = fechaInicio;
		this.encabezadoActoAdministrativo = encabezadoActoAdministrativo;
	}

	public EmpleadoPuesto(
			Long idEmpleadoPuesto, PlantaCargoDet plantaCargoDet,
			TipoNombramiento tipoNombramiento, Persona persona, int lineaPresupuestaria,
			String usuAlta, String usuMod, Date fechaMod, Date fechaAlta, boolean activo,
			Integer nroContrato, String categoria, boolean actual, Boolean contratado,
			Date fechaInicio, Date fechaFin, Date fechaFirmaContrato, Date fechaFinContrato,
			Set<Importacion> importacions, Set<HistoricoRemuneraciones> historicoRemuneracioneses,
			Set<Remuneraciones> remuneracioneses, int monto, DatosEspecificos idDatosEspTipoVinculacion, 
			String encabezadoActoAdministrativo, String descripcionFunciones) {
		this.idEmpleadoPuesto = idEmpleadoPuesto;
		this.plantaCargoDet = plantaCargoDet;
		this.tipoNombramiento = tipoNombramiento;
		this.persona = persona;
		this.lineaPresupuestaria = lineaPresupuestaria;
		this.usuAlta = usuAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.nroContrato = nroContrato;
		this.categoria = categoria;
		this.actual = actual;
		this.contratado = contratado;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.fechaFirmaContrato = fechaFirmaContrato;
		this.fechaFinContrato = fechaFinContrato;
		this.importacions = importacions;
		this.historicoRemuneracioneses = historicoRemuneracioneses;
		this.remuneracioneses = remuneracioneses;
		this.encabezadoActoAdministrativo = encabezadoActoAdministrativo;
		this.descripcionFunciones = descripcionFunciones;
	}

	@Id
	@GeneratedValue(generator = "EMPLEADO_PUESTO_GENERATOR")
	@SequenceGenerator(name = "EMPLEADO_PUESTO_GENERATOR", sequenceName = "general.empleado_puesto_id_empleado_puesto_seq")
	@Column(name = "id_empleado_puesto", unique = true, nullable = false)
	public Long getIdEmpleadoPuesto() {
		return this.idEmpleadoPuesto;
	}

	public void setIdEmpleadoPuesto(Long idEmpleadoPuesto) {
		this.idEmpleadoPuesto = idEmpleadoPuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_planta_cargo_det")
	public PlantaCargoDet getPlantaCargoDet() {
		return this.plantaCargoDet;
	}

	public void setPlantaCargoDet(PlantaCargoDet plantaCargoDet) {
		this.plantaCargoDet = plantaCargoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_nombramiento")
	public TipoNombramiento getTipoNombramiento() {
		return this.tipoNombramiento;
	}

	public void setTipoNombramiento(TipoNombramiento tipoNombramiento) {
		this.tipoNombramiento = tipoNombramiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "linea_presupuestaria", nullable = false)
	public int getLineaPresupuestaria() {
		return this.lineaPresupuestaria;
	}

	public void setLineaPresupuestaria(int lineaPresupuestaria) {
		this.lineaPresupuestaria = lineaPresupuestaria;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "nro_contrato")
	public Integer getNroContrato() {
		return this.nroContrato;
	}

	public void setNroContrato(Integer nroContrato) {
		this.nroContrato = nroContrato;
	}

	@Column(name = "categoria", length = 10)
	@Length(max = 10)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "actual", nullable = false)
	public boolean isActual() {
		return this.actual;
	}

	public void setActual(boolean actual) {
		this.actual = actual;
	}

	@Column(name = "contratado", nullable = false)
	public Boolean getContratado() {
		return this.contratado;
	}

	public void setContratado(Boolean contratado) {
		this.contratado = contratado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	@NotNull
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_firma_contrato", length = 13)
	public Date getFechaFirmaContrato() {
		return this.fechaFirmaContrato;
	}

	public void setFechaFirmaContrato(Date fechaFirmaContrato) {
		this.fechaFirmaContrato = fechaFirmaContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin_contrato", length = 13)
	public Date getFechaFinContrato() {
		return this.fechaFinContrato;
	}

	public void setFechaFinContrato(Date fechaFinContrato) {
		this.fechaFinContrato = fechaFinContrato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoPuesto")
	public Set<EmpleadoConceptoPago> getEmpleadoConceptoPagos() {
		return this.empleadoConceptoPagos;
	}

	public void setEmpleadoConceptoPagos(Set<EmpleadoConceptoPago> empleadoConceptoPagos) {
		this.empleadoConceptoPagos = empleadoConceptoPagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoPuesto")
	public Set<SumarioCab> getSumarioCabs() {
		return this.sumarioCabs;
	}

	public void setSumarioCabs(Set<SumarioCab> sumarioCabs) {
		this.sumarioCabs = sumarioCabs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_tipo_ingreso_movilidad")
	public DatosEspecificos getDatosEspecificosByIdDatosEspTipoIngresoMovilidad() {
		return this.datosEspecificosByIdDatosEspTipoIngresoMovilidad;
	}

	public void setDatosEspecificosByIdDatosEspTipoIngresoMovilidad(DatosEspecificos datosEspecificosByIdDatosEspTipoIngresoMovilidad) {
		this.datosEspecificosByIdDatosEspTipoIngresoMovilidad =
			datosEspecificosByIdDatosEspTipoIngresoMovilidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_estado")
	public DatosEspecificos getDatosEspecificosByIdDatosEspEstado() {
		return this.datosEspecificosByIdDatosEspEstado;
	}

	public void setDatosEspecificosByIdDatosEspEstado(DatosEspecificos datosEspecificosByIdDatosEspEstado) {
		this.datosEspecificosByIdDatosEspEstado = datosEspecificosByIdDatosEspEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_tipo_registro")
	public DatosEspecificos getDatosEspecificosByIdDatosEspTipoRegistro() {
		return this.datosEspecificosByIdDatosEspTipoRegistro;
	}

	public void setDatosEspecificosByIdDatosEspTipoRegistro(DatosEspecificos datosEspecificosByIdDatosEspTipoRegistro) {
		this.datosEspecificosByIdDatosEspTipoRegistro = datosEspecificosByIdDatosEspTipoRegistro;
	}

	@Column(name = "discapacitado")
	public Integer getDiscapacitado() {
		return discapacitado;
	}

	public void setDiscapacitado(Integer discapacitado) {
		this.discapacitado = discapacitado;
	}

	@Column(name = "pin", length = 40)
	@Length(max = 40)
	public String getPin() {
		return pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Transient
	public boolean isSelecciono() {
		return selecciono;
	}

	public void setSelecciono(boolean selecciono) {
		this.selecciono = selecciono;
	}

	@Transient
	public boolean isSelecciono2() {
		return selecciono2;
	}

	public void setSelecciono2(boolean selecciono) {
		this.selecciono2 = selecciono;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_situacion")
	public DatosEspecificos getDatosEspecificosByIdDatosEspSituacion() {
		return datosEspecificosByIdDatosEspSituacion;
	}

	public void setDatosEspecificosByIdDatosEspSituacion(DatosEspecificos datosEspecificosByIdDatosEspSituacion) {
		this.datosEspecificosByIdDatosEspSituacion = datosEspecificosByIdDatosEspSituacion;
	}

	@Column(name = "incide_antiguedad", nullable = false )
	public Boolean getIncidenAntiguedad() {
		return incidenAntiguedad;
	}

	public void setIncidenAntiguedad(Boolean incidenAntiguedad) {
		this.incidenAntiguedad = incidenAntiguedad;
	}

	@Column(name = "desc_puesto_historico", length = 200)
	public String getDescPuestoHistorico() {
		return descPuestoHistorico;
	}

	public void setDescPuestoHistorico(String descPuestoHistorico) {
		this.descPuestoHistorico = descPuestoHistorico;
	}

	@Column(name = "desc_oee_historico", length = 200)
	public String getDescOeeHistorico() {
		return descOeeHistorico;
	}

	public void setDescOeeHistorico(String descOeeHistorico) {
		this.descOeeHistorico = descOeeHistorico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoPuesto")
	public Set<Importacion> getImportacions() {
		return this.importacions;
	}

	public void setImportacions(Set<Importacion> importacions) {
		this.importacions = importacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoPuesto")
	public Set<HistoricoRemuneraciones> getHistoricoRemuneracioneses() {
		return this.historicoRemuneracioneses;
	}

	public void setHistoricoRemuneracioneses(Set<HistoricoRemuneraciones> historicoRemuneracioneses) {
		this.historicoRemuneracioneses = historicoRemuneracioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoPuesto")
	public Set<Remuneraciones> getRemuneracioneses() {
		return this.remuneracioneses;
	}

	public void setRemuneracioneses(Set<Remuneraciones> remuneracioneses) {
		this.remuneracioneses = remuneracioneses;
	}
	

	@Column(name = "encabezado_acto_administrativo", length = 500)
	@Length(max = 500)
	public String getEncabezadoActoAdministrativo() {
		return encabezadoActoAdministrativo;
	}

	public void setEncabezadoActoAdministrativo(String encabezadoActoAdministrativo) {
		this.encabezadoActoAdministrativo = encabezadoActoAdministrativo;
	}
	
	@Column(name = "descripcion_funciones")
	public String getDescripcionFunciones() {
		return descripcionFunciones;
	}

	public void setDescripcionFunciones(String descripcionFunciones) {
		this.descripcionFunciones = descripcionFunciones;
	}

	@Column(name = "desc_uo_historico")
	public String getDescUoHistorico() {
		return descUoHistorico;
	}

	public void setDescUoHistorico(String descUoHistorico) {
		this.descUoHistorico = descUoHistorico;
	}

}
