package py.com.excelsis.sicca.entity;

// Generated 26-nov-2012 11:02:29 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EmpleadoMovilidadDocTcl generated by hbm2java
 */
@Entity
@Table(name = "empleado_movilidad_doc_tcl", schema = "movilidad")
public class EmpleadoMovilidadDocTcl implements java.io.Serializable {

	private Long idEmpleadoMovilidadMovilidadDocTcl;
	private EmpleadoMovilidadCab empleadoMovilidadCab;
	private Boolean notaSolicitud;
	private Boolean resolucionAceptacion;
	private Boolean copiaLegajo;
	private Boolean constanciaUaf;
	private Boolean cuadroPresupuesto;
	private Boolean informeSfp;
	private Boolean informeHacienda;
	private Boolean resolucionMhSeaf;
	private Boolean decreto;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public EmpleadoMovilidadDocTcl() {
	}

	public EmpleadoMovilidadDocTcl(Long idEmpleadoMovilidadMovilidadDocTcl,
			EmpleadoMovilidadCab empleadoMovilidadCab, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idEmpleadoMovilidadMovilidadDocTcl = idEmpleadoMovilidadMovilidadDocTcl;
		this.empleadoMovilidadCab = empleadoMovilidadCab;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EmpleadoMovilidadDocTcl(Long idEmpleadoMovilidadMovilidadDocTcl,
			EmpleadoMovilidadCab empleadoMovilidadCab, Boolean notaSolicitud,
			Boolean resolucionAceptacion, Boolean copiaLegajo,
			Boolean constanciaUaf, Boolean cuadroPresupuesto,
			Boolean informeSfp, Boolean informeHacienda,
			Boolean resolucionMhSeaf, Boolean decreto, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idEmpleadoMovilidadMovilidadDocTcl = idEmpleadoMovilidadMovilidadDocTcl;
		this.empleadoMovilidadCab = empleadoMovilidadCab;
		this.notaSolicitud = notaSolicitud;
		this.resolucionAceptacion = resolucionAceptacion;
		this.copiaLegajo = copiaLegajo;
		this.constanciaUaf = constanciaUaf;
		this.cuadroPresupuesto = cuadroPresupuesto;
		this.informeSfp = informeSfp;
		this.informeHacienda = informeHacienda;
		this.resolucionMhSeaf = resolucionMhSeaf;
		this.decreto = decreto;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_empleado_movilidad_movilidad_doc_tcl", unique = true, nullable = false)
	@GeneratedValue(generator = "EMPLEADO_MOVILIDAD_DOC_TCL_GENERATOR")
	@SequenceGenerator(name = "EMPLEADO_MOVILIDAD_DOC_TCL_GENERATOR", sequenceName = "movilidad.empleado_movilidad_doc_tcl_id_empleado_movilidad_movilidad__seq")
	public Long getIdEmpleadoMovilidadMovilidadDocTcl() {
		return this.idEmpleadoMovilidadMovilidadDocTcl;
	}

	public void setIdEmpleadoMovilidadMovilidadDocTcl(
			Long idEmpleadoMovilidadMovilidadDocTcl) {
		this.idEmpleadoMovilidadMovilidadDocTcl = idEmpleadoMovilidadMovilidadDocTcl;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_movilidad_cab", nullable = false)
	@NotNull
	public EmpleadoMovilidadCab getEmpleadoMovilidadCab() {
		return empleadoMovilidadCab;
	}

	public void setEmpleadoMovilidadCab(EmpleadoMovilidadCab empleadoMovilidadCab) {
		this.empleadoMovilidadCab = empleadoMovilidadCab;
	}

	
	@Column(name = "nota_solicitud")
	public Boolean getNotaSolicitud() {
		return this.notaSolicitud;
	}

	public void setNotaSolicitud(Boolean notaSolicitud) {
		this.notaSolicitud = notaSolicitud;
	}

	@Column(name = "resolucion_aceptacion")
	public Boolean getResolucionAceptacion() {
		return this.resolucionAceptacion;
	}

	public void setResolucionAceptacion(Boolean resolucionAceptacion) {
		this.resolucionAceptacion = resolucionAceptacion;
	}

	@Column(name = "copia_legajo")
	public Boolean getCopiaLegajo() {
		return this.copiaLegajo;
	}

	public void setCopiaLegajo(Boolean copiaLegajo) {
		this.copiaLegajo = copiaLegajo;
	}

	@Column(name = "constancia_uaf")
	public Boolean getConstanciaUaf() {
		return this.constanciaUaf;
	}

	public void setConstanciaUaf(Boolean constanciaUaf) {
		this.constanciaUaf = constanciaUaf;
	}

	@Column(name = "cuadro_presupuesto")
	public Boolean getCuadroPresupuesto() {
		return this.cuadroPresupuesto;
	}

	public void setCuadroPresupuesto(Boolean cuadroPresupuesto) {
		this.cuadroPresupuesto = cuadroPresupuesto;
	}

	@Column(name = "informe_sfp")
	public Boolean getInformeSfp() {
		return this.informeSfp;
	}

	public void setInformeSfp(Boolean informeSfp) {
		this.informeSfp = informeSfp;
	}

	@Column(name = "informe_hacienda")
	public Boolean getInformeHacienda() {
		return this.informeHacienda;
	}

	public void setInformeHacienda(Boolean informeHacienda) {
		this.informeHacienda = informeHacienda;
	}

	@Column(name = "resolucion_mh_seaf")
	public Boolean getResolucionMhSeaf() {
		return this.resolucionMhSeaf;
	}

	public void setResolucionMhSeaf(Boolean resolucionMhSeaf) {
		this.resolucionMhSeaf = resolucionMhSeaf;
	}

	@Column(name = "decreto")
	public Boolean getDecreto() {
		return this.decreto;
	}

	public void setDecreto(Boolean decreto) {
		this.decreto = decreto;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
