package py.com.excelsis.sicca.entity;

// Generated 05-nov-2012 16:44:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EmpleadoMovilidadCab generated by hbm2java
 */
@Entity
@Table(name = "empleado_movilidad_cab", schema = "movilidad")
public class EmpleadoMovilidadCab implements java.io.Serializable {

	private Long idEmpleadoMovilidadCab;
	private EmpleadoPuesto empleadoPuestoAnterior;
	private EmpleadoPuesto empleadoPuestoNuevo;
	private EmpleadoPuesto empleadoPuestoVirtual;
	private SolicitudTrasladoCab solicitudTrasladoCab;
	private Date fechaInicio;
	private Date fechaFin;
	private boolean movilidadSicca;
	private String observacion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private ConfiguracionUoDet configuracionUoDetAnterior;
	private ConfiguracionUoDet configuracionUoDetNuevo;
	

	public EmpleadoMovilidadCab() {
	}

	public EmpleadoMovilidadCab(Long idEmpleadoMovilidadCab,
			EmpleadoPuesto empleadoPuestoAnterior, EmpleadoPuesto empleadoPuestoNuevo,
			Date fechaInicio, boolean movilidadSicca, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idEmpleadoMovilidadCab = idEmpleadoMovilidadCab;
		this.empleadoPuestoAnterior = empleadoPuestoAnterior;
		this.empleadoPuestoNuevo = empleadoPuestoNuevo;
		this.fechaInicio = fechaInicio;
		this.movilidadSicca = movilidadSicca;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EmpleadoMovilidadCab(Long idEmpleadoMovilidadCab,
			EmpleadoPuesto empleadoPuestoAnterior, EmpleadoPuesto empleadoPuestoNuevo,
			EmpleadoPuesto empleadoPuestoVirtual, SolicitudTrasladoCab idSolicitudTrasladoCab,
			Date fechaInicio, Date fechaFin, boolean movilidadSicca,
			String observacion, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idEmpleadoMovilidadCab = idEmpleadoMovilidadCab;
		this.empleadoPuestoAnterior = empleadoPuestoAnterior;
		this.empleadoPuestoNuevo = empleadoPuestoNuevo;
		this.empleadoPuestoVirtual = empleadoPuestoVirtual;
		this.solicitudTrasladoCab = idSolicitudTrasladoCab;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.movilidadSicca = movilidadSicca;
		this.observacion = observacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		
	}
	
	public EmpleadoMovilidadCab(Long idEmpleadoMovilidadCab,
			EmpleadoPuesto empleadoPuestoAnterior, EmpleadoPuesto empleadoPuestoNuevo,
			EmpleadoPuesto empleadoPuestoVirtual, SolicitudTrasladoCab idSolicitudTrasladoCab,
			Date fechaInicio, Date fechaFin, boolean movilidadSicca,
			String observacion, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod, ConfiguracionUoDet configuracionUoDetAnterior,
			ConfiguracionUoDet configuracionUoDetNuevo) {
		this.idEmpleadoMovilidadCab = idEmpleadoMovilidadCab;
		this.empleadoPuestoAnterior = empleadoPuestoAnterior;
		this.empleadoPuestoNuevo = empleadoPuestoNuevo;
		this.empleadoPuestoVirtual = empleadoPuestoVirtual;
		this.solicitudTrasladoCab = idSolicitudTrasladoCab;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.movilidadSicca = movilidadSicca;
		this.observacion = observacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.configuracionUoDetAnterior = configuracionUoDetAnterior;
		this.configuracionUoDetNuevo = configuracionUoDetNuevo;
		
	}

	@Id
	@GeneratedValue(generator = "EMPLEADO_MOVILIDAD_CAB_GENERATOR")
	@SequenceGenerator(name = "EMPLEADO_MOVILIDAD_CAB_GENERATOR", sequenceName = "movilidad.empleado_movilidad_cab_id_empleado_movilidad_cab_seq")
	@Column(name = "id_empleado_movilidad_cab", unique = true, nullable = false)
	public Long getIdEmpleadoMovilidadCab() {
		return this.idEmpleadoMovilidadCab;
	}

	public void setIdEmpleadoMovilidadCab(Long idEmpleadoMovilidadCab) {
		this.idEmpleadoMovilidadCab = idEmpleadoMovilidadCab;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto_anterior")
	public EmpleadoPuesto getEmpleadoPuestoAnterior() {
		return empleadoPuestoAnterior;
	}

	public void setEmpleadoPuestoAnterior(EmpleadoPuesto empleadoPuestoAnterior) {
		this.empleadoPuestoAnterior = empleadoPuestoAnterior;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto_nuevo")
	public EmpleadoPuesto getEmpleadoPuestoNuevo() {
		return empleadoPuestoNuevo;
	}

	public void setEmpleadoPuestoNuevo(EmpleadoPuesto empleadoPuestoNuevo) {
		this.empleadoPuestoNuevo = empleadoPuestoNuevo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto_virtual")
	public EmpleadoPuesto getEmpleadoPuestoVirtual() {
		return empleadoPuestoVirtual;
	}

	public void setEmpleadoPuestoVirtual(EmpleadoPuesto empleadoPuestoVirtual) {
		this.empleadoPuestoVirtual = empleadoPuestoVirtual;
	}

	
		@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_solicitud_traslado_cab")
	public SolicitudTrasladoCab getSolicitudTrasladoCab() {
		return solicitudTrasladoCab;
	}

	public void setSolicitudTrasladoCab(SolicitudTrasladoCab solicitudTrasladoCab) {
		this.solicitudTrasladoCab = solicitudTrasladoCab;
	}

	
	

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	@NotNull
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "movilidad_sicca", nullable = false)
	public boolean isMovilidadSicca() {
		return this.movilidadSicca;
	}

	public void setMovilidadSicca(boolean movilidadSicca) {
		this.movilidadSicca = movilidadSicca;
	}

	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_det_anterior")
	public ConfiguracionUoDet getConfiguracionUoDetAnterior() {
		return configuracionUoDetAnterior;
	}

	public void setConfiguracionUoDetAnterior(
			ConfiguracionUoDet configuracionUoDetAnterior) {
		this.configuracionUoDetAnterior = configuracionUoDetAnterior;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_det_nuevo")
	public ConfiguracionUoDet getConfiguracionUoDetNuevo() {
		return configuracionUoDetNuevo;
	}

	public void setConfiguracionUoDetNuevo(
			ConfiguracionUoDet configuracionUoDetNuevo) {
		this.configuracionUoDetNuevo = configuracionUoDetNuevo;
	}

	
	
}
