package py.com.excelsis.sicca.entity;

// Generated 06/11/2012 09:12:17 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * EmpleadoPuesto651 generated by hbm2java
 */
@Entity
@Table(name = "empleado_puesto_651", schema = "general")
public class EmpleadoPuesto651 implements java.io.Serializable {

	private String oee;
	private String uo;
	private String puesto;
	private Date fechaInicio;
	private Date fechaFin;
	private String estado;
	private Long idPersona;
	private Long id;
	private String tipo;

	public EmpleadoPuesto651() {
	}

	public EmpleadoPuesto651(String oee, String uo, String puesto,
			Date fechaInicio, Date fechaFin, String estado, Long idPersona,
			Long id) {
		this.oee = oee;
		this.uo = uo;
		this.puesto = puesto;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
		this.idPersona = idPersona;
		this.id = id;
	}


	@Column(name = "id")
	@Id
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "oee", length = 100)
	@Length(max = 100)
	public String getOee() {
		return this.oee;
	}

	public void setOee(String oee) {
		this.oee = oee;
	}

	@Column(name = "uo")
	public String getUo() {
		return this.uo;
	}

	public void setUo(String uo) {
		this.uo = uo;
	}

	@Column(name = "puesto", length = 200)
	@Length(max = 200)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "estado")
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "id_persona")
	public Long getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Long idPersona) {
		this.idPersona = idPersona;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}




}
