package py.com.excelsis.sicca.entity;

// Generated 09/11/2012 10:32:07 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import py.com.excelsis.sicca.evaluacion.session.EvaluacionDesempenoList;

/**
 * EmpleadoMovilidadDet generated by hbm2java
 */
@Entity
@Table(name = "empleado_movilidad_det", schema = "movilidad")
public class EmpleadoMovilidadDet implements java.io.Serializable {

	private long idEmpleadoMovilidadDet;
	private EmpleadoMovilidadCab empleadoMovilidadCab;
	private String origen;
	private EvaluacionDesempeno evaluacionDesempeno;
	private Capacitaciones capacitacion;
	private EstudiosRealizados estudiosRealizados;
	private Documentos documento;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public EmpleadoMovilidadDet() {
	}

	public EmpleadoMovilidadDet(long idEmpleadoMovilidadDet,
			EmpleadoMovilidadCab empleadoMovilidadCab, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idEmpleadoMovilidadDet = idEmpleadoMovilidadDet;
		this.empleadoMovilidadCab = empleadoMovilidadCab;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EmpleadoMovilidadDet(long idEmpleadoMovilidadDet,
			EmpleadoMovilidadCab empleadoMovilidadCab, String origen,
			EvaluacionDesempeno idEvaluacionDesempeno, Capacitaciones idCapacitacion,
			EstudiosRealizados idEstudiosRealizados, Documentos idDocumento, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idEmpleadoMovilidadDet = idEmpleadoMovilidadDet;
		this.empleadoMovilidadCab = empleadoMovilidadCab;
		this.origen = origen;
		this.evaluacionDesempeno = idEvaluacionDesempeno;
		this.capacitacion = idCapacitacion;
		this.estudiosRealizados = idEstudiosRealizados;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_empleado_movilidad_det", unique = true, nullable = false)
	@GeneratedValue(generator = "EMPLEADO_MOVILIDAD_DET_GENERATOR")
	@SequenceGenerator(name = "EMPLEADO_MOVILIDAD_DET_GENERATOR", sequenceName = "movilidad.empleado_movilidad_det_id_empleado_movilidad_det_seq")
	
	public long getIdEmpleadoMovilidadDet() {
		return this.idEmpleadoMovilidadDet;
	}

	public void setIdEmpleadoMovilidadDet(long idEmpleadoMovilidadDet) {
		this.idEmpleadoMovilidadDet = idEmpleadoMovilidadDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_movilidad_cab", nullable = false)
	@NotNull
	public EmpleadoMovilidadCab getEmpleadoMovilidadCab() {
		return this.empleadoMovilidadCab;
	}

	public void setEmpleadoMovilidadCab(
			EmpleadoMovilidadCab empleadoMovilidadCab) {
		this.empleadoMovilidadCab = empleadoMovilidadCab;
	}

	@Column(name = "origen", length = 20)
	@Length(max = 20)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno")
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion")
	public Capacitaciones getCapacitacion() {
		return capacitacion;
	}

	public void setCapacitacion(Capacitaciones capacitacion) {
		this.capacitacion = capacitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudios_realizados")
	public EstudiosRealizados getEstudiosRealizados() {
		return estudiosRealizados;
	}

	public void setEstudiosRealizados(EstudiosRealizados estudiosRealizados) {
		this.estudiosRealizados = estudiosRealizados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
