
package py.com.excelsis.sicca.entity;

// Generated 08/11/2012 01:57:46 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EmpleadoMovilidadAnexo generated by hbm2java
 */
@Entity
@Table(name = "empleado_movilidad_anexo", schema = "movilidad")
public class EmpleadoMovilidadAnexo implements java.io.Serializable {

	private Long idEmpleadoMovilidadAnexo;
	private EmpleadoMovilidadCab empleadoMovilidadCab;
	private String anexoOee;
	private String linea;
	private String descripcion;
	private String categoria;
	private Integer objCodigo;
	private Integer monto;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public EmpleadoMovilidadAnexo() {
	}

	public EmpleadoMovilidadAnexo(Long idEmpleadoMovilidadAnexo,
			EmpleadoMovilidadCab empleadoMovilidadCab, String anexoOee,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idEmpleadoMovilidadAnexo = idEmpleadoMovilidadAnexo;
		this.empleadoMovilidadCab = empleadoMovilidadCab;
		this.anexoOee = anexoOee;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EmpleadoMovilidadAnexo(Long idEmpleadoMovilidadAnexo,
			EmpleadoMovilidadCab empleadoMovilidadCab, String anexoOee,
			String linea, String descripcion, String categoria,
			Integer objCodigo, Integer monto, boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idEmpleadoMovilidadAnexo = idEmpleadoMovilidadAnexo;
		this.empleadoMovilidadCab = empleadoMovilidadCab;
		this.anexoOee = anexoOee;
		this.linea = linea;
		this.descripcion = descripcion;
		this.categoria = categoria;
		this.objCodigo = objCodigo;
		this.monto = monto;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_empleado_movilidad_anexo", unique = true, nullable = false)
	@GeneratedValue(generator = "EMPLEADO_MOVILIDAD_ANEXO_GENERATOR")
	@SequenceGenerator(name = "EMPLEADO_MOVILIDAD_ANEXO_GENERATOR", sequenceName = "movilidad.empleado_movilidad_anexo_id_empleado_movilidad_anexo_seq")
	public Long getIdEmpleadoMovilidadAnexo() {
		return this.idEmpleadoMovilidadAnexo;
	}

	public void setIdEmpleadoMovilidadAnexo(Long idEmpleadoMovilidadAnexo) {
		this.idEmpleadoMovilidadAnexo = idEmpleadoMovilidadAnexo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_movilidad_cab", nullable = false)
	@NotNull
	public EmpleadoMovilidadCab getEmpleadoMovilidadCab() {
		return this.empleadoMovilidadCab;
	}

	public void setEmpleadoMovilidadCab(
			EmpleadoMovilidadCab empleadoMovilidadCab) {
		this.empleadoMovilidadCab = empleadoMovilidadCab;
	}

	@Column(name = "anexo_oee", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getAnexoOee() {
		return this.anexoOee;
	}

	public void setAnexoOee(String anexoOee) {
		this.anexoOee = anexoOee;
	}

	@Column(name = "linea", length = 15)
	@Length(max = 15)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Column(name = "descripcion", length = 50)
	@Length(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "categoria", length = 10)
	@Length(max = 10)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "obj_codigo")
	public Integer getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(Integer objCodigo) {
		this.objCodigo = objCodigo;
	}

	@Column(name = "monto")
	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
