package py.com.excelsis.sicca.entity;

//Generated 02/02/2012 03:58:12 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EmpleadoConceptoPago generated by hbm2java
 */
@Entity
@Table(name = "empleado_concepto_pago", schema = "general")
public class EmpleadoConceptoPago implements java.io.Serializable {

	private Long idEmpleadoConceptoPago;
	private EmpleadoPuesto empleadoPuesto;
	private String categoria;
	private Integer objCodigo;
	private Integer monto;
	private Integer anho;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private boolean activo;
	private boolean actual;
	private Date fechaInicio;
	private Date fechaFin;
	private boolean seleccionar;

	public EmpleadoConceptoPago() {
	}

	public EmpleadoConceptoPago(
			Long idEmpleadoConceptoPago, EmpleadoPuesto empleadoPuesto, String categoria,
			Integer monto, String usuAlta, Date fechaAlta) {
		this.idEmpleadoConceptoPago = idEmpleadoConceptoPago;
		this.empleadoPuesto = empleadoPuesto;
		this.categoria = categoria;
		this.monto = monto;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EmpleadoConceptoPago(
			Long idEmpleadoConceptoPago, EmpleadoPuesto empleadoPuesto, String categoria,
			Integer objCodigo, Integer monto, Integer anho, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idEmpleadoConceptoPago = idEmpleadoConceptoPago;
		this.empleadoPuesto = empleadoPuesto;
		this.categoria = categoria;
		this.objCodigo = objCodigo;
		this.monto = monto;
		this.anho = anho;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "EMPLEADO_CONCEPTO_PAGO_GENERATOR")
	@SequenceGenerator(name = "EMPLEADO_CONCEPTO_PAGO_GENERATOR", sequenceName = "general.empleado_concepto_pago_id_empleado_concepto_pago_seq")
	@Column(name = "id_empleado_concepto_pago", unique = true, nullable = false)
	public Long getIdEmpleadoConceptoPago() {
		return this.idEmpleadoConceptoPago;
	}

	public void setIdEmpleadoConceptoPago(Long idEmpleadoConceptoPago) {
		this.idEmpleadoConceptoPago = idEmpleadoConceptoPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto", nullable = false)
	@NotNull
	public EmpleadoPuesto getEmpleadoPuesto() {
		return this.empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

	@Column(name = "categoria", length = 10)
	@Length(max = 10)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "obj_codigo")
	public Integer getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(Integer objCodigo) {
		this.objCodigo = objCodigo;
	}

	@Column(name = "monto", nullable = false)
	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

	@Column(name = "anho")
	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}
	
	@Column(name = "actual", nullable = false)
	public boolean isActual() {
		return this.actual;
	}

	public void setActual(boolean actual) {
		this.actual = actual;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio",length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Transient
	public boolean isSeleccionar() {
		return seleccionar;
	}

	public void setSeleccionar(boolean seleccionar) {
		this.seleccionar = seleccionar;
	}
	
	

}
