package py.com.excelsis.sicca.entity;

// Generated 13/10/2011 09:48:59 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EmpresaPersona generated by hbm2java
 */
@Entity
@Table(name = "empresa_persona", schema = "seleccion")
public class EmpresaPersona implements java.io.Serializable {

	private Long idSelEmpresaPersona;
	private EmprTercerizada emprTercerizada;
	private Persona persona;
	private String cargo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Integer posicion;

	public EmpresaPersona() {
	}

	public EmpresaPersona(Long idSelEmpresaPersona,
			EmprTercerizada emprTercerizada, String cargo,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idSelEmpresaPersona = idSelEmpresaPersona;
		this.emprTercerizada = emprTercerizada;
		this.cargo = cargo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EmpresaPersona(Long idSelEmpresaPersona,
			EmprTercerizada emprTercerizada, String cargo,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idSelEmpresaPersona = idSelEmpresaPersona;
		this.emprTercerizada = emprTercerizada;
		this.cargo = cargo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_sel_empresa_persona", unique = true, nullable = false)
	@GeneratedValue(generator="EMPRESA_PERSONA_GENERATOR")
	@SequenceGenerator(name="EMPRESA_PERSONA_GENERATOR",sequenceName="seleccion.empresa_persona_id_sel_empresa_persona_seq")
	public Long getIdSelEmpresaPersona() {
		return this.idSelEmpresaPersona;
	}

	public void setIdSelEmpresaPersona(Long idSelEmpresaPersona) {
		this.idSelEmpresaPersona = idSelEmpresaPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa_tercerizada", nullable = false)
	@NotNull
	public EmprTercerizada getEmprTercerizada() {
		return this.emprTercerizada;
	}

	public void setEmprTercerizada(EmprTercerizada emprTercerizada) {
		this.emprTercerizada = emprTercerizada;
	}

	@Column(name = "cargo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	@NotNull
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Transient
	public Integer getPosicion() {
		return posicion;
	}

	public void setPosicion(Integer posicion) {
		this.posicion = posicion;
	}
}
