package py.com.excelsis.sicca.entity;

// Generated 16/09/2011 02:34:48 AM by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name = "entidad", schema = "planificacion")
public class Entidad implements java.io.Serializable {

	private Long idEntidad;
	private SinEntidad sinEntidad;
	private Oficina oficina;
	private Integer anho;
	private Long codSicca;
	private Integer mes;
	private String descripcion;
	private BigDecimal aniAniopre;
	private BigDecimal nenCodigo;
	private BigDecimal entCodigo;
	private ConfiguracionUoCab configuracionUoCab;
	private Set<ConfiguracionUoCab> configuracionUoCabs = new HashSet<ConfiguracionUoCab>(
			0);

	public Entidad() {
	}

	public Entidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	public Entidad(Long idEntidad, SinEntidad sinEntidad, Oficina oficina,
			Integer anho, Long codSicca, Integer mes,
			Set<ConfiguracionUoCab> configuracionUoCabs) {
		this.idEntidad = idEntidad;
		this.sinEntidad = sinEntidad;
		this.oficina = oficina;
		this.anho = anho;
		this.codSicca = codSicca;
		this.mes = mes;
		this.configuracionUoCabs = configuracionUoCabs;
	}

	@Id
	@Column(name = "id_entidad", unique = true, nullable = false)
	@GeneratedValue(generator="ENTIDAD_GENERATOR")
	@SequenceGenerator(name="ENTIDAD_GENERATOR",sequenceName="planificacion.entidad_id_entidad_seq")
	public Long getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sin_entidad")
	public SinEntidad getSinEntidad() {
		return this.sinEntidad;
	}

	public void setSinEntidad(SinEntidad sinEntidad) {
		this.sinEntidad = sinEntidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oficina")
	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	@Column(name = "anho")
	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@Column(name = "cod_sicca")
	public Long getCodSicca() {
		return this.codSicca;
	}

	public void setCodSicca(Long codSicca) {
		this.codSicca = codSicca;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<ConfiguracionUoCab> getConfiguracionUoCabs() {
		return this.configuracionUoCabs;
	}

	public void setConfiguracionUoCabs(
			Set<ConfiguracionUoCab> configuracionUoCabs) {
		this.configuracionUoCabs = configuracionUoCabs;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ani_aniopre")
	public BigDecimal getAniAniopre() {
		return aniAniopre;
	}

	public void setAniAniopre(BigDecimal aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "nen_codigo")
	public BigDecimal getNenCodigo() {
		return nenCodigo;
	}

	public void setNenCodigo(BigDecimal nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo")
	public BigDecimal getEntCodigo() {
		return entCodigo;
	}

	public void setEntCodigo(BigDecimal entCodigo) {
		this.entCodigo = entCodigo;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}
	
	

}
