package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * EscalaCondSegur generated by Generality
 */
@Entity
@Table(name = "escala_cond_segur", schema = "planificacion")
public class EscalaCondSegur implements java.io.Serializable {
	private Long idEscalaCondSegur;
	
	private String descripcion;
	private Integer desde;
	private Integer hasta;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public EscalaCondSegur() {
	}

	public EscalaCondSegur(Long idEscalaCondSegur) {
		this.idEscalaCondSegur = idEscalaCondSegur;
	}

	@Id
	@GeneratedValue(generator="ESCALA_COND_SEGUR_GENERATOR")
	@SequenceGenerator(name="ESCALA_COND_SEGUR_GENERATOR",sequenceName="planificacion.escala_cond_segur_id_escala_cond_segur_seq")

	@Column(name = "id_escala_cond_segur")
	public Long getIdEscalaCondSegur() {
		return this.idEscalaCondSegur;
	}

	public void setIdEscalaCondSegur(Long idEscalaCondSegur) {
		this.idEscalaCondSegur = idEscalaCondSegur;
	}
	

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	

	@Column(name = "desde")
	public Integer getDesde() {
		return this.desde;
	}

	public void setDesde(Integer desde) {
		this.desde = desde;
	}
	

	@Column(name = "hasta")
	public Integer getHasta() {
		return this.hasta;
	}

	public void setHasta(Integer hasta) {
		this.hasta = hasta;
	}
	

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEscalaCondSegur == null) ? 0 : idEscalaCondSegur.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EscalaCondSegur other = (EscalaCondSegur) obj;
		if (idEscalaCondSegur == null) {
			if (other.idEscalaCondSegur != null)
				return false;
		} else if (!idEscalaCondSegur.equals(other.idEscalaCondSegur))
			return false;
		return true;
	}
}
