package py.com.excelsis.sicca.entity;

// Generated 28/09/2011 11:21:46 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstadoDet generated by hbm2java
 */
@Entity
@Table(name = "estado_det", schema = "planificacion")
public class EstadoDet implements java.io.Serializable {

	private Long idEstadoDet;
	private EstadoCab estadoCab;
	private String descripcion;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean activo;

	public EstadoDet() {
	}

	public EstadoDet(Long idEstadoDet, EstadoCab estadoCab, String descripcion,
			String usuAlta, Date fechaAlta, Boolean activo) {
		this.idEstadoDet = idEstadoDet;
		this.estadoCab = estadoCab;
		this.descripcion = descripcion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
	}

	public EstadoDet(Long idEstadoDet, EstadoCab estadoCab, String descripcion,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Boolean activo) {
		this.idEstadoDet = idEstadoDet;
		this.estadoCab = estadoCab;
		this.descripcion = descripcion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.activo = activo;
	}

	@Id
	@GeneratedValue(generator="ESTADO_DET_GENERATOR")
	@SequenceGenerator(name="ESTADO_DET_GENERATOR",sequenceName="planificacion.estado_det_id_estado_det_seq")
	@Column(name = "id_estado_det", unique = true, nullable = false)
	public Long getIdEstadoDet() {
		return this.idEstadoDet;
	}

	public void setIdEstadoDet(Long idEstadoDet) {
		this.idEstadoDet = idEstadoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_cab", nullable = false)
	@NotNull
	public EstadoCab getEstadoCab() {
		return this.estadoCab;
	}

	public void setEstadoCab(EstadoCab estadoCab) {
		this.estadoCab = estadoCab;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

}
