package py.com.excelsis.sicca.entity;

// Generated 24/10/2011 03:08:10 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.swing.text.StyledEditorKit.BoldAction;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstudiosRealizados generated by hbm2java
 */
@Entity
@Table(name = "estudios_realizados", schema = "legajo")
public class EstudiosRealizadosLegajo implements java.io.Serializable {

	private Long idEstudiosRealizados;
	private InstitucionEducativa institucionEducativa;
	private TituloAcademico tituloAcademico;
	private Persona persona;
	private String otroTituloObt;
	private Date fechaInicio;
	private Date fechaFin;
	private Boolean finalizo;
	private Integer duracionHoras;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Especialidades especialidades;
	private boolean activo;
	private String otraInstit;
	private Pais pais;
	private Documentos documentos;
	private PersonaPostulante personaPostulante;
	private String tipoDuracion;
	private String tipo;
	private String usuAltaOee;
	private Date fechaAltaOee;
	private String usuModOee;
	private Date fechaModOee;
	private String otroNivel;
	private String estadoActual;
	
	public EstudiosRealizadosLegajo() {
	}

	public EstudiosRealizadosLegajo(Long idEstudiosRealizados,
			InstitucionEducativa institucionEducativa, Persona persona,
			Date fechaInicio, Boolean finalizo, Integer duracionHoras,
			String usuAlta, Date fechaAlta) {
		this.idEstudiosRealizados = idEstudiosRealizados;
		this.institucionEducativa = institucionEducativa;
		this.persona = persona;
		this.fechaInicio = fechaInicio;
		this.finalizo = finalizo;
		this.duracionHoras = duracionHoras;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EstudiosRealizadosLegajo(Long idEstudiosRealizados,
			InstitucionEducativa institucionEducativa,
			TituloAcademico tituloAcademico, Persona persona,
			String otroTituloObt, Date fechaInicio, Date fechaFin,
			Boolean finalizo, Integer duracionHoras, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idEstudiosRealizados = idEstudiosRealizados;
		this.institucionEducativa = institucionEducativa;
		this.tituloAcademico = tituloAcademico;
		this.persona = persona;
		this.otroTituloObt = otroTituloObt;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.finalizo = finalizo;
		this.duracionHoras = duracionHoras;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_estudios_realizados_legajo", unique = true, nullable = false)
	@GeneratedValue(generator="ESTUDIOS_REALIZADOS_LEGAJO_GENERATOR")
	@SequenceGenerator(name="ESTUDIOS_REALIZADOS_LEGAJO_GENERATOR",sequenceName="legajo.estudios_realizados_legajo_id_formacion_acad_seq")
	public Long getIdEstudiosRealizados() {
		return this.idEstudiosRealizados;
	}

	public void setIdEstudiosRealizados(Long idEstudiosRealizados) {
		this.idEstudiosRealizados = idEstudiosRealizados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inst_educativa", nullable = false)
	@NotNull
	public InstitucionEducativa getInstitucionEducativa() {
		return this.institucionEducativa;
	}

	public void setInstitucionEducativa(
			InstitucionEducativa institucionEducativa) {
		this.institucionEducativa = institucionEducativa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_titulo_academico")
	public TituloAcademico getTituloAcademico() {
		return this.tituloAcademico;
	}

	public void setTituloAcademico(TituloAcademico tituloAcademico) {
		this.tituloAcademico = tituloAcademico;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "otro_titulo_obt", length = 100)
	@Length(max = 100)
	public String getOtroTituloObt() {
		return this.otroTituloObt;
	}

	public void setOtroTituloObt(String otroTituloObt) {
		this.otroTituloObt = otroTituloObt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	
	
	@Column(name = "finalizo", nullable = false)
	public Boolean getFinalizo() {
		return finalizo;
	}

	public void setFinalizo(Boolean finalizo) {
		this.finalizo = finalizo;
	}

	@Column(name = "duracion_horas")
	public Integer getDuracionHoras() {
		return this.duracionHoras;
	}

	public void setDuracionHoras(Integer duracionHoras) {
		this.duracionHoras = duracionHoras;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_especialidad")
	
	public Especialidades getEspecialidades() {
		return especialidades;
	}

	public void setEspecialidades(Especialidades especialidades) {
		this.especialidades = especialidades;
	}
	
	
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}


	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "otra_instit", length = 150)
	@Length(max = 150)
	public String getOtraInstit() {
		return otraInstit;
	}

	public void setOtraInstit(String otraInstit) {
		this.otraInstit = otraInstit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais")
	public Pais getPais() {
		return pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_postulante")
	public PersonaPostulante getPersonaPostulante() {
		return personaPostulante;
	}

	public void setPersonaPostulante(PersonaPostulante personaPostulante) {
		this.personaPostulante = personaPostulante;
	}

	
	@Column(name = "tipo_duracion")
	public String getTipoDuracion() {
		return tipoDuracion;
	}

	public void setTipoDuracion(String tipoDuracion) {
		this.tipoDuracion = tipoDuracion;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "usu_alta_oee")
	public String getUsuAltaOee() {
		return usuAltaOee;
	}

	public void setUsuAltaOee(String usuAltaOee) {
		this.usuAltaOee = usuAltaOee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta_oee", length = 29)
	public Date getFechaAltaOee() {
		return fechaAltaOee;
	}

	public void setFechaAltaOee(Date fechaAltaOee) {
		this.fechaAltaOee = fechaAltaOee;
	}

	@Column(name = "usu_mod_oee")
	public String getUsuModOee() {
		return usuModOee;
	}

	public void setUsuModOee(String usuModOee) {
		this.usuModOee = usuModOee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod_oee", length = 29)
	public Date getFechaModOee() {
		return fechaModOee;
	}

	public void setFechaModOee(Date fechaModOee) {
		this.fechaModOee = fechaModOee;
	}
	@Column(name = "otro_nivel", length = 100)
	public String getOtroNivel() {
		return otroNivel;
	}

	public void setOtroNivel(String otroNivel) {
		this.otroNivel = otroNivel;
	}
	
	@Column(name = "estado_actual", length = 20)
	public String getEstadoActual() {
		return estadoActual;
	}

	public void setEstadoActual(String estadoActual) {
		this.estadoActual = estadoActual;
	}
	
	

}
