package py.com.excelsis.sicca.entity;

// Generated 17-nov-2011 17:00:10 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvalDocumentalDet generated by hbm2java
 */
@Entity
@Table(name = "eval_documental_det", schema = "seleccion")
public class EvalDocumentalDet implements java.io.Serializable {

	private Long idEvalDocumentalDet;
	private MatrizDocConfigDet matrizDocConfigDet;
	private EvalDocumentalCab evalDocumentalCab;
	private boolean aprobadoConDocumentos;
	private boolean aprobadoPorComision;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public EvalDocumentalDet() {
	}

	public EvalDocumentalDet(Long idEvalDocumentalDet,
			MatrizDocConfigDet matrizDocConfigDet,
			EvalDocumentalCab evalDocumentalCab, boolean aprobadoConDocumentos,
			boolean aprobadoPorComision, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idEvalDocumentalDet = idEvalDocumentalDet;
		this.matrizDocConfigDet = matrizDocConfigDet;
		this.evalDocumentalCab = evalDocumentalCab;
		this.aprobadoConDocumentos = aprobadoConDocumentos;
		this.aprobadoPorComision = aprobadoPorComision;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvalDocumentalDet(Long idEvalDocumentalDet,
			MatrizDocConfigDet matrizDocConfigDet,
			EvalDocumentalCab evalDocumentalCab, boolean aprobadoConDocumentos,
			boolean aprobadoPorComision, boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idEvalDocumentalDet = idEvalDocumentalDet;
		this.matrizDocConfigDet = matrizDocConfigDet;
		this.evalDocumentalCab = evalDocumentalCab;
		this.aprobadoConDocumentos = aprobadoConDocumentos;
		this.aprobadoPorComision = aprobadoPorComision;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="EVAL_DOCUMENTAL_DET_GENERATOR")
	@SequenceGenerator(name="EVAL_DOCUMENTAL_DET_GENERATOR",sequenceName="seleccion.eval_documental_det_id_eval_documental_det_seq")
	@Column(name = "id_eval_documental_det", unique = true, nullable = false)
	public Long getIdEvalDocumentalDet() {
		return this.idEvalDocumentalDet;
	}

	public void setIdEvalDocumentalDet(Long idEvalDocumentalDet) {
		this.idEvalDocumentalDet = idEvalDocumentalDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_matriz_doc_config_det", nullable = false)
	@NotNull
	public MatrizDocConfigDet getMatrizDocConfigDet() {
		return this.matrizDocConfigDet;
	}

	public void setMatrizDocConfigDet(MatrizDocConfigDet matrizDocConfigDet) {
		this.matrizDocConfigDet = matrizDocConfigDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_documental_cab", nullable = false)
	@NotNull
	public EvalDocumentalCab getEvalDocumentalCab() {
		return this.evalDocumentalCab;
	}

	public void setEvalDocumentalCab(EvalDocumentalCab evalDocumentalCab) {
		this.evalDocumentalCab = evalDocumentalCab;
	}

	@Column(name = "aprobado_con_documentos")
	public boolean isAprobadoConDocumentos() {
		return this.aprobadoConDocumentos;
	}

	public void setAprobadoConDocumentos(boolean aprobadoConDocumentos) {
		this.aprobadoConDocumentos = aprobadoConDocumentos;
	}

	@Column(name = "aprobado_por_comision")
	public boolean isAprobadoPorComision() {
		return this.aprobadoPorComision;
	}

	public void setAprobadoPorComision(boolean aprobadoPorComision) {
		this.aprobadoPorComision = aprobadoPorComision;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
