package py.com.excelsis.sicca.entity;

// Generated 09/12/2011 10:17:53 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * EvalAbiertas generated by hbm2java
 */
@Entity
@Table(name = "eval_abiertas", schema = "seleccion")
public class EvalAbiertas implements java.io.Serializable {

	private Long idEvalAbiertas;
	private Postulacion postulacion;
	private EvalDocumentalCab evalDocumentalCab;
	private EvalReferencial evalReferencial;
	private EvalReferencialTipoeval evalReferencialTipoeval;
	private DatosEspecificos datosEspecificos;
	private Long concursoPuestoAgr;

	public EvalAbiertas() {
	}

	public EvalAbiertas(
			Postulacion postulacion, EvalDocumentalCab evalDocumentalCab,
			EvalReferencial evalReferencial, EvalReferencialTipoeval evalReferencialTipoeval,
			DatosEspecificos datosEspecificos) {
		super();
		this.postulacion = postulacion;
		this.evalDocumentalCab = evalDocumentalCab;
		this.evalReferencial = evalReferencial;
		this.evalReferencialTipoeval = evalReferencialTipoeval;
		this.datosEspecificos = datosEspecificos;
	}

	@Id
	@Column(name = "id_eval_abiertas", unique = true, nullable = false)
	public Long getIdEvalAbiertas() {
		return idEvalAbiertas;
	}

	public void setIdEvalAbiertas(Long idEvalAbiertas) {
		this.idEvalAbiertas = idEvalAbiertas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_documental_cab", nullable = false)
	@NotNull
	public EvalDocumentalCab getEvalDocumentalCab() {
		return this.evalDocumentalCab;
	}

	public void setEvalDocumentalCab(EvalDocumentalCab evalDocumentalCab) {
		this.evalDocumentalCab = evalDocumentalCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_referencial", nullable = true)
	public EvalReferencial getEvalReferencial() {
		return evalReferencial;
	}

	public void setEvalReferencial(EvalReferencial evalReferencial) {
		this.evalReferencial = evalReferencial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_referencial_tipoeval", nullable = true)
	public EvalReferencialTipoeval getEvalReferencialTipoeval() {
		return this.evalReferencialTipoeval;
	}

	public void setEvalReferencialTipoeval(EvalReferencialTipoeval evalReferencialTipoeval) {
		this.evalReferencialTipoeval = evalReferencialTipoeval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos", nullable = true)
	public DatosEspecificos getDatosEspecificos() {
		return datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}
	
	@Column(name = "id_concurso_puesto_agr")
	public Long getConcursoPuestoAgr() {
		return concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(Long concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

}
