package py.com.excelsis.sicca.entity;

// Generated 02/01/2012 10:19:22 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvalReferencialConvocatoria generated by hbm2java
 */
@Entity
@Table(name = "eval_referencial_convocatoria", schema = "seleccion")
public class EvalReferencialConvocatoria implements java.io.Serializable {

	private Long idEvalReferencialConvocatoria;
	private EvalReferencialTipoeval evalReferencialTipoeval;
	private Date fechaConvocatoria;
	private Date horaDesde;
	private Date horaHasta;
	private String lugar;
	private Long idCiudad;
	private String direccion;
	private String observacion;
	private String motivo;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaPublicacion;
	
	private ConcursoPuestoAgr concursoPuestoAgr;

	public EvalReferencialConvocatoria() {
	}

	public EvalReferencialConvocatoria(
			Long idEvalReferencialConvocatoria, EvalReferencialTipoeval evalReferencialTipoeval,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idEvalReferencialConvocatoria = idEvalReferencialConvocatoria;
		this.evalReferencialTipoeval = evalReferencialTipoeval;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvalReferencialConvocatoria(
			Long idEvalReferencialConvocatoria, EvalReferencialTipoeval evalReferencialTipoeval,
			Date fechaConvocatoria, Date horaDesde, Date horaHasta, String lugar, Long idCiudad,
			String direccion, String observacion, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idEvalReferencialConvocatoria = idEvalReferencialConvocatoria;
		this.evalReferencialTipoeval = evalReferencialTipoeval;
		this.fechaConvocatoria = fechaConvocatoria;
		this.horaDesde = horaDesde;
		this.horaHasta = horaHasta;
		this.lugar = lugar;
		this.idCiudad = idCiudad;
		this.direccion = direccion;
		this.observacion = observacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="EVAL_REFERENCIAL_CONVOCATORIA_GENERATOR")
	@SequenceGenerator(name="EVAL_REFERENCIAL_CONVOCATORIA_GENERATOR",sequenceName="seleccion.eval_referencial_convocatoria_id_eval_referencial_convoc264")
	@Column(name = "id_eval_referencial_convocatoria", unique = true, nullable = false)
	public Long getIdEvalReferencialConvocatoria() {
		return this.idEvalReferencialConvocatoria;
	}

	public void setIdEvalReferencialConvocatoria(Long idEvalReferencialConvocatoria) {
		this.idEvalReferencialConvocatoria = idEvalReferencialConvocatoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_referencial_tipoeval")
	public EvalReferencialTipoeval getEvalReferencialTipoeval() {
		return this.evalReferencialTipoeval;
	}

	public void setEvalReferencialTipoeval(EvalReferencialTipoeval evalReferencialTipoeval) {
		this.evalReferencialTipoeval = evalReferencialTipoeval;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_convocatoria", length = 29)
	public Date getFechaConvocatoria() {
		return this.fechaConvocatoria;
	}

	public void setFechaConvocatoria(Date fechaConvocatoria) {
		this.fechaConvocatoria = fechaConvocatoria;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_desde", length = 15)
	public Date getHoraDesde() {
		return this.horaDesde;
	}

	public void setHoraDesde(Date horaDesde) {
		this.horaDesde = horaDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_hasta", length = 15)
	public Date getHoraHasta() {
		return this.horaHasta;
	}

	public void setHoraHasta(Date horaHasta) {
		this.horaHasta = horaHasta;
	}

	@Column(name = "lugar", length = 150)
	@Length(max = 150)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "id_ciudad")
	public Long getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(Long idCiudad) {
		this.idCiudad = idCiudad;
	}

	@Column(name = "direccion", length = 150)
	@Length(max = 150)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	
	@Column(name = "motivo", length = 150)
	@Length(max = 150)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_publicacion", length = 29)
	public Date getFechaPublicacion() {
		return fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}


}
