package py.com.excelsis.sicca.entity;

// Generated 06-dic-2011 13:43:57 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvalReferencialPostulante generated by hbm2java
 */
@Entity
@Table(name = "eval_referencial_postulante", schema = "seleccion")
public class EvalReferencialPostulante implements java.io.Serializable, Comparable {

	private Long idEvalReferencialPostulante;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Postulacion postulacion;
	private Float puntajeRealizado;
	private Date fechaEvaluacion;
	private boolean activo;
	private Boolean excluido;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean listaCorta;
	private Boolean seleccionado;
	private Boolean listaCortaReplica;
	private Boolean seleccionadoReplica;
	private Boolean selAdjudicado;
	private String obsElegible;
	private String obsEmpate;
	private Integer orden;
	private Boolean presente;
	private Boolean var;
	private Excepcion excepcion;
	private Boolean cambiado  ;
	private Boolean elegible ;
	private String obsExclusion;
	private Boolean incluido;
	// transients
	private Boolean excluir = false;
	private Boolean pasaAelegible = false;
	private Boolean cambiar = false;


	public EvalReferencialPostulante() {
	}

	public EvalReferencialPostulante(
			Long idEvalReferencialPostulante, ConcursoPuestoAgr concursoPuestoAgr,
			Postulacion postulacion, Float puntajeRealizado, Date fechaEvaluacion, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idEvalReferencialPostulante = idEvalReferencialPostulante;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.postulacion = postulacion;
		this.puntajeRealizado = puntajeRealizado;
		this.fechaEvaluacion = fechaEvaluacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvalReferencialPostulante(
			Long idEvalReferencialPostulante, ConcursoPuestoAgr concursoPuestoAgr,
			Postulacion postulacion, Float puntajeRealizado, Date fechaEvaluacion, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod, Boolean listaCorta,
			Boolean seleccionado, Boolean selAdjudicado, String obsElegible, String obsEmpate,
			Integer orden, Boolean presente) {
		this.idEvalReferencialPostulante = idEvalReferencialPostulante;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.postulacion = postulacion;
		this.puntajeRealizado = puntajeRealizado;
		this.fechaEvaluacion = fechaEvaluacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.listaCorta = listaCorta;
		this.seleccionado = seleccionado;
		this.selAdjudicado = selAdjudicado;
		this.obsElegible = obsElegible;
		this.obsEmpate = obsEmpate;
		this.orden = orden;
		this.presente = presente;
	}

	@Id
	@GeneratedValue(generator = "EVAL_REFERENCIAL_POSTULANTE_GENERATOR")
	@SequenceGenerator(name = "EVAL_REFERENCIAL_POSTULANTE_GENERATOR", sequenceName = "seleccion.eval_referencial_post_id_eval_ref_postulan_seq")
	
	@Column(name = "id_eval_referencial_postulante", unique = true, nullable = false)
	public Long getIdEvalReferencialPostulante() {
		return this.idEvalReferencialPostulante;
	}

	public void setIdEvalReferencialPostulante(Long idEvalReferencialPostulante) {
		this.idEvalReferencialPostulante = idEvalReferencialPostulante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr", nullable = false)
	@NotNull
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@Column(name = "puntaje_realizado", nullable = false, precision = 8, scale = 8)
	public Float getPuntajeRealizado() {
		return this.puntajeRealizado;
	}

	public void setPuntajeRealizado(Float puntajeRealizado) {
		this.puntajeRealizado = puntajeRealizado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_evaluacion", nullable = false, length = 29)
	@NotNull
	public Date getFechaEvaluacion() {
		return this.fechaEvaluacion;
	}

	public void setFechaEvaluacion(Date fechaEvaluacion) {
		this.fechaEvaluacion = fechaEvaluacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "lista_corta")
	public Boolean getListaCorta() {
		return this.listaCorta;
	}

	public void setListaCorta(Boolean listaCorta) {
		this.listaCorta = listaCorta;
	}
	
	@Column(name = "lista_corta_replica")
	public Boolean getListaCortaReplica() {
		return this.listaCortaReplica;
	}

	public void setListaCortaReplica(Boolean listaCortaReplica) {
		this.listaCortaReplica = listaCortaReplica;
	}

	@Column(name = "seleccionado")
	public Boolean getSeleccionado() {
		return this.seleccionado;
	}

	public void setSeleccionado(Boolean seleccionado) {
		this.seleccionado = seleccionado;
	}
	
	
	@Column(name = "seleccionado_replica")
	public Boolean getSeleccionadoReplica() {
		return this.seleccionadoReplica;
	}

	public void setSeleccionadoReplica(Boolean seleccionadoReplica) {
		this.seleccionadoReplica = seleccionadoReplica;
	}

	@Column(name = "sel_adjudicado")
	public Boolean getSelAdjudicado() {
		return this.selAdjudicado;
	}

	public void setSelAdjudicado(Boolean selAdjudicado) {
		this.selAdjudicado = selAdjudicado;
	}

	@Column(name = "obs_elegible", length = 250)
	@Length(max = 250)
	public String getObsElegible() {
		return this.obsElegible;
	}

	public void setObsElegible(String obsElegible) {
		this.obsElegible = obsElegible;
	}

	@Column(name = "obs_empate", length = 250)
	@Length(max = 250)
	public String getObsEmpate() {
		return this.obsEmpate;
	}

	public void setObsEmpate(String obsEmpate) {
		this.obsEmpate = obsEmpate;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "presente")
	public Boolean getPresente() {
		return this.presente;
	}

	public void setPresente(Boolean presente) {
		this.presente = presente;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;

		EvalReferencialPostulante e = (EvalReferencialPostulante) obj;
		return this.getIdEvalReferencialPostulante().longValue() == e
				.getIdEvalReferencialPostulante().longValue();
	}

	public int compareTo(Object o) {
		EvalReferencialPostulante e = (EvalReferencialPostulante) o;

		return this.puntajeRealizado.compareTo(e.getPuntajeRealizado());

	}

	@Column(name = "var")
	public Boolean getVar() {
		return var;
	}

	public void setVar(Boolean var) {
		this.var = var;
	}

	@Column(name = "excluido")
	public Boolean getExcluido() {
		return excluido;
	}

	public void setExcluido(Boolean excluido) {
		this.excluido = excluido;
	}

	// Transient
	@Transient
	public Boolean getExcluir() {
		return excluir;
	}

	public void setExcluir(Boolean excluir) {
		this.excluir = excluir;
	}

	@Transient
	public Boolean getPasaAelegible() {
		return pasaAelegible;
	}

	public void setPasaAelegible(Boolean pasaAelegible) {
		this.pasaAelegible = pasaAelegible;
	}

	@Transient
	public Boolean getCambiar() {
		return cambiar;
	}

	public void setCambiar(Boolean cambiar) {
		this.cambiar = cambiar;
	}



	@Column(name = "a_elegible")
	public Boolean getElegible() {
		return elegible;
	}

	public void setElegible(Boolean elegible) {
		this.elegible = elegible;
	}

	@Column(name = "cambiado")
	public Boolean getCambiado() {
		return cambiado;
	}

	public void setCambiado(Boolean cambiado) {
		this.cambiado = cambiado;
	}

	@Column(name = "obs_exclusion", length = 250)
	@Length(max = 250)
	public String getObsExclusion() {
		return obsExclusion;
	}

	public void setObsExclusion(String obsExclusion) {
		this.obsExclusion = obsExclusion;
	}

	@Column(name = "incluido")
	public Boolean getIncluido() {
		return incluido;
	}

	public void setIncluido(Boolean incluido) {
		this.incluido = incluido;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_excepcion" )
	 
	public Excepcion getExcepcion() {
		return this.excepcion;
	}

	public void setExcepcion(Excepcion excepcion) {
		this.excepcion = excepcion;
	}
}
