package py.com.excelsis.sicca.entity;

// Generated 09/12/2011 10:17:53 AM by Hibernate Tools 3.4.0.Beta1

import java.text.DecimalFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvalReferencial generated by hbm2java
 */
@Entity
@Table(name = "eval_referencial", schema = "seleccion")
public class EvalReferencial implements java.io.Serializable {

	private Long idEvalReferencial;
	private EvalReferencialTipoeval evalReferencialTipoeval;
	private Postulacion postulacion;
	private int nroOrden;
	private String observacion;
	private boolean presente;
	private Boolean aprobado;
	private float puntajeRealizado;
	private float porcRealizado;
	private Date fechaEvaluacion;
	private boolean activo;
	private Boolean siendoEvaluado;
	
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<EvalReferencialCab> evalReferencialCabs = new HashSet<EvalReferencialCab>(0);
	private Set<EvalReferencialComis> evalReferencialComises = new HashSet<EvalReferencialComis>(0);

	public EvalReferencial() {
	}

	public EvalReferencial(
			Long idEvalReferencial, EvalReferencialTipoeval evalReferencialTipoeval,
			Postulacion postulacion, int nroOrden, boolean presente, float puntajeRealizado,
			float porcRealizado, Date fechaEvaluacion, boolean activo, String usuAlta,
			Date fechaAlta, boolean siendoEvaluado) {
		this.idEvalReferencial = idEvalReferencial;
		this.evalReferencialTipoeval = evalReferencialTipoeval;
		this.postulacion = postulacion;
		this.nroOrden = nroOrden;
		this.presente = presente;
		this.puntajeRealizado = puntajeRealizado;
		this.porcRealizado = porcRealizado;
		this.fechaEvaluacion = fechaEvaluacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.siendoEvaluado = siendoEvaluado;
	}

	public EvalReferencial(
			Long idEvalReferencial, EvalReferencialTipoeval evalReferencialTipoeval,
			Postulacion postulacion, int nroOrden, String observacion, boolean presente,
			Boolean aprobado, float puntajeRealizado, float porcRealizado, Date fechaEvaluacion,
			boolean activo, String usuAlta, Boolean siendoEvaluado, Date fechaAlta, String usuMod, Date fechaMod,
			Set<EvalReferencialCab> evalReferencialCabs,
			Set<EvalReferencialComis> evalReferencialComises) {
		this.idEvalReferencial = idEvalReferencial;
		this.evalReferencialTipoeval = evalReferencialTipoeval;
		this.postulacion = postulacion;
		this.nroOrden = nroOrden;
		this.observacion = observacion;
		this.presente = presente;
		this.aprobado = aprobado;
		this.puntajeRealizado = puntajeRealizado;
		this.porcRealizado = porcRealizado;
		this.fechaEvaluacion = fechaEvaluacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.siendoEvaluado = siendoEvaluado;
		this.evalReferencialCabs = evalReferencialCabs;
		this.evalReferencialComises = evalReferencialComises;
	}

	@Id
	@Column(name = "id_eval_referencial", unique = true, nullable = false)
	@GeneratedValue(generator = "EVAL_REFERENCIAL_GENERATOR")
	@SequenceGenerator(name = "EVAL_REFERENCIAL_GENERATOR", sequenceName = "seleccion.eval_referencial_id_eval_referencial_seq")
	public Long getIdEvalReferencial() {
		return this.idEvalReferencial;
	}

	public void setIdEvalReferencial(Long idEvalReferencial) {
		this.idEvalReferencial = idEvalReferencial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_referencial_tipoeval", nullable = false)
	@NotNull
	public EvalReferencialTipoeval getEvalReferencialTipoeval() {
		return this.evalReferencialTipoeval;
	}

	public void setEvalReferencialTipoeval(EvalReferencialTipoeval evalReferencialTipoeval) {
		this.evalReferencialTipoeval = evalReferencialTipoeval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@Column(name = "nro_orden", nullable = false)
	public int getNroOrden() {
		return this.nroOrden;
	}

	public void setNroOrden(int nroOrden) {
		this.nroOrden = nroOrden;
	}

	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "presente", nullable = false)
	public boolean isPresente() {
		return this.presente;
	}

	public void setPresente(boolean presente) {
		this.presente = presente;
	}

	@Column(name = "aprobado")
	public Boolean getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(Boolean aprobado) {
		this.aprobado = aprobado;
	}

	@Column(name = "puntaje_realizado", nullable = false, precision = 8, scale = 8)
	public float getPuntajeRealizado() {
		return this.puntajeRealizado;
	}
	
	@Transient
	public String getPuntajeRealizadoFormateado() {
		DecimalFormat myFormatter = new DecimalFormat("##.##");
		return myFormatter.format(new Float(this.puntajeRealizado));
	}

	public void setPuntajeRealizado(float puntajeRealizado) {
		this.puntajeRealizado = puntajeRealizado;
	}

	@Column(name = "porc_realizado", nullable = false, precision = 8, scale = 8)
	public float getPorcRealizado() {
		return this.porcRealizado;
	}

	@Transient
	public String getPorcRealizadoFormateado() {
		DecimalFormat myFormatter = new DecimalFormat("##.##");
		return myFormatter.format(new Float(this.porcRealizado));
	}

	public void setPorcRealizado(float porcRealizado) {
		this.porcRealizado = porcRealizado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_evaluacion", nullable = false, length = 29)
	@NotNull
	public Date getFechaEvaluacion() {
		return this.fechaEvaluacion;
	}

	public void setFechaEvaluacion(Date fechaEvaluacion) {
		this.fechaEvaluacion = fechaEvaluacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "evalReferencial")
	public Set<EvalReferencialCab> getEvalReferencialCabs() {
		return this.evalReferencialCabs;
	}

	public void setEvalReferencialCabs(Set<EvalReferencialCab> evalReferencialCabs) {
		this.evalReferencialCabs = evalReferencialCabs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evalReferencial")
	public Set<EvalReferencialComis> getEvalReferencialComises() {
		return this.evalReferencialComises;
	}

	public void setEvalReferencialComises(Set<EvalReferencialComis> evalReferencialComises) {
		this.evalReferencialComises = evalReferencialComises;
	}
	
	@Column(name = "siendo_evaluado")
	public Boolean isSiendoEvaluado() {
		if (this.siendoEvaluado == null)
			return false;
		else
			return this.siendoEvaluado;
	}

	public void setSiendoEvaluado(Boolean siendoEvaluado) {
		this.siendoEvaluado = siendoEvaluado;
	}

}
