package py.com.excelsis.sicca.entity;

// Generated 02/07/2012 09:08:40 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvaluacionTipo generated by hbm2java
 */
@Entity
@Table(name = "evaluacion_tipo", schema = "capacitacion")
public class EvaluacionTipo implements java.io.Serializable {

	private Long idEval;
	private Capacitaciones capacitaciones;
	private String tipo;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuInicio;
	private Date fechaInicio;
	private String usuCierre;
	private Date fechaCierre;
	private Long cantidad;
	private Set<EvaluacionInscPost> evaluacionInscPosts = new HashSet<EvaluacionInscPost>(0);
	private Set<EvaluacionPart> evaluacionParts = new HashSet<EvaluacionPart>(0);

	public EvaluacionTipo() {
	}

	public EvaluacionTipo(
			long idEval, Capacitaciones capacitaciones, String tipo, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idEval = idEval;
		this.capacitaciones = capacitaciones;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvaluacionTipo(
			Long idEval, Capacitaciones capacitaciones, String tipo, boolean activo,
			String usuAlta, Date fechaAlta, String usuInicio, Date fechaInicio, String usuCierrre,
			Date fechaCierre, Long cantidad, Set<EvaluacionInscPost> evaluacionInscPosts) {
		this.idEval = idEval;
		this.capacitaciones = capacitaciones;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuInicio = usuInicio;
		this.fechaInicio = fechaInicio;
		this.usuCierre = usuCierrre;
		this.fechaCierre = fechaCierre;
		this.cantidad = cantidad;
		this.evaluacionInscPosts = evaluacionInscPosts;
	}

	@Id
	@GeneratedValue(generator="EVALUACION_TIPO_GENERATOR")
	@SequenceGenerator(name="EVALUACION_TIPO_GENERATOR",sequenceName="capacitacion.evaluacion_tipo_id_lista_cab_seq")
	@Column(name = "id_eval", unique = true, nullable = false)
	public Long getIdEval() {
		return this.idEval;
	}

	public void setIdEval(Long idEval) {
		this.idEval = idEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion", nullable = false)
	@NotNull
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}

	@Column(name = "tipo", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_inicio", length = 50)
	@Length(max = 50)
	public String getUsuInicio() {
		return this.usuInicio;
	}

	public void setUsuInicio(String usuInicio) {
		this.usuInicio = usuInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "usu_cierre", length = 50)
	@Length(max = 50)
	public String getUsuCierrre() {
		return this.usuCierre;
	}

	public void setUsuCierrre(String usuCierrre) {
		this.usuCierre = usuCierrre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cierre", length = 29)
	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	@Column(name = "cantidad")
	public Long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Long cantidad) {
		this.cantidad = cantidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evaluacionTipo")
	public Set<EvaluacionInscPost> getEvaluacionInscPosts() {
		return this.evaluacionInscPosts;
	}

	public void setEvaluacionInscPosts(Set<EvaluacionInscPost> evaluacionInscPosts) {
		this.evaluacionInscPosts = evaluacionInscPosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evaluacionTipo")
	public Set<EvaluacionPart> getEvaluacionParts() {
		return this.evaluacionParts;
	}

	public void setEvaluacionParts(Set<EvaluacionPart> evaluacionParts) {
		this.evaluacionParts = evaluacionParts;
	}

}
