package py.com.excelsis.sicca.entity;

// Generated 04-oct-2012 9:16:31 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;

/**
 * EvaluacionesFuncionario generated by hbm2java
 */
@Entity
@Table(name = "evaluaciones_funcionario", schema = "eval_desempeno")
public class EvaluacionesFuncionario implements java.io.Serializable {

	private String oee;
	private Byte nenCod;
	private String nenNom;
	private String entCod;
	private String entNombre;
	private String orden;
	private String denominacionUnidad;
	private String uoCodigo;
	private String titulo;
	
	private String grupo;
	private String plantilla;
	private Date fechaEvalDesde;
	private Date fechaEvalHasta;
	private String funcionario;
	private String documentoIdentidad;
	private String puesto;
	private String area;
	private String planMejora;
	private Float puntaje;
	private String observacion;
	private EmpleadoPuesto empleadoPuesto;
	private Persona persona;
	private Long idConfiguracionUo;
	private Documentos documento;
	private EvaluacionDesempeno evaluacionDesempeno;
	private Long idGrupoMetodologia;
	private boolean seleccionar;

	

	public EvaluacionesFuncionario(String oee, Byte nenCod, String nenNom,
			String entCod, String entNombre, String orden,
			String denominacionUnidad, String uoCodigo, String titulo,
			String plantilla, Date fechaEvalDesde, Date fechaEvalHasta,
			String funcionario, String documentoIdentidad, String puesto,
			String area, String planMejora, Float puntaje, String observacion,
			EmpleadoPuesto idEmpleadoPuesto, Persona idPersona, Long idConfiguracionUo,
			Documentos idDocumento) {
		this.oee = oee;
		this.nenCod = nenCod;
		this.nenNom = nenNom;
		this.entCod = entCod;
		this.entNombre = entNombre;
		this.orden = orden;
		this.denominacionUnidad = denominacionUnidad;
		this.uoCodigo = uoCodigo;
		this.titulo = titulo;
		this.plantilla = plantilla;
		this.fechaEvalDesde = fechaEvalDesde;
		this.fechaEvalHasta = fechaEvalHasta;
		this.funcionario = funcionario;
		this.documentoIdentidad = documentoIdentidad;
		this.puesto = puesto;
		this.area = area;
		this.planMejora = planMejora;
		this.puntaje = puntaje;
		this.observacion = observacion;
		this.empleadoPuesto = idEmpleadoPuesto;
		this.persona = idPersona;
		this.idConfiguracionUo = idConfiguracionUo;
		this.documento = idDocumento;
	}

	public EvaluacionesFuncionario() {
	}

	@Column(name = "oee", length = 100)
	@Length(max = 100)
	public String getOee() {
		return this.oee;
	}

	public void setOee(String oee) {
		this.oee = oee;
	}

	@Column(name = "nen_cod", precision = 2, scale = 0)
	public Byte getNenCod() {
		return this.nenCod;
	}

	public void setNenCod(Byte nenCod) {
		this.nenCod = nenCod;
	}

	@Column(name = "nen_nom", length = 60)
	@Length(max = 60)
	public String getNenNom() {
		return this.nenNom;
	}

	public void setNenNom(String nenNom) {
		this.nenNom = nenNom;
	}

	@Column(name = "ent_cod")
	public String getEntCod() {
		return this.entCod;
	}

	public void setEntCod(String entCod) {
		this.entCod = entCod;
	}

	@Column(name = "ent_nombre", length = 60)
	@Length(max = 60)
	public String getEntNombre() {
		return this.entNombre;
	}

	public void setEntNombre(String entNombre) {
		this.entNombre = entNombre;
	}

	@Column(name = "orden")
	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	@Column(name = "denominacion_unidad", length = 100)
	@Length(max = 100)
	public String getDenominacionUnidad() {
		return this.denominacionUnidad;
	}

	public void setDenominacionUnidad(String denominacionUnidad) {
		this.denominacionUnidad = denominacionUnidad;
	}

	@Column(name = "uo_codigo")
	public String getUoCodigo() {
		return this.uoCodigo;
	}

	public void setUoCodigo(String uoCodigo) {
		this.uoCodigo = uoCodigo;
	}

	@Column(name = "titulo", length = 250)
	@Length(max = 250)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
	
	
	@Column(name = "grupo")
	public String getGrupo() {
		return grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "plantilla", length = 500)
	@Length(max = 500)
	public String getPlantilla() {
		return this.plantilla;
	}

	public void setPlantilla(String plantilla) {
		this.plantilla = plantilla;
	}

	@Column(name = "fecha_eval_desde", length = 29)
	public Date getFechaEvalDesde() {
		return this.fechaEvalDesde;
	}

	public void setFechaEvalDesde(Date fechaEvalDesde) {
		this.fechaEvalDesde = fechaEvalDesde;
	}

	@Column(name = "fecha_eval_hasta", length = 29)
	public Date getFechaEvalHasta() {
		return this.fechaEvalHasta;
	}

	public void setFechaEvalHasta(Date fechaEvalHasta) {
		this.fechaEvalHasta = fechaEvalHasta;
	}

	@Column(name = "funcionario")
	public String getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(String funcionario) {
		this.funcionario = funcionario;
	}

	@Column(name = "documento_identidad", length = 30)
	@Length(max = 30)
	public String getDocumentoIdentidad() {
		return this.documentoIdentidad;
	}

	public void setDocumentoIdentidad(String documentoIdentidad) {
		this.documentoIdentidad = documentoIdentidad;
	}

	@Column(name = "puesto", length = 200)
	@Length(max = 200)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@Column(name = "area", length = 100)
	@Length(max = 100)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Id
	@Column(name = "plan_mejora")
	public String getPlanMejora() {
		return this.planMejora;
	}

	public void setPlanMejora(String planMejora) {
		this.planMejora = planMejora;
	}

	@Column(name = "puntaje", precision = 8, scale = 8)
	public Float getPuntaje() {
		return this.puntaje;
	}

	public void setPuntaje(Float puntaje) {
		this.puntaje = puntaje;
	}

	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto")
	public EmpleadoPuesto getEmpleadoPuesto() {
		return empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	
	@Column(name = "id_configuracion_uo")
	public Long getIdConfiguracionUo() {
		return this.idConfiguracionUo;
	}

	public void setIdConfiguracionUo(Long idConfiguracionUo) {
		this.idConfiguracionUo = idConfiguracionUo;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno")
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}


	
	//@Id
	@Column(name = "id_grupo_metodologia")
	public Long getIdGrupoMetodologia() {
		return idGrupoMetodologia;
	}

	public void setIdGrupoMetodologia(Long idGrupoMetodologia) {
		this.idGrupoMetodologia = idGrupoMetodologia;
	}

	@Transient
	public boolean isSeleccionar() {
		return seleccionar;
	}

	public void setSeleccionar(boolean seleccionar) {
		this.seleccionar = seleccionar;
	}
	
	

}
