package py.com.excelsis.sicca.entity;

// Generated 29-nov-2011 11:19:08 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvalDocumentalComis generated by hbm2java
 */
@Entity
@Table(name = "eval_documental_comis", schema = "seleccion")
public class EvalDocumentalComis implements java.io.Serializable {

	private long idEvalDocumentalComis;
	private ComisionSeleccionDet comisionSeleccionDet;
	private EmpresaPersona empresaPersona;
	private EvalDocumentalCab evalDocumentalCab;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public EvalDocumentalComis() {
	}

	public EvalDocumentalComis(long idEvalDocumentalComis,
			EvalDocumentalCab evalDocumentalCab, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idEvalDocumentalComis = idEvalDocumentalComis;
		this.evalDocumentalCab = evalDocumentalCab;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvalDocumentalComis(long idEvalDocumentalComis,
			ComisionSeleccionDet comisionSeleccionDet,
			EmpresaPersona empresaPersona, EvalDocumentalCab evalDocumentalCab,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idEvalDocumentalComis = idEvalDocumentalComis;
		this.comisionSeleccionDet = comisionSeleccionDet;
		this.empresaPersona = empresaPersona;
		this.evalDocumentalCab = evalDocumentalCab;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="EVAL_DOCUMENTAL_COMIS_GENERATOR")
	@SequenceGenerator(name="EVAL_DOCUMENTAL_COMIS_GENERATOR",sequenceName="seleccion.eval_documental_comis_id_eval_documental_comis_seq")
	@Column(name = "id_eval_documental_comis", unique = true, nullable = false)
	public long getIdEvalDocumentalComis() {
		return this.idEvalDocumentalComis;
	}

	public void setIdEvalDocumentalComis(long idEvalDocumentalComis) {
		this.idEvalDocumentalComis = idEvalDocumentalComis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comision_det")
	public ComisionSeleccionDet getComisionSeleccionDet() {
		return this.comisionSeleccionDet;
	}

	public void setComisionSeleccionDet(
			ComisionSeleccionDet comisionSeleccionDet) {
		this.comisionSeleccionDet = comisionSeleccionDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa_persona")
	public EmpresaPersona getEmpresaPersona() {
		return this.empresaPersona;
	}

	public void setEmpresaPersona(EmpresaPersona empresaPersona) {
		this.empresaPersona = empresaPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_documental_cab", nullable = false)
	@NotNull
	public EvalDocumentalCab getEvalDocumentalCab() {
		return this.evalDocumentalCab;
	}

	public void setEvalDocumentalCab(EvalDocumentalCab evalDocumentalCab) {
		this.evalDocumentalCab = evalDocumentalCab;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
