package py.com.excelsis.sicca.entity;

// Generated 09/12/2011 10:17:53 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvalReferencialCab generated by hbm2java
 */
@Entity
@Table(name = "eval_referencial_cab", schema = "seleccion")
public class EvalReferencialCab implements java.io.Serializable {

	private Long idEvalReferencialCab;
	private EvalReferencial evalReferencial;
	private float puntajeRealizado;
	private MatrizRefConfEnc matrizRefConfEnc;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<EvalReferencialDet> evalReferencialDets = new HashSet<EvalReferencialDet>(0);

	public EvalReferencialCab() {
	}

	public EvalReferencialCab(Long idEvalReferencialCab,
			EvalReferencial evalReferencial, MatrizRefConfEnc matrizRefConfEnc,
			float puntajeRealizado, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idEvalReferencialCab = idEvalReferencialCab;
		this.evalReferencial = evalReferencial;
		this.matrizRefConfEnc = matrizRefConfEnc;
		this.puntajeRealizado = puntajeRealizado;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvalReferencialCab(Long idEvalReferencialCab,
			EvalReferencial evalReferencial, MatrizRefConfEnc matrizRefConfEnc,
			float puntajeRealizado, boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod,
			Set<EvalReferencialDet> evalReferencialDets) {
		this.idEvalReferencialCab = idEvalReferencialCab;
		this.evalReferencial = evalReferencial;
		this.matrizRefConfEnc = matrizRefConfEnc;
		this.puntajeRealizado = puntajeRealizado;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.evalReferencialDets = evalReferencialDets;
	}

	@Id
	@Column(name = "id_eval_referencial_cab", unique = true, nullable = false)
	@GeneratedValue(generator="EVAL_REFERENCIAL_CAB_GENERATOR")
	@SequenceGenerator(name="EVAL_REFERENCIAL_CAB_GENERATOR", sequenceName="seleccion.eval_referencial_cab_id_eval_referencial_cab_seq")
	public Long getIdEvalReferencialCab() {
		return this.idEvalReferencialCab;
	}

	public void setIdEvalReferencialCab(Long idEvalReferencialCab) {
		this.idEvalReferencialCab = idEvalReferencialCab;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_eval_referencial", nullable = false)
	@NotNull
	public EvalReferencial getEvalReferencial() {
		return this.evalReferencial;
	}

	public void setEvalReferencial(EvalReferencial evalReferencial) {
		this.evalReferencial = evalReferencial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_matriz_ref_conf_enc", nullable = false)
	@NotNull
	public MatrizRefConfEnc getMatrizRefConfEnc() {
		return this.matrizRefConfEnc;
	}

	public void setMatrizRefConfEnc(MatrizRefConfEnc matrizRefConfEnc) {
		this.matrizRefConfEnc = matrizRefConfEnc;
	}

	@Column(name = "puntaje_realizado", nullable = false, precision = 8, scale = 8)
	public float getPuntajeRealizado() {
		return this.puntajeRealizado;
	}

	public void setPuntajeRealizado(float puntajeRealizado) {
		this.puntajeRealizado = puntajeRealizado;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "evalReferencialCab")
	public Set<EvalReferencialDet> getEvalReferencialDets() {
		return this.evalReferencialDets;
	}

	public void setEvalReferencialDets(
			Set<EvalReferencialDet> evalReferencialDets) {
		this.evalReferencialDets = evalReferencialDets;
	}

}
