package py.com.excelsis.sicca.entity;

// Generated 12-sep-2012 9:08:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvaluacionDesempeno generated by hbm2java
 */
@Entity
@Table(name = "evaluacion_desempeno", schema = "eval_desempeno")
public class EvaluacionDesempeno implements java.io.Serializable {

	private Long idEvaluacionDesempeno;
	private ConfiguracionUoCab configuracionUoCab;
	private String titulo;
	private String observacion;
	private Long idProcessInstance;
	private boolean activo;
	private Date fechaEvalDesde;
	private Date fechaEvalHasta;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Integer estado;
	private Boolean esEvaluacionRapida;
	private Set<Sujetos> sujetoses = new HashSet<Sujetos>(0);
	private Set<GruposEvaluacion> gruposEvaluacions = new HashSet<GruposEvaluacion>(
			0);
	private Set<ComisionEval> comisionEvals = new HashSet<ComisionEval>(0);

	public EvaluacionDesempeno() {
	}

	public EvaluacionDesempeno(Long idEvaluacionDesempeno,
			ConfiguracionUoCab configuracionUoCab, String titulo, boolean activo,
			String usuAlta, Date fechaAlta, Integer estado, Boolean esEvaluacionRapida) {
		this.idEvaluacionDesempeno = idEvaluacionDesempeno;
		this.configuracionUoCab = configuracionUoCab;
		this.titulo = titulo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.estado = estado;
		this.esEvaluacionRapida = esEvaluacionRapida;
	}

	public EvaluacionDesempeno(Long idEvaluacionDesempeno,
			ConfiguracionUoCab configuracionUoCab, String titulo, String observacion,
			Long idProcessInstance, Boolean activo, Date fechaEvalDesde,
			Date fechaEvalHasta, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Integer estado, Set<Sujetos> sujetoses,
			Set<GruposEvaluacion> gruposEvaluacions,
			Set<ComisionEval> comisionEvals) {
		this.idEvaluacionDesempeno = idEvaluacionDesempeno;
		this.configuracionUoCab = configuracionUoCab;
		this.titulo = titulo;
		this.observacion = observacion;
		this.idProcessInstance = idProcessInstance;
		this.activo = activo;
		this.fechaEvalDesde = fechaEvalDesde;
		this.fechaEvalHasta = fechaEvalHasta;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.estado = estado;
		this.sujetoses = sujetoses;
		this.gruposEvaluacions = gruposEvaluacions;
		this.comisionEvals = comisionEvals;
	}

	@Id
	@GeneratedValue(generator="EVAL_DESEMPENHO_GENERATOR")
	@SequenceGenerator(name="EVAL_DESEMPENHO_GENERATOR",sequenceName="eval_desempeno.evaluacion_desempeno_id_evaluacion_desempeno_seq")
	@Column(name = "id_evaluacion_desempeno", unique = true, nullable = false)
	public Long getIdEvaluacionDesempeno() {
		return this.idEvaluacionDesempeno;
	}

	public void setIdEvaluacionDesempeno(Long idEvaluacionDesempeno) {
		this.idEvaluacionDesempeno = idEvaluacionDesempeno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_cab")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "titulo", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "observacion", length = 1000)
	@Length(max = 1000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "id_process_instance")
	public Long getIdProcessInstance() {
		return this.idProcessInstance;
	}

	public void setIdProcessInstance(Long idProcessInstance) {
		this.idProcessInstance = idProcessInstance;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eval_desde", length = 29)
	public Date getFechaEvalDesde() {
		return this.fechaEvalDesde;
	}

	public void setFechaEvalDesde(Date fechaEvalDesde) {
		this.fechaEvalDesde = fechaEvalDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_eval_hasta", length = 29)
	public Date getFechaEvalHasta() {
		return this.fechaEvalHasta;
	}

	public void setFechaEvalHasta(Date fechaEvalHasta) {
		this.fechaEvalHasta = fechaEvalHasta;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "estado", nullable = false)
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evaluacionDesempeno")
	public Set<Sujetos> getSujetoses() {
		return this.sujetoses;
	}

	public void setSujetoses(Set<Sujetos> sujetoses) {
		this.sujetoses = sujetoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evaluacionDesempeno")
	public Set<GruposEvaluacion> getGruposEvaluacions() {
		return this.gruposEvaluacions;
	}

	public void setGruposEvaluacions(Set<GruposEvaluacion> gruposEvaluacions) {
		this.gruposEvaluacions = gruposEvaluacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evaluacionDesempeno")
	public Set<ComisionEval> getComisionEvals() {
		return this.comisionEvals;
	}

	public void setComisionEvals(Set<ComisionEval> comisionEvals) {
		this.comisionEvals = comisionEvals;
	}
	
	@Column(name = "es_eval_rapida")
	public Boolean getEsEvaluacionRapida() {
		return this.esEvaluacionRapida;
	}

	public void setEsEvaluacionRapida(Boolean esEvaluacionRapida) {
		this.esEvaluacionRapida = esEvaluacionRapida;
	}

}
