package py.com.excelsis.sicca.entity;

// Generated 02/07/2012 02:48:54 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvaluacionPart generated by hbm2java
 */
@Entity
@Table(name = "evaluacion_part", schema = "capacitacion")
public class EvaluacionPart implements java.io.Serializable {

	private Long idEvalP;
	private PostulacionCap postulacionCap;
	private EvaluacionTipo evaluacionTipo;
	private Boolean finalizo;
	private Long asistencia;
	private Boolean satisfactoriamente;
	private Long calificacion;
	private String observacion;
	private String certificado;
	private Documentos documento;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String sino;

	public EvaluacionPart() {
	}

	public EvaluacionPart(Long idEvalP, PostulacionCap postulacionCap,
			EvaluacionTipo evaluacionTipo, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idEvalP = idEvalP;
		this.postulacionCap = postulacionCap;
		this.evaluacionTipo = evaluacionTipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvaluacionPart(Long idEvalP, PostulacionCap postulacionCap,
			EvaluacionTipo evaluacionTipo, Boolean finalizo, Long asistencia,
			Boolean satisfactoriamente, Long calificacion, String observacion,
			String certificado, Documentos documento, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idEvalP = idEvalP;
		this.postulacionCap = postulacionCap;
		this.evaluacionTipo = evaluacionTipo;
		this.finalizo = finalizo;
		this.asistencia = asistencia;
		this.satisfactoriamente = satisfactoriamente;
		this.calificacion = calificacion;
		this.observacion = observacion;
		this.certificado = certificado;
		this.documento = documento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="EVALUACION_PART_GENERATOR")
	@SequenceGenerator(name="EVALUACION_PART_GENERATOR",sequenceName="capacitacion.evaluacion_part_id_eval_p_seq")
	@Column(name = "id_eval_p", unique = true, nullable = false)
	public Long getIdEvalP() {
		return this.idEvalP;
	}

	public void setIdEvalP(Long idEvalP) {
		this.idEvalP = idEvalP;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public PostulacionCap getPostulacionCap() {
		return this.postulacionCap;
	}

	public void setPostulacionCap(PostulacionCap postulacionCap) {
		this.postulacionCap = postulacionCap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval", nullable = false)
	@NotNull
	public EvaluacionTipo getEvaluacionTipo() {
		return this.evaluacionTipo;
	}

	public void setEvaluacionTipo(EvaluacionTipo evaluacionTipo) {
		this.evaluacionTipo = evaluacionTipo;
	}

	@Column(name = "finalizo")
	public Boolean getFinalizo() {
		return this.finalizo;
	}

	public void setFinalizo(Boolean finalizo) {
		this.finalizo = finalizo;
	}

	@Column(name = "asistencia")
	public Long getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Long asistencia) {
		this.asistencia = asistencia;
	}

	@Column(name = "satisfactoriamente")
	public Boolean getSatisfactoriamente() {
		return this.satisfactoriamente;
	}

	public void setSatisfactoriamente(Boolean satisfactoriamente) {
		this.satisfactoriamente = satisfactoriamente;
	}

	@Column(name = "calificacion")
	public Long getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Long calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "observacion", length = 5000)
	@Length(max = 5000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "certificado", length = 1)
	@Length(max = 1)
	public String getCertificado() {
		return this.certificado;
	}

	public void setCertificado(String certificado) {
		this.certificado = certificado;
	}

	

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	@Transient
	public String getSino() {
		return sino;
	}

	public void setSino(String sino) {
		this.sino = sino;
	}
	
	

}
