package py.com.excelsis.sicca.entity;

// Generated 17-nov-2011 17:00:10 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EvalDocumentalCab generated by hbm2java
 */
@Entity
@Table(name = "eval_documental_cab", schema = "seleccion")
public class EvalDocumentalCab implements java.io.Serializable {

	private Long idEvalDocumentalCab;
	private Postulacion postulacion;
	private String tipo;
	private Boolean aprobado;
	private Boolean evaluado;
	private Date fechaEvaluacion;
	private String observacion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Boolean incluido;
	private Excepcion excepcion;
	private Set<EvalDocumentalDet> evalDocumentalDets = new HashSet<EvalDocumentalDet>(0);

	public EvalDocumentalCab() {
	}

	public EvalDocumentalCab(Long idEvalDocumentalCab, Postulacion postulacion,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idEvalDocumentalCab = idEvalDocumentalCab;
		this.postulacion = postulacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public EvalDocumentalCab(Long idEvalDocumentalCab,
			Postulacion postulacion,
			String tipo, Boolean aprobado, Boolean evaluado,
			Date fechaEvaluacion, String observacion, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<EvalDocumentalDet> evalDocumentalDets) {
		this.idEvalDocumentalCab = idEvalDocumentalCab;
		this.postulacion = postulacion;
		this.tipo = tipo;
		this.aprobado = aprobado;
		this.evaluado = evaluado;
		this.fechaEvaluacion = fechaEvaluacion;
		this.observacion = observacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.evalDocumentalDets = evalDocumentalDets;
	}

	@Id
	@GeneratedValue(generator="EVAL_DOCUMENTAL_CAB_GENERATOR")
	@SequenceGenerator(name="EVAL_DOCUMENTAL_CAB_GENERATOR",sequenceName="seleccion.eval_documental_cab_id_eval_documental_seq")
	@Column(name = "id_eval_documental_cab", unique = true, nullable = false)
	public Long getIdEvalDocumentalCab() {
		return this.idEvalDocumentalCab;
	}

	public void setIdEvalDocumentalCab(Long idEvalDocumentalCab) {
		this.idEvalDocumentalCab = idEvalDocumentalCab;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@Column(name = "tipo", length = 30)
	@Length(max = 30)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "aprobado")
	public Boolean getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(Boolean aprobado) {
		this.aprobado = aprobado;
	}

	@Column(name = "evaluado")
	public Boolean getEvaluado() {
		return this.evaluado;
	}

	public void setEvaluado(Boolean evaluado) {
		this.evaluado = evaluado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_evaluacion", length = 29)
	public Date getFechaEvaluacion() {
		return this.fechaEvaluacion;
	}

	public void setFechaEvaluacion(Date fechaEvaluacion) {
		this.fechaEvaluacion = fechaEvaluacion;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evalDocumentalCab")
	public Set<EvalDocumentalDet> getEvalDocumentalDets() {
		return this.evalDocumentalDets;
	}

	public void setEvalDocumentalDets(Set<EvalDocumentalDet> evalDocumentalDets) {
		this.evalDocumentalDets = evalDocumentalDets;
	}

	@Column(name = "incluido")
	public Boolean getIncluido() {
		return incluido;
	}

	public void setIncluido(Boolean incluido) {
		this.incluido = incluido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_excepcion")
	public Excepcion getExcepcion() {
		return excepcion;
	}

	public void setExcepcion(Excepcion excepcion) {
		this.excepcion = excepcion;
	}
	
	
	
	

}
