package py.com.excelsis.sicca.entity;

// Generated 28/02/2012 09:47:43 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Excepcionados generated by hbm2java
 */
@Entity
@Table(name = "excepcionados", schema = "juridicos")
public class Excepcionados implements java.io.Serializable {

	private Long idExcepcionado;
	private Persona persona;
	private ConfiguracionUoCab configuracionUoCab;
	private Integer anio;
	private Date fecha;
	private String nroDictamen;
	private String motivo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaHasta;

	public Excepcionados() {
	}

	public Excepcionados(Long idExcepcionado, Persona persona,
			Integer anio, Date fecha, String nroDictamen,
			String motivo, boolean activo, String usuAlta, Date fechaAlta) {
		this.idExcepcionado = idExcepcionado;
		this.persona = persona;
		this.anio = anio;
		this.fecha = fecha;
		this.nroDictamen = nroDictamen;
		this.motivo = motivo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public Excepcionados(Long idExcepcionado, Persona persona,
			 Integer anio, Date fecha, String nroDictamen,
			String motivo, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idExcepcionado = idExcepcionado;
		this.persona = persona;
		this.anio = anio;
		this.fecha = fecha;
		this.nroDictamen = nroDictamen;
		this.motivo = motivo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_excepcionado", unique = true, nullable = false)
	@GeneratedValue(generator="EXCEPCIONADOS_GENERATOR")
	@SequenceGenerator(name="EXCEPCIONADOS_GENERATOR",sequenceName="juridicos.excepcionados_id_excepcionado_seq")
	public Long getIdExcepcionado() {
		return this.idExcepcionado;
	}

	public void setIdExcepcionado(Long idExcepcionado) {
		this.idExcepcionado = idExcepcionado;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "anio", nullable = false)
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "nro_dictamen", nullable = false)
	@NotNull
	public String getNroDictamen() {
		return this.nroDictamen;
	}

	public void setNroDictamen(String nroDictamen) {
		this.nroDictamen = nroDictamen;
	}

	@Column(name = "motivo", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hasta",  length = 29)
	public Date getFechaHasta() {
		return fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}
	
	
	

}
