package py.com.excelsis.sicca.entity;

// Generated 05/09/2012 03:01:47 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ExcepcionElegibles generated by hbm2java
 */
@Entity
@Table(name = "excepcion_elegibles", schema = "seleccion")
public class ExcepcionElegibles implements java.io.Serializable {

	private Long idExcepcionElegibles;
	private Postulacion postulacion;
	private Excepcion excepcion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ExcepcionElegibles() {
	}

	public ExcepcionElegibles(Long idExcepcionElegibles,
			Postulacion postulacion, Excepcion excepcion, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idExcepcionElegibles = idExcepcionElegibles;
		this.postulacion = postulacion;
		this.excepcion = excepcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ExcepcionElegibles(Long idExcepcionElegibles,
			Postulacion postulacion, Excepcion excepcion, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idExcepcionElegibles = idExcepcionElegibles;
		this.postulacion = postulacion;
		this.excepcion = excepcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_excepcion_elegibles", unique = true, nullable = false)
	@GeneratedValue(generator = "EXCEPCION_ELEGIBLE_GENERATOR")
	@SequenceGenerator(name = "EXCEPCION_ELEGIBLE_GENERATOR", sequenceName = "seleccion.excepcion_elegibles_id_excepcion_elegibles_seq")
	public Long getIdExcepcionElegibles() {
		return this.idExcepcionElegibles;
	}

	public void setIdExcepcionElegibles(Long idExcepcionElegibles) {
		this.idExcepcionElegibles = idExcepcionElegibles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_excepcion", nullable = false)
	@NotNull
	public Excepcion getExcepcion() {
		return this.excepcion;
	}

	public void setExcepcion(Excepcion excepcion) {
		this.excepcion = excepcion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
