package py.com.excelsis.sicca.entity;

// Generated 15-oct-2012 15:52:09 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Familiares generated by hbm2java
 */
@Entity
@Table(name = "familiares", schema = "legajo")
public class Familiares implements java.io.Serializable {

	private Long idFamiliar;
	private Persona personaFamiliar;
	private DatosEspecificos datosEspecificosFamiliar;
	private Persona persona;
	private Integer funcionarioPublico;
	private Long personasACargo;
	private Long observacion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private ConfiguracionUoCab configuracionUoCab;
	private String observaciones;
	private String nombresFamiliar;
	private String apellidosFamiliar;
	private String sexo;
	private String estadoCivil;
	private Date fechaNacimiento;
	private Documentos documento;
	private Pais paisByIdPaisExpedicionDoc;
	private String telefonos;
	private String EMail;
	private Boolean personaACargo;
	
	

	public Familiares() {
	}

	public Familiares(
			Long idFamiliar, Persona personaFamiliar, DatosEspecificos datosEspecificosFamiliar,
			Persona persona, Integer funcionarioPublico, boolean activo, String usuAlta,
			Date fechaAlta, Boolean personaACargo) {
		this.idFamiliar = idFamiliar;
		this.personaFamiliar = personaFamiliar;
		this.datosEspecificosFamiliar = datosEspecificosFamiliar;
		this.persona = persona;
		this.funcionarioPublico = funcionarioPublico;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.personaACargo = personaACargo;
	}

	public Familiares(
			Long idFamiliar, Persona personaFamiliar, DatosEspecificos datosEspecificosFamiliar,
			Persona persona, Integer funcionarioPublico, ConfiguracionUoCab configuracionUoCab,
			Long personasACargo, Long observacion, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idFamiliar = idFamiliar;
		this.personaFamiliar = personaFamiliar;
		this.datosEspecificosFamiliar = datosEspecificosFamiliar;
		this.persona = persona;
		this.funcionarioPublico = funcionarioPublico;
		this.configuracionUoCab = configuracionUoCab;
		this.personasACargo = personasACargo;
		this.observacion = observacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "FAMILIARES_GENERATOR")
	@SequenceGenerator(name = "FAMILIARES_GENERATOR", sequenceName = "legajo.familiares_id_familiar_seq")
	@Column(name = "id_familiar", unique = true, nullable = false)
	public Long getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(Long idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_familiar")
	public Persona getPersonaFamiliar() {
		return personaFamiliar;
	}

	public void setPersonaFamiliar(Persona personaFamiliar) {
		this.personaFamiliar = personaFamiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_familiar")
	public DatosEspecificos getDatosEspecificosFamiliar() {
		return datosEspecificosFamiliar;
	}

	public void setDatosEspecificosFamiliar(DatosEspecificos datosEspecificosFamiliar) {
		this.datosEspecificosFamiliar = datosEspecificosFamiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "funcionario_publico", nullable = true)
	public Integer getFuncionarioPublico() {
		return this.funcionarioPublico;
	}

	public void setFuncionarioPublico(Integer funcionarioPublico) {
		this.funcionarioPublico = funcionarioPublico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "personas_a_cargo")
	public Long getPersonasACargo() {
		return this.personasACargo;
	}

	public void setPersonasACargo(Long personasACargo) {
		this.personasACargo = personasACargo;
	}

	@Column(name = "observacion")
	public Long getObservacion() {
		return this.observacion;
	}

	public void setObservacion(Long observacion) {
		this.observacion = observacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Column(name = "observaciones", length = 250)
	@Length(max = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}
	
	
	@Column(name = "nombres_familiar")
	public String getNombresFamiliar() {
		return nombresFamiliar;
	}

	public void setNombresFamiliar(String nombresFamiliar) {
		this.nombresFamiliar = nombresFamiliar;
	}
	
	
	@Column(name = "apellidos_familiar")
	public String getApellidosFamiliar() {
		return apellidosFamiliar;
	}

	public void setApellidosFamiliar(String apellidosFamiliar) {
		this.apellidosFamiliar = apellidosFamiliar;
	}

	@Column(name = "sexo", length = 1)
	@Length(max = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "estado_civil", length = 1)
	@Length(max = 1)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return documento;
	}

	public void setDocumentos(Documentos documentos) {
		this.documento = documentos;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais_expedicion_doc")
	public Pais getPaisByIdPaisExpedicionDoc() {
		return this.paisByIdPaisExpedicionDoc;
	}

	public void setPaisByIdPaisExpedicionDoc(Pais paisByIdPaisExpedicionDoc) {
		this.paisByIdPaisExpedicionDoc = paisByIdPaisExpedicionDoc;
	}
	
	@Column(name = "e_mail", length = 50)
	@Length(max = 50)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}
	
	@Column(name = "telefonos", length = 50)
	@Length(max = 50)
	public String getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(String telefonos) {
		this.telefonos = telefonos;
	}

	@Column(name = "persona_a_cargo")
	public Boolean getPersonaACargo() {
		return this.personaACargo;
	}

	public void setPersonaACargo(Boolean personaACargo) {
		this.personaACargo = personaACargo;
	}
	

}
