package py.com.excelsis.sicca.entity;

// Generated 10/11/2011 09:13:30 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FechasGrupoPuesto generated by hbm2java
 */
@Entity
@Table(name = "fechas_grupo", schema = "seleccion")
public class FechasGrupo implements java.io.Serializable {

	private Long idFechas;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Date fechaPublicacionDesde;
	private Date horaPublicacionDesde;
	private Date fechaPublicacionHasta;
	private Date horaPublicacionHasta;
	private Date fechaRecepcionDesde;
	private Date horaRecepcionDesde;
	private Date fechaRecepcionHasta;
	private Date horaRecepcionHasta;
	private Date fechaVigProcDesde;
	private Date horaVigProcDesde;
	private Date fechaVigProcHasta;
	private Date horaVigProcHasta;
	private Date fechaVigHastaAnt;	 
	private Date fechaVigProcDesdeAnt;
	private Date horaVigProcDesdeAnt;	 
	private Date horaVigProcHastaAnt;
	private String estado;
	private Date fechaRecepcionDesdeAnt;
	private Date horaRecepcionDesdeAnt;
	private Date fechaRecepcionHastaAnt;
	private Date horaRecepcionHastaAnt;

	public FechasGrupo() {
	}



	@Id
	@Column(name = "id_fechas", unique = true, nullable = false)
	public Long getIdFechas() {
		return this.idFechas;
	}

	public void setIdFechas(Long idFechas) {
		this.idFechas = idFechas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	 
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_publicacion_desde", nullable = false, length = 13)
	@NotNull
	public Date getFechaPublicacionDesde() {
		return this.fechaPublicacionDesde;
	}

	public void setFechaPublicacionDesde(Date fechaPublicacionDesde) {
		this.fechaPublicacionDesde = fechaPublicacionDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_publicacion_desde", nullable = false, length = 15)
	@NotNull
	public Date getHoraPublicacionDesde() {
		return this.horaPublicacionDesde;
	}

	public void setHoraPublicacionDesde(Date horaPublicacionDesde) {
		this.horaPublicacionDesde = horaPublicacionDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_publicacion_hasta", nullable = false, length = 13)
	@NotNull
	public Date getFechaPublicacionHasta() {
		return this.fechaPublicacionHasta;
	}

	public void setFechaPublicacionHasta(Date fechaPublicacionHasta) {
		this.fechaPublicacionHasta = fechaPublicacionHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_publicacion_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHoraPublicacionHasta() {
		return this.horaPublicacionHasta;
	}

	public void setHoraPublicacionHasta(Date horaPublicacionHasta) {
		this.horaPublicacionHasta = horaPublicacionHasta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_desde", nullable = false, length = 13)
	@NotNull
	public Date getFechaRecepcionDesde() {
		return this.fechaRecepcionDesde;
	}

	public void setFechaRecepcionDesde(Date fechaRecepcionDesde) {
		this.fechaRecepcionDesde = fechaRecepcionDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_recepcion_desde", nullable = false, length = 15)
	@NotNull
	public Date getHoraRecepcionDesde() {
		return this.horaRecepcionDesde;
	}

	public void setHoraRecepcionDesde(Date horaRecepcionDesde) {
		this.horaRecepcionDesde = horaRecepcionDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_hasta", nullable = false, length = 13)
	@NotNull
	public Date getFechaRecepcionHasta() {
		return this.fechaRecepcionHasta;
	}

	public void setFechaRecepcionHasta(Date fechaRecepcionHasta) {
		this.fechaRecepcionHasta = fechaRecepcionHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_recepcion_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHoraRecepcionHasta() {
		return this.horaRecepcionHasta;
	}

	public void setHoraRecepcionHasta(Date horaRecepcionHasta) {
		this.horaRecepcionHasta = horaRecepcionHasta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_proc_desde", nullable = false, length = 13)
	@NotNull
	public Date getFechaVigProcDesde() {
		return this.fechaVigProcDesde;
	}

	public void setFechaVigProcDesde(Date fechaVigProcDesde) {
		this.fechaVigProcDesde = fechaVigProcDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_desde", nullable = false, length = 15)
	@NotNull
	public Date getHoraVigProcDesde() {
		return this.horaVigProcDesde;
	}

	public void setHoraVigProcDesde(Date horaVigProcDesde) {
		this.horaVigProcDesde = horaVigProcDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_proc_hasta", nullable = false, length = 13)
	@NotNull
	public Date getFechaVigProcHasta() {
		return this.fechaVigProcHasta;
	}

	public void setFechaVigProcHasta(Date fechaVigProcHasta) {
		this.fechaVigProcHasta = fechaVigProcHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHoraVigProcHasta() {
		return this.horaVigProcHasta;
	}

	public void setHoraVigProcHasta(Date horaVigProcHasta) {
		this.horaVigProcHasta = horaVigProcHasta;
	}



	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_hasta_ant", length = 13)
	public Date getFechaVigHastaAnt() {
		return this.fechaVigHastaAnt;
	}

	public void setFechaVigHastaAnt(Date fechaVigHastaAnt) {
		this.fechaVigHastaAnt = fechaVigHastaAnt;
	}


	@Column(name = "estado")
	@Length(max = 20)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_desde_ant", length = 13)
	public Date getFechaRecepcionDesdeAnt() {
		return this.fechaRecepcionDesdeAnt;
	}

	public void setFechaRecepcionDesdeAnt(Date fechaRecepcionDesdeAnt) {
		this.fechaRecepcionDesdeAnt = fechaRecepcionDesdeAnt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_recepcion_desde_ant", length = 15)
	public Date getHoraRecepcionDesdeAnt() {
		return this.horaRecepcionDesdeAnt;
	}

	public void setHoraRecepcionDesdeAnt(Date horaRecepcionDesdeAnt) {
		this.horaRecepcionDesdeAnt = horaRecepcionDesdeAnt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_hasta_ant", length = 13)
	public Date getFechaRecepcionHastaAnt() {
		return this.fechaRecepcionHastaAnt;
	}

	public void setFechaRecepcionHastaAnt(Date fechaRecepcionHastaAnt) {
		this.fechaRecepcionHastaAnt = fechaRecepcionHastaAnt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_recepcion_hasta_ant", length = 29)
	public Date getHoraRecepcionHastaAnt() {
		return this.horaRecepcionHastaAnt;
	}

	public void setHoraRecepcionHastaAnt(Date horaRecepcionHastaAnt) {
		this.horaRecepcionHastaAnt = horaRecepcionHastaAnt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_proc_desde_ant", length = 13)
	public Date getFechaVigProcDesdeAnt() {
		return this.fechaVigProcDesdeAnt;
	}

	public void setFechaVigProcDesdeAnt(Date fechaVigProcDesdeAnt) {
		this.fechaVigProcDesdeAnt = fechaVigProcDesdeAnt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_desde_ant", length = 15)
	public Date getHoraVigProcDesdeAnt() {
		return this.horaVigProcDesdeAnt;
	}

	public void setHoraVigProcDesdeAnt(Date horaVigProcDesdeAnt) {
		this.horaVigProcDesdeAnt = horaVigProcDesdeAnt;
	}
	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_hasta_ant", length = 15)
	public Date getHoraVigProcHastaAnt() {
		return this.horaVigProcHastaAnt;
	}

	public void setHoraVigProcHastaAnt(Date horaVigProcHastaAnt) {
		this.horaVigProcHastaAnt = horaVigProcHastaAnt;
	}
	
}
