package py.com.excelsis.sicca.entity;

// Generated 10/11/2011 09:13:30 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FechasGrupoPuesto generated by hbm2java
 */
@Entity
@Table(name = "fechas_grupo_puesto", schema = "seleccion")
public class FechasGrupoPuesto implements java.io.Serializable {

	private Long idFechas;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Concurso concurso;
	private Date fechaPublicacionDesde;
	private Date horaPublicacionDesde;
	private Date fechaPublicacionHasta;
	private Date horaPublicacionHasta;
	private Date fechaRecepcionDesde;
	private Date horaRecepcionDesde;
	private Date fechaRecepcionHasta;
	private Date horaRecepcionHasta;
	private Date fechaVigProcDesde;
	private Date horaVigProcDesde;
	private Date fechaVigProcHasta;
	private Date horaVigProcHasta;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaVigHastaAnt;	 
	private Date fechaVigProcDesdeAnt;
	private Date horaVigProcDesdeAnt;	 
	private Date horaVigProcHastaAnt;
	private String estado;
	private Date fechaRecepcionDesdeAnt;
	private Date horaRecepcionDesdeAnt;
	private Date fechaRecepcionHastaAnt;
	private Date horaRecepcionHastaAnt;
	private String observacion;
	private Date fechaPublicacionDesdeAnt;
	private Date fechaPublicacionHastaAnt;
	private Date horaPublicacionDesdeAnt;
	private Date horaPublicacionHastaAnt;

	private Set<SolicProrrogaCab> solicProrrogaCabs = new HashSet<SolicProrrogaCab>(0);

	public FechasGrupoPuesto() {
	}

	public FechasGrupoPuesto(
			Long idFechas, ConcursoPuestoAgr concursoPuestoAgr, Date fechaPublicacionDesde,
			Date horaPublicacionDesde, Date fechaPublicacionHasta, Date horaPublicacionHasta,
			Date fechaRecepcionDesde, Date horaRecepcionDesde, Date fechaRecepcionHasta,
			Date horaRecepcionHasta, Date fechaVigProcDesde, Date horaVigProcDesde,
			Date fechaVigProcHasta, Date horaVigProcHasta, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idFechas = idFechas;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.fechaPublicacionDesde = fechaPublicacionDesde;
		this.horaPublicacionDesde = horaPublicacionDesde;
		this.fechaPublicacionHasta = fechaPublicacionHasta;
		this.horaPublicacionHasta = horaPublicacionHasta;
		this.fechaRecepcionDesde = fechaRecepcionDesde;
		this.horaRecepcionDesde = horaRecepcionDesde;
		this.fechaRecepcionHasta = fechaRecepcionHasta;
		this.horaRecepcionHasta = horaRecepcionHasta;
		this.fechaVigProcDesde = fechaVigProcDesde;
		this.horaVigProcDesde = horaVigProcDesde;
		this.fechaVigProcHasta = fechaVigProcHasta;
		this.horaVigProcHasta = horaVigProcHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public FechasGrupoPuesto(
			Long idFechas, ConcursoPuestoAgr concursoPuestoAgr, Date fechaPublicacionDesde,
			Date horaPublicacionDesde, Date fechaPublicacionHasta, Date horaPublicacionHasta,
			Date fechaRecepcionDesde, Date horaRecepcionDesde, Date fechaRecepcionHasta,
			Date horaRecepcionHasta, Date fechaVigProcDesde, Date horaVigProcDesde,
			Date fechaVigProcHasta, Date horaVigProcHasta, boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idFechas = idFechas;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.fechaPublicacionDesde = fechaPublicacionDesde;
		this.horaPublicacionDesde = horaPublicacionDesde;
		this.fechaPublicacionHasta = fechaPublicacionHasta;
		this.horaPublicacionHasta = horaPublicacionHasta;
		this.fechaRecepcionDesde = fechaRecepcionDesde;
		this.horaRecepcionDesde = horaRecepcionDesde;
		this.fechaRecepcionHasta = fechaRecepcionHasta;
		this.horaRecepcionHasta = horaRecepcionHasta;
		this.fechaVigProcDesde = fechaVigProcDesde;
		this.horaVigProcDesde = horaVigProcDesde;
		this.fechaVigProcHasta = fechaVigProcHasta;
		this.horaVigProcHasta = horaVigProcHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "FECHA_GRUPO_PUESTO")
	@SequenceGenerator(name = "FECHA_GRUPO_PUESTO", sequenceName = "seleccion.fechas_grupo_puesto_id_fechas_seq")
	@Column(name = "id_fechas", unique = true, nullable = false)
	public Long getIdFechas() {
		return this.idFechas;
	}

	public void setIdFechas(Long idFechas) {
		this.idFechas = idFechas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	 
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_publicacion_desde", nullable = false, length = 13)
	@NotNull
	public Date getFechaPublicacionDesde() {
		return this.fechaPublicacionDesde;
	}

	public void setFechaPublicacionDesde(Date fechaPublicacionDesde) {
		this.fechaPublicacionDesde = fechaPublicacionDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_publicacion_desde", nullable = false, length = 15)
	@NotNull
	public Date getHoraPublicacionDesde() {
		return this.horaPublicacionDesde;
	}

	public void setHoraPublicacionDesde(Date horaPublicacionDesde) {
		this.horaPublicacionDesde = horaPublicacionDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_publicacion_hasta", nullable = false, length = 13)
	@NotNull
	public Date getFechaPublicacionHasta() {
		return this.fechaPublicacionHasta;
	}

	public void setFechaPublicacionHasta(Date fechaPublicacionHasta) {
		this.fechaPublicacionHasta = fechaPublicacionHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_publicacion_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHoraPublicacionHasta() {
		return this.horaPublicacionHasta;
	}

	public void setHoraPublicacionHasta(Date horaPublicacionHasta) {
		this.horaPublicacionHasta = horaPublicacionHasta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_desde", nullable = false, length = 13)
	@NotNull
	public Date getFechaRecepcionDesde() {
		return this.fechaRecepcionDesde;
	}

	public void setFechaRecepcionDesde(Date fechaRecepcionDesde) {
		this.fechaRecepcionDesde = fechaRecepcionDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_recepcion_desde", nullable = false, length = 15)
	@NotNull
	public Date getHoraRecepcionDesde() {
		return this.horaRecepcionDesde;
	}

	public void setHoraRecepcionDesde(Date horaRecepcionDesde) {
		this.horaRecepcionDesde = horaRecepcionDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_hasta", nullable = false, length = 13)
	@NotNull
	public Date getFechaRecepcionHasta() {
		return this.fechaRecepcionHasta;
	}

	public void setFechaRecepcionHasta(Date fechaRecepcionHasta) {
		this.fechaRecepcionHasta = fechaRecepcionHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_recepcion_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHoraRecepcionHasta() {
		return this.horaRecepcionHasta;
	}

	public void setHoraRecepcionHasta(Date horaRecepcionHasta) {
		this.horaRecepcionHasta = horaRecepcionHasta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_proc_desde", nullable = false, length = 13)
	@NotNull
	public Date getFechaVigProcDesde() {
		return this.fechaVigProcDesde;
	}

	public void setFechaVigProcDesde(Date fechaVigProcDesde) {
		this.fechaVigProcDesde = fechaVigProcDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_desde", nullable = false, length = 15)
	@NotNull
	public Date getHoraVigProcDesde() {
		return this.horaVigProcDesde;
	}

	public void setHoraVigProcDesde(Date horaVigProcDesde) {
		this.horaVigProcDesde = horaVigProcDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_proc_hasta", nullable = false, length = 13)
	@NotNull
	public Date getFechaVigProcHasta() {
		return this.fechaVigProcHasta;
	}

	public void setFechaVigProcHasta(Date fechaVigProcHasta) {
		this.fechaVigProcHasta = fechaVigProcHasta;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHoraVigProcHasta() {
		return this.horaVigProcHasta;
	}

	public void setHoraVigProcHasta(Date horaVigProcHasta) {
		this.horaVigProcHasta = horaVigProcHasta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_hasta_ant", length = 13)
	public Date getFechaVigHastaAnt() {
		return this.fechaVigHastaAnt;
	}

	public void setFechaVigHastaAnt(Date fechaVigHastaAnt) {
		this.fechaVigHastaAnt = fechaVigHastaAnt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso")
	public Concurso getConcurso() {
		return this.concurso;
	}

	public void setConcurso(Concurso concurso) {
		this.concurso = concurso;
	}

	@Column(name = "estado")
	@Length(max = 20)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fechasGrupoPuesto")
	public Set<SolicProrrogaCab> getSolicProrrogaCabs() {
		return this.solicProrrogaCabs;
	}

	public void setSolicProrrogaCabs(Set<SolicProrrogaCab> solicProrrogaCabs) {
		this.solicProrrogaCabs = solicProrrogaCabs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_desde_ant", length = 13)
	public Date getFechaRecepcionDesdeAnt() {
		return this.fechaRecepcionDesdeAnt;
	}

	public void setFechaRecepcionDesdeAnt(Date fechaRecepcionDesdeAnt) {
		this.fechaRecepcionDesdeAnt = fechaRecepcionDesdeAnt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_recepcion_desde_ant", length = 15)
	public Date getHoraRecepcionDesdeAnt() {
		return this.horaRecepcionDesdeAnt;
	}

	public void setHoraRecepcionDesdeAnt(Date horaRecepcionDesdeAnt) {
		this.horaRecepcionDesdeAnt = horaRecepcionDesdeAnt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion_hasta_ant", length = 13)
	public Date getFechaRecepcionHastaAnt() {
		return this.fechaRecepcionHastaAnt;
	}

	public void setFechaRecepcionHastaAnt(Date fechaRecepcionHastaAnt) {
		this.fechaRecepcionHastaAnt = fechaRecepcionHastaAnt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_recepcion_hasta_ant", length = 29)
	public Date getHoraRecepcionHastaAnt() {
		return this.horaRecepcionHastaAnt;
	}

	public void setHoraRecepcionHastaAnt(Date horaRecepcionHastaAnt) {
		this.horaRecepcionHastaAnt = horaRecepcionHastaAnt;
	}

	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vig_proc_desde_ant", length = 13)
	public Date getFechaVigProcDesdeAnt() {
		return this.fechaVigProcDesdeAnt;
	}

	public void setFechaVigProcDesdeAnt(Date fechaVigProcDesdeAnt) {
		this.fechaVigProcDesdeAnt = fechaVigProcDesdeAnt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_desde_ant", length = 15)
	public Date getHoraVigProcDesdeAnt() {
		return this.horaVigProcDesdeAnt;
	}

	public void setHoraVigProcDesdeAnt(Date horaVigProcDesdeAnt) {
		this.horaVigProcDesdeAnt = horaVigProcDesdeAnt;
	}
	@Temporal(TemporalType.TIME)
	@Column(name = "hora_vig_proc_hasta_ant", length = 15)
	public Date getHoraVigProcHastaAnt() {
		return this.horaVigProcHastaAnt;
	}

	public void setHoraVigProcHastaAnt(Date horaVigProcHastaAnt) {
		this.horaVigProcHastaAnt = horaVigProcHastaAnt;
	}


	
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_publicacion_desde_ant", length = 13)
	public Date getFechaPublicacionDesdeAnt() {
		return this.fechaPublicacionDesdeAnt;
	}

	public void setFechaPublicacionDesdeAnt(Date fechaPublicacionDesdeAnt) {
		this.fechaPublicacionDesdeAnt = fechaPublicacionDesdeAnt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_publicacion_hasta_ant", length = 13)
	public Date getFechaPublicacionHastaAnt() {
		return this.fechaPublicacionHastaAnt;
	}

	public void setFechaPublicacionHastaAnt(Date fechaPublicacionHastaAnt) {
		this.fechaPublicacionHastaAnt = fechaPublicacionHastaAnt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_publicacion_desde_ant", length = 15)
	public Date getHoraPublicacionDesdeAnt() {
		return this.horaPublicacionDesdeAnt;
	}

	public void setHoraPublicacionDesdeAnt(Date horaPublicacionDesdeAnt) {
		this.horaPublicacionDesdeAnt = horaPublicacionDesdeAnt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_publicacion_hasta_ant", length = 15)
	public Date getHoraPublicacionHastaAnt() {
		return this.horaPublicacionHastaAnt;
	}

	public void setHoraPublicacionHastaAnt(Date horaPublicacionHastaAnt) {
		this.horaPublicacionHastaAnt = horaPublicacionHastaAnt;
	}	 
	
}
