package py.com.excelsis.sicca.entity;

// Generated 25/10/2011 02:45:03 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FuncionarioOee generated by hbm2java
 */
@Entity
@Table(name = "funcionario_oee", schema = "seleccion")
public class FuncionarioOee implements java.io.Serializable {

	private Long idFuncionarioOee;
	private TipoNombramiento tipoNombramiento;
	private ConfiguracionUoCab configuracionUoCab;
	private Persona persona;
	private Date fechaIngreso;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String modalidadOcupacion;
	private Boolean mostrarEliminar;
	private Boolean activo;
	private String usuAltaOee;
	private Date fechaAltaOee;

	public FuncionarioOee() {
	}

	public FuncionarioOee(
			Long idFuncionarioOee, TipoNombramiento tipoNombramiento,
			ConfiguracionUoCab configuracionUo, Persona persona, Date fechaIngreso, String usuAlta,
			Date fechaAlta) {
		this.idFuncionarioOee = idFuncionarioOee;
		this.tipoNombramiento = tipoNombramiento;
		this.configuracionUoCab = configuracionUo;
		this.persona = persona;
		this.fechaIngreso = fechaIngreso;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public FuncionarioOee(
			Long idFuncionarioOee, TipoNombramiento tipoNombramiento, Persona persona,
			Date fechaIngreso, String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idFuncionarioOee = idFuncionarioOee;
		this.tipoNombramiento = tipoNombramiento;
		this.persona = persona;
		this.fechaIngreso = fechaIngreso;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_funcionario_oee", unique = true, nullable = false)
	@GeneratedValue(generator = "FUNCIONARIO_OEE_GENERATOR")
	@SequenceGenerator(name = "FUNCIONARIO_OEE_GENERATOR", sequenceName = "seleccion.funcionario_oee_id_funcionario_oee_seq")
	public Long getIdFuncionarioOee() {
		return this.idFuncionarioOee;
	}

	public void setIdFuncionarioOee(Long idFuncionarioOee) {
		this.idFuncionarioOee = idFuncionarioOee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_nombramiento")
	public TipoNombramiento getTipoNombramiento() {
		return this.tipoNombramiento;
	}

	public void setTipoNombramiento(TipoNombramiento tipoNombramiento) {
		this.tipoNombramiento = tipoNombramiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	@NotNull
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	@NotNull
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	@NotNull
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public String getModalidadOcupacion() {
		return modalidadOcupacion;
	}

	public void setModalidadOcupacion(String modalidadOcupacion) {
		this.modalidadOcupacion = modalidadOcupacion;
	}

	@Transient
	public Boolean getMostrarEliminar() {
		return mostrarEliminar;
	}

	public void setMostrarEliminar(Boolean mostrarEliminar) {
		this.mostrarEliminar = mostrarEliminar;
	}

	@Column(name = "usu_alta_oee", length = 50)
	@Length(max = 50)
	public String getUsuAltaOee() {
		return usuAltaOee;
	}

	public void setUsuAltaOee(String usuAltaOee) {
		this.usuAltaOee = usuAltaOee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta_oee", length = 29)
	public Date getFechaAltaOee() {
		return fechaAltaOee;
	}

	public void setFechaAltaOee(Date fechaAltaOee) {
		this.fechaAltaOee = fechaAltaOee;
	}

}
