package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Properties;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.EntityBase;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * GradoSalarial generated by Generality
 */
@Entity
@Table(name = "grado_salarial", schema = "planificacion")
public class GradoSalarial extends EntityBase  {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3748740127328873095L;
	private Long idGradoSalarial;
	private Integer numero;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Integer montoMinimo;
	private Integer montoMaximo;
	private Integer anho;
	private AgrupamientoCce agrupamientoCce;
	private GradoSalarialCab gradoSalarialCab;

	public GradoSalarial() {
	}

	public GradoSalarial(Long idGradoSalarial) {
		this.idGradoSalarial = idGradoSalarial;
	}

	@Id
	@GeneratedValue(generator="GRADO_SALARIAL_GENERATOR")
	@SequenceGenerator(name="GRADO_SALARIAL_GENERATOR",sequenceName="planificacion.grado_salarial_id_grado_salarial_seq")

	@Column(name = "id_grado_salarial")
	public Long getIdGradoSalarial() {
		return this.idGradoSalarial;
	}

	public void setIdGradoSalarial(Long idGradoSalarial) {
		this.idGradoSalarial = idGradoSalarial;
	}
	

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}
	

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agrupamiento_cce")
		public AgrupamientoCce getAgrupamientoCce() {
		return agrupamientoCce;
	}

	public void setAgrupamientoCce(AgrupamientoCce agrupamientoCce) {
		this.agrupamientoCce = agrupamientoCce;
	}
	
	
	@Column(name = "monto_minimo")
	public Integer getMontoMinimo() {
		return montoMinimo;
	}

	public void setMontoMinimo(Integer montoMinimo) {
		this.montoMinimo = montoMinimo;
	}
	
	@Column(name = "monto_maximo")
	public Integer getMontoMaximo() {
		return montoMaximo;
	}

	public void setMontoMaximo(Integer montoMaximo) {
		this.montoMaximo = montoMaximo;
	}

	@Column(name = "anho")
	public Integer getAnho() {
		return anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grado_salarial_cab")
	public GradoSalarialCab getGradoSalarialCab() {
		return gradoSalarialCab;
	}

	public void setGradoSalarialCab(GradoSalarialCab gradoSalarialCab) {
		this.gradoSalarialCab = gradoSalarialCab;
	}

	@Transient
	public Long getId() {
		return idGradoSalarial;
	}

	


	/**
	 * 
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.GRADO_SALARIAL_ID, getId());
		return properties;
	}

	/**
	 * 
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}
}
