package py.com.excelsis.sicca.entity;

// Generated 03/10/2011 01:58:56 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * GradoSalarialCab generated by hbm2java
 */
@Entity
@Table(name = "grado_salarial_cab", schema = "planificacion")
public class GradoSalarialCab implements java.io.Serializable {

	private Long idGradoSalarialCab;
	private TipoCce tipoCce;
	private Integer anho;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean activo;
	private Set<GradoSalarial> gradoSalarials = new HashSet<GradoSalarial>(0);

	public GradoSalarialCab() {
	}

	public GradoSalarialCab(Long idGradoSalarialCab, TipoCce tipoCce, Integer anho,
			String usuAlta, Date fechaAlta) {
		this.idGradoSalarialCab = idGradoSalarialCab;
		this.tipoCce = tipoCce;
		this.anho = anho;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public GradoSalarialCab(Long idGradoSalarialCab, TipoCce tipoCce, Integer anho,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<GradoSalarial> gradoSalarials) {
		this.idGradoSalarialCab = idGradoSalarialCab;
		this.tipoCce = tipoCce;
		this.anho = anho;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.gradoSalarials = gradoSalarials;
	}

	@Id
	@Column(name = "id_grado_salarial_cab", unique = true, nullable = false)
	@GeneratedValue(generator="GRADO_SALARIAL_CAB_GENERATOR")
	@SequenceGenerator(name="GRADO_SALARIAL_CAB_GENERATOR",sequenceName="planificacion.grado_salarial_cab_id_grado_salarial_cab_seq")

	public Long getIdGradoSalarialCab() {
		return this.idGradoSalarialCab;
	}

	public void setIdGradoSalarialCab(Long idGradoSalarialCab) {
		this.idGradoSalarialCab = idGradoSalarialCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cce", nullable = false)
	@NotNull
	public TipoCce getTipoCce() {
		return this.tipoCce;
	}

	public void setTipoCce(TipoCce tipoCce) {
		this.tipoCce = tipoCce;
	}

	@Column(name = "anho", nullable = false)
	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoSalarialCab")
	public Set<GradoSalarial> getGradoSalarials() {
		return this.gradoSalarials;
	}

	public void setGradoSalarials(Set<GradoSalarial> gradoSalarials) {
		this.gradoSalarials = gradoSalarials;
	}
	
	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	

}
