package py.com.excelsis.sicca.entity;

// Generated 15-nov-2011 10:31:17 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * GrupoConceptoPago generated by hbm2java
 */
@Entity
@Table(name = "grupo_concepto_pago", schema = "seleccion")
public class GrupoConceptoPago implements java.io.Serializable {

	private Long idGrupoConceptoPago;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Integer monto;
	private Integer objCodigo;
	private String categoria;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Integer anho;
	private String tipo;
	private Integer estado;
	private Boolean activo;

	public GrupoConceptoPago() {
	}

	public GrupoConceptoPago(Long idGrupoConceptoPago,
			ConcursoPuestoAgr concursoPuestoAgr, Integer monto, String categoria,
			String usuAlta, Date fechaAlta) {
		this.idGrupoConceptoPago = idGrupoConceptoPago;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.monto = monto;
		this.categoria = categoria;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public GrupoConceptoPago(Long idGrupoConceptoPago,
			ConcursoPuestoAgr concursoPuestoAgr, Integer monto, Integer objCodigo,
			String categoria, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idGrupoConceptoPago = idGrupoConceptoPago;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.monto = monto;
		this.objCodigo = objCodigo;
		this.categoria = categoria;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="GRUPO_CONCEPTO_PAGO_GENERATOR")
	@SequenceGenerator(name="GRUPO_CONCEPTO_PAGO_GENERATOR",sequenceName="seleccion.grupo_concepto_pago_id_grupo_concepto_pago_seq")
	@Column(name = "id_grupo_concepto_pago", unique = true, nullable = false)
	public Long getIdGrupoConceptoPago() {
		return this.idGrupoConceptoPago;
	}

	public void setIdGrupoConceptoPago(Long idGrupoConceptoPago) {
		this.idGrupoConceptoPago = idGrupoConceptoPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr", nullable = false)
	@NotNull
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "monto")
	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

	@Column(name = "obj_codigo")
	public Integer getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(Integer objCodigo) {
		this.objCodigo = objCodigo;
	}

	@Column(name = "categoria", length = 10)
	@Length(max = 10)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "anho")
	public Integer getAnho() {
		return anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	
	

}
