package py.com.excelsis.sicca.entity;

// Generated 12-sep-2012 9:08:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * GruposEvaluacion generated by hbm2java
 */
@Entity
@Table(name = "grupos_evaluacion", schema = "eval_desempeno")
public class GruposEvaluacion implements java.io.Serializable {

	private Long idGruposEvaluacion;
	private ComisionEval comisionEval;
	private EvaluacionDesempeno evaluacionDesempeno;
	private String grupo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String motivoCancelacion;
	private String usuCancelacion;
	private Date fechaCancelacion;
	private Set<GruposSujetos> gruposSujetoses = new HashSet<GruposSujetos>(0);

	public GruposEvaluacion() {
	}

	public GruposEvaluacion(Long idGruposEvaluacion, ComisionEval comisionEval,
			EvaluacionDesempeno evaluacionDesempeno, String grupo,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idGruposEvaluacion = idGruposEvaluacion;
		this.comisionEval = comisionEval;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.grupo = grupo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public GruposEvaluacion(Long idGruposEvaluacion, ComisionEval comisionEval,
			EvaluacionDesempeno evaluacionDesempeno, String grupo,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, String motivoCancelacion, String usuCancelacion,
			Date fechaCancelacion,
			Set<GruposSujetos> gruposSujetoses) {
		this.idGruposEvaluacion = idGruposEvaluacion;
		this.comisionEval = comisionEval;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.grupo = grupo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.motivoCancelacion = motivoCancelacion;
		this.usuCancelacion = usuCancelacion;
		this.fechaCancelacion = fechaCancelacion;
		this.gruposSujetoses = gruposSujetoses;
	}

	@Id
	@GeneratedValue(generator="GRUPOS_EVALUACION_GENERATOR")
	@SequenceGenerator(name="GRUPOS_EVALUACION_GENERATOR",sequenceName="eval_desempeno.grupos_evaluacion_id_grupos_evaluacion_seq")
	@Column(name = "id_grupos_evaluacion", unique = true, nullable = false)
	public Long getIdGruposEvaluacion() {
		return this.idGruposEvaluacion;
	}

	public void setIdGruposEvaluacion(Long idGruposEvaluacion) {
		this.idGruposEvaluacion = idGruposEvaluacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comision_eval", nullable = false)
	@NotNull
	public ComisionEval getComisionEval() {
		return this.comisionEval;
	}

	public void setComisionEval(ComisionEval comisionEval) {
		this.comisionEval = comisionEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno", nullable = false)
	@NotNull
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return this.evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}

	@Column(name = "grupo", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "motivo_cancelacion", length = 1000)
	@Length(max = 1000)
	public String getMotivoCancelacion() {
		return this.motivoCancelacion;
	}

	public void setMotivoCancelacion(String motivoCancelacion) {
		this.motivoCancelacion = motivoCancelacion;
	}

	@Column(name = "usu_cancelacion", length = 50)
	@Length(max = 50)
	public String getUsuCancelacion() {
		return this.usuCancelacion;
	}

	public void setUsuCancelacion(String usuCancelacion) {
		this.usuCancelacion = usuCancelacion;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cancelacion", length = 29)
	public Date getFechaCancelacion() {
		return fechaCancelacion;
	}

	public void setFechaCancelacion(Date fechaCancelacion) {
		this.fechaCancelacion = fechaCancelacion;
	}


	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gruposEvaluacion")
	public Set<GruposSujetos> getGruposSujetoses() {
		return this.gruposSujetoses;
	}

	
	public void setGruposSujetoses(Set<GruposSujetos> gruposSujetoses) {
		this.gruposSujetoses = gruposSujetoses;
	}

}
