package py.com.excelsis.sicca.entity;

// Generated 12-sep-2012 9:08:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Digits;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * GruposSujetos generated by hbm2java
 */
@Entity
@Table(name = "grupos_sujetos", schema = "eval_desempeno")
public class GruposSujetos implements java.io.Serializable {

	private Long idGrupoSujeto;
	private Sujetos sujetos;
	private GruposEvaluacion gruposEvaluacion;
	private Documentos documentos;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean presente;
	private String observacion;
	private Float puntajeFinal;
	private Boolean selected;
	private Set<ResultadoEval> resultadoEvals = new HashSet<ResultadoEval>(0);
	//Agregado; Werner.
	private Float puntajePdec;
	private Float puntajePercepcion;
	
	private String comentarioPercepcion;
	//******************************
	public GruposSujetos() {
	}

	public GruposSujetos(
			Long idGrupoSujeto, Sujetos sujetos, GruposEvaluacion gruposEvaluacion, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idGrupoSujeto = idGrupoSujeto;
		this.sujetos = sujetos;
		this.gruposEvaluacion = gruposEvaluacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;

	}

	public GruposSujetos(
			Long idGrupoSujeto, Sujetos sujetos, GruposEvaluacion gruposEvaluacion, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod, Boolean presente,
			String observacion, Float puntajeFinal, Set<ResultadoEval> resultadoEvals,
			Documentos documentos, Float puntajePdec, Float puntajePercepcion, 
			String comentarioPercepcion) {
		this.idGrupoSujeto = idGrupoSujeto;
		this.sujetos = sujetos;
		this.gruposEvaluacion = gruposEvaluacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.presente = presente;
		this.observacion = observacion;
		this.puntajeFinal = puntajeFinal;
		this.resultadoEvals = resultadoEvals;
		this.documentos = documentos;
		//agregado
		this.puntajePdec = puntajePdec;
		this.puntajePercepcion = puntajePercepcion;
		this.comentarioPercepcion = comentarioPercepcion;
	}

	@Id
	@GeneratedValue(generator = "GRUPOS_SUJETO_GENERATOR")
	@SequenceGenerator(name = "GRUPOS_SUJETO_GENERATOR", sequenceName = "eval_desempeno.grupos_sujetos_id_grupo_sujeto_seq")
	@Column(name = "id_grupo_sujeto", unique = true, nullable = false)
	public Long getIdGrupoSujeto() {
		return this.idGrupoSujeto;
	}

	public void setIdGrupoSujeto(Long idGrupoSujeto) {
		this.idGrupoSujeto = idGrupoSujeto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sujetos", nullable = false)
	@NotNull
	public Sujetos getSujetos() {
		return this.sujetos;
	}

	public void setSujetos(Sujetos sujetos) {
		this.sujetos = sujetos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupos_evaluacion")
	public GruposEvaluacion getGruposEvaluacion() {
		return this.gruposEvaluacion;
	}

	public void setGruposEvaluacion(GruposEvaluacion gruposEvaluacion) {
		this.gruposEvaluacion = gruposEvaluacion;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gruposSujetos")
	public Set<ResultadoEval> getResultadoEvals() {
		return this.resultadoEvals;
	}

	public void setResultadoEvals(Set<ResultadoEval> resultadoEvals) {
		this.resultadoEvals = resultadoEvals;
	}

	@Column(name = "presente")
	public Boolean getPresente() {
		return this.presente;
	}

	public void setPresente(Boolean presente) {
		this.presente = presente;
	}

	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "puntaje_final", precision = 5, scale = 2)
	@Digits(integerDigits=5,fractionalDigits=2)
	public Float getPuntajeFinal() {
		return this.puntajeFinal;
	}

	public void setPuntajeFinal(Float puntajeFinal) {
		this.puntajeFinal = puntajeFinal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	@Transient
	public Boolean getSelected() {
		return selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

	@Column(name = "puntaje_pdec", precision = 5, scale = 2)
	@Digits(integerDigits=5,fractionalDigits=2)
	public Float getPuntajePdec() {
		return puntajePdec;
	}

	public void setPuntajePdec(Float puntajePdec) {
		this.puntajePdec = puntajePdec;
	}

	@Column(name = "puntaje_percepcion", precision = 5, scale = 2)
	@Digits(integerDigits=5,fractionalDigits=2)
	public Float getPuntajePercepcion() {
		return puntajePercepcion;
	}

	public void setPuntajePercepcion(Float puntajePercepcion) {
		this.puntajePercepcion = puntajePercepcion;
	}

	@Column(name = "comentario_percepcion", length = 1000)
	@Length(max = 1000)
	public String getComentarioPercepcion() {
		return comentarioPercepcion;
	}

	public void setComentarioPercepcion(String comentarioPercepcion) {
		this.comentarioPercepcion = comentarioPercepcion;
	}
}
