package py.com.excelsis.sicca.entity;

// Generated 08/11/2012 10:10:53 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * HistoricoRemuneraciones generated by hbm2java
 */
@Entity
@Table(name = "historico_remuneraciones", schema = "remuneracion")
public class HistoricoRemuneraciones implements java.io.Serializable {

	private long idHistoricoRemuneracion;
	private EmpleadoPuesto empleadoPuesto;
	private ConfiguracionUoCab configuracionUo;
	private Integer objCodigo;
	private String categoria;
	private Integer anho;
	private Integer mes;
	private Integer presupuestado;
	private Integer devengado;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String descripCategoria;
	private Integer linea;
	private String descripConcepto;
	private Integer fuenteFinanciamiento;
	private String movimiento;
	private String lugar;
	private String cargaHoraria;
	private Integer remuneracionTotal;


	public HistoricoRemuneraciones() {
	}

	public HistoricoRemuneraciones(long idHistoricoRemuneracion,
			EmpleadoPuesto empleadoPuesto, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idHistoricoRemuneracion = idHistoricoRemuneracion;
		this.empleadoPuesto = empleadoPuesto;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public HistoricoRemuneraciones(long idHistoricoRemuneracion,
			EmpleadoPuesto empleadoPuesto, Integer objCodigo, String categoria,
			Integer anho, Integer mes, Integer presupuestado,
			Integer devengado, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod, String descripCategoria,
			Integer linea, String descripConcepto, String movimiento,
			String lugar, String cargaHoraria, Integer remuneracionTotal) {
		
		this.idHistoricoRemuneracion = idHistoricoRemuneracion;
		this.empleadoPuesto = empleadoPuesto;
		this.objCodigo = objCodigo;
		this.categoria = categoria;
		this.anho = anho;
		this.mes = mes;
		this.presupuestado = presupuestado;
		this.devengado = devengado;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.descripCategoria = descripCategoria;
		this.linea = linea;
		this.descripConcepto = descripConcepto;
		this.movimiento = movimiento;
		this.lugar = lugar;
		this.cargaHoraria = cargaHoraria;
		this.remuneracionTotal = remuneracionTotal;
	}

	@Id
	@Column(name = "id_historico_remuneracion", unique = true, nullable = false)
	@GeneratedValue(generator="HISTORICO_REMUNERACION_GENERATOR")
	@SequenceGenerator(name="HISTORICO_REMUNERACION_GENERATOR",sequenceName="remuneracion.historico_remuneraciones_id_remuneracion_seq")
	public long getIdHistoricoRemuneracion() {
		return this.idHistoricoRemuneracion;
	}

	public void setIdHistoricoRemuneracion(long idHistoricoRemuneracion) {
		this.idHistoricoRemuneracion = idHistoricoRemuneracion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto")
	public EmpleadoPuesto getEmpleadoPuesto() {
		return this.empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUo() {
		return configuracionUo;
	}

	public void setConfiguracionUo(ConfiguracionUoCab configuracionUo) {
		this.configuracionUo = configuracionUo;
	}

	@Column(name = "obj_codigo")
	public Integer getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(Integer objCodigo) {
		this.objCodigo = objCodigo;
	}

	@Column(name = "categoria", length = 10)
	@Length(max = 10)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "anho")
	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "presupuestado")
	public Integer getPresupuestado() {
		return this.presupuestado;
	}

	public void setPresupuestado(Integer presupuestado) {
		this.presupuestado = presupuestado;
	}

	@Column(name = "devengado")
	public Integer getDevengado() {
		return this.devengado;
	}

	public void setDevengado(Integer devengado) {
		this.devengado = devengado;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "descrip_categoria", length = 200)
	@Length(max = 200)
	public String getDescripCategoria() {
		return this.descripCategoria;
	}

	public void setDescripCategoria(String descripCategoria) {
		this.descripCategoria = descripCategoria;
	}

	@Column(name = "linea")
	public Integer getLinea() {
		return this.linea;
	}

	public void setLinea(Integer linea) {
		this.linea = linea;
	}

	@Column(name = "descrip_concepto", length = 200)
	@Length(max = 200)
	public String getDescripConcepto() {
		return this.descripConcepto;
	}

	public void setDescripConcepto(String descripConcepto) {
		this.descripConcepto = descripConcepto;
	}

	@Column(name = "fuente_financiamiento")
	public Integer getFuenteFinanciamiento() {
		return this.fuenteFinanciamiento;
	}

	public void setFuenteFinanciamiento(Integer fuenteFinanciamiento) {
		this.fuenteFinanciamiento = fuenteFinanciamiento;
	}
	
	@Column(name = "remuneracion_total")
	public Integer getRemuneracionTotal() {
		return this.remuneracionTotal;
	}

	public void setRemuneracionTotal(Integer remuneracionTotal) {
		this.remuneracionTotal = remuneracionTotal;
	}
	
	@Column(name = "movimiento", length = 2)
	@Length(max = 2)
	public String getMovimiento() {
		return movimiento;
	}

	public void setMovimiento(String movimiento) {
		this.movimiento = movimiento;
	}
	
	@Column(name = "lugar", length = 125)
	@Length(max = 125)
	public String getLugar() {
		return lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}
	
	@Column(name = "carga_horaria")
	public String getCargaHoraria() {
		return cargaHoraria;
	}

	public void setCargaHoraria(String cargaHoraria) {
		this.cargaHoraria = cargaHoraria;
	}
}
