package py.com.excelsis.sicca.entity;

// Generated 08/10/2012 03:22:03 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * HistorialExcepcion generated by hbm2java
 */
@Entity
@Table(name = "historial_excepcion", schema = "seleccion")
public class HistorialExcepcion implements java.io.Serializable {

	private Long idHistorialExcepcion;
	private ConcursoPuestoAgr concursoGrupoAgr;
	private Excepcion excepcion;
	private String observacion;
	private String estado;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public HistorialExcepcion() {
	}

	public HistorialExcepcion(Long idHistorialExcepcion,
			ConcursoPuestoAgr idConcursoGrupoAgr, Excepcion idExcepcion, String usuAlta,
			Date fechaAlta) {
		this.idHistorialExcepcion = idHistorialExcepcion;
		this.concursoGrupoAgr = idConcursoGrupoAgr;
		this.excepcion = idExcepcion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public HistorialExcepcion(Long idHistorialExcepcion,
			ConcursoPuestoAgr idConcursoGrupoAgr, Excepcion idExcepcion, String observacion,
			String estado, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idHistorialExcepcion = idHistorialExcepcion;
		this.concursoGrupoAgr = idConcursoGrupoAgr;
		this.excepcion = idExcepcion;
		this.observacion = observacion;
		this.estado = estado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_historial_excepcion", nullable = false)
	@GeneratedValue(generator = "HISTORIAL_EXCEPCION_GENERATOR")
	@SequenceGenerator(name = "HISTORIAL_EXCEPCION_GENERATOR", sequenceName = "seleccion.historial_excepcion_id_historial_excepcion_seq")
	public Long getIdHistorialExcepcion() {
		return this.idHistorialExcepcion;
	}

	public void setIdHistorialExcepcion(Long idHistorialExcepcion) {
		this.idHistorialExcepcion = idHistorialExcepcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_grupo_agr", nullable = false)
	public ConcursoPuestoAgr getConcursoGrupoAgr() {
		return concursoGrupoAgr;
	}

	public void setConcursoGrupoAgr(ConcursoPuestoAgr concursoGrupoAgr) {
		this.concursoGrupoAgr = concursoGrupoAgr;
	}

	

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_excepcion", nullable = false)
	public Excepcion getExcepcion() {
		return excepcion;
	}

	public void setExcepcion(Excepcion excepcion) {
		this.excepcion = excepcion;
	}

	
	

	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "estado", length = 30)
	@Length(max = 30)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
