package py.com.excelsis.sicca.entity;

// Generated 11/12/2012 11:34:58 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * HistoricoMovilidad generated by hbm2java
 */
@Entity
@Table(name = "historico_movilidad", schema = "movilidad")
public class HistoricoMovilidad implements java.io.Serializable {

	private Long idSolicitudTrasladoCab;
	private String codActividad;
	private String actividad;
	private Date fechaCreacion;
	private String usuarioInicio;
	private Date fechaInicio;
	private String usuarioFin;
	private Date fechaFin;
	private Long id;

	public HistoricoMovilidad() {
	}

	public HistoricoMovilidad(Long idSolicitudTrasladoCab,
			String codActividad, String actividad, Date fechaCreacion,
			String usuarioInicio, Date fechaInicio, String usuarioFin,
			Date fechaFin) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
		this.codActividad = codActividad;
		this.actividad = actividad;
		this.fechaCreacion = fechaCreacion;
		this.usuarioInicio = usuarioInicio;
		this.fechaInicio = fechaInicio;
		this.usuarioFin = usuarioFin;
		this.fechaFin = fechaFin;
	}

	
	@Id
	@Column(name = "id")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "id_solicitud_traslado_cab")
	public Long getIdSolicitudTrasladoCab() {
		return this.idSolicitudTrasladoCab;
	}

	public void setIdSolicitudTrasladoCab(Long idSolicitudTrasladoCab) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
	}

	@Column(name = "cod_actividad", length = 50)
	@Length(max = 50)
	public String getCodActividad() {
		return this.codActividad;
	}

	public void setCodActividad(String codActividad) {
		this.codActividad = codActividad;
	}

	@Column(name = "actividad", length = 200)
	@Length(max = 200)
	public String getActividad() {
		return this.actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "usuario_inicio")
	public String getUsuarioInicio() {
		return this.usuarioInicio;
	}

	public void setUsuarioInicio(String usuarioInicio) {
		this.usuarioInicio = usuarioInicio;
	}

	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "usuario_fin")
	public String getUsuarioFin() {
		return this.usuarioFin;
	}

	public void setUsuarioFin(String usuarioFin) {
		this.usuarioFin = usuarioFin;
	}

	@Column(name = "fecha_fin", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}


}
