package py.com.excelsis.sicca.entity;

// Generated 05/11/2012 03:13:42 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Remuneraciones generated by hbm2java
 */
@Entity
@Table(name = "historico_remuneraciones_tmp", schema = "remuneracion")
public class HistoricoRemuneracionesTmp implements java.io.Serializable {

	private Long idHistoricoRemuneracion;
	private Integer anho;
	private Integer mes;
	private Integer nivel;
	private Integer entidad;
	private Integer oee;
	private Integer linea;
	private String documentoIdentidad;
	private String nombres;
    private String apellidos;
    private String estado;
    private Integer remuneracionTotal;
	private Integer objCodigo;
	private Integer fuenteFinanciamiento;
    private String categoria;
    private Integer presupuestado;
    private Integer devengado;
    private String concepto;
    private String movimiento;
    private String lugar;
    private String cargo;
    private String funcionCumplida;
    private String cargaHoraria;
    private boolean discapacidad;
    private Integer tipoDiscapacidad;
    private Integer anhoIngreso;
    private boolean activo;
    private String usuAlta;
    private Date fechaAlta;
    private String usuMod;
    private Date fechaMod;
    private String usuPasoHistorico;
    private Date fechaPasoHistorico;
    private ConfiguracionUoCab configuracionUoCab;
    private Persona persona;

	public HistoricoRemuneracionesTmp() {
	}

	public HistoricoRemuneracionesTmp(Long idHistoricoRemuneracion, Integer anho, Integer mes, Integer nivel, Integer entidad, Integer oee,
			Integer linea, String documentoIdentidad, String nombres, String apellidos, String estado, Integer remuneracionTotal, 
			Integer objCodigo, Integer fuenteFinanciamiento, String categoria, Integer presupuestado, Integer devengado, 
			String concepto, String movimiento, String lugar, String cargo, String funcionCumplida, String cargaHoraria, 
			boolean discapacidad, Integer tipoDiscapacidad, Integer anhoIngreso, ConfiguracionUoCab configuracionUoCab, Persona persona,
			String usuPasoHistorico, Date fechaPasoHistorico) {
		
		this.idHistoricoRemuneracion = idHistoricoRemuneracion;
		this.anho = anho;
		this.mes = mes;
		this.nivel = nivel;
		this.entidad = entidad;
		this.oee = oee;
		this.linea = linea;
		this.documentoIdentidad = documentoIdentidad;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.estado = estado;
		this.remuneracionTotal = remuneracionTotal;
		this.objCodigo = objCodigo;
		this.fuenteFinanciamiento = fuenteFinanciamiento;
		this.categoria = categoria;
		this.presupuestado = presupuestado;
		this.devengado = devengado;
		this.concepto = concepto;
		this.movimiento = movimiento;
		this.lugar = lugar;
		this.cargo = cargo;
		this.funcionCumplida = funcionCumplida;
		this.cargaHoraria = cargaHoraria;
		this.discapacidad = discapacidad;
		this.tipoDiscapacidad = tipoDiscapacidad;
		this.anhoIngreso = anhoIngreso;
		this.configuracionUoCab = configuracionUoCab;
		this.persona = persona;
		this.usuPasoHistorico = usuPasoHistorico;
		this.fechaPasoHistorico = fechaPasoHistorico;
	}

	@Id
	@Column(name = "id_historico_remuneracion_tmp", unique = true, nullable = false)
	@GeneratedValue(generator="HISTORICO_REMUNERACION_TMP_GENERATOR")
	@SequenceGenerator(name="HISTORICO_REMUNERACION_TMP_GENERATOR",sequenceName="remuneracion.historico_remuneraciones_tmp_id_historico_remuneracion_tmp_seq")
	public Long getIdHistoricoRemuneracion() {
		return this.idHistoricoRemuneracion;
	}

	public void setIdHistoricoRemuneracion(Long idHistoricoRemuneracion) {
		this.idHistoricoRemuneracion = idHistoricoRemuneracion;
	}
	
	@Column(name = "anho")
	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}
	
	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}
	
	@Column(name = "nivel")
	public Integer getNivel() {
		return nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
	
	@Column(name = "entidad")
	public Integer getEntidad() {
		return entidad;
	}

	public void setEntidad(Integer entidad) {
		this.entidad = entidad;
	}
	
	@Column(name = "oee")
	public Integer getOee() {
		return oee;
	}

	public void setOee(Integer oee) {
		this.oee = oee;
	}
	
	@Column(name = "linea")
	public Integer getLinea() {
		return this.linea;
	}

	public void setLinea(Integer linea) {
		this.linea = linea;
	}
	
	@Column(name = "documento_identidad", length = 30)
	@Length(max = 30)
	public String getDocumentoIdentidad() {
		return documentoIdentidad;
	}

	public void setDocumentoIdentidad(String documentoIdentidad) {
		this.documentoIdentidad = documentoIdentidad;
	}
	
	@Column(name = "nombres", length = 50)
	@Length(max = 50)
	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", length = 50)
	@Length(max = 50)
	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}
	
	@Column(name = "estado", length = 12)
	@Length(max = 12)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	@Column(name = "remuneracion_total")
	public Integer getRemuneracionTotal() {
		return this.remuneracionTotal;
	}

	public void setRemuneracionTotal(Integer remuneracionTotal) {
		this.remuneracionTotal = remuneracionTotal;
	}

	@Column(name = "obj_codigo")
	public Integer getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(Integer objCodigo) {
		this.objCodigo = objCodigo;
	}
	
	@Column(name = "fuente_financiamiento")
	public Integer getFuenteFinanciamiento() {
		return this.fuenteFinanciamiento;
	}

	public void setFuenteFinanciamiento(Integer fuenteFinanciamiento) {
		this.fuenteFinanciamiento = fuenteFinanciamiento;
	}

	@Column(name = "categoria", length = 10)
	@Length(max = 10)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "presupuestado")
	public Integer getPresupuestado() {
		return this.presupuestado;
	}

	public void setPresupuestado(Integer presupuestado) {
		this.presupuestado = presupuestado;
	}

	@Column(name = "devengado")
	public Integer getDevengado() {
		return this.devengado;
	}

	public void setDevengado(Integer devengado) {
		this.devengado = devengado;
	}

	@Column(name = "concepto", length = 200)
	@Length(max = 200)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}
	
	@Column(name = "movimiento", length = 3)
	@Length(max = 3)
	public String getMovimiento() {
		return movimiento;
	}

	public void setMovimiento(String movimiento) {
		this.movimiento = movimiento;
	}
	
	@Column(name = "lugar", length = 125)
	@Length(max = 125)
	public String getLugar() {
		return lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}
	
	@Column(name = "cargo", length = 250)
	@Length(max = 250)
	public String getCargo() {
		return cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}
	
	@Column(name = "funcion_cumplida", length = 500)
	@Length(max = 500)
	public String getFuncionCumplida() {
		return funcionCumplida;
	}

	public void setFuncionCumplida(String funcionCumplida) {
		this.funcionCumplida = funcionCumplida;
	}
	
	@Column(name = "carga_horaria")
	public String getCargaHoraria() {
		return cargaHoraria;
	}

	public void setCargaHoraria(String cargaHoraria) {
		this.cargaHoraria = cargaHoraria;
	}
	
	@Column(name = "discapacidad")
	public boolean getDiscapacidad() {
		return discapacidad;
	}

	public void setDiscapacidad(boolean discapacidad) {
		this.discapacidad = discapacidad;
	}
	
	@Column(name = "tipo_discapacidad")
	public Integer getTipoDiscapacidad() {
		return tipoDiscapacidad;
	}

	public void setTipoDiscapacidad(Integer tipoDiscapacidad) {
		this.tipoDiscapacidad = tipoDiscapacidad;
	}
	
	@Column(name = "anho_ingreso")
	public Integer getAnhoIngreso() {
		return anhoIngreso;
	}

	public void setAnhoIngreso(Integer anhoIngreso) {
		this.anhoIngreso = anhoIngreso;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona () {
		return this.persona ;
	}

	public void setPersona (Persona persona) {
		this.persona  = persona;
	}
	
	@Column(name = "usu_paso_historico", length = 50)
	@Length(max = 50)
	public String getUsuPasoHistorico() {
		return this.usuPasoHistorico;
	}

	public void setUsuPasoHistorico(String usuPasoHistorico) {
		this.usuPasoHistorico = usuPasoHistorico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_paso_historico", length = 29)
	public Date getFechaPasoHistorico() {
		return this.fechaPasoHistorico;
	}

	public void setFechaPasoHistorico(Date fechaPasoHistorico) {
		this.fechaPasoHistorico = fechaPasoHistorico;
	}
}
