package py.com.excelsis.sicca.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.hibernate.validator.Length;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
* HistorialActividadesGrupo generated by hbm2java
*/
@Entity
@Table(name = "historial_actividades_grupo", schema = "seleccion")
public class HistorialActividadesGrupo implements java.io.Serializable {

	private Long id;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private String descripcionGrupo;
	private String descripcion;
	private Date fechaCreacion;
	private String usuarioInicio;
	private Date fechaInicio;
	private String usuarioFin;
	private Date fechaFin;
	private String observacion;
	private String codActividad;

	public HistorialActividadesGrupo() {
		
	}

	
	@Id 
	@Column(name = "id_", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "descripcion_grupo", length = 100)
	@Length(max = 100)
	public String getDescripcionGrupo() {
		return this.descripcionGrupo;
	}

	public void setDescripcionGrupo(String descripcionGrupo) {
		this.descripcionGrupo = descripcionGrupo;
	}

	@Column(name = "descripcion", length = 200)
	@Length(max = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "usuario_inicio")
	public String getUsuarioInicio() {
		return this.usuarioInicio;
	}

	public void setUsuarioInicio(String usuarioInicio) {
		this.usuarioInicio = usuarioInicio;
	}

	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "usuario_fin")
	public String getUsuarioFin() {
		return this.usuarioFin;
	}

	public void setUsuarioFin(String usuarioFin) {
		this.usuarioFin = usuarioFin;
	}

	@Column(name = "fecha_fin", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	
	@Column(name = "cod_actividad")
	public String getCodActividad() {
		return codActividad;
	}
	public void setCodActividad(String codActividad) {
		this.codActividad = codActividad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistorialActividadesGrupo))
			return false;
		HistorialActividadesGrupo castOther = (HistorialActividadesGrupo) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getDescripcionGrupo() == castOther
						.getDescripcionGrupo()) || (this.getDescripcionGrupo() != null
						&& castOther.getDescripcionGrupo() != null && this
						.getDescripcionGrupo().equals(
								castOther.getDescripcionGrupo())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getFechaCreacion() == castOther.getFechaCreacion()) || (this
						.getFechaCreacion() != null
						&& castOther.getFechaCreacion() != null && this
						.getFechaCreacion()
						.equals(castOther.getFechaCreacion())))
				&& ((this.getUsuarioInicio() == castOther.getUsuarioInicio()) || (this
						.getUsuarioInicio() != null
						&& castOther.getUsuarioInicio() != null && this
						.getUsuarioInicio()
						.equals(castOther.getUsuarioInicio())))
				&& ((this.getFechaInicio() == castOther.getFechaInicio()) || (this
						.getFechaInicio() != null
						&& castOther.getFechaInicio() != null && this
						.getFechaInicio().equals(castOther.getFechaInicio())))
				&& ((this.getUsuarioFin() == castOther.getUsuarioFin()) || (this
						.getUsuarioFin() != null
						&& castOther.getUsuarioFin() != null && this
						.getUsuarioFin().equals(castOther.getUsuarioFin())))
				&& ((this.getFechaFin() == castOther.getFechaFin()) || (this
						.getFechaFin() != null
						&& castOther.getFechaFin() != null && this
						.getFechaFin().equals(castOther.getFechaFin())))
				&& ((this.getObservacion() == castOther.getObservacion()) || (this
						.getObservacion() != null
						&& castOther.getObservacion() != null && this
						.getObservacion().equals(castOther.getObservacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		result = 37
				* result
				+ (getDescripcionGrupo() == null ? 0 : this
						.getDescripcionGrupo().hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		result = 37
				* result
				+ (getFechaCreacion() == null ? 0 : this.getFechaCreacion()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioInicio() == null ? 0 : this.getUsuarioInicio()
						.hashCode());
		result = 37
				* result
				+ (getFechaInicio() == null ? 0 : this.getFechaInicio()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioFin() == null ? 0 : this.getUsuarioFin()
						.hashCode());
		result = 37 * result
				+ (getFechaFin() == null ? 0 : this.getFechaFin().hashCode());
		result = 37
				* result
				+ (getObservacion() == null ? 0 : this.getObservacion()
						.hashCode());
		return result;
	}

}

