package py.com.excelsis.sicca.entity;
// Generated 15-nov-2011 13:36:58 by Hibernate Tools 3.4.0.Beta1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * HomologacionPerfilMatrizDet generated by hbm2java
 */
@Entity
@Table(name="homologacion_perfil_matriz_det",schema="seleccion")
public class HomologacionPerfilMatrizDet  implements java.io.Serializable {


     private Long idHomologacionDet;
     private HomologacionPerfilMatriz homologacionPerfilMatriz;
     private Integer nroObs;
     private String observacion;
     private String usuObs;
     private Date fechaObs;
     private Boolean aceptaSfp;
     private Integer nroRpta;
     private String respuesta;
     private String usuRpta;
     private Date fechaRpta;
     private Boolean ajusteEnviado;
     private Boolean ajustadoOee;
     private String usuAlta;
     private Date fechaAlta;
     private String usuMod;
     private Date fechaMod;
     private Boolean activo;
     private Boolean firmaResolucion;

    public HomologacionPerfilMatrizDet() {
    }


    @Id
	@Column(name = "id_homologacion_det", unique = true, nullable = false)
	@GeneratedValue(generator="HOMOLOGACION_DET_GENERATOR")
	@SequenceGenerator(name="HOMOLOGACION_DET_GENERATOR", sequenceName="seleccion.homologacion_perfil_matriz_det_id_homologacion_det_seq")
    public Long getIdHomologacionDet() {
        return this.idHomologacionDet;
    }
    
    public void setIdHomologacionDet(Long idHomologacionDet) {
        this.idHomologacionDet = idHomologacionDet;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_homologacion", nullable=false)
    @NotNull
    public HomologacionPerfilMatriz getHomologacionPerfilMatriz() {
        return this.homologacionPerfilMatriz;
    }
    
    public void setHomologacionPerfilMatriz(HomologacionPerfilMatriz homologacionPerfilMatriz) {
        this.homologacionPerfilMatriz = homologacionPerfilMatriz;
    }

    
    @Column(name="nro_obs", nullable=false)
    public Integer getNroObs() {
        return this.nroObs;
    }
    
    public void setNroObs(Integer nroObs) {
        this.nroObs = nroObs;
    }

    
    @Column(name="observacion", nullable=false, length=1000)
    @NotNull
    @Length(max=1000)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="usu_obs", nullable=false, length=50)
    @NotNull
    @Length(max=50)
    public String getUsuObs() {
        return this.usuObs;
    }
    
    public void setUsuObs(String usuObs) {
        this.usuObs = usuObs;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_obs", nullable=false, length=29)
    @NotNull
    public Date getFechaObs() {
        return this.fechaObs;
    }
    
    public void setFechaObs(Date fechaObs) {
        this.fechaObs = fechaObs;
    }

    
    @Column(name="acepta_sfp")
    public Boolean getAceptaSfp() {
        return this.aceptaSfp;
    }
    
    public void setAceptaSfp(Boolean aceptaSfp) {
        this.aceptaSfp = aceptaSfp;
    }

    
    @Column(name="nro_rpta")
    public Integer getNroRpta() {
        return this.nroRpta;
    }
    
    public void setNroRpta(Integer nroRpta) {
        this.nroRpta = nroRpta;
    }

    
    @Column(name="respuesta", length=1000)
    @Length(max=1000)
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    
    @Column(name="usu_rpta", length=50)
    @Length(max=50)
    public String getUsuRpta() {
        return this.usuRpta;
    }
    
    public void setUsuRpta(String usuRpta) {
        this.usuRpta = usuRpta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_rpta", length=29)
    public Date getFechaRpta() {
        return this.fechaRpta;
    }
    
    public void setFechaRpta(Date fechaRpta) {
        this.fechaRpta = fechaRpta;
    }

  
    @Column(name="ajuste_enviado", nullable=false)
    public Boolean getAjusteEnviado() {
		return ajusteEnviado;
	}


	public void setAjusteEnviado(Boolean ajusteEnviado) {
		this.ajusteEnviado = ajusteEnviado;
	}

	@Column(name="ajustado_oee", nullable=false) 
    public Boolean getAjustadoOee() {
		return ajustadoOee;
	}


	public void setAjustadoOee(Boolean ajustadoOee) {
		this.ajustadoOee = ajustadoOee;
	}

	@Column(name="activo", nullable=false)
	public Boolean getActivo() {
		return activo;
	}


	public void setActivo(Boolean activo) {
		this.activo = activo;
	}


	@Column(name="usu_alta", nullable=false, length=50)
    @NotNull
    @Length(max=50)
    public String getUsuAlta() {
        return this.usuAlta;
    }
    
    public void setUsuAlta(String usuAlta) {
        this.usuAlta = usuAlta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_alta", nullable=false, length=29)
    @NotNull
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    
    @Column(name="usu_mod", length=50)
    @Length(max=50)
    public String getUsuMod() {
        return this.usuMod;
    }
    
    public void setUsuMod(String usuMod) {
        this.usuMod = usuMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_mod", length=29)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

	@Column(name="firma_resolucion", nullable=true)
	public Boolean getFirmaResolucion() {
		return firmaResolucion;
	}


	public void setFirmaResolucion(Boolean firmaResolucion) {
		this.firmaResolucion = firmaResolucion;
	}


}


