package py.com.excelsis.sicca.entity;

// Generated 15-nov-2011 13:36:58 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * HomologacionPerfilMatriz generated by hbm2java
 */
@Entity
@Table(name = "homologacion_perfil_matriz", schema = "seleccion")
public class HomologacionPerfilMatriz implements java.io.Serializable {

	private Long idHomologacion;
	private Cpt cpt;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private ConfiguracionUoCab configuracionUoCab;
	private Integer numero;
	private Integer anio;
	private String estado;
	private Date fechaPresentacion;
	private String usuAlta;
	private Date fechaAlta;
	private Date fechaVencimiento;
	private String usuMod;
	private Date fechaMod;
	private String usuHomolog;
	private Date fechaHomolog;
	private String objetivo;
	private String denominacion;
	private String mision;
	private String contacto;
	private String lugar;
	private String postHabilitados;
	private Date fechaLimite;
	private String condLaborales;
	private String otrasInf;
	private String remuneracion;
	private String modalidad;
	private String misionEspecifica;
	private String documentos;
	private String horario;
	private Boolean activo;
	private String tipo;

	private String fuenteFinanciacion;
	private String otrosBeneficios;
	private String postNoHabilitados;

	private Set<HomologacionPerfilMatrizDet> homologacionPerfilMatrizDets =
		new HashSet<HomologacionPerfilMatrizDet>(0);

	public HomologacionPerfilMatriz() {
	}

	@Id
	@Column(name = "id_homologacion", unique = true, nullable = false)
	@GeneratedValue(generator = "HOMOLOGACION_GENERATOR")
	@SequenceGenerator(name = "HOMOLOGACION_GENERATOR", sequenceName = "seleccion.homologacion_perfil_matriz_id_homologacion_seq")
	public Long getIdHomologacion() {
		return this.idHomologacion;
	}

	public void setIdHomologacion(Long idHomologacion) {
		this.idHomologacion = idHomologacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cpt", nullable = false)
	@NotNull
	public Cpt getCpt() {
		return this.cpt;
	}

	public void setCpt(Cpt cpt) {
		this.cpt = cpt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "estado", length = 50)
	@Length(max = 50)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_presentacion", length = 29)
	public Date getFechaPresentacion() {
		return this.fechaPresentacion;
	}

	public void setFechaPresentacion(Date fechaPresentacion) {
		this.fechaPresentacion = fechaPresentacion;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_vencimiento", length = 29)
	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "usu_homolog", length = 50)
	@Length(max = 50)
	public String getUsuHomolog() {
		return this.usuHomolog;
	}

	public void setUsuHomolog(String usuHomolog) {
		this.usuHomolog = usuHomolog;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_homolog", length = 29)
	public Date getFechaHomolog() {
		return this.fechaHomolog;
	}

	public void setFechaHomolog(Date fechaHomolog) {
		this.fechaHomolog = fechaHomolog;
	}

	@Column(name = "objetivo", length = 500)
	@Length(max = 500)
	public String getObjetivo() {
		return this.objetivo;
	}

	public void setObjetivo(String objetivo) {
		this.objetivo = objetivo;
	}

	@Column(name = "denominacion", length = 200)
	@Length(max = 200)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "mision", length = 500)
	@Length(max = 500)
	public String getMision() {
		return this.mision;
	}

	public void setMision(String mision) {
		this.mision = mision;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "homologacionPerfilMatriz")
	public Set<HomologacionPerfilMatrizDet> getHomologacionPerfilMatrizDets() {
		return this.homologacionPerfilMatrizDets;
	}

	public void setHomologacionPerfilMatrizDets(Set<HomologacionPerfilMatrizDet> homologacionPerfilMatrizDets) {
		this.homologacionPerfilMatrizDets = homologacionPerfilMatrizDets;
	}

	@Column(name = "contacto", length = 500)
	@Length(max = 500)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "lugar", length = 500)
	@Length(max = 500)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "post_habilitados", length = 500)
	@Length(max = 500)
	public String getPostHabilitados() {
		return this.postHabilitados;
	}

	public void setPostHabilitados(String postHabilitados) {
		this.postHabilitados = postHabilitados;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_limite", length = 13)
	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	@Column(name = "cond_laborales", length = 500)
	@Length(max = 500)
	public String getCondLaborales() {
		return this.condLaborales;
	}

	public void setCondLaborales(String condLaborales) {
		this.condLaborales = condLaborales;
	}

	@Column(name = "otras_inf", length = 500)
	@Length(max = 500)
	public String getOtrasInf() {
		return this.otrasInf;
	}

	public void setOtrasInf(String otrasInf) {
		this.otrasInf = otrasInf;
	}

	@Column(name = "remuneracion", length = 5000)
	@Length(max = 5000)
	public String getRemuneracion() {
		return this.remuneracion;
	}

	public void setRemuneracion(String remuneracion) {
		this.remuneracion = remuneracion;
	}

	@Column(name = "modalidad", length = 50)
	@Length(max = 50)
	public String getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(String modalidad) {
		this.modalidad = modalidad;
	}

	@Column(name = "mision_especifica", length = 500)
	@Length(max = 500)
	public String getMisionEspecifica() {
		return this.misionEspecifica;
	}

	public void setMisionEspecifica(String misionEspecifica) {
		this.misionEspecifica = misionEspecifica;
	}

	@Column(name = "documentos", length = 500)
	@Length(max = 500)
	public String getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(String documentos) {
		this.documentos = documentos;
	}

	@Column(name = "horario", length = 250)
	@Length(max = 250)
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "fuente_financiacion", length = 150)
	@Length(max = 150)
	public String getFuenteFinanciacion() {
		return fuenteFinanciacion;
	}

	public void setFuenteFinanciacion(String fuenteFinanciacion) {
		this.fuenteFinanciacion = fuenteFinanciacion;
	}

	@Column(name = "otros_beneficios", length = 500)
	@Length(max = 500)
	public String getOtrosBeneficios() {
		return otrosBeneficios;
	}

	public void setOtrosBeneficios(String otrosBeneficios) {
		this.otrosBeneficios = otrosBeneficios;
	}

	@Column(name = "post_no_habilitados", length = 500)
	@Length(max = 500)
	public String getPostNoHabilitados() {
		return postNoHabilitados;
	}

	public void setPostNoHabilitados(String postNoHabilitados) {
		this.postNoHabilitados = postNoHabilitados;
	}

	@Column(name = "tipo", length = 10)
	@Length(max = 10)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
