package py.com.excelsis.sicca.entity;

// Generated 24/10/2011 03:08:10 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * IdiomasPersona generated by hbm2java
 */
@Entity
@Table(name = "idiomas_persona", schema = "legajo")
public class IdiomasLegajoPersona implements java.io.Serializable {

	private Long idIdiomaPersona;
	private DatosEspecificos datosEspecificos;
	private String habla;
	private String escribe;
	private String lee;
	private Persona persona;
	private String usuAlta;
	private Date fechaAlta;
	private boolean activo;
	private PersonaPostulante personaPostulante;
	private String tipo;
	private String usuAltaOee;
	private Date fechaAltaOee;
	private String usuModOee;
	private Date fechaModOee;

	public IdiomasLegajoPersona() {
	}

	public IdiomasLegajoPersona(Long idIdiomaPersona,
			DatosEspecificos datosEspecificos, String habla, String escribe,
			String lee, Persona idPersona, String usuAlta, Date fechaAlta) {
		this.idIdiomaPersona = idIdiomaPersona;
		this.datosEspecificos = datosEspecificos;
		this.habla = habla;
		this.escribe = escribe;
		this.lee = lee;
		this.persona = idPersona;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	@Id
	@Column(name = "id_idioma_legajo_persona", unique = true, nullable = false)
	@GeneratedValue(generator="IDIOMA_LEGAJOPERSONA_GENERATOR")
	@SequenceGenerator(name="IDIOMA_LEGAJOPERSONA_GENERATOR",sequenceName="legajo.idiomas_persona_id_idioma_legajo_persona_seq")
	public Long getIdIdiomaPersona() {
		return this.idIdiomaPersona;
	}

	public void setIdIdiomaPersona(Long idIdiomaPersona) {
		this.idIdiomaPersona = idIdiomaPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_idioma", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@Column(name = "habla", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getHabla() {
		return this.habla;
	}

	public void setHabla(String habla) {
		this.habla = habla;
	}

	@Column(name = "escribe", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getEscribe() {
		return this.escribe;
	}

	public void setEscribe(String escribe) {
		this.escribe = escribe;
	}

	@Column(name = "lee", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getLee() {
		return this.lee;
	}

	public void setLee(String lee) {
		this.lee = lee;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}



	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_postulante")
	public PersonaPostulante getPersonaPostulante() {
		return personaPostulante;
	}

	public void setPersonaPostulante(PersonaPostulante personaPostulante) {
		this.personaPostulante = personaPostulante;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "usu_alta_oee")
	public String getUsuAltaOee() {
		return usuAltaOee;
	}

	public void setUsuAltaOee(String usuAltaOee) {
		this.usuAltaOee = usuAltaOee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta_oee", length = 29)
	public Date getFechaAltaOee() {
		return fechaAltaOee;
	}

	public void setFechaAltaOee(Date fechaAltaOee) {
		this.fechaAltaOee = fechaAltaOee;
	}


	@Column(name = "usu_mod_oee")
	public String getUsuModOee() {
		return usuModOee;
	}

	public void setUsuModOee(String usuModOee) {
		this.usuModOee = usuModOee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod_oee", length = 29)
	public Date getFechaModOee() {
		return fechaModOee;
	}

	public void setFechaModOee(Date fechaModOee) {
		this.fechaModOee = fechaModOee;
	}
	
	

}
