package py.com.excelsis.sicca.entity;

// Generated 29/05/2012 10:38:34 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Instructores generated by hbm2java
 */
@Entity
@Table(name = "instructores", schema = "capacitacion", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_persona", "id_capacitacion","activo" }))
public class Instructores implements java.io.Serializable {

	private Long idInstructor;
	private Capacitaciones capacitaciones;
	private Persona persona;
	private String descripcionCv;
	private Documentos documento;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private EmpleadoPuesto empleadoPuesto;

	public Instructores() {
	}

	public Instructores(Long idInstructor, Capacitaciones capacitaciones,
			Persona idPersona, String descripcionCv, Documentos idDocumento,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idInstructor = idInstructor;
		this.capacitaciones = capacitaciones;
		this.persona = idPersona;
		this.descripcionCv = descripcionCv;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public Instructores(Long idInstructor, Capacitaciones capacitaciones,
			Persona idPersona, String descripcionCv, Documentos idDocumento,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idInstructor = idInstructor;
		this.capacitaciones = capacitaciones;
		this.persona = idPersona;
		this.descripcionCv = descripcionCv;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_instructor", unique = true, nullable = false)
	@GeneratedValue(generator="INSTRUCTORES_GENERATOR")
	@SequenceGenerator(name="INSTRUCTORES_GENERATOR",sequenceName="capacitacion.instructores_id_instructor_seq")
	
	public Long getIdInstructor() {
		return this.idInstructor;
	}

	public void setIdInstructor(Long idInstructor) {
		this.idInstructor = idInstructor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion", nullable = false)
	@NotNull
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	@Column(name = "descripcion_cv", nullable = false, length = 5000)
	@NotNull
	@Length(max = 5000)
	public String getDescripcionCv() {
		return this.descripcionCv;
	}

	

	public void setDescripcionCv(String descripcionCv) {
		this.descripcionCv = descripcionCv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	@NotNull
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto")
	public EmpleadoPuesto getEmpleadoPuesto() {
		return empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

}
