package py.com.excelsis.sicca.entity;

// Generated 02-may-2012 10:35:24 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * JbpmTaskinstance generated by hbm2java
 */
@Entity
@Table(name = "jbpm_taskinstance", schema = "jbpm")
public class JbpmTaskinstance implements java.io.Serializable {

	private long id;
	private char class_;
	private int version;
	private String name;
	private String description;
	private String actorid;
	private Date create;
	private Date start;
	private Date end;
	private Date duedate;
	private Integer priority;
	private Boolean iscancelled;
	private Boolean issuspended;
	private Boolean isopen;
	private Boolean issignalling;
	private Boolean isblocking;
	private Long task;
	private Long token;
	private Long procinst;
	private Long swimlaninstance;
	private Long taskmgmtinstance;
	private String userend;

	public JbpmTaskinstance() {
	}


	@Id
	@Column(name = "id_", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "class_", nullable = false, length = 1)
	public char getClass_() {
		return this.class_;
	}

	public void setClass_(char class_) {
		this.class_ = class_;
	}

	@Column(name = "version_", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "name_")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description_", length = 4000)
	@Length(max = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "actorid_")
	public String getActorid() {
		return this.actorid;
	}

	public void setActorid(String actorid) {
		this.actorid = actorid;
	}
	
	
	@Column(name = "userend_")
	public String getUserend() {
		return userend;
	}
	public void setUserend(String userend) {
		this.userend = userend;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_", length = 29)
	public Date getCreate() {
		return this.create;
	}

	public void setCreate(Date create) {
		this.create = create;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_", length = 29)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_", length = 29)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "duedate_", length = 29)
	public Date getDuedate() {
		return this.duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	@Column(name = "priority_")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "iscancelled_")
	public Boolean getIscancelled() {
		return this.iscancelled;
	}

	public void setIscancelled(Boolean iscancelled) {
		this.iscancelled = iscancelled;
	}

	@Column(name = "issuspended_")
	public Boolean getIssuspended() {
		return this.issuspended;
	}

	public void setIssuspended(Boolean issuspended) {
		this.issuspended = issuspended;
	}

	@Column(name = "isopen_")
	public Boolean getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Boolean isopen) {
		this.isopen = isopen;
	}

	@Column(name = "issignalling_")
	public Boolean getIssignalling() {
		return this.issignalling;
	}

	public void setIssignalling(Boolean issignalling) {
		this.issignalling = issignalling;
	}

	@Column(name = "isblocking_")
	public Boolean getIsblocking() {
		return this.isblocking;
	}

	public void setIsblocking(Boolean isblocking) {
		this.isblocking = isblocking;
	}

	@Column(name = "task_")
	public Long getTask() {
		return this.task;
	}

	public void setTask(Long task) {
		this.task = task;
	}

	@Column(name = "token_")
	public Long getToken() {
		return this.token;
	}

	public void setToken(Long token) {
		this.token = token;
	}

	@Column(name = "procinst_")
	public Long getProcinst() {
		return this.procinst;
	}

	public void setProcinst(Long procinst) {
		this.procinst = procinst;
	}

	@Column(name = "swimlaninstance_")
	public Long getSwimlaninstance() {
		return this.swimlaninstance;
	}

	public void setSwimlaninstance(Long swimlaninstance) {
		this.swimlaninstance = swimlaninstance;
	}

	@Column(name = "taskmgmtinstance_")
	public Long getTaskmgmtinstance() {
		return this.taskmgmtinstance;
	}

	public void setTaskmgmtinstance(Long taskmgmtinstance) {
		this.taskmgmtinstance = taskmgmtinstance;
	}

}
