package py.com.excelsis.sicca.entity;

// Generated 29-nov-2011 11:19:08 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ListaLarga generated by hbm2java
 */
@Entity
@Table(name = "lista", schema = "seleccion")
public class Lista implements java.io.Serializable {

	private Long idLista;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Date fechaPublicacion;
	private String usuPublicacion;
	private Date fechaConv;
	private Date horaDesde;
	private Date horaHasta;
	private String lugar;
	private Ciudad ciudad;
	private String direccion;
	private String observacion;
	private String usuMod;
	private Date fechaMod;
	private String tipo;
	private Date fechaVencElegible;
	private Boolean conCedula;

	public Lista() {
	}

	public Lista(Long idLista, ConcursoPuestoAgr concursoPuestoAgr) {
		this.idLista = idLista;
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	public Lista(Long idLista, ConcursoPuestoAgr concursoPuestoAgr,
			Date fechaPublicacion, String usuPublicacion, Date fechaConv,
			Date horaDesde, Date horaHasta, String lugar, Ciudad ciudad,
			String direccion, String observacion, String usuMod, Date fechaMod) {
		this.idLista = idLista;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.fechaPublicacion = fechaPublicacion;
		this.usuPublicacion = usuPublicacion;
		this.fechaConv = fechaConv;
		this.horaDesde = horaDesde;
		this.horaHasta = horaHasta;
		this.lugar = lugar;
		this.ciudad = ciudad;
		this.direccion = direccion;
		this.observacion = observacion;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="LISTA_LARGA_GENERATOR")
	@SequenceGenerator(name="LISTA_LARGA_GENERATOR",sequenceName="seleccion.lista_larga_id_lista_larga_seq")
	@Column(name = "id_lista", unique = true, nullable = false)
	public Long getIdLista() {
		return this.idLista;
	}

	public void setIdLista(Long idLista) {
		this.idLista = idLista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr", nullable = false)
	@NotNull
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_publicacion", length = 29)
	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	@Column(name = "usu_publicacion", length = 50)
	@Length(max = 50)
	public String getUsuPublicacion() {
		return this.usuPublicacion;
	}

	public void setUsuPublicacion(String usuPublicacion) {
		this.usuPublicacion = usuPublicacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_conv", length = 13)
	public Date getFechaConv() {
		return this.fechaConv;
	}

	public void setFechaConv(Date fechaConv) {
		this.fechaConv = fechaConv;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_desde", length = 15)
	public Date getHoraDesde() {
		return this.horaDesde;
	}

	public void setHoraDesde(Date horaDesde) {
		this.horaDesde = horaDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_hasta", length = 15)
	public Date getHoraHasta() {
		return this.horaHasta;
	}

	public void setHoraHasta(Date horaHasta) {
		this.horaHasta = horaHasta;
	}

	@Column(name = "lugar", length = 150)
	@Length(max = 150)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciudad")
	public Ciudad getCiudad() {
		return ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "direccion", length = 150)
	@Length(max = 150)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "tipo", length = 20)
	@Length(max = 20)
	public String getTipo() {
		return tipo;
	}

	
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_venc_elegible", length = 29)
	public Date getFechaVencElegible() {
		return fechaVencElegible;
	}

	public void setFechaVencElegible(Date fechaVencElegible) {
		this.fechaVencElegible = fechaVencElegible;
	}

	@Column(name = "con_cedula")
	public Boolean getConCedula() {
		return conCedula;
	}

	public void setConCedula(Boolean conCedula) {
		this.conCedula = conCedula;
	}
	
	

	
	
	
	
}
