package py.com.excelsis.sicca.entity;

// Generated 13-jul-2012 8:48:33 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ListaDet generated by hbm2java
 */
@Entity
@Table(name = "lista_det", schema = "capacitacion")
public class ListaDet implements java.io.Serializable {

	private Long idListaDet;
	private ListaCab listaCab;
	private PostulacionCap postulacionCap;
	private String tipo;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private DatosEspecificos datosEspecificosDesv;
	private String observacion;
	private Date fechaDesvinculacion;
	private Documentos documento;
	private String usuDesv;
	private Date fechaDesv;
	private String usuMod;
	private Date fechaMod;
	private String usuHabilit;
	private Date fechaHabilit;
	private String motivoHabilit;
	
	public ListaDet() {
	}

	public ListaDet(Long idListaDet, ListaCab listaCab,
			PostulacionCap postulacionCap, String tipo, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idListaDet = idListaDet;
		this.listaCab = listaCab;
		this.postulacionCap = postulacionCap;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ListaDet(Long idListaDet, ListaCab listaCab,
			PostulacionCap postulacionCap, String tipo, boolean activo,
			String usuAlta, Date fechaAlta, DatosEspecificos datosEspecificosDesv,
			String observacion, Date fechaDesvinculacion, Documentos documento,
			String usuDesv, Date fechaDesv) {
		this.idListaDet = idListaDet;
		this.listaCab = listaCab;
		this.postulacionCap = postulacionCap;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.datosEspecificosDesv = datosEspecificosDesv;
		this.observacion = observacion;
		this.fechaDesvinculacion = fechaDesvinculacion;
		this.documento = documento;
		this.usuDesv = usuDesv;
		this.fechaDesv = fechaDesv;
	}

	@Id
	@GeneratedValue(generator = "LISTA_DET_GENERATOR")
	@SequenceGenerator(name = "LISTA_DET_GENERATOR", sequenceName = "capacitacion.lista_det_id_lista_det_seq")
	@Column(name = "id_lista_det", unique = true, nullable = false)
	public Long getIdListaDet() {
		return this.idListaDet;
	}

	public void setIdListaDet(Long idListaDet) {
		this.idListaDet = idListaDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_lista", nullable = false)
	@NotNull
	public ListaCab getListaCab() {
		return this.listaCab;
	}

	public void setListaCab(ListaCab listaCab) {
		this.listaCab = listaCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public PostulacionCap getPostulacionCap() {
		return this.postulacionCap;
	}

	public void setPostulacionCap(PostulacionCap postulacionCap) {
		this.postulacionCap = postulacionCap;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}



	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_desvinculacion", length = 29)
	public Date getFechaDesvinculacion() {
		return this.fechaDesvinculacion;
	}

	public void setFechaDesvinculacion(Date fechaDesvinculacion) {
		this.fechaDesvinculacion = fechaDesvinculacion;
	}


	@Column(name = "usu_desv", length = 50)
	@Length(max = 50)
	public String getUsuDesv() {
		return this.usuDesv;
	}

	public void setUsuDesv(String usuDesv) {
		this.usuDesv = usuDesv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_desv", length = 29)
	public Date getFechaDesv() {
		return this.fechaDesv;
	}

	public void setFechaDesv(Date fechaDesv) {
		this.fechaDesv = fechaDesv;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_desv")
	public DatosEspecificos getDatosEspecificosDesv() {
		return datosEspecificosDesv;
	}

	public void setDatosEspecificosDesv(DatosEspecificos datosEspecificosDesv) {
		this.datosEspecificosDesv = datosEspecificosDesv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	@Column(name = "usu_habilit", length = 50)
	@Length(max = 50)
	public String getUsuHabilit() {
		return usuHabilit;
	}

	public void setUsuHabilit(String usuHabilit) {
		this.usuHabilit = usuHabilit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_habilit", length = 29)
	public Date getFechaHabilit() {
		return fechaHabilit;
	}

	public void setFechaHabilit(Date fechaHabilit) {
		this.fechaHabilit = fechaHabilit;
	}

	@Column(name = "motivo_habilit", length = 500)
	@Length(max = 500)
	public String getMotivoHabilit() {
		return motivoHabilit;
	}

	public void setMotivoHabilit(String motivoHabilit) {
		this.motivoHabilit = motivoHabilit;
	}
	
	

	
	
	
}
