package py.com.excelsis.sicca.entity;

// Generated 13-jul-2012 8:48:33 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ListaCab generated by hbm2java
 */
@Entity
@Table(name = "lista_cab", schema = "capacitacion")
public class ListaCab implements java.io.Serializable {

	private Long idLista;
	private Capacitaciones capacitaciones;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<ListaDet> listaDets = new HashSet<ListaDet>(0);

	public ListaCab() {
	}

	public ListaCab(Long idLista, Capacitaciones capacitaciones,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idLista = idLista;
		this.capacitaciones = capacitaciones;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ListaCab(Long idLista, Capacitaciones capacitaciones,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Set<ListaDet> listaDets) {
		this.idLista = idLista;
		this.capacitaciones = capacitaciones;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.listaDets = listaDets;
	}

	@Id
	@GeneratedValue(generator = "LISTA_CAB_GENERATOR")
	@SequenceGenerator(name = "LISTA_CAB_GENERATOR", sequenceName = "capacitacion.lista_cab_id_lista_seq")
	@Column(name = "id_lista", unique = true, nullable = false)
	public Long getIdLista() {
		return this.idLista;
	}

	public void setIdLista(Long idLista) {
		this.idLista = idLista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion", nullable = false)
	@NotNull
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listaCab")
	public Set<ListaDet> getListaDets() {
		return this.listaDets;
	}

	public void setListaDets(Set<ListaDet> listaDets) {
		this.listaDets = listaDets;
	}

}
