package py.com.excelsis.sicca.entity;

// Generated 19/10/2011 10:58:12 AM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import java.util.Comparator;

/**
 * MatrizReferencial generated by hbm2java
 */
@Entity
@Table(name = "matriz_referencial", schema = "seleccion")
public class MatrizReferencial implements java.io.Serializable {

	private Long idMatrizReferencial;
	private DatosEspecificos datosEspecificos;
	private String descripcion;
	private Float puntajeMaximo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private List<MatrizReferencialEnc> matrizReferencialEncs = new ArrayList<MatrizReferencialEnc>(
			0);
	

	public MatrizReferencial() {
	}

	public MatrizReferencial(Long idMatrizReferencial,
			DatosEspecificos datosEspecificos, String descripcion,
			Float puntajeMaximo, Boolean activo, String usuAlta, Date fechaAlta) {
		this.idMatrizReferencial = idMatrizReferencial;
		this.datosEspecificos = datosEspecificos;
		this.descripcion = descripcion;
		this.puntajeMaximo = puntajeMaximo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public MatrizReferencial(Long idMatrizReferencial,
			DatosEspecificos datosEspecificos, String descripcion,
			Float puntajeMaximo, Boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod,
			List<MatrizReferencialEnc> matrizReferencialEncs) {
		this.idMatrizReferencial = idMatrizReferencial;
		this.datosEspecificos = datosEspecificos;
		this.descripcion = descripcion;
		this.puntajeMaximo = puntajeMaximo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.matrizReferencialEncs = matrizReferencialEncs;
	}

	@Id
	@GeneratedValue(generator="MATRIZ_REFERENCIAL_GENERATOR")
	@SequenceGenerator(name="MATRIZ_REFERENCIAL_GENERATOR",sequenceName="seleccion.matriz_referencial_id_matriz_referencial_seq")
	@Column(name = "id_matriz_referencial", unique = true, nullable = false)
	public Long getIdMatrizReferencial() {
		return this.idMatrizReferencial;
	}

	public void setIdMatrizReferencial(Long idMatrizReferencial) {
		this.idMatrizReferencial = idMatrizReferencial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_conc", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion.toUpperCase();
	}

	@Column(name = "puntaje_maximo", nullable = false, precision = 8, scale = 8)
	public Float getPuntajeMaximo() {
		return this.puntajeMaximo;
	}

	public void setPuntajeMaximo(Float puntajeMaximo) {
		this.puntajeMaximo = puntajeMaximo;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matrizReferencial")
	public List<MatrizReferencialEnc> getMatrizReferencialEncs() {
		if(this.matrizReferencialEncs!= null){
			Collections.sort(this.matrizReferencialEncs, new MyNroOrdenComparator());
		}
		return this.matrizReferencialEncs;
	}

	public void setMatrizReferencialEncs(
			List<MatrizReferencialEnc> matrizReferencialEncs) {
		this.matrizReferencialEncs = matrizReferencialEncs;
	}
	
	public class MyNroOrdenComparator implements Comparator<MatrizReferencialEnc>{
		 
		public int compare(MatrizReferencialEnc o1, MatrizReferencialEnc o2) {
	        return (o1.getNroOrden()<o2.getNroOrden() ? -1 : (o1.getNroOrden()==o2.getNroOrden() ? 0 : 1));
	    }
	}

}
