package py.com.excelsis.sicca.entity;

// Generated 19/10/2011 10:58:12 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MatrizReferencialEnc generated by hbm2java
 */
@Entity
@Table(name = "matriz_referencial_enc", schema = "seleccion")
public class MatrizReferencialEnc implements java.io.Serializable {

	private Long idMatrizReferencialEnc;
	private DatosEspecificos datosEspecificos;
	private MatrizReferencial matrizReferencial;
	private Integer nroOrden;
	private String descripcion;
	private Float puntajeMaximo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean obligatorioSN;
	private Boolean sumItemsSN;
	private Set<MatrizReferencialDet> matrizReferencialDets = new HashSet<MatrizReferencialDet>(
			0);

	public MatrizReferencialEnc() {
	}

	public MatrizReferencialEnc(Long idMatrizReferencialEnc,
			DatosEspecificos datosEspecificos,
			MatrizReferencial matrizReferencial, Integer nroOrden,
			String descripcion, Float puntajeMaximo, Boolean activo,
			String usuAlta, Date fechaAlta, Boolean obligatorioSN,
			Boolean sumItemsSN) {
		this.idMatrizReferencialEnc = idMatrizReferencialEnc;
		this.datosEspecificos = datosEspecificos;
		this.matrizReferencial = matrizReferencial;
		this.nroOrden = nroOrden;
		this.descripcion = descripcion;
		this.puntajeMaximo = puntajeMaximo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.obligatorioSN = obligatorioSN;
		this.sumItemsSN = sumItemsSN;
	}

	public MatrizReferencialEnc(Long idMatrizReferencialEnc,
			DatosEspecificos datosEspecificos,
			MatrizReferencial matrizReferencial, Integer nroOrden,
			String descripcion, Float puntajeMaximo, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Boolean obligatorioSN, Boolean sumItemsSN,
			Set<MatrizReferencialDet> matrizReferencialDets) {
		this.idMatrizReferencialEnc = idMatrizReferencialEnc;
		this.datosEspecificos = datosEspecificos;
		this.matrizReferencial = matrizReferencial;
		this.nroOrden = nroOrden;
		this.descripcion = descripcion;
		this.puntajeMaximo = puntajeMaximo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.obligatorioSN = obligatorioSN;
		this.sumItemsSN = sumItemsSN;
		this.matrizReferencialDets = matrizReferencialDets;
	}

	@Id
	@GeneratedValue(generator="MATRIZ_REFERENCIAL_ENC_GENERATOR")
	@SequenceGenerator(name="MATRIZ_REFERENCIAL_ENC_GENERATOR",sequenceName="seleccion.matriz_referencial_enc_id_matriz_referencial_enc_seq")
	@Column(name = "id_matriz_referencial_enc", unique = true, nullable = false)
	public Long getIdMatrizReferencialEnc() {
		return this.idMatrizReferencialEnc;
	}

	public void setIdMatrizReferencialEnc(Long idMatrizReferencialEnc) {
		this.idMatrizReferencialEnc = idMatrizReferencialEnc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_eval", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_matriz_referencial", nullable = false)
	@NotNull
	public MatrizReferencial getMatrizReferencial() {
		return this.matrizReferencial;
	}

	public void setMatrizReferencial(MatrizReferencial matrizReferencial) {
		this.matrizReferencial = matrizReferencial;
	}

	@Column(name = "nro_orden", nullable = false)
	public Integer getNroOrden() {
		return this.nroOrden;
	}

	public void setNroOrden(Integer nroOrden) {
		this.nroOrden = nroOrden;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "puntaje_maximo", nullable = false, precision = 8, scale = 8)
	public Float getPuntajeMaximo() {
		return this.puntajeMaximo;
	}

	public void setPuntajeMaximo(Float puntajeMaximo) {
		this.puntajeMaximo = puntajeMaximo;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "obligatorio_s_n", nullable = false)
	public Boolean getObligatorioSN() {
		return this.obligatorioSN;
	}

	public void setObligatorioSN(Boolean obligatorioSN) {
		this.obligatorioSN = obligatorioSN;
	}

	@Column(name = "sum_items_s_n", nullable = false)
	public Boolean getSumItemsSN() {
		return this.sumItemsSN;
	}

	public void setSumItemsSN(Boolean sumItemsSN) {
		this.sumItemsSN = sumItemsSN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matrizReferencialEnc")
	public Set<MatrizReferencialDet> getMatrizReferencialDets() {
		return this.matrizReferencialDets;
	}

	public void setMatrizReferencialDets(
			Set<MatrizReferencialDet> matrizReferencialDets) {
		this.matrizReferencialDets = matrizReferencialDets;
	}

}
