package py.com.excelsis.sicca.entity;

// Generated 08/11/2011 01:56:15 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MatrizDocConfigDet generated by hbm2java
 */
@Entity
@Table(name = "matriz_doc_config_grupos", schema = "seleccion")
public class MatrizDocConfigGrupos implements java.io.Serializable {

	private Long idMatrizDocConfigGrupos;
	private MatrizDocConfigEnc matrizDocConfigEnc;
	private Integer nroOrden;
	private String descripcion;
	private Boolean obligatorio;
	private Boolean evaluacionDoc;
	private Boolean adjudicacion = false;//no se podrán agrupar documentos para la Adjudicación - EC
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	
	
	public MatrizDocConfigGrupos() {
	}

	public MatrizDocConfigGrupos(Long idMatrizDocConfigGrupos,
			MatrizDocConfigEnc matrizDocConfigEnc,int nroOrden,
			Boolean obligatorio, Boolean evaluacionDoc, Boolean adjudicacion,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idMatrizDocConfigGrupos = idMatrizDocConfigGrupos;
		this.matrizDocConfigEnc = matrizDocConfigEnc;
		this.nroOrden = nroOrden;
		this.obligatorio = obligatorio;
		this.evaluacionDoc = evaluacionDoc;
		this.adjudicacion = adjudicacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public MatrizDocConfigGrupos(Long idMatrizDocConfigGrupos,
			MatrizDocConfigEnc matrizDocConfigEnc, int nroOrden,
			Boolean obligatorio, Boolean evaluacionDoc, Boolean adjudicacion,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idMatrizDocConfigGrupos = idMatrizDocConfigGrupos;
		this.matrizDocConfigEnc = matrizDocConfigEnc;
				this.nroOrden = nroOrden;
		this.obligatorio = obligatorio;
		this.evaluacionDoc = evaluacionDoc;
		this.adjudicacion = adjudicacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_matriz_doc_config_grupos", unique = true, nullable = false)
	@GeneratedValue(generator="MATRIZ_CONFIG_DOC_GRUPOS_GENERATOR")
	@SequenceGenerator(name="MATRIZ_CONFIG_DOC_GRUPOS_GENERATOR",sequenceName="seleccion.matriz_doc_config_grupos_id_matriz_doc_config_grupos_seq")
	public Long getIdMatrizDocConfigGrupos() {
		return this.idMatrizDocConfigGrupos;
	}

	public void setIdMatrizDocConfigGrupos(Long idMatrizDocConfigGrupos) {
		this.idMatrizDocConfigGrupos = idMatrizDocConfigGrupos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_matriz_doc_config_enc", nullable = false)
	@NotNull
	public MatrizDocConfigEnc getMatrizDocConfigEnc() {
		return this.matrizDocConfigEnc;
	}

	public void setMatrizDocConfigEnc(MatrizDocConfigEnc matrizDocConfigEnc) {
		this.matrizDocConfigEnc = matrizDocConfigEnc;
	}
	
	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

		
	@Column(name = "obligatorio", nullable = false)
	public Boolean getObligatorio() {
		return obligatorio;
	}

	public void setObligatorio(Boolean obligatorio) {
		this.obligatorio = obligatorio;
	}

	
	
	@Column(name = "evaluacion_doc", nullable = false)
	public Boolean getEvaluacionDoc() {
		return evaluacionDoc;
	}

	public void setEvaluacionDoc(Boolean evaluacionDoc) {
		this.evaluacionDoc = evaluacionDoc;
	}

	
	
	@Column(name = "adjudicacion", nullable = false)
	public Boolean getAdjudicacion() {
		return adjudicacion;
	}

	public void setAdjudicacion(Boolean adjudicacion) {
		this.adjudicacion = adjudicacion;
	}

	
	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	@Column(name = "nro_orden", nullable = false)
	public Integer getNroOrden() {
		return nroOrden;
	}

	public void setNroOrden(Integer nroOrden) {
		this.nroOrden = nroOrden;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	
	

	
	

}
