package py.com.excelsis.sicca.entity;

// Generated 19/10/2011 10:58:12 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MatrizDocumentalDet generated by hbm2java
 */
@Entity
@Table(name = "matriz_documental_det", schema = "seleccion")
public class MatrizDocumentalDet implements java.io.Serializable {

	private Long idMatrizDocumentalDet;
	private MatrizDocumentalEnc matrizDocumentalEnc;
	private DatosEspecificos datosEspecificos;
	private Integer nroOrden;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public MatrizDocumentalDet() {
	}

	public MatrizDocumentalDet(Long idMatrizDocumentalDet,
			MatrizDocumentalEnc matrizDocumentalEnc,
			DatosEspecificos datosEspecificos, Integer nroOrden, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idMatrizDocumentalDet = idMatrizDocumentalDet;
		this.matrizDocumentalEnc = matrizDocumentalEnc;
		this.datosEspecificos = datosEspecificos;
		this.nroOrden = nroOrden;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public MatrizDocumentalDet(Long idMatrizDocumentalDet,
			MatrizDocumentalEnc matrizDocumentalEnc,
			DatosEspecificos datosEspecificos, Integer nroOrden, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idMatrizDocumentalDet = idMatrizDocumentalDet;
		this.matrizDocumentalEnc = matrizDocumentalEnc;
		this.datosEspecificos = datosEspecificos;
		this.nroOrden = nroOrden;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="MATRIZ_DOC_DET_GENERATOR")
	@SequenceGenerator(name="MATRIZ_DOC_DET_GENERATOR",sequenceName="seleccion.matriz_documental_det_id_matriz_documental_det_seq")
	@Column(name = "id_matriz_documental_det", unique = true, nullable = false)
	public Long getIdMatrizDocumentalDet() {
		return this.idMatrizDocumentalDet;
	}

	public void setIdMatrizDocumentalDet(Long idMatrizDocumentalDet) {
		this.idMatrizDocumentalDet = idMatrizDocumentalDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_matriz_documental_enc", nullable = false)
	@NotNull
	public MatrizDocumentalEnc getMatrizDocumentalEnc() {
		return this.matrizDocumentalEnc;
	}

	public void setMatrizDocumentalEnc(MatrizDocumentalEnc matrizDocumentalEnc) {
		this.matrizDocumentalEnc = matrizDocumentalEnc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_docu", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@Column(name = "nro_orden", nullable = false)
	public Integer getNroOrden() {
		return this.nroOrden;
	}

	public void setNroOrden(Integer nroOrden) {
		this.nroOrden = nroOrden;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
