package py.com.excelsis.sicca.entity;

// Generated 10/11/2011 03:16:02 PM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MatrizRefConf generated by hbm2java
 */
@Entity
@Table(name = "matriz_ref_conf", schema = "seleccion")
public class MatrizRefConf implements java.io.Serializable {

	private Long idMatrizRefConf;
	private DatosEspecificos datosEspecificos;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private String descripcion;
	private float puntajeMaximo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String tipo;
	private String otrosDatos;

	private HomologacionPerfilMatriz homologacionPerfilMatriz;

	private List<MatrizRefConfEnc> matrizRefConfEncs = new ArrayList<MatrizRefConfEnc>(0);

	public MatrizRefConf() {
	}

	public MatrizRefConf(
			Long idMatrizRefConf, DatosEspecificos datosEspecificos,
			ConcursoPuestoAgr concursoPuestoAgr, String descripcion, float puntajeMaximo,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idMatrizRefConf = idMatrizRefConf;
		this.datosEspecificos = datosEspecificos;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.descripcion = descripcion;
		this.puntajeMaximo = puntajeMaximo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public MatrizRefConf(
			Long idMatrizRefConf, DatosEspecificos datosEspecificos,
			ConcursoPuestoAgr concursoPuestoAgr, String descripcion, float puntajeMaximo,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			List<MatrizRefConfEnc> matrizRefConfEncs) {
		this.idMatrizRefConf = idMatrizRefConf;
		this.datosEspecificos = datosEspecificos;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.descripcion = descripcion;
		this.puntajeMaximo = puntajeMaximo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.matrizRefConfEncs = matrizRefConfEncs;
	}

	@Id
	@GeneratedValue(generator = "MATRIZ_REF_CONF_GENERATOR")
	@SequenceGenerator(name = "MATRIZ_REF_CONF_GENERATOR", sequenceName = "seleccion.matriz_ref_conf_id_matriz_ref_conf_seq")
	@Column(name = "id_matriz_ref_conf", unique = true, nullable = false)
	public Long getIdMatrizRefConf() {
		return this.idMatrizRefConf;
	}

	public void setIdMatrizRefConf(Long idMatrizRefConf) {
		this.idMatrizRefConf = idMatrizRefConf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_conc", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "puntaje_maximo", nullable = false, precision = 8, scale = 8)
	public float getPuntajeMaximo() {
		return this.puntajeMaximo;
	}

	public void setPuntajeMaximo(float puntajeMaximo) {
		this.puntajeMaximo = puntajeMaximo;
	}

	
	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matrizRefConf")
	public List<MatrizRefConfEnc> getMatrizRefConfEncs() {
		return this.matrizRefConfEncs;
	}

	public void setMatrizRefConfEncs(List<MatrizRefConfEnc> matrizRefConfEncs) {
		this.matrizRefConfEncs = matrizRefConfEncs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_homologacion")
	public HomologacionPerfilMatriz getHomologacionPerfilMatriz() {
		return homologacionPerfilMatriz;
	}

	public void setHomologacionPerfilMatriz(HomologacionPerfilMatriz homologacionPerfilMatriz) {
		this.homologacionPerfilMatriz = homologacionPerfilMatriz;
	}

	@Column(name = "tipo", length = 20)
	@Length(max = 20)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "otros_datos")
	public String getOtrosDatos() {
		return this.otrosDatos;
	}

	public void setOtrosDatos(String otrosDatos) {
		this.otrosDatos = otrosDatos;
	}	

}
