package py.com.excelsis.sicca.entity;

// Generated 08/11/2011 01:56:15 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MatrizDocConfigDet generated by hbm2java
 */
@Entity
@Table(name = "matriz_doc_config_det", schema = "seleccion")
public class MatrizDocConfigDet implements java.io.Serializable {

	private Long idMatrizDocConfigDet;
	private MatrizDocConfigEnc matrizDocConfigEnc;
	private MatrizDocConfigGrupos matrizDocConfigGrupos;
	private DatosEspecificos datosEspecificos;
	private Integer nroOrden;
	private Boolean obligatorio;
	private Boolean evaluacionDoc;
	private Boolean agrupado;
	private Boolean adjudicacion;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	
	private MatrizDocumentalDet matrizDocumentalDet;

	public MatrizDocConfigDet() {
	}

	public MatrizDocConfigDet(Long idMatrizDocConfigDet,
			MatrizDocConfigEnc matrizDocConfigEnc,
			MatrizDocConfigGrupos matrizDocConfigGrupos,
			Boolean agrupado,
			DatosEspecificos datosEspecificos, int nroOrden,
			Boolean obligatorio, Boolean evaluacionDoc, Boolean adjudicacion,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idMatrizDocConfigDet = idMatrizDocConfigDet;
		this.matrizDocConfigEnc = matrizDocConfigEnc;
		this.datosEspecificos = datosEspecificos;
		this.nroOrden = nroOrden;
		this.obligatorio = obligatorio;
		this.evaluacionDoc = evaluacionDoc;
		this.adjudicacion = adjudicacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.matrizDocConfigGrupos = matrizDocConfigGrupos;
		this.agrupado = agrupado;
	}

	public MatrizDocConfigDet(Long idMatrizDocConfigDet,
			MatrizDocConfigEnc matrizDocConfigEnc,
			MatrizDocConfigGrupos matrizDocConfigGrupos,
			Boolean agrupado,
			DatosEspecificos datosEspecificos, int nroOrden,
			Boolean obligatorio, Boolean evaluacionDoc, Boolean adjudicacion,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idMatrizDocConfigDet = idMatrizDocConfigDet;
		this.matrizDocConfigEnc = matrizDocConfigEnc;
		this.datosEspecificos = datosEspecificos;
		this.nroOrden = nroOrden;
		this.obligatorio = obligatorio;
		this.evaluacionDoc = evaluacionDoc;
		this.adjudicacion = adjudicacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.matrizDocConfigGrupos = matrizDocConfigGrupos;
		this.agrupado = agrupado;
	}

	@Id
	@Column(name = "id_matriz_doc_config_det", unique = true, nullable = false)
	@GeneratedValue(generator="MATRIZ_CONFIG_DOC_DET_GENERATOR")
	@SequenceGenerator(name="MATRIZ_CONFIG_DOC_DET_GENERATOR",sequenceName="seleccion.matriz_referencial_det_id_matriz_referencial_det_seq")
	public Long getIdMatrizDocConfigDet() {
		return this.idMatrizDocConfigDet;
	}

	public void setIdMatrizDocConfigDet(Long idMatrizDocConfigDet) {
		this.idMatrizDocConfigDet = idMatrizDocConfigDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_matriz_doc_config_enc", nullable = false)
	@NotNull
	public MatrizDocConfigEnc getMatrizDocConfigEnc() {
		return this.matrizDocConfigEnc;
	}

	public void setMatrizDocConfigEnc(MatrizDocConfigEnc matrizDocConfigEnc) {
		this.matrizDocConfigEnc = matrizDocConfigEnc;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_docu", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}
	
	@Column(name = "obligatorio")
	public Boolean getObligatorio() {
		return obligatorio;
	}

	public void setObligatorio(Boolean obligatorio) {
		this.obligatorio = obligatorio;
	}

	
	
	@Column(name = "evaluacion_doc")
	public Boolean getEvaluacionDoc() {
		return evaluacionDoc;
	}

	public void setEvaluacionDoc(Boolean evaluacionDoc) {
		this.evaluacionDoc = evaluacionDoc;
	}

	
	
	@Column(name = "adjudicacion")
	public Boolean getAdjudicacion() {
		return adjudicacion;
	}

	public void setAdjudicacion(Boolean adjudicacion) {
		this.adjudicacion = adjudicacion;
	}

	
	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	@Column(name = "nro_orden", nullable = false)
	public Integer getNroOrden() {
		return nroOrden;
	}

	public void setNroOrden(Integer nroOrden) {
		this.nroOrden = nroOrden;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_matriz_doc_config_grupos")
	
	public MatrizDocConfigGrupos getMatrizDocConfigGrupos() {
		return this.matrizDocConfigGrupos;
	}

	public void setMatrizDocConfigGrupos(MatrizDocConfigGrupos matrizDocConfigGrupos) {
		this.matrizDocConfigGrupos = matrizDocConfigGrupos;
	}
	
	@Column(name = "agrupado")
	public Boolean getAgrupado() {
		return agrupado;
	}
	
	public void setAgrupado(Boolean agrupado) {
		this.agrupado = agrupado;
	}

	
	@Transient
	public MatrizDocumentalDet getMatrizDocumentalDet() {
		return matrizDocumentalDet;
	}

	public void setMatrizDocumentalDet(MatrizDocumentalDet matrizDocumentalDet) {
		this.matrizDocumentalDet = matrizDocumentalDet;
	}


	
	

}
