package py.com.excelsis.sicca.entity;

// Generated 14/11/2011 04:49:57 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MemoHomologacion generated by hbm2java
 */
@Entity
@Table(name = "memo_homologacion", schema = "seleccion")
public class MemoHomologacion implements java.io.Serializable {

	private Long idMemoHomologacion;
	private PlantillaMemoHomologacion plantillaMemoHomologacion;
	private Integer nroMemo;
	private String titulo;
	private String texto;
	private Date fecha;
	private String ref;
	private String a;
	private String usuMod;
	private String usuAlta;
	private Date fechaAlta;
	private Date fechaMod;
	private String de;
	private Documentos documentos;
	private Set<ConcursoPuestoAgr> concursoPuestoAgrs = new HashSet<ConcursoPuestoAgr>(
			0);

	public MemoHomologacion() {
	}

	public MemoHomologacion(Long idMemoHomologacion,
			PlantillaMemoHomologacion plantillaMemoHomologacion, Integer nroMemo,
			Date fecha, String usuAlta, Date fechaAlta) {
		this.idMemoHomologacion = idMemoHomologacion;
		this.plantillaMemoHomologacion = plantillaMemoHomologacion;
		this.nroMemo = nroMemo;
		this.fecha = fecha;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public MemoHomologacion(Long idMemoHomologacion,
			PlantillaMemoHomologacion plantillaMemoHomologacion, Integer nroMemo,
			String titulo, String texto, Date fecha, String ref, String a,
			String usuMod, String usuAlta, Date fechaAlta, Date fechaMod,
			Set<ConcursoPuestoAgr> concursoPuestoAgrs) {
		this.idMemoHomologacion = idMemoHomologacion;
		this.plantillaMemoHomologacion = plantillaMemoHomologacion;
		this.nroMemo = nroMemo;
		this.titulo = titulo;
		this.texto = texto;
		this.fecha = fecha;
		this.ref = ref;
		this.a = a;
		this.usuMod = usuMod;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.fechaMod = fechaMod;
		this.concursoPuestoAgrs = concursoPuestoAgrs;
	}

	@Id
	@Column(name = "id_memo_homologacion", unique = true, nullable = false)
	@GeneratedValue(generator="MEMO_HOMOLOGACION_GENERATOR")
	@SequenceGenerator(name="MEMO_HOMOLOGACION_GENERATOR",sequenceName="seleccion.memo_homologacion_id_memo_homologacion_seq")

	public Long getIdMemoHomologacion() {
		return this.idMemoHomologacion;
	}

	public void setIdMemoHomologacion(Long idMemoHomologacion) {
		this.idMemoHomologacion = idMemoHomologacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_memo_homologacion")
	public PlantillaMemoHomologacion getPlantillaMemoHomologacion() {
		return this.plantillaMemoHomologacion;
	}

	public void setPlantillaMemoHomologacion(
			PlantillaMemoHomologacion plantillaMemoHomologacion) {
		this.plantillaMemoHomologacion = plantillaMemoHomologacion;
	}

	@Column(name = "nro_memo", nullable = false)
	public Integer getNroMemo() {
		return this.nroMemo;
	}

	public void setNroMemo(Integer nroMemo) {
		this.nroMemo = nroMemo;
	}

	@Column(name = "titulo", length = 500)
	@Length(max = 500)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "texto", length = 2000)
	@Length(max = 2000)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha",  length = 29)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "ref", length = 500)
	@Length(max = 500)
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	@Column(name = "a", length = 500)
	@Length(max = 500)
	public String getA() {
		return this.a;
	}

	public void setA(String a) {
		this.a = a;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memoHomologacion")
	public Set<ConcursoPuestoAgr> getConcursoPuestoAgrs() {
		return this.concursoPuestoAgrs;
	}

	public void setConcursoPuestoAgrs(Set<ConcursoPuestoAgr> concursoPuestoAgrs) {
		this.concursoPuestoAgrs = concursoPuestoAgrs;
	}

	@Column(name = "de", length = 500)
	@Length(max = 500)
	public String getDe() {
		return de;
	}

	public void setDe(String de) {
		this.de = de;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}
	

	
}
