package py.com.excelsis.sicca.entity;

// Generated 18/09/2011 08:56:37 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "mensaje", schema = "general")
public class Mensaje implements java.io.Serializable {

	private Long idMensaje;
	private String valorMensaje;
	private String codigoMensaje;
	private Boolean activo;

	public Mensaje() {
	}

	@Id
	@Column(name = "id_mensaje", unique = true, nullable = false)
	public Long getIdMensaje() {
		return this.idMensaje;
	}

	public void setIdMensaje(Long idMensaje) {
		this.idMensaje = idMensaje;
	}

	@Transient
	public Long getId() {
		return idMensaje;
	}

	@Column(name = "valor_mensaje", length = 300)
	@Length(max = 300)
	public String getValorMensaje() {
		return this.valorMensaje;
	}

	public void setValorMensaje(String valorMensaje) {
		this.valorMensaje = valorMensaje;
	}

	@Column(name = "codigo_mensaje", length = 50)
	@Length(max = 50)
	public String getCodigoMensaje() {
		return this.codigoMensaje;
	}

	public void setCodigoMensaje(String codigoMensaje) {
		this.codigoMensaje = codigoMensaje;
	}
	
	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}


	
	
}
