package py.com.excelsis.sicca.entity;

// Generated 18-jun-2012 15:55:25 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MovUsuariosTarea generated by hbm2java
 */
@Entity
@Table(name = "mov_usuarios_tarea", schema = "capacitacion")
public class MovUsuariosTarea implements java.io.Serializable {

	private Long idMov;
	private String usuOrigen;
	private Date fechaOrigen;
	private String motivo;
	private long idProcessInstance;
	private String usuAlta;
	private Date fechaAlta;
	private String usuDest;
	private Date fechaDest;
	private String tipo;

	public MovUsuariosTarea() {
	}

	public MovUsuariosTarea(Long idMov, String usuOrigen, Date fechaOrigen,
			String motivo, long idProcessInstance, String usuAlta,
			Date fechaAlta) {
		this.idMov = idMov;
		this.usuOrigen = usuOrigen;
		this.fechaOrigen = fechaOrigen;
		this.motivo = motivo;
		this.idProcessInstance = idProcessInstance;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public MovUsuariosTarea(Long idMov, String usuOrigen, Date fechaOrigen,
			String motivo, long idProcessInstance, String usuAlta,
			Date fechaAlta, String usuDest, Date fechaDest, String tipo) {
		this.idMov = idMov;
		this.usuOrigen = usuOrigen;
		this.fechaOrigen = fechaOrigen;
		this.motivo = motivo;
		this.idProcessInstance = idProcessInstance;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuDest = usuDest;
		this.fechaDest = fechaDest;
		this.tipo = tipo;
	}

	@Id
	@GeneratedValue(generator="MOV_USUARIOS_GENERATOR")
	@SequenceGenerator(name="MOV_USUARIOS_GENERATOR",sequenceName="capacitacion.mov_usuarios_tarea_id_mov_seq")
	@Column(name = "id_mov", unique = true, nullable = false)
	public Long getIdMov() {
		return this.idMov;
	}

	public void setIdMov(Long idMov) {
		this.idMov = idMov;
	}

	@Column(name = "usu_origen", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuOrigen() {
		return this.usuOrigen;
	}

	public void setUsuOrigen(String usuOrigen) {
		this.usuOrigen = usuOrigen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_origen", nullable = false, length = 29)
	@NotNull
	public Date getFechaOrigen() {
		return this.fechaOrigen;
	}

	public void setFechaOrigen(Date fechaOrigen) {
		this.fechaOrigen = fechaOrigen;
	}

	@Column(name = "motivo", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "id_process_instance", nullable = false)
	public long getIdProcessInstance() {
		return this.idProcessInstance;
	}

	public void setIdProcessInstance(long idProcessInstance) {
		this.idProcessInstance = idProcessInstance;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_dest", length = 50)
	@Length(max = 50)
	public String getUsuDest() {
		return this.usuDest;
	}

	public void setUsuDest(String usuDest) {
		this.usuDest = usuDest;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_dest", length = 29)
	public Date getFechaDest() {
		return this.fechaDest;
	}

	public void setFechaDest(Date fechaDest) {
		this.fechaDest = fechaDest;
	}

	@Column(name = "tipo", length = 1)
	@Length(max = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
