package py.com.excelsis.sicca.entity;

// Generated 05/10/2011 11:41:21 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * NivelEstudio generated by hbm2java
 */
@Entity
@Table(name = "nivel_estudio", schema = "seleccion")
public class NivelEstudio implements java.io.Serializable {

	private Long idNivelEstudio;
	private String descripcion;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<TituloAcademico> tituloAcademicos = new HashSet<TituloAcademico>(
			0);

	public NivelEstudio() {
	}

	public NivelEstudio(Long idNivelEstudio, String descripcion,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idNivelEstudio = idNivelEstudio;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public NivelEstudio(Long idNivelEstudio, String descripcion,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Set<TituloAcademico> tituloAcademicos) {
		this.idNivelEstudio = idNivelEstudio;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.tituloAcademicos = tituloAcademicos;
	}

	@Id
	@Column(name = "id_nivel_estudio", unique = true, nullable = false)
	@GeneratedValue(generator="NIVEL_ESTUDIO_GENERATOR")
	@SequenceGenerator(name="NIVEL_ESTUDIO_GENERATOR",sequenceName="seleccion.sel_nivel_estudio_id_nivel_estudio_seq")
	public Long getIdNivelEstudio() {
		return this.idNivelEstudio;
	}

	public void setIdNivelEstudio(Long idNivelEstudio) {
		this.idNivelEstudio = idNivelEstudio;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEstudio")
	public Set<TituloAcademico> getTituloAcademicos() {
		return this.tituloAcademicos;
	}

	public void setTituloAcademicos(Set<TituloAcademico> tituloAcademicos) {
		this.tituloAcademicos = tituloAcademicos;
	}

}
