package py.com.excelsis.sicca.entity;

// Generated 19/06/2012 11:39:40 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ObsCapEval generated by hbm2java
 */
@Entity
@Table(name = "obs_cap_eval", schema = "capacitacion")
public class ObsCapEval implements java.io.Serializable {

	private Long idObservacion;
	private Capacitaciones capacitacion;
	private String observacion;
	private Long idTaskInstance;
	private String usuAlta;
	private Date fechaAlta;
	private Date fechaMod;
	private String usuMod;
	private EvaluacionDesempeno evaluacionDesempeno;

	public ObsCapEval() {
	}

	public ObsCapEval(Long idObservacion, String observacion,
			Long idTaskInstance, String usuAlta, Date fechaAlta) {
		this.idObservacion = idObservacion;
		this.observacion = observacion;
		this.idTaskInstance = idTaskInstance;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ObsCapEval(Long idObservacion, Capacitaciones idCapacitacion,
			String observacion, Long idTaskInstance, String usuAlta,
			Date fechaAlta, Date fechaMod, String usuMod) {
		this.idObservacion = idObservacion;
		this.capacitacion = idCapacitacion;
		this.observacion = observacion;
		this.idTaskInstance = idTaskInstance;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.fechaMod = fechaMod;
		this.usuMod = usuMod;
	}

	@Id
	@Column(name = "id_observacion", unique = true, nullable = false)
	@GeneratedValue(generator="OBSCAPEVAL_GENERATOR")
	@SequenceGenerator(name="OBSCAPEVAL_GENERATOR",sequenceName="capacitacion.obs_cap_eval_id_observacion_seq")
	public Long getIdObservacion() {
		return this.idObservacion;
	}

	public void setIdObservacion(Long idObservacion) {
		this.idObservacion = idObservacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion")
	public Capacitaciones getCapacitacion() {
		return capacitacion;
	}

	public void setCapacitacion(Capacitaciones capacitacion) {
		this.capacitacion = capacitacion;
	}
	
	
	@Column(name = "observacion", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getObservacion() {
		return this.observacion;
	}

	

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "id_task_instance", nullable = false)
	public Long getIdTaskInstance() {
		return this.idTaskInstance;
	}

	public void setIdTaskInstance(Long idTaskInstance) {
		this.idTaskInstance = idTaskInstance;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno")
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}
	
	

}
