package py.com.excelsis.sicca.entity;

// Generated 06/02/2012 02:08:03 PM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * OrganizacionDiscapacitados generated by hbm2java
 */
@Entity
@Table(name = "organizacion_discapacitados", schema = "seleccion")
public class OrganizacionDiscapacitados implements java.io.Serializable {

	private Long idOrganizacion;
	private Ciudad ciudad;
	private String nombre;
	private String ruc;
	private String EMail;
	private String direccion;
	private String telefono;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	
	private List<OrgDiscapacitadosPersona> orgDiscapacitadosPersonas = new ArrayList<OrgDiscapacitadosPersona>(0);

	public OrganizacionDiscapacitados() {
	}

	public OrganizacionDiscapacitados(Long idOrganizacion, Ciudad ciudad,
			String nombre, String ruc, String EMail, String direccion,
			String telefono, boolean activo, String usuAlta, Date fechaAlta) {
		this.idOrganizacion = idOrganizacion;
		this.ciudad = ciudad;
		this.nombre = nombre;
		this.ruc = ruc;
		this.EMail = EMail;
		this.direccion = direccion;
		this.telefono = telefono;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public OrganizacionDiscapacitados(Long idOrganizacion, Ciudad ciudad,
			String nombre, String ruc, String EMail, String direccion,
			String telefono, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idOrganizacion = idOrganizacion;
		this.ciudad = ciudad;
		this.nombre = nombre;
		this.ruc = ruc;
		this.EMail = EMail;
		this.direccion = direccion;
		this.telefono = telefono;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="OrganizacionDiscapacitados_GENERATOR")
	@SequenceGenerator(name="OrganizacionDiscapacitados_GENERATOR",sequenceName="seleccion.org_discapacitados_persona_id_org_funcionario_persona_seq")
	@Column(name = "id_organizacion", unique = true, nullable = false)
	public Long getIdOrganizacion() {
		return this.idOrganizacion;
	}

	public void setIdOrganizacion(Long idOrganizacion) {
		this.idOrganizacion = idOrganizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciudad", nullable = false)
	@NotNull
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ruc", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "e_mail", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "direccion", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizacionDiscapacitados")
	public List<OrgDiscapacitadosPersona> getOrgDiscapacitadosPersonas() {
		return this.orgDiscapacitadosPersonas;
	}

	public void setOrgDiscapacitadosPersonas(
			List<OrgDiscapacitadosPersona> orgDiscapacitadosPersonas) {
		this.orgDiscapacitadosPersonas = orgDiscapacitadosPersonas;
	}
}
