package py.com.excelsis.sicca.entity;

// Generated 18/07/2012 09:44:43 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlanCapacitacionDet generated by hbm2java
 */
@Entity
@Table(name = "plan_capacitacion_det", schema = "capacitacion")
public class PlanCapacitacionDet implements java.io.Serializable {

	private Long idPlanDet;
	private PlanCapacitacion planCapacitacion;
	private String descripcion;
	private Documentos documento;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public PlanCapacitacionDet() {
	}

	public PlanCapacitacionDet(Long idPlanDet,
			PlanCapacitacion planCapacitacion, Boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idPlanDet = idPlanDet;
		this.planCapacitacion = planCapacitacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PlanCapacitacionDet(Long idPlanDet,
			PlanCapacitacion planCapacitacion, String descripcion,
			Documentos idDocumento, Boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idPlanDet = idPlanDet;
		this.planCapacitacion = planCapacitacion;
		this.descripcion = descripcion;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_plan_det", unique = true, nullable = false)
	@GeneratedValue(generator="PLAN_CAPACITACION_DET_GENERATOR")
	@SequenceGenerator(name="PLAN_CAPACITACION_DET_GENERATOR",sequenceName="capacitacion.plan_capacitacion_det_id_plan_det_seq")

	public Long getIdPlanDet() {
		return this.idPlanDet;
	}

	public void setIdPlanDet(Long idPlanDet) {
		this.idPlanDet = idPlanDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plan", nullable = false)
	@NotNull
	public PlanCapacitacion getPlanCapacitacion() {
		return this.planCapacitacion;
	}

	public void setPlanCapacitacion(PlanCapacitacion planCapacitacion) {
		this.planCapacitacion = planCapacitacion;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	
	
	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
