package py.com.excelsis.sicca.entity;

// Generated 10/09/2012 04:57:06 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlantillaEvalPdecCab generated by hbm2java
 */
@Entity
@Table(name = "plantilla_eval_pdec_cab", schema = "eval_desempeno")
public class PlantillaEvalPdecCab implements java.io.Serializable {

	private Long idPlantillaEvalPdecCab;
	private PlantillaEvalPdec plantillaEvalPdec;
	private String descripcion;
	private Long orden;
	private Float puntaje;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Float resultado;
	private String justificacion;
	private String comentario;
	
	//agregado para el pesoPDEC; Werner
	private Float pesoPdec;
	//*********************************
	
	private Set<PlantillaEvalPdecDet> plantillaEvalPdecDets = new HashSet<PlantillaEvalPdecDet>(0);
	private Set<ResultadoEvalPlan> resultadoEvalPlans = new HashSet<ResultadoEvalPlan>(0);
	private List<PlanMejora> lPM;

	public PlantillaEvalPdecCab() {
	}

	public PlantillaEvalPdecCab(
			Long idPlantillaEvalPdecCab, PlantillaEvalPdec plantillaEvalPdec, String descripcion,
			Long orden, Float puntaje, Boolean activo, String usuAlta, Date fechaAlta, Date fechaMod, Float pesoPdec) {
		this.idPlantillaEvalPdecCab = idPlantillaEvalPdecCab;
		this.plantillaEvalPdec = plantillaEvalPdec;
		this.descripcion = descripcion;
		this.orden = orden;
		this.puntaje = puntaje;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.fechaMod = fechaMod;
		this.pesoPdec = pesoPdec;
	}

	public PlantillaEvalPdecCab(
			Long idPlantillaEvalPdecCab, PlantillaEvalPdec plantillaEvalPdec, String descripcion,
			Long orden, Float puntaje, Boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod, Float resultado, String justificacion, String comentario,
			Set<PlantillaEvalPdecDet> plantillaEvalPdecDets,
			Set<ResultadoEvalPlan> resultadoEvalPlans, Float pesoPdec) {
		this.idPlantillaEvalPdecCab = idPlantillaEvalPdecCab;
		this.plantillaEvalPdec = plantillaEvalPdec;
		this.descripcion = descripcion;
		this.orden = orden;
		this.puntaje = puntaje;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.resultado = resultado;
		this.justificacion = justificacion;
		this.comentario = comentario;
		this.plantillaEvalPdec = plantillaEvalPdec;
		this.resultadoEvalPlans = resultadoEvalPlans;
		this.pesoPdec = pesoPdec;
	}

	@Id
	@Column(name = "id_plantilla_eval_pdec_cab", unique = true, nullable = false)
	@GeneratedValue(generator = "PLANTILLA_EVAL_PDEC_CAB_GENERATOR")
	@SequenceGenerator(name = "PLANTILLA_EVAL_PDEC_CAB_GENERATOR", sequenceName = "eval_desempeno.plantilla_eval_pdec_cab_id_plantilla_eval_pdec_cab_seq")
	public Long getIdPlantillaEvalPdecCab() {
		return this.idPlantillaEvalPdecCab;
	}

	public void setIdPlantillaEvalPdecCab(Long idPlantillaEvalPdecCab) {
		this.idPlantillaEvalPdecCab = idPlantillaEvalPdecCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_eval_pdec", nullable = false)
	@NotNull
	public PlantillaEvalPdec getPlantillaEvalPdec() {
		return this.plantillaEvalPdec;
	}

	public void setPlantillaEvalPdec(PlantillaEvalPdec plantillaEvalPdec) {
		this.plantillaEvalPdec = plantillaEvalPdec;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden", nullable = false)
	public Long getOrden() {
		return this.orden;
	}

	public void setOrden(Long orden) {
		this.orden = orden;
	}

	@Column(name = "puntaje", nullable = false, precision = 8, scale = 8)
	public Float getPuntaje() {
		return this.puntaje;
	}

	public void setPuntaje(Float puntaje) {
		this.puntaje = puntaje;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "resultado", precision = 8, scale = 8)
	public Float getResultado() {
		return this.resultado;
	}

	public void setResultado(Float resultado) {
		this.resultado = resultado;
	}

	@Column(name = "justificacion", length = 500)
	@Length(max = 500)
	public String getJustificacion() {
		return this.justificacion;
	}

	public void setJustificacion(String justificacion) {
		this.justificacion = justificacion;
	}

	@Column(name = "comentario", length = 500)
	@Length(max = 500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantillaEvalPdecCab")
	public Set<PlantillaEvalPdecDet> getPlantillaEvalPdecDets() {
		return this.plantillaEvalPdecDets;
	}

	public void setPlantillaEvalPdecDets(Set<PlantillaEvalPdecDet> plantillaEvalPdecDets) {
		this.plantillaEvalPdecDets = plantillaEvalPdecDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantillaEvalPdecCab")
	public Set<ResultadoEvalPlan> getResultadoEvalPlans() {
		return this.resultadoEvalPlans;
	}

	public void setResultadoEvalPlans(Set<ResultadoEvalPlan> resultadoEvalPlans) {
		this.resultadoEvalPlans = resultadoEvalPlans;
	}

	@Transient
	public List<PlanMejora> getlPM() {
		return lPM;
	}

	public void setlPM(List<PlanMejora> lPM) {
		this.lPM = lPM;
	}
	
	@Column(name = "peso_pdec", nullable = false, precision = 8, scale = 8)
	public Float getPesoPdec() {
		return this.pesoPdec;
	}

	public void setPesoPdec(Float pesoPdec) {
		this.pesoPdec = pesoPdec;
	}
}
