package py.com.excelsis.sicca.entity;

// Generated 12-sep-2012 9:08:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlantillaEvalDet generated by hbm2java
 */
@Entity
@Table(name = "plantilla_eval_det", schema = "eval_desempeno")
public class PlantillaEvalDet implements java.io.Serializable {

	private Long idPlantillaEvalDet;
	private PlantillaEval plantillaEval;
	private Long orden;
	private String resultadoEsperado;
	private String actividades;
	private String indicadoresCump;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public PlantillaEvalDet() {
	}

	public PlantillaEvalDet(Long idPlantillaEvalDet,
			PlantillaEval plantillaEval, Long orden, String resultadoEsperado,
			String actividades, String indicadoresCump, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idPlantillaEvalDet = idPlantillaEvalDet;
		this.plantillaEval = plantillaEval;
		this.orden = orden;
		this.resultadoEsperado = resultadoEsperado;
		this.actividades = actividades;
		this.indicadoresCump = indicadoresCump;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PlantillaEvalDet(Long idPlantillaEvalDet,
			PlantillaEval plantillaEval, Long orden, String resultadoEsperado,
			String actividades, String indicadoresCump, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idPlantillaEvalDet = idPlantillaEvalDet;
		this.plantillaEval = plantillaEval;
		this.orden = orden;
		this.resultadoEsperado = resultadoEsperado;
		this.actividades = actividades;
		this.indicadoresCump = indicadoresCump;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="PLANTILLA_EVAL_DET_GENERATOR")
	@SequenceGenerator(name="PLANTILLA_EVAL_DET_GENERATOR",sequenceName="eval_desempeno.plantilla_eval_det_id_plantilla_eval_det_seq")
	@Column(name = "id_plantilla_eval_det", unique = true, nullable = false)
	public Long getIdPlantillaEvalDet() {
		return this.idPlantillaEvalDet;
	}

	public void setIdPlantillaEvalDet(Long idPlantillaEvalDet) {
		this.idPlantillaEvalDet = idPlantillaEvalDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_eval", nullable = false)
	@NotNull
	public PlantillaEval getPlantillaEval() {
		return this.plantillaEval;
	}

	public void setPlantillaEval(PlantillaEval plantillaEval) {
		this.plantillaEval = plantillaEval;
	}

	@Column(name = "orden", nullable = false)
	public Long getOrden() {
		return this.orden;
	}

	public void setOrden(Long orden) {
		this.orden = orden;
	}

	@Column(name = "resultado_esperado", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getResultadoEsperado() {
		return this.resultadoEsperado;
	}

	public void setResultadoEsperado(String resultadoEsperado) {
		this.resultadoEsperado = resultadoEsperado;
	}

	@Column(name = "actividades", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getActividades() {
		return this.actividades;
	}

	public void setActividades(String actividades) {
		this.actividades = actividades;
	}

	@Column(name = "indicadores_cump", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getIndicadoresCump() {
		return this.indicadoresCump;
	}

	public void setIndicadoresCump(String indicadoresCump) {
		this.indicadoresCump = indicadoresCump;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
