package py.com.excelsis.sicca.entity;

// Generated 13/07/2012 08:32:42 AM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlantillaConfigurada generated by hbm2java
 */
@Entity
@Table(name = "plantilla_configurada", schema = "capacitacion")
public class PlantillaConfigurada implements java.io.Serializable {

	private Long idPlantillaConf;
	private Capacitaciones capacitaciones;
	private String nombre;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Long actualEval;
	private Long totalEval;
	private Long valor;
	private String estado;
	private List<PreguntaConfigurada> preguntaConfiguradas = new ArrayList<PreguntaConfigurada>();

	public PlantillaConfigurada() {
	}

	public PlantillaConfigurada(Long idPlantillaConf,
			Capacitaciones capacitaciones, String nombre, Boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idPlantillaConf = idPlantillaConf;
		this.capacitaciones = capacitaciones;
		this.nombre = nombre;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PlantillaConfigurada(Long idPlantillaConf,
			Capacitaciones capacitaciones, String nombre, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Long actualEval, Long totalEval,
			List<PreguntaConfigurada> preguntaConfiguradas) {
		this.idPlantillaConf = idPlantillaConf;
		this.capacitaciones = capacitaciones;
		this.nombre = nombre;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.actualEval = actualEval;
		this.totalEval = totalEval;
		this.preguntaConfiguradas = preguntaConfiguradas;
	}

	@Id
	@GeneratedValue(generator="PLANTILLA_CONFIGURADA_GENERATOR")
	@SequenceGenerator(name="PLANTILLA_CONFIGURADA_GENERATOR",sequenceName="capacitacion.plantilla_configurada_id_plantilla_conf_seq")
	@Column(name = "id_plantilla_conf", unique = true, nullable = false)
	public Long getIdPlantillaConf() {
		return this.idPlantillaConf;
	}

	public void setIdPlantillaConf(Long idPlantillaConf) {
		this.idPlantillaConf = idPlantillaConf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion", nullable = false)
	@NotNull
	public Capacitaciones getCapacitaciones() {
		return this.capacitaciones;
	}

	public void setCapacitaciones(Capacitaciones capacitaciones) {
		this.capacitaciones = capacitaciones;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "actual_eval")
	public Long getActualEval() {
		return this.actualEval;
	}

	public void setActualEval(Long actualEval) {
		this.actualEval = actualEval;
	}

	@Column(name = "total_eval")
	public Long getTotalEval() {
		return this.totalEval;
	}

	public void setTotalEval(Long totalEval) {
		this.totalEval = totalEval;
	}
	
	@Column(name = "valor")
	public Long getValor() {
		return valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	@Column(name = "estado")
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantillaConfigurada")
	public List<PreguntaConfigurada> getPreguntaConfiguradas() {
		return this.preguntaConfiguradas;
	}

	public void setPreguntaConfiguradas(
			List<PreguntaConfigurada> preguntaConfiguradas) {
		this.preguntaConfiguradas = preguntaConfiguradas;
	}

}
