package py.com.excelsis.sicca.entity;

// Generated 18/07/2012 09:44:43 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlanCapacitacion generated by hbm2java
 */
@Entity
@Table(name = "plan_capacitacion", schema = "capacitacion")
public class PlanCapacitacion implements java.io.Serializable {

	private Long idPlan;
	private ConfiguracionUoCab configuracionUoCab;
	private ConfiguracionUoDet configuracionUoDet;
	private Long nro;
	private Long anio;
	private Double monto;
	private String observacion;
	private String estado;
	private Documentos documento;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<PlanCapacitacionDet> planCapacitacionDets = new HashSet<PlanCapacitacionDet>(
			0);

	public PlanCapacitacion() {
	}

	public PlanCapacitacion(Long idPlan, ConfiguracionUoCab idConfiguracionUo, Long nro,
			Long anio, Double monto, String estado, Boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idPlan = idPlan;
		this.configuracionUoCab= idConfiguracionUo;
		this.nro = nro;
		this.anio = anio;
		this.monto = monto;
		this.estado = estado;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PlanCapacitacion(Long idPlan, ConfiguracionUoCab idConfiguracionUo,
			ConfiguracionUoDet idConfiguracionUoDet, Long nro, Long anio, Double monto,
			String observacion, String estado, Documentos idDocumento,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Set<PlanCapacitacionDet> planCapacitacionDets) {
		this.idPlan = idPlan;
		this.configuracionUoCab = idConfiguracionUo;
		this.configuracionUoDet = idConfiguracionUoDet;
		this.nro = nro;
		this.anio = anio;
		this.monto = monto;
		this.observacion = observacion;
		this.estado = estado;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.planCapacitacionDets = planCapacitacionDets;
	}

	@Id
	@Column(name = "id_plan", unique = true, nullable = false)
	@GeneratedValue(generator="PLAN_CAPACITACION_GENERATOR")
	@SequenceGenerator(name="PLAN_CAPACITACION_GENERATOR",sequenceName="capacitacion.plan_capacitacion_id_plan_seq")

	public Long getIdPlan() {
		return this.idPlan;
	}

	public void setIdPlan(Long idPlan) {
		this.idPlan = idPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_det")
	public ConfiguracionUoDet getConfiguracionUoDet() {
		return configuracionUoDet;
	}

	

	public void setConfiguracionUoDet(ConfiguracionUoDet configuracionUoDet) {
		this.configuracionUoDet = configuracionUoDet;
	}

	

	@Column(name = "nro", nullable = false)
	public Long getNro() {
		return this.nro;
	}

	public void setNro(Long nro) {
		this.nro = nro;
	}

	@Column(name = "anio", nullable = false)
	public Long getAnio() {
		return this.anio;
	}

	public void setAnio(Long anio) {
		this.anio = anio;
	}

	@Column(name = "monto", nullable = false, precision = 17, scale = 17)
	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "estado", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planCapacitacion")
	public Set<PlanCapacitacionDet> getPlanCapacitacionDets() {
		return this.planCapacitacionDets;
	}

	public void setPlanCapacitacionDets(
			Set<PlanCapacitacionDet> planCapacitacionDets) {
		this.planCapacitacionDets = planCapacitacionDets;
	}

}
