package py.com.excelsis.sicca.entity;

// Generated 14/11/2011 04:49:57 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlantillaNotaHomologacion generated by hbm2java
 */
@Entity
@Table(name = "plantilla_nota_homologacion", schema = "seleccion")
public class PlantillaNotaHomologacion implements java.io.Serializable {

	private long idPlantillaNotaHomologacion;
	private String descripcion;
	private String referencia;
	private String titulo1;
	private String titulo2;
	private String cuerpo;
	private String firma;
	private String cargo;
	private String institucionFirma;
	private String a;
	private String don;
	private String itemFinal;
	private String institucion;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private boolean activo;
	private Set<NotaHomologacion> notaHomologacions = new HashSet<NotaHomologacion>(
			0);

	public PlantillaNotaHomologacion() {
	}

	public PlantillaNotaHomologacion(long idPlantillaNotaHomologacion,
			String descripcion, String lugar, String fecha, String referencia,
			String titulo1, String titulo2, String cuerpo, String firma,
			String cargo, String institucionFirma, String a, String don,
			String institucion, String usuAlta, Date fechaAlta, boolean activo) {
		this.idPlantillaNotaHomologacion = idPlantillaNotaHomologacion;
		this.descripcion = descripcion;
		this.referencia = referencia;
		this.titulo1 = titulo1;
		this.titulo2 = titulo2;
		this.cuerpo = cuerpo;
		this.firma = firma;
		this.cargo = cargo;
		this.institucionFirma = institucionFirma;
		this.a = a;
		this.don = don;
		this.institucion = institucion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
	}

	public PlantillaNotaHomologacion(long idPlantillaNotaHomologacion,
			String descripcion, String referencia,
			String titulo1, String titulo2, String cuerpo, String firma,
			String cargo, String institucionFirma, String a, String don,
			String itemFinal, String institucion, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod, boolean activo,
			Set<NotaHomologacion> notaHomologacions) {
		this.idPlantillaNotaHomologacion = idPlantillaNotaHomologacion;
		this.descripcion = descripcion;
		
		this.referencia = referencia;
		this.titulo1 = titulo1;
		this.titulo2 = titulo2;
		this.cuerpo = cuerpo;
		this.firma = firma;
		this.cargo = cargo;
		this.institucionFirma = institucionFirma;
		this.a = a;
		this.don = don;
		this.itemFinal = itemFinal;
		this.institucion = institucion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.activo = activo;
		this.notaHomologacions = notaHomologacions;
	}

	@Id
	@Column(name = "id_plantilla_nota_homologacion", unique = true, nullable = false)
	@GeneratedValue(generator="PLANTILLA_NOTA_HOMOLOGACION_GENERATOR")
	@SequenceGenerator(name="PLANTILLA_NOTA_HOMOLOGACION_GENERATOR",sequenceName="seleccion.plantilla_nota_homologacion_id_plantilla_nota_homologacion_seq")
	public long getIdPlantillaNotaHomologacion() {
		return this.idPlantillaNotaHomologacion;
	}

	public void setIdPlantillaNotaHomologacion(long idPlantillaNotaHomologacion) {
		this.idPlantillaNotaHomologacion = idPlantillaNotaHomologacion;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	

	@Column(name = "referencia", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "titulo_1", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getTitulo1() {
		return this.titulo1;
	}

	public void setTitulo1(String titulo1) {
		this.titulo1 = titulo1;
	}

	@Column(name = "titulo_2", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getTitulo2() {
		return this.titulo2;
	}

	public void setTitulo2(String titulo2) {
		this.titulo2 = titulo2;
	}

	@Column(name = "cuerpo", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

	@Column(name = "firma", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	@Column(name = "cargo", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "institucion_firma", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getInstitucionFirma() {
		return this.institucionFirma;
	}

	public void setInstitucionFirma(String institucionFirma) {
		this.institucionFirma = institucionFirma;
	}

	@Column(name = "a", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getA() {
		return this.a;
	}

	public void setA(String a) {
		this.a = a;
	}

	@Column(name = "don", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDon() {
		return this.don;
	}

	public void setDon(String don) {
		this.don = don;
	}

	@Column(name = "item_final", length = 250)
	@Length(max = 250)
	public String getItemFinal() {
		return this.itemFinal;
	}

	public void setItemFinal(String itemFinal) {
		this.itemFinal = itemFinal;
	}

	@Column(name = "institucion", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantillaNotaHomologacion")
	public Set<NotaHomologacion> getNotaHomologacions() {
		return this.notaHomologacions;
	}

	public void setNotaHomologacions(Set<NotaHomologacion> notaHomologacions) {
		this.notaHomologacions = notaHomologacions;
	}

}
