package py.com.excelsis.sicca.entity;

// Generated 25/09/2012 10:17:38 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlantillaEvalPdecDet generated by hbm2java
 */
@Entity
@Table(name = "plantilla_eval_pdec_det", schema = "eval_desempeno")
public class PlantillaEvalPdecDet implements java.io.Serializable {

	private Long idPlantillaEvalPdecDet;
	private PlantillaEvalPdecCab plantillaEvalPdecCab;
	private String descripcion;

	public PlantillaEvalPdecDet() {
	}

	public PlantillaEvalPdecDet(Long idPlantillaEvalPdecDet,
			PlantillaEvalPdecCab plantillaEvalPdecCab, String descripcion) {
		this.idPlantillaEvalPdecDet = idPlantillaEvalPdecDet;
		this.plantillaEvalPdecCab = plantillaEvalPdecCab;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id_plantilla_eval_pdec_det", unique = true, nullable = false)
	@GeneratedValue(generator="PLANTILLA_EVAL_PDEC_DET_GENERATOR")
	@SequenceGenerator(name="PLANTILLA_EVAL_PDEC_DET_GENERATOR",sequenceName="eval_desempeno.plantilla_eval_pdec_det_id_plantilla_eval_pdec_det_seq")
	public Long getIdPlantillaEvalPdecDet() {
		return this.idPlantillaEvalPdecDet;
	}

	public void setIdPlantillaEvalPdecDet(Long idPlantillaEvalPdecDet) {
		this.idPlantillaEvalPdecDet = idPlantillaEvalPdecDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_eval_pdec_cab", nullable = false)
	@NotNull
	public PlantillaEvalPdecCab getPlantillaEvalPdecCab() {
		return this.plantillaEvalPdecCab;
	}

	public void setPlantillaEvalPdecCab(
			PlantillaEvalPdecCab plantillaEvalPdecCab) {
		this.plantillaEvalPdecCab = plantillaEvalPdecCab;
	}

	@Column(name = "descripcion", nullable = false, length = 3000)
	@NotNull
	@Length(max = 3000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
