package py.com.excelsis.sicca.entity;

// Generated 25/09/2012 10:17:38 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlanMejora generated by hbm2java
 */
@Entity
@Table(name = "plan_mejora", schema = "eval_desempeno")
public class PlanMejora implements java.io.Serializable {

	private Long idPlanMejora;
	private Long identificador;
	private String descripcion;
	private ConfiguracionUoCab configuracionUo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean selected = false;

	public PlanMejora() {
	}

	public PlanMejora(
			Long idPlanMejora, String descripcion, ConfiguracionUoCab idConfiguracionUo,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idPlanMejora = idPlanMejora;
		this.descripcion = descripcion;
		this.configuracionUo = idConfiguracionUo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PlanMejora(
			Long idPlanMejora, Long identificador, String descripcion,
			ConfiguracionUoCab idConfiguracionUo, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idPlanMejora = idPlanMejora;
		this.identificador = identificador;
		this.descripcion = descripcion;
		this.configuracionUo = idConfiguracionUo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_plan_mejora", unique = true, nullable = false)
	@GeneratedValue(generator = "PLAN_MEJORA_GENERATOR")
	@SequenceGenerator(name = "PLAN_MEJORA_GENERATOR", sequenceName = "eval_desempeno.plan_mejora_id_plan_mejora_seq")
	public Long getIdPlanMejora() {
		return this.idPlanMejora;
	}

	public void setIdPlanMejora(Long idPlanMejora) {
		this.idPlanMejora = idPlanMejora;
	}

	@Column(name = "identificador")
	public Long getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(Long identificador) {
		this.identificador = identificador;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	@NotNull
	public ConfiguracionUoCab getConfiguracionUo() {
		return configuracionUo;
	}

	public void setConfiguracionUo(ConfiguracionUoCab configuracionUo) {
		this.configuracionUo = configuracionUo;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Transient
	public Boolean getSelected() {
		return selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

}
