package py.com.excelsis.sicca.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Properties;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.EntityBase;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * PlantaCargoDet generated by Generality
 */
@Entity
@Table(name = "planta_cargo_det", schema = "planificacion")
public class PlantaCargoDet extends EntityBase implements Comparable {
	private Long idPlantaCargoDet;
	private String descripcion;
	private String fundamentacionTecnica;
	private String mision;
	private String objetivo;
	private Boolean contratado;
	private Boolean permanente;
	private Boolean comisionado;//MODIFICADO RV
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Boolean activo;
	private Boolean jefatura;
	private Date luHoraDesde;
	private Date maHoraDesde;
	private Date miHoraDesde;
	private Date juHoraDesde;
	private Date viHoraDesde;
	private Date saHoraDesde;
	private Date doHoraDesde;
	private Date luHoraHasta;
	private Date maHoraHasta;
	private Date miHoraHasta;
	private Date juHoraHasta;
	private Date viHoraHasta;
	private Date saHoraHasta;
	private Date doHoraHasta;
	private ConfiguracionUoDet configuracionUoDet;
	private EstadoCab estadoCab;
	private Cpt cpt;
	private Oficina oficina;
	private Entidad entidad;
	private Integer orden;
	private Especialidades especialidades;
	private EstadoDet estadoDet;
	private Boolean seleccionado;
	private Boolean esPlantilla;
	private Set<DocumentoActo> documentoActos = new HashSet<DocumentoActo>(0);
	private Set<DetReqMin> detReqMins = new HashSet<DetReqMin>(0);
	private Set<DetContenidoFuncional> detContenidoFuncionals =
		new HashSet<DetContenidoFuncional>(0);
	private Set<DetCondicionTrabajo> detCondicionTrabajos = new HashSet<DetCondicionTrabajo>(0);
	private List<DetTipoNombramiento> detTipoNombramientos = new ArrayList<DetTipoNombramiento>(0);
	private Set<DetCondicionSegur> detCondicionSegurs = new HashSet<DetCondicionSegur>(0);
	private Set<HistoricosEstado> historicosEstados = new HashSet<HistoricosEstado>(0);
	private Set<DetCondicionTrabajoEspecif> detCondicionTrabajoEspecifs =
		new HashSet<DetCondicionTrabajoEspecif>(0);
	private Set<PuestoConceptoPago> puestoConceptoPagos = new HashSet<PuestoConceptoPago>(0);
	private Set<ExcepcionGrPuesto> excepcionGrPuestos = new HashSet<ExcepcionGrPuesto>(0);
	private Set<ConcursoPuestoDet> concursoPuestoDets= new HashSet<ConcursoPuestoDet>(0);
	private List<EmpleadoPuesto> empleadoPuestos = new ArrayList<EmpleadoPuesto>();

	public PlantaCargoDet() {
	}

	public PlantaCargoDet(
			Long idPlantaCargoDet, Cpt cpt, Oficina oficina, ConfiguracionUoDet configuracionUoDet,
			String descripcion, String fundamentacionTecnica, String mision, String objetivo,
			Boolean contratado, Boolean permanente, Boolean comisionado, String usuAlta, Date fechaAlta, Boolean activo,
			Date luHoraDesde, Date maHoraDesde, Date miHoraDesde, Date juHoraDesde,
			Date viHoraDesde, Date saHoraDesde, Date doHoraDesde, Date luHoraHasta,
			Date maHoraHasta, Date miHoraHasta, Date juHoraHasta, Date viHoraHasta,
			Date saHoraHasta, Date doHoraHasta) {
		this.idPlantaCargoDet = idPlantaCargoDet;
		this.cpt = cpt;
		this.oficina = oficina;
		this.configuracionUoDet = configuracionUoDet;
		this.descripcion = descripcion;
		this.fundamentacionTecnica = fundamentacionTecnica;
		this.mision = mision;
		this.objetivo = objetivo;
		this.contratado = contratado;
		this.permanente = permanente;
		this.comisionado = comisionado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.luHoraDesde = luHoraDesde;
		this.maHoraDesde = maHoraDesde;
		this.miHoraDesde = miHoraDesde;
		this.juHoraDesde = juHoraDesde;
		this.viHoraDesde = viHoraDesde;
		this.saHoraDesde = saHoraDesde;
		this.doHoraDesde = doHoraDesde;
		this.luHoraHasta = luHoraHasta;
		this.maHoraHasta = maHoraHasta;
		this.miHoraHasta = miHoraHasta;
		this.juHoraHasta = juHoraHasta;
		this.viHoraHasta = viHoraHasta;
		this.saHoraHasta = saHoraHasta;
		this.doHoraHasta = doHoraHasta;
	}

	public PlantaCargoDet(
			Long idPlantaCargoDet, Cpt cpt, Oficina oficina, EstadoCab estadoCab,
			ConfiguracionUoDet configuracionUoDet, String descripcion,
			String fundamentacionTecnica, String mision, String objetivo, Boolean contratado,
			Boolean permanente, Boolean comisionado, String usuAlta, String usuMod, Date fechaMod, Date fechaAlta,
			Boolean activo, Date luHoraDesde, Date maHoraDesde, Date miHoraDesde, Date juHoraDesde,
			Date viHoraDesde, Date saHoraDesde, Date doHoraDesde, Date luHoraHasta,
			Date maHoraHasta, Date miHoraHasta, Date juHoraHasta, Date viHoraHasta,
			Date saHoraHasta, Date doHoraHasta, Entidad entidad, Set<DocumentoActo> documentoActos,
			Set<DetReqMin> detReqMins, Set<DetContenidoFuncional> detContenidoFuncionals,
			Set<DetCondicionTrabajo> detCondicionTrabajos,
			List<DetTipoNombramiento> detTipoNombramientos,
			Set<DetCondicionSegur> detCondicionSegurs, Set<HistoricosEstado> historicosEstados,
			Set<DetCondicionTrabajoEspecif> detCondicionTrabajoEspecifs,
			Set<PuestoConceptoPago> puestoConceptoPagos) {
		this.idPlantaCargoDet = idPlantaCargoDet;
		this.cpt = cpt;
		this.oficina = oficina;
		this.estadoCab = estadoCab;
		this.configuracionUoDet = configuracionUoDet;
		this.descripcion = descripcion;
		this.fundamentacionTecnica = fundamentacionTecnica;
		this.mision = mision;
		this.objetivo = objetivo;
		this.contratado = contratado;
		this.permanente = permanente;
		this.comisionado = comisionado;
		this.usuAlta = usuAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.fechaAlta = fechaAlta;
		this.activo = activo;
		this.luHoraDesde = luHoraDesde;
		this.maHoraDesde = maHoraDesde;
		this.miHoraDesde = miHoraDesde;
		this.juHoraDesde = juHoraDesde;
		this.viHoraDesde = viHoraDesde;
		this.saHoraDesde = saHoraDesde;
		this.doHoraDesde = doHoraDesde;
		this.luHoraHasta = luHoraHasta;
		this.maHoraHasta = maHoraHasta;
		this.miHoraHasta = miHoraHasta;
		this.juHoraHasta = juHoraHasta;
		this.viHoraHasta = viHoraHasta;
		this.saHoraHasta = saHoraHasta;
		this.doHoraHasta = doHoraHasta;
		this.entidad = entidad;
		this.documentoActos = documentoActos;
		this.detReqMins = detReqMins;
		this.detContenidoFuncionals = detContenidoFuncionals;
		this.detCondicionTrabajos = detCondicionTrabajos;
		this.detTipoNombramientos = detTipoNombramientos;
		this.detCondicionSegurs = detCondicionSegurs;
		this.historicosEstados = historicosEstados;
		this.detCondicionTrabajoEspecifs = detCondicionTrabajoEspecifs;
		this.puestoConceptoPagos = puestoConceptoPagos;
	}

	@Id
	@GeneratedValue(generator = "PLANTA_CARGO_DET_GENERATOR")
	@SequenceGenerator(name = "PLANTA_CARGO_DET_GENERATOR", sequenceName = "planificacion.planta_cargo_det_id_planta_cargo_det_seq")
	@Column(name = "id_planta_cargo_det")
	public Long getIdPlantaCargoDet() {
		return this.idPlantaCargoDet;
	}

	public void setIdPlantaCargoDet(Long idPlantaCargoDet) {
		this.idPlantaCargoDet = idPlantaCargoDet;
	}

	@Column(name = "descripcion")
	@Length(max = 200, message = "#{messages.GENERICO_NO_SUPERAR_MAX_LEN_TEXTO}")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "fundamentacion_tecnica")
	@Length(max = 250, message = "#{messages.GENERICO_NO_SUPERAR_MAX_LEN_TEXTO}")
	public String getFundamentacionTecnica() {
		return this.fundamentacionTecnica;
	}

	public void setFundamentacionTecnica(String fundamentacionTecnica) {
		this.fundamentacionTecnica = fundamentacionTecnica;
	}

	@Column(name = "mision")
	@Length(max = 500, message = "#{messages.GENERICO_NO_SUPERAR_MAX_LEN_TEXTO}")
	public String getMision() {
		return this.mision;
	}

	public void setMision(String mision) {
		this.mision = mision;
	}

	@Column(name = "objetivo")
	@Length(max = 500, message = "#{messages.GENERICO_NO_SUPERAR_MAX_LEN_TEXTO}")
	public String getObjetivo() {
		return this.objetivo;
	}

	public void setObjetivo(String objetivo) {
		this.objetivo = objetivo;
	}

	@Column(name = "contratado")
	public Boolean getContratado() {
		return this.contratado;
	}

	public void setContratado(Boolean contratado) {
		this.contratado = contratado;
	}

	@Column(name = "permanente")
	public Boolean getPermanente() {
		return this.permanente;
	}

	public void setPermanente(Boolean permanente) {
		this.permanente = permanente;
	}

	@Column(name = "comisionado")//MODIFICADO RV
	public Boolean getComisionado() {
		return this.comisionado;
	}

	public void setComisionado(Boolean comisionado) {
		this.comisionado = comisionado;
	}
	
	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "es_plantilla")
	public Boolean getEsPlantilla() {
		return esPlantilla;
	}

	public void setEsPlantilla(Boolean esPlantilla) {
		this.esPlantilla = esPlantilla;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lu_hora_desde")
	public Date getLuHoraDesde() {
		return this.luHoraDesde;
	}

	public void setLuHoraDesde(Date luHoraDesde) {
		this.luHoraDesde = luHoraDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ma_hora_desde")
	public Date getMaHoraDesde() {
		return this.maHoraDesde;
	}

	public void setMaHoraDesde(Date maHoraDesde) {
		this.maHoraDesde = maHoraDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mi_hora_desde")
	public Date getMiHoraDesde() {
		return this.miHoraDesde;
	}

	public void setMiHoraDesde(Date miHoraDesde) {
		this.miHoraDesde = miHoraDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ju_hora_desde")
	public Date getJuHoraDesde() {
		return this.juHoraDesde;
	}

	public void setJuHoraDesde(Date juHoraDesde) {
		this.juHoraDesde = juHoraDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vi_hora_desde")
	public Date getViHoraDesde() {
		return this.viHoraDesde;
	}

	public void setViHoraDesde(Date viHoraDesde) {
		this.viHoraDesde = viHoraDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sa_hora_desde")
	public Date getSaHoraDesde() {
		return this.saHoraDesde;
	}

	public void setSaHoraDesde(Date saHoraDesde) {
		this.saHoraDesde = saHoraDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "do_hora_desde")
	public Date getDoHoraDesde() {
		return this.doHoraDesde;
	}

	public void setDoHoraDesde(Date doHoraDesde) {
		this.doHoraDesde = doHoraDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lu_hora_hasta")
	public Date getLuHoraHasta() {
		return this.luHoraHasta;
	}

	public void setLuHoraHasta(Date luHoraHasta) {
		this.luHoraHasta = luHoraHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ma_hora_hasta")
	public Date getMaHoraHasta() {
		return this.maHoraHasta;
	}

	public void setMaHoraHasta(Date maHoraHasta) {
		this.maHoraHasta = maHoraHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mi_hora_hasta")
	public Date getMiHoraHasta() {
		return this.miHoraHasta;
	}

	public void setMiHoraHasta(Date miHoraHasta) {
		this.miHoraHasta = miHoraHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ju_hora_hasta")
	public Date getJuHoraHasta() {
		return this.juHoraHasta;
	}

	public void setJuHoraHasta(Date juHoraHasta) {
		this.juHoraHasta = juHoraHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vi_hora_hasta")
	public Date getViHoraHasta() {
		return this.viHoraHasta;
	}

	public void setViHoraHasta(Date viHoraHasta) {
		this.viHoraHasta = viHoraHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sa_hora_hasta")
	public Date getSaHoraHasta() {
		return this.saHoraHasta;
	}

	public void setSaHoraHasta(Date saHoraHasta) {
		this.saHoraHasta = saHoraHasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "do_hora_hasta")
	public Date getDoHoraHasta() {
		return this.doHoraHasta;
	}

	public void setDoHoraHasta(Date doHoraHasta) {
		this.doHoraHasta = doHoraHasta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo_det")
	public ConfiguracionUoDet getConfiguracionUoDet() {
		return this.configuracionUoDet;
	}

	public void setConfiguracionUoDet(ConfiguracionUoDet configuracionUoDet) {
		this.configuracionUoDet = configuracionUoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_cab")
	public EstadoCab getEstadoCab() {
		return this.estadoCab;
	}

	public void setEstadoCab(EstadoCab estadoCab) {
		this.estadoCab = estadoCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_det")
	public EstadoDet getEstadoDet() {
		return estadoDet;
	}

	public void setEstadoDet(EstadoDet estadoDet) {
		this.estadoDet = estadoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cpt")
	public Cpt getCpt() {
		return this.cpt;
	}

	public void setCpt(Cpt cpt) {
		this.cpt = cpt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oficina")
	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad getEntidad() {
		return entidad;
	}

	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}

	@Column(name = "orden", nullable = false)
	@NotNull
	public Integer getOrden() {
		return orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_especialidades")
	public Especialidades getEspecialidades() {
		return especialidades;
	}

	public void setEspecialidades(Especialidades especialidades) {
		this.especialidades = especialidades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<DocumentoActo> getDocumentoActos() {
		return this.documentoActos;
	}

	public void setDocumentoActos(Set<DocumentoActo> documentoActos) {
		this.documentoActos = documentoActos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<DetReqMin> getDetReqMins() {
		return this.detReqMins;
	}

	public void setDetReqMins(Set<DetReqMin> detReqMins) {
		this.detReqMins = detReqMins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<DetContenidoFuncional> getDetContenidoFuncionals() {
		return this.detContenidoFuncionals;
	}

	public void setDetContenidoFuncionals(Set<DetContenidoFuncional> detContenidoFuncionals) {
		this.detContenidoFuncionals = detContenidoFuncionals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<DetCondicionTrabajo> getDetCondicionTrabajos() {
		return this.detCondicionTrabajos;
	}

	public void setDetCondicionTrabajos(Set<DetCondicionTrabajo> detCondicionTrabajos) {
		this.detCondicionTrabajos = detCondicionTrabajos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public List<DetTipoNombramiento> getDetTipoNombramientos() {
		return this.detTipoNombramientos;
	}

	public void setDetTipoNombramientos(List<DetTipoNombramiento> detTipoNombramientos) {
		this.detTipoNombramientos = detTipoNombramientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<DetCondicionSegur> getDetCondicionSegurs() {
		return this.detCondicionSegurs;
	}

	public void setDetCondicionSegurs(Set<DetCondicionSegur> detCondicionSegurs) {
		this.detCondicionSegurs = detCondicionSegurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<HistoricosEstado> getHistoricosEstados() {
		return this.historicosEstados;
	}

	public void setHistoricosEstados(Set<HistoricosEstado> historicosEstados) {
		this.historicosEstados = historicosEstados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<DetCondicionTrabajoEspecif> getDetCondicionTrabajoEspecifs() {
		return this.detCondicionTrabajoEspecifs;
	}

	public void setDetCondicionTrabajoEspecifs(Set<DetCondicionTrabajoEspecif> detCondicionTrabajoEspecifs) {
		this.detCondicionTrabajoEspecifs = detCondicionTrabajoEspecifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<PuestoConceptoPago> getPuestoConceptoPagos() {
		return this.puestoConceptoPagos;
	}

	public void setPuestoConceptoPagos(Set<PuestoConceptoPago> puestoConceptoPagos) {
		this.puestoConceptoPagos = puestoConceptoPagos;

	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<ExcepcionGrPuesto> getExcepcionGrPuestos() {
		return this.excepcionGrPuestos;
	}

	public void setExcepcionGrPuestos(Set<ExcepcionGrPuesto> excepcionGrPuestos) {
		this.excepcionGrPuestos = excepcionGrPuestos;
	}

	@Transient
	public Long getId() {
		return idPlantaCargoDet;
	}

	/**
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.PLANTA_CARGO_DET_ID, getId());
		properties.put(SICCASessionParameters.PLANTA_CARGO_DET_DESCRIPCION, descripcion);

		return properties;
	}

	/**
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}

	public int compareTo(Object o) {
		PlantaCargoDet plantaCargoDet = (PlantaCargoDet) o;
		return this.orden.compareTo(plantaCargoDet.orden);
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public List<EmpleadoPuesto> getEmpleadoPuestos() {
		return empleadoPuestos;
	}

	public void setEmpleadoPuestos(List<EmpleadoPuesto> empleadoPuestos) {
		this.empleadoPuestos = empleadoPuestos;
	}

	@Column(name = "jefatura")
	public Boolean getJefatura() {
		return jefatura;
	}

	public void setJefatura(Boolean jefatura) {
		this.jefatura = jefatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantaCargoDet")
	public Set<ConcursoPuestoDet> getConcursoPuestoDets() {
		return concursoPuestoDets;
	}

	public void setConcursoPuestoDets(Set<ConcursoPuestoDet> concursoPuestoDets) {
		this.concursoPuestoDets = concursoPuestoDets;
	}

	@Transient
	public Boolean getSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(Boolean seleccionado) {
		this.seleccionado = seleccionado;
	}
	
	/**
	 * Valida que el puesto haya sido creado correctamente. 
	 * Retorna el string "Ok" si la validacion es correcta.
	 * Si hay un error, retorna un String que describe el error,
	 * ideal para usarse por ejemplo con StatusMessages.
	 * @return      Una cadena "Ok" si esta bien. Una cadena describiendo el error si está mal.
	 */
	public String validarCondiciones() {
		if (this.getDetCondicionSegurs().size() < 7) {
			return "No se han completado las Condiciones de Seguridad del puesto "+ this.descripcion +". Verifique.";
		}
		if (this.getDetCondicionTrabajos().size() < 4) {
			return "No se han completado las Condiciones de Trabajo del puesto "+ this.descripcion +". Verifique.";
		}
		if (this.getDetCondicionTrabajoEspecifs().size() < 18) {
			return "No se han completado las condiciones de trabajo especificas del puesto "+ this.descripcion +". Verifique.";
		}
		if (this.getDetContenidoFuncionals().size() == 0) {
			return "No se ha completado el Contenido Funcional del puesto "+ this.descripcion +". Verifique.";
		}

		return "Ok";
	}
	

}
