package py.com.excelsis.sicca.entity;

// Generated 10/09/2012 04:57:06 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlantillaEvalPdec generated by hbm2java
 */
@Entity
@Table(name = "plantilla_eval_pdec", schema = "eval_desempeno")
public class PlantillaEvalPdec implements java.io.Serializable {

	private Long idPlantillaEvalPdec;
	private Sujetos sujetos;
	private GrupoMetodologia grupoMetodologia;
	private String tipo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<PlantillaEvalPdecCab> plantillaEvalPdecCabs = new HashSet<PlantillaEvalPdecCab>(0);

	private GruposSujetos grupoSujeto = null;
	
	//agregado; Werner.
	private String comentarioPdec;

	public PlantillaEvalPdec() {
	}

	public PlantillaEvalPdec(
			Long idPlantillaEvalPdec, GrupoMetodologia grupoMetodologia, String tipo,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idPlantillaEvalPdec = idPlantillaEvalPdec;
		this.grupoMetodologia = grupoMetodologia;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PlantillaEvalPdec(
			Long idPlantillaEvalPdec, Sujetos sujetos, GrupoMetodologia grupoMetodologia,
			String tipo, Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Set<PlantillaEvalPdecCab> plantillaEvalPdecCabs, String comentarioPdec) {
		this.idPlantillaEvalPdec = idPlantillaEvalPdec;
		this.sujetos = sujetos;
		this.grupoMetodologia = grupoMetodologia;
		this.tipo = tipo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.plantillaEvalPdecCabs = plantillaEvalPdecCabs;
		this.comentarioPdec = comentarioPdec;
	}

	@Id
	@Column(name = "id_plantilla_eval_pdec", unique = true, nullable = false)
	@GeneratedValue(generator = "PLANTILLA_EVAL_PDEC_GENERATOR")
	@SequenceGenerator(name = "PLANTILLA_EVAL_PDEC_GENERATOR", sequenceName = "eval_desempeno.plantilla_eval_pdec_id_plantilla_eval_pdec_seq")
	public Long getIdPlantillaEvalPdec() {
		return this.idPlantillaEvalPdec;
	}

	public void setIdPlantillaEvalPdec(Long idPlantillaEvalPdec) {
		this.idPlantillaEvalPdec = idPlantillaEvalPdec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sujetos")
	public Sujetos getSujetos() {
		return this.sujetos;
	}

	public void setSujetos(Sujetos sujetos) {
		this.sujetos = sujetos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_metodologia", nullable = false)
	@NotNull
	public GrupoMetodologia getGrupoMetodologia() {
		return this.grupoMetodologia;
	}

	public void setGrupoMetodologia(GrupoMetodologia grupoMetodologia) {
		this.grupoMetodologia = grupoMetodologia;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plantillaEvalPdec")
	public Set<PlantillaEvalPdecCab> getPlantillaEvalPdecCabs() {
		return this.plantillaEvalPdecCabs;
	}

	public void setPlantillaEvalPdecCabs(Set<PlantillaEvalPdecCab> plantillaEvalPdecCabs) {
		this.plantillaEvalPdecCabs = plantillaEvalPdecCabs;
	}

	
	@Transient
	public GruposSujetos getGrupoSujeto() {
		return grupoSujeto;
	}

	public void setGrupoSujeto(GruposSujetos grupoSujeto) {
		this.grupoSujeto = grupoSujeto;
	}
	
	@Column(name = "comentario_pdec", length = 1000)
	@Length(max = 1000)
	public String getComentarioPdec() {
		return comentarioPdec;
	}

	public void setComentarioPdec(String comentarioPdec) {
		this.comentarioPdec = comentarioPdec;
	}
}
