package py.com.excelsis.sicca.entity;

// Generated 10/09/2012 04:57:06 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PlantillaResolucionEval generated by hbm2java
 */
@Entity
@Table(name = "plantilla_resolucion_eval", schema = "eval_desempeno")
public class PlantillaResolucionEval implements java.io.Serializable {

	private Long idPlantillaResolucionEval;
	private String descripcion;
	private String titulo;
	private String visto;
	private String considerando;
	private String porTanto;
	private String resuelve;
	private String firma;
	private String cargo;
	private String institucion;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public PlantillaResolucionEval() {
	}

	public PlantillaResolucionEval(Long idPlantillaResolucionEval,
			String descripcion, String titulo, String visto,
			String considerando, String porTanto, String resuelve,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idPlantillaResolucionEval = idPlantillaResolucionEval;
		this.descripcion = descripcion;
		this.titulo = titulo;
		this.visto = visto;
		this.considerando = considerando;
		this.porTanto = porTanto;
		this.resuelve = resuelve;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PlantillaResolucionEval(Long idPlantillaResolucionEval,
			String descripcion, String titulo, String visto,
			String considerando, String porTanto, String resuelve,
			String firma, String cargo, String institucion, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idPlantillaResolucionEval = idPlantillaResolucionEval;
		this.descripcion = descripcion;
		this.titulo = titulo;
		this.visto = visto;
		this.considerando = considerando;
		this.porTanto = porTanto;
		this.resuelve = resuelve;
		this.firma = firma;
		this.cargo = cargo;
		this.institucion = institucion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_plantilla_resolucion_eval", unique = true, nullable = false)
	@GeneratedValue(generator = "PLANTILLA_RESOLUCION_GENERATOR")
	@SequenceGenerator(name = "PLANTILLA_RESOLUCION_GENERATOR", sequenceName = "eval_desempeno.plantilla_eval_id_plantilla_eval_seq")
	public Long getIdPlantillaResolucionEval() {
		return this.idPlantillaResolucionEval;
	}

	public void setIdPlantillaResolucionEval(Long idPlantillaResolucionEval) {
		this.idPlantillaResolucionEval = idPlantillaResolucionEval;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "titulo", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "visto", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getVisto() {
		return this.visto;
	}

	public void setVisto(String visto) {
		this.visto = visto;
	}

	@Column(name = "considerando", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getConsiderando() {
		return this.considerando;
	}

	public void setConsiderando(String considerando) {
		this.considerando = considerando;
	}

	@Column(name = "por_tanto", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getPorTanto() {
		return this.porTanto;
	}

	public void setPorTanto(String porTanto) {
		this.porTanto = porTanto;
	}

	@Column(name = "resuelve", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getResuelve() {
		return this.resuelve;
	}

	public void setResuelve(String resuelve) {
		this.resuelve = resuelve;
	}

	@Column(name = "firma", length = 250)
	@Length(max = 250)
	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	@Column(name = "cargo", length = 250)
	@Length(max = 250)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "institucion", length = 250)
	@Length(max = 250)
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
