package py.com.excelsis.sicca.entity;

// Generated 17-nov-2011 17:00:10 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Postulacion generated by hbm2java
 */
@Entity
@Table(name = "postulacion", schema = "seleccion")
public class Postulacion implements java.io.Serializable {

	private Long idPostulacion;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private PersonaPostulante personaPostulante;
	private boolean activo;
	private String usuPostulacion;
	private Date fechaPostulacion;
	private String obsCancelacion;
	private String usuCancelacion;
	private String usuAltaOee;
	private String tipo;
	private Date fechaCancelacion;
	private Date fechaAltaOee;
	private String interesCargo;
	private Excepcion excepcion;
	private String usuModif;
	private Date fechaModif;
	private Boolean seleccionado;
	private Persona persona;
	private String usuModOee;
	private Date fechaModOee;
	private DatosEspecificos datosEspecificosTipoCanc;
	private Date fechaSorteo;
	private String usuAltaSorteo;
	private Date fechaAltaSorteo;
	private String estadoPostulacion;
	
	private Set<PostulacionAdjuntos> postulacionAdjuntoses = new HashSet<PostulacionAdjuntos>(0);
	private Set<EvalDocumentalCab> evalDocumentalCabs = new HashSet<EvalDocumentalCab>(0);
	private Set<DetListaElegibles> detListaElegibleses = new HashSet<DetListaElegibles>(0);
	//Posibles estados de la postulación durante el proceso de Selección;
	public static final String ESTADO_POSTULACION_CANCELADO = "CANCELADO";
	public static final String ESTADO_POSTULACION_EXCLUIDO = "EXCLUIDO";
	public static final String ESTADO_POSTULACION_ACTIVO = "ACTIVO";

	public Postulacion() {
	}

	public Postulacion(
			Long idPostulacion, ConcursoPuestoAgr concursoPuestoAgr,
			PersonaPostulante personaPostulante, boolean activo, String usuPostulacion,
			Date fechaPostulacion) {
		this.idPostulacion = idPostulacion;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.personaPostulante = personaPostulante;
		this.activo = activo;
		this.usuPostulacion = usuPostulacion;
		this.fechaPostulacion = fechaPostulacion;
	}

	public Postulacion(
			Long idPostulacion, ConcursoPuestoAgr concursoPuestoAgr,
			PersonaPostulante personaPostulante, boolean activo, String usuPostulacion,
			Date fechaPostulacion, String obsCancelacion, String usuCancelacion,
			Date fechaCancelacion, String interesCargo,
			Set<PostulacionAdjuntos> postulacionAdjuntoses,
			Set<EvalDocumentalCab> evalDocumentalCabs) {
		this.idPostulacion = idPostulacion;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.personaPostulante = personaPostulante;
		this.activo = activo;
		this.usuPostulacion = usuPostulacion;
		this.fechaPostulacion = fechaPostulacion;
		this.obsCancelacion = obsCancelacion;
		this.usuCancelacion = usuCancelacion;
		this.fechaCancelacion = fechaCancelacion;
		this.interesCargo = interesCargo;
		this.postulacionAdjuntoses = postulacionAdjuntoses;
		this.evalDocumentalCabs = evalDocumentalCabs;
	}

	@Id
	@GeneratedValue(generator = "POSTULACIONES_GENERATOR")
	@SequenceGenerator(name = "POSTULACIONES_GENERATOR", sequenceName = "seleccion.postulacion_id_postulacion_seq")
	@Column(name = "id_postulacion", unique = true, nullable = false)
	public Long getIdPostulacion() {
		return this.idPostulacion;
	}

	public void setIdPostulacion(Long idPostulacion) {
		this.idPostulacion = idPostulacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr", nullable = false)
	@NotNull
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_postulante", nullable = true)
	public PersonaPostulante getPersonaPostulante() {
		return this.personaPostulante;
	}

	public void setPersonaPostulante(PersonaPostulante personaPostulante) {
		this.personaPostulante = personaPostulante;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_postulacion", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuPostulacion() {
		return this.usuPostulacion;
	}

	public void setUsuPostulacion(String usuPostulacion) {
		this.usuPostulacion = usuPostulacion;
	}
	@Column(name = "estado_postulacion", length = 50)
	@Length(max = 50)
	public String getEstadoPostulacion() {
		return estadoPostulacion;
	}

	public void setEstadoPostulacion(String estadoPostulacion) {
		this.estadoPostulacion = estadoPostulacion;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_postulacion", nullable = false, length = 29)
	@NotNull
	public Date getFechaPostulacion() {
		return this.fechaPostulacion;
	}

	public void setFechaPostulacion(Date fechaPostulacion) {
		this.fechaPostulacion = fechaPostulacion;
	}

	@Column(name = "obs_cancelacion", length = 1000)
	@Length(max = 1000)
	public String getObsCancelacion() {
		return this.obsCancelacion;
	}

	public void setObsCancelacion(String obsCancelacion) {
		this.obsCancelacion = obsCancelacion;
	}

	@Column(name = "usu_cancelacion", length = 50)
	@Length(max = 50)
	public String getUsuCancelacion() {
		return this.usuCancelacion;
	}

	public void setUsuCancelacion(String usuCancelacion) {
		this.usuCancelacion = usuCancelacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cancelacion", length = 29)
	public Date getFechaCancelacion() {
		return this.fechaCancelacion;
	}

	public void setFechaCancelacion(Date fechaCancelacion) {
		this.fechaCancelacion = fechaCancelacion;
	}

	@Column(name = "interes_cargo", length = 1000)
	@Length(max = 1000)
	public String getInteresCargo() {
		return this.interesCargo;
	}

	public void setInteresCargo(String interesCargo) {
		this.interesCargo = interesCargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_excepcion")
	public Excepcion getExcepcion() {
		return excepcion;
	}

	public void setExcepcion(Excepcion excepcion) {
		this.excepcion = excepcion;
	}

	@Column(name = "usu_modif", length = 50)
	@Length(max = 50)
	public String getUsuModif() {
		return usuModif;
	}

	public void setUsuModif(String usuModif) {
		this.usuModif = usuModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modif", length = 29)
	public Date getFechaModif() {
		return fechaModif;
	}

	public void setFechaModif(Date fechaModif) {
		this.fechaModif = fechaModif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postulacion")
	public Set<PostulacionAdjuntos> getPostulacionAdjuntoses() {
		return this.postulacionAdjuntoses;
	}

	public void setPostulacionAdjuntoses(Set<PostulacionAdjuntos> postulacionAdjuntoses) {
		this.postulacionAdjuntoses = postulacionAdjuntoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postulacion")
	public Set<EvalDocumentalCab> getEvalDocumentalCabs() {
		return this.evalDocumentalCabs;
	}

	public void setEvalDocumentalCabs(Set<EvalDocumentalCab> evalDocumentalCabs) {
		this.evalDocumentalCabs = evalDocumentalCabs;
	}

	@Column(name = "seleccionado")
	public Boolean getSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(Boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

	@Column(name = "tipo", length = 100)
	@Length(max = 100)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_canc")
	public DatosEspecificos getDatosEspecificosTipoCanc() {
		return datosEspecificosTipoCanc;
	}

	public void setDatosEspecificosTipoCanc(DatosEspecificos datosEspecificosTipoCanc) {
		this.datosEspecificosTipoCanc = datosEspecificosTipoCanc;
	}

	@Column(name = "usu_alta_oee", length = 50)
	@Length(max = 50)
	public String getUsuAltaOee() {
		return usuAltaOee;
	}

	public void setUsuAltaOee(String usuAltaOee) {
		this.usuAltaOee = usuAltaOee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta_oee", length = 29)
	public Date getFechaAltaOee() {
		return fechaAltaOee;
	}

	public void setFechaAltaOee(Date fechaAltaOee) {
		this.fechaAltaOee = fechaAltaOee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod_oee", length = 29)
	public Date getFechaModOee() {
		return fechaModOee;
	}

	public void setFechaModOee(Date fechaModOee) {
		this.fechaModOee = fechaModOee;
	}

	@Column(name = "usu_mod_oee", length = 50)
	public String getUsuModOee() {
		return usuModOee;
	}

	public void setUsuModOee(String usuModOee) {
		this.usuModOee = usuModOee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postulacion")
	public Set<DetListaElegibles> getDetListaElegibleses() {
		return this.detListaElegibleses;
	}

	public void setDetListaElegibleses(Set<DetListaElegibles> detListaElegibleses) {
		this.detListaElegibleses = detListaElegibleses;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_sorteo", length = 29)
	public Date getFechaSorteo() {
		return fechaSorteo;
	}

	public void setFechaSorteo(Date fechaSorteo) {
		this.fechaSorteo = fechaSorteo;
	}

	@Column(name = "usu_alta_sorteo", length = 50)
	public String getUsuAltaSorteo() {
		return usuAltaSorteo;
	}

	public void setUsuAltaSorteo(String usuAltaSorteo) {
		this.usuAltaSorteo = usuAltaSorteo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta_sorteo", length = 29)
	public Date getFechaAltaSorteo() {
		return fechaAltaSorteo;
	}

	public void setFechaAltaSorteo(Date fechaAltaSorteo) {
		this.fechaAltaSorteo = fechaAltaSorteo;
	}
	

}
