package py.com.excelsis.sicca.entity;

// Generated 17-nov-2011 17:00:10 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PostulacionAdjuntos generated by hbm2java
 */
@Entity
@Table(name = "postulacion_adjuntos", schema = "seleccion")
public class PostulacionAdjuntos implements java.io.Serializable {

	private Long idPostulacionAdjuntos;
	private Postulacion postulacion;
	private Documentos documento;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public PostulacionAdjuntos() {
	}

	public PostulacionAdjuntos(Long idPostulacionAdjuntos,
			Postulacion postulacion, Documentos documento, String usuAlta,
			Date fechaAlta) {
		this.idPostulacionAdjuntos = idPostulacionAdjuntos;
		this.postulacion = postulacion;
		this.documento = documento;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PostulacionAdjuntos(Long idPostulacionAdjuntos,
			Postulacion postulacion, Documentos documento, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idPostulacionAdjuntos = idPostulacionAdjuntos;
		this.postulacion = postulacion;
		this.documento = documento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="POSTULACION_GENERATOR")
	@SequenceGenerator(name="POSTULACION_GENERATOR",sequenceName="seleccion.postulacion_id_postulacion_seq")
	@Column(name = "id_postulacion_adjuntos", unique = true, nullable = false)
	public Long getIdPostulacionAdjuntos() {
		return this.idPostulacionAdjuntos;
	}

	public void setIdPostulacionAdjuntos(Long idPostulacionAdjuntos) {
		this.idPostulacionAdjuntos = idPostulacionAdjuntos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento", nullable = false)
	@NotNull
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}


	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
