package py.com.excelsis.sicca.entity;

// Generated 25/06/2012 10:03:51 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PostulacionCapAdj generated by hbm2java
 */
@Entity
@Table(name = "postulacion_cap_adj", schema = "capacitacion")
public class PostulacionCapAdj implements java.io.Serializable {

	private Long idPostulacionAdj;
	private PostulacionCap postulacionCap;
	private Documentos documento;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public PostulacionCapAdj() {
	}

	public PostulacionCapAdj(Long idPostulacionAdj,
			PostulacionCap postulacionCap, Documentos idDocumento, Boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idPostulacionAdj = idPostulacionAdj;
		this.postulacionCap = postulacionCap;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PostulacionCapAdj(Long idPostulacionAdj,
			PostulacionCap postulacionCap, Documentos idDocumento, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idPostulacionAdj = idPostulacionAdj;
		this.postulacionCap = postulacionCap;
		this.documento = idDocumento;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="POSTULACION_CAB_ADJ_GENERATOR")
	@SequenceGenerator(name="POSTULACION_CAB_ADJ_GENERATOR",sequenceName="capacitacion.postulacion_cap_adj_id_postulacion_adj_seq")
	@Column(name = "id_postulacion_adj", unique = true, nullable = false)
	public Long getIdPostulacionAdj() {
		return this.idPostulacionAdj;
	}

	public void setIdPostulacionAdj(Long idPostulacionAdj) {
		this.idPostulacionAdj = idPostulacionAdj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion", nullable = false)
	@NotNull
	public PostulacionCap getPostulacionCap() {
		return this.postulacionCap;
	}

	public void setPostulacionCap(PostulacionCap postulacionCap) {
		this.postulacionCap = postulacionCap;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento", nullable = false)
	public Documentos getDocumento() {
		return documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
