package py.com.excelsis.sicca.entity;

// Generated 25/06/2012 10:03:51 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PostulacionCap generated by hbm2java
 */
@Entity
@Table(name = "postulacion_cap", schema = "capacitacion")
public class PostulacionCap implements java.io.Serializable {

	private Long idPostulacion;
	private Persona persona;
	private boolean ficha;
	private Capacitaciones capacitacion;
	private PersonaPostulante personaPostulante;
	private String proyectoCord;
	private String nombreAp;
	private String cargo;
	private String direccion;
	private String EMail;
	private String telefono;
	private String fax;
	private String proyectoPart;
	private String proyectoActi;
	private String funcionGral;
	private String funcionEspecif;
	private String potencialBenef;
	private String cursoRealiza;
	private String diasAsisCur;
	private String horarioCur;
	private String otraAct;
	private String horarioAct;
	private String diasAsisAct;
	private String usuFicha;
	private Date fechaFicha;
	private String usuMod;
	private Date fechaMod;
	private String usuPost;
	private Date fechaPost;
	private boolean activo;
	private String usuCancelacion;
	private Date fechaCancelacion;
	private String obsCancelacion;
	private EmpleadoPuesto empleadoPuesto;
	private String tipo;
	private String oee;
	private String unidadOrganizativa;

	private Set<PostulacionCapAdj> postulacionCapAdjs = new HashSet<PostulacionCapAdj>(0);
	private Set<EvaluacionInscPost> evaluacionInscPosts = new HashSet<EvaluacionInscPost>(0);

	private Set<EvaluacionPart> evaluacionParts = new HashSet<EvaluacionPart>(0);

	public PostulacionCap() {
	}

	public PostulacionCap(
			Long idPostulacion, Persona idPersona, boolean ficha, Capacitaciones idCapacitacion,
			String cargo, String direccion, String EMail, String telefono, String fax,
			String usuFicha, Date fechaFicha, boolean activo) {
		this.idPostulacion = idPostulacion;
		this.persona = idPersona;
		this.ficha = ficha;
		this.capacitacion = idCapacitacion;
		this.cargo = cargo;
		this.direccion = direccion;
		this.EMail = EMail;
		this.telefono = telefono;
		this.fax = fax;
		this.usuFicha = usuFicha;
		this.fechaFicha = fechaFicha;
		this.activo = activo;
	}

	public PostulacionCap(
			Long idPostulacion, Persona idPersona, boolean ficha, Capacitaciones idCapacitacion,
			PersonaPostulante idPersonaPostulante, String proyectoCord, String nombreAp,
			String cargo, String direccion, String EMail, String telefono, String fax,
			String proyectoPart, String proyectoActi, String funcionGral, String funcionEspecif,
			String potencialBenef, String cursoRealiza, String diasAsisCur, String horarioCur,
			String otraAct, String horarioAct, String diasAsisAct, String usuFicha,
			Date fechaFicha, String usuMod, Date fechaMod, String usuPost, Date fechaPost,
			boolean activo, String usuCancelacion, Date fechaCancelacion, String obsCancelacion,
			Set<PostulacionCapAdj> postulacionCapAdjs) {
		this.idPostulacion = idPostulacion;
		this.persona = idPersona;
		this.ficha = ficha;
		this.capacitacion = idCapacitacion;
		this.personaPostulante = idPersonaPostulante;
		this.proyectoCord = proyectoCord;
		this.nombreAp = nombreAp;
		this.cargo = cargo;
		this.direccion = direccion;
		this.EMail = EMail;
		this.telefono = telefono;
		this.fax = fax;
		this.proyectoPart = proyectoPart;
		this.proyectoActi = proyectoActi;
		this.funcionGral = funcionGral;
		this.funcionEspecif = funcionEspecif;
		this.potencialBenef = potencialBenef;
		this.cursoRealiza = cursoRealiza;
		this.diasAsisCur = diasAsisCur;
		this.horarioCur = horarioCur;
		this.otraAct = otraAct;
		this.horarioAct = horarioAct;
		this.diasAsisAct = diasAsisAct;
		this.usuFicha = usuFicha;
		this.fechaFicha = fechaFicha;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.usuPost = usuPost;
		this.fechaPost = fechaPost;
		this.activo = activo;
		this.usuCancelacion = usuCancelacion;
		this.fechaCancelacion = fechaCancelacion;
		this.obsCancelacion = obsCancelacion;
		this.postulacionCapAdjs = postulacionCapAdjs;
	}

	@Id
	@GeneratedValue(generator = "POSTULACION_CAB_GENERATOR")
	@SequenceGenerator(name = "POSTULACION_CAB_GENERATOR", sequenceName = "capacitacion.postulacion_cap_id_postulacion_seq")
	@Column(name = "id_postulacion", unique = true, nullable = false)
	public Long getIdPostulacion() {
		return this.idPostulacion;
	}

	public void setIdPostulacion(Long idPostulacion) {
		this.idPostulacion = idPostulacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "ficha", nullable = false)
	public boolean isFicha() {
		return this.ficha;
	}

	public void setFicha(boolean ficha) {
		this.ficha = ficha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capacitacion")
	public Capacitaciones getCapacitacion() {
		return capacitacion;
	}

	public void setCapacitacion(Capacitaciones capacitacion) {
		this.capacitacion = capacitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_postulante")
	public PersonaPostulante getPersonaPostulante() {
		return personaPostulante;
	}

	public void setPersonaPostulante(PersonaPostulante personaPostulante) {
		this.personaPostulante = personaPostulante;
	}

	@Column(name = "proyecto_cord", length = 1000)
	@Length(max = 1000)
	public String getProyectoCord() {
		return this.proyectoCord;
	}

	public void setProyectoCord(String proyectoCord) {
		this.proyectoCord = proyectoCord;
	}

	@Column(name = "nombre_ap", length = 200)
	@Length(max = 200)
	public String getNombreAp() {
		return this.nombreAp;
	}

	public void setNombreAp(String nombreAp) {
		this.nombreAp = nombreAp;
	}

	@Column(name = "cargo", nullable = true, length = 200)
	@Length(max = 200)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "direccion", nullable = true, length = 500)
	@Length(max = 500)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "e_mail", nullable = true, length = 500)
	@Length(max = 500)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "telefono", nullable = true, length = 500)
	@Length(max = 500)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "fax", nullable = true, length = 500)
	@Length(max = 500)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "proyecto_part", length = 1000)
	@Length(max = 1000)
	public String getProyectoPart() {
		return this.proyectoPart;
	}

	public void setProyectoPart(String proyectoPart) {
		this.proyectoPart = proyectoPart;
	}

	@Column(name = "proyecto_acti", length = 5000)
	@Length(max = 5000)
	public String getProyectoActi() {
		return this.proyectoActi;
	}

	public void setProyectoActi(String proyectoActi) {
		this.proyectoActi = proyectoActi;
	}

	@Column(name = "funcion_gral", length = 5000)
	@Length(max = 5000)
	public String getFuncionGral() {
		return this.funcionGral;
	}

	public void setFuncionGral(String funcionGral) {
		this.funcionGral = funcionGral;
	}

	@Column(name = "funcion_especif", length = 5000)
	@Length(max = 5000)
	public String getFuncionEspecif() {
		return this.funcionEspecif;
	}

	public void setFuncionEspecif(String funcionEspecif) {
		this.funcionEspecif = funcionEspecif;
	}

	@Column(name = "potencial_benef", length = 5000)
	@Length(max = 5000)
	public String getPotencialBenef() {
		return this.potencialBenef;
	}

	public void setPotencialBenef(String potencialBenef) {
		this.potencialBenef = potencialBenef;
	}

	@Column(name = "curso_realiza", length = 1000)
	@Length(max = 1000)
	public String getCursoRealiza() {
		return this.cursoRealiza;
	}

	public void setCursoRealiza(String cursoRealiza) {
		this.cursoRealiza = cursoRealiza;
	}

	@Column(name = "dias_asis_cur", length = 500)
	@Length(max = 500)
	public String getDiasAsisCur() {
		return this.diasAsisCur;
	}

	public void setDiasAsisCur(String diasAsisCur) {
		this.diasAsisCur = diasAsisCur;
	}

	@Column(name = "horario_cur", length = 500)
	@Length(max = 500)
	public String getHorarioCur() {
		return this.horarioCur;
	}

	public void setHorarioCur(String horarioCur) {
		this.horarioCur = horarioCur;
	}

	@Column(name = "otra_act", length = 5000)
	@Length(max = 5000)
	public String getOtraAct() {
		return this.otraAct;
	}

	public void setOtraAct(String otraAct) {
		this.otraAct = otraAct;
	}

	@Column(name = "horario_act", length = 500)
	@Length(max = 500)
	public String getHorarioAct() {
		return this.horarioAct;
	}

	public void setHorarioAct(String horarioAct) {
		this.horarioAct = horarioAct;
	}

	@Column(name = "dias_asis_act", length = 500)
	@Length(max = 500)
	public String getDiasAsisAct() {
		return this.diasAsisAct;
	}

	public void setDiasAsisAct(String diasAsisAct) {
		this.diasAsisAct = diasAsisAct;
	}

	@Column(name = "usu_ficha", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuFicha() {
		return this.usuFicha;
	}

	public void setUsuFicha(String usuFicha) {
		this.usuFicha = usuFicha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_ficha", nullable = false, length = 29)
	@NotNull
	public Date getFechaFicha() {
		return this.fechaFicha;
	}

	public void setFechaFicha(Date fechaFicha) {
		this.fechaFicha = fechaFicha;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "usu_post", length = 50)
	@Length(max = 50)
	public String getUsuPost() {
		return this.usuPost;
	}

	public void setUsuPost(String usuPost) {
		this.usuPost = usuPost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_post", length = 29)
	public Date getFechaPost() {
		return this.fechaPost;
	}

	public void setFechaPost(Date fechaPost) {
		this.fechaPost = fechaPost;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_cancelacion", length = 50)
	@Length(max = 50)
	public String getUsuCancelacion() {
		return this.usuCancelacion;
	}

	public void setUsuCancelacion(String usuCancelacion) {
		this.usuCancelacion = usuCancelacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cancelacion", length = 29)
	public Date getFechaCancelacion() {
		return this.fechaCancelacion;
	}

	public void setFechaCancelacion(Date fechaCancelacion) {
		this.fechaCancelacion = fechaCancelacion;
	}

	@Column(name = "obs_cancelacion", length = 1000)
	@Length(max = 1000)
	public String getObsCancelacion() {
		return this.obsCancelacion;
	}

	public void setObsCancelacion(String obsCancelacion) {
		this.obsCancelacion = obsCancelacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postulacionCap")
	public Set<PostulacionCapAdj> getPostulacionCapAdjs() {
		return this.postulacionCapAdjs;
	}

	public void setPostulacionCapAdjs(Set<PostulacionCapAdj> postulacionCapAdjs) {
		this.postulacionCapAdjs = postulacionCapAdjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postulacionCap")
	public Set<EvaluacionInscPost> getEvaluacionInscPosts() {
		return this.evaluacionInscPosts;
	}

	public void setEvaluacionInscPosts(Set<EvaluacionInscPost> evaluacionInscPosts) {
		this.evaluacionInscPosts = evaluacionInscPosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postulacionCap")
	public Set<EvaluacionPart> getEvaluacionParts() {
		return this.evaluacionParts;
	}

	public void setEvaluacionParts(Set<EvaluacionPart> evaluacionParts) {
		this.evaluacionParts = evaluacionParts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto")
	public EmpleadoPuesto getEmpleadoPuesto() {
		return empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}
	@Column(name = "tipo", length = 2)
	@Length(max = 2)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	@Column(name = "oee", length = 100)
	@Length(max = 100)
	public String getOee() {
		return this.oee;
	}

	public void setOee(String oee) {
		this.oee = oee;
	}
	
	@Column(name = "unidad_organizativa", length = 100)
	@Length(max = 100)
	public String getUnidadOrganizativa() {
		return this.unidadOrganizativa;
	}

	public void setUnidadOrganizativa(String unidadOrganizativa) {
		this.unidadOrganizativa = unidadOrganizativa;
	}

}
