package py.com.excelsis.sicca.entity;

// Generated 13/07/2012 08:32:42 AM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Preguntas generated by hbm2java
 */
@Entity
@Table(name = "preguntas", schema = "capacitacion")
public class Preguntas implements java.io.Serializable {

	private Long idPregunta;
	private PlantillaEncuesta plantillaEncuesta;
	private DatosEspecificos datosEspecificosGrupo;
	private Long orden;
	private String pregunta;
	private String tipoPregunta;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Boolean obligatorio;
	private String respuestasMultiples;
	private List<RespuestaMultiple> respuestaMultiples = new ArrayList<RespuestaMultiple>();

	public Preguntas() {
	}

	public Preguntas(Long idPregunta, PlantillaEncuesta plantillaEncuesta,
			DatosEspecificos idDatosEspecificosGrupo, Long orden, String pregunta,
			String tipoPregunta, Boolean activo, String usuAlta,
			Date fechaAlta, Boolean obligatorio) {
		this.idPregunta = idPregunta;
		this.plantillaEncuesta = plantillaEncuesta;
		this.datosEspecificosGrupo = idDatosEspecificosGrupo;
		this.orden = orden;
		this.pregunta = pregunta;
		this.tipoPregunta = tipoPregunta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.obligatorio = obligatorio;
	}

	public Preguntas(Long idPregunta, PlantillaEncuesta plantillaEncuesta,
			DatosEspecificos idDatosEspecificosGrupo, Long orden, String pregunta,
			String tipoPregunta, Boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod, Boolean obligatorio,
			List<RespuestaMultiple> respuestaMultiples) {
		this.idPregunta = idPregunta;
		this.plantillaEncuesta = plantillaEncuesta;
		this.datosEspecificosGrupo = idDatosEspecificosGrupo;
		this.orden = orden;
		this.pregunta = pregunta;
		this.tipoPregunta = tipoPregunta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.obligatorio = obligatorio;
		this.respuestaMultiples = respuestaMultiples;
	}

	@Id
	@GeneratedValue(generator = "PREGUNTAS_GENERATOR")
	@SequenceGenerator(name = "PREGUNTAS_GENERATOR", sequenceName = "capacitacion.preguntas_id_pregunta_seq")
	@Column(name = "id_pregunta", unique = true, nullable = false)
	public Long getIdPregunta() {
		return this.idPregunta;
	}

	public void setIdPregunta(Long idPregunta) {
		this.idPregunta = idPregunta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla", nullable = false)
	@NotNull
	public PlantillaEncuesta getPlantillaEncuesta() {
		return this.plantillaEncuesta;
	}

	public void setPlantillaEncuesta(PlantillaEncuesta plantillaEncuesta) {
		this.plantillaEncuesta = plantillaEncuesta;
	}

	


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_grupo", nullable = false)
	public DatosEspecificos getDatosEspecificosGrupo() {
		return datosEspecificosGrupo;
	}

	public void setDatosEspecificosGrupo(DatosEspecificos datosEspecificosGrupo) {
		this.datosEspecificosGrupo = datosEspecificosGrupo;
	}
	@Column(name = "orden", nullable = false)
	public Long getOrden() {
		return this.orden;
	}

	public void setOrden(Long orden) {
		this.orden = orden;
	}

	@Column(name = "pregunta", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	@Column(name = "tipo_pregunta", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getTipoPregunta() {
		return this.tipoPregunta;
	}

	public void setTipoPregunta(String tipoPregunta) {
		this.tipoPregunta = tipoPregunta;
	}

	

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "obligatorio", nullable = false)
	public Boolean getObligatorio() {
		return obligatorio;
	}

	public void setObligatorio(Boolean obligatorio) {
		this.obligatorio = obligatorio;
	}

	
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preguntas")
	public List<RespuestaMultiple> getRespuestaMultiples() {
		return this.respuestaMultiples;
	}

	public void setRespuestaMultiples(List<RespuestaMultiple> respuestaMultiples) {
		this.respuestaMultiples = respuestaMultiples;
	}

	@Transient
	public String getRespuestasMultiples() {
		return respuestasMultiples;
	}

	public void setRespuestasMultiples(String respuestasMultiples) {
		this.respuestasMultiples = respuestasMultiples;
	}
	
	

}
