package py.com.excelsis.sicca.entity;

// Generated 11/11/2011 02:29:19 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PresentAclaracDoc generated by hbm2java
 */
@Entity
@Table(name = "present_aclarac_doc", schema = "seleccion")
public class PresentAclaracDoc implements java.io.Serializable {

	private Long idPresentAclaracDoc;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private String lugar;
	private String descripcion;
	private String direccion;
	private String telefono;
	private String email;
	private Date horarioDesde;
	private Date horarioHasta;
	private String tipoPA;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaPresDesde;
	private Date fechaPresHasta;
	private Concurso concurso;

	public PresentAclaracDoc() {
	}

	public PresentAclaracDoc(Long idPresentAclaracDoc,
			ConcursoPuestoAgr concursoPuestoAgr, String lugar,
			Date horarioDesde, Date horarioHasta, String tipoPA,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idPresentAclaracDoc = idPresentAclaracDoc;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.lugar = lugar;
		this.horarioDesde = horarioDesde;
		this.horarioHasta = horarioHasta;
		this.tipoPA = tipoPA;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PresentAclaracDoc(Long idPresentAclaracDoc,
			ConcursoPuestoAgr concursoPuestoAgr, String lugar,
			String descripcion, String direccion, String telefono,
			String email, Date horarioDesde, Date horarioHasta, String tipoPA,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idPresentAclaracDoc = idPresentAclaracDoc;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.lugar = lugar;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.horarioDesde = horarioDesde;
		this.horarioHasta = horarioHasta;
		this.tipoPA = tipoPA;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_present_aclarac_doc", unique = true, nullable = false)
	@GeneratedValue(generator="PRESENT_ACLARA_GENERATOR")
	@SequenceGenerator(name="PRESENT_ACLARA_GENERATOR",sequenceName="seleccion.present_aclarac_doc_id_presentacion_seq")
	public Long getIdPresentAclaracDoc() {
		return this.idPresentAclaracDoc;
	}

	public void setIdPresentAclaracDoc(Long idPresentAclaracDoc) {
		this.idPresentAclaracDoc = idPresentAclaracDoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@Column(name = "lugar", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "direccion", length = 250)
	@Length(max = 250)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 150)
	@Length(max = 150)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email", length = 200)
	@Length(max = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horario_desde", nullable = false, length = 15)
	@NotNull
	public Date getHorarioDesde() {
		return this.horarioDesde;
	}

	public void setHorarioDesde(Date horarioDesde) {
		this.horarioDesde = horarioDesde;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horario_hasta", nullable = false, length = 15)
	@NotNull
	public Date getHorarioHasta() {
		return this.horarioHasta;
	}

	public void setHorarioHasta(Date horarioHasta) {
		this.horarioHasta = horarioHasta;
	}

	@Column(name = "tipo_p_a", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getTipoPA() {
		return this.tipoPA;
	}

	public void setTipoPA(String tipoPA) {
		this.tipoPA = tipoPA;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pres_desde", length = 29)
	public Date getFechaPresDesde() {
		return fechaPresDesde;
	}

	public void setFechaPresDesde(Date fechaPresDesde) {
		this.fechaPresDesde = fechaPresDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pres_hasta", length = 29)
	public Date getFechaPresHasta() {
		return fechaPresHasta;
	}

	public void setFechaPresHasta(Date fechaPresHasta) {
		this.fechaPresHasta = fechaPresHasta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso")
	public Concurso getConcurso() {
		return concurso;
	}

	public void setConcurso(Concurso concurso) {
		this.concurso = concurso;
	}
	
	

}
