package py.com.excelsis.sicca.entity;

// Generated 05/11/2012 03:13:42 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Remuneraciones generated by hbm2java
 */
@Entity
@Table(name = "Procesamiento", schema = "remuneracion")
public class Procesamiento implements java.io.Serializable {

	private Long idProcesamiento;
	private Integer anho;
	private Integer mes;
	private ConfiguracionUoCab configuracionUoCab;
	private Date minFechaAlta;
	private Integer cantProc;
    private boolean activo;
    private String usuAlta;
    private Date fechaAlta;
    private String usuMod;
    private Date fechaMod;
    
    //ZD 01/04/16
    private Integer cantLineas;

	public Procesamiento() {
	}

	public Procesamiento(Long idProcesamiento, Integer anho, Integer mes, ConfiguracionUoCab configuracionUoCab, 
			Date minFechaAlta, Integer cantProc, Integer cantLineas) {
		
		this.idProcesamiento = idProcesamiento;
		this.anho = anho;
		this.mes = mes;
		this.configuracionUoCab = configuracionUoCab;
		this.minFechaAlta = minFechaAlta;
		this.cantProc = cantProc;
		this.cantLineas = cantLineas;
	}

	@Id
	@Column(name = "id_procesamiento", unique = true, nullable = false)
	@GeneratedValue(generator="PROCESAMIENTO_GENERATOR")
	@SequenceGenerator(name="PROCESAMIENTO_GENERATOR",sequenceName="remuneracion.procesamiento_id_procesamiento_seq")
	public Long getIdProcesamiento() {
		return this.idProcesamiento;
	}

	public void setIdProcesamiento(Long idProcesamiento) {
		this.idProcesamiento = idProcesamiento;
	}
	
	@Column(name = "anho", nullable = false)
	@NotNull
	public Integer getAnho() {
		return this.anho;
	}

	public void setAnho(Integer anho) {
		this.anho = anho;
	}
	
	@Column(name = "mes", nullable = false)
	@NotNull
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "min_fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getMinFechaAlta() {
		return this.minFechaAlta;
	}

	public void setMinFechaAlta(Date minFechaAlta) {
		this.minFechaAlta = minFechaAlta;
	}
	
	@Column(name = "cant_proc", nullable = false)
	@NotNull
	public Integer getCantProc() {
		return this.cantProc;
	}

	public void setCantProc(Integer cantProc) {
		this.cantProc = cantProc;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}
	
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}
	
	public void setActivo(boolean activo) {
		this.activo = activo;
	}
	
	@Column(name = "usu_alta", length = 50)
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", length = 29)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "cant_lineas")
	public Integer getCantLineas() {
		return cantLineas;
	}

	public void setCantLineas(Integer cantLineas) {
		this.cantLineas = cantLineas;
	}
	
}
