package py.com.excelsis.sicca.entity;

// Generated 03-nov-2011 17:17:28 by Hibernate Tools 3.4.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.Properties;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import py.com.excelsis.sicca.seguridad.entity.Rol;
import py.com.excelsis.sicca.util.EntityBase;

/**
 * ProcActividadRol generated by hbm2java
 */
@Entity
@Table(name = "proc_actividad_rol", schema = "proceso")
public class ProcActividadRol extends EntityBase {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5122327013376930653L;
	private long idProcActividadRol;
	private Rol rol;
	private ActividadProceso actividadProceso;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ProcActividadRol() {
	}

	public ProcActividadRol(long idProcActividadRol, Rol rol,
			ActividadProceso actividadProceso, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idProcActividadRol = idProcActividadRol;
		this.rol = rol;
		this.actividadProceso = actividadProceso;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ProcActividadRol(long idProcActividadRol, Rol rol,
			ActividadProceso actividadProceso, boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idProcActividadRol = idProcActividadRol;
		this.rol = rol;
		this.actividadProceso = actividadProceso;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}
	
	@Id
	@Column(name = "id_proc_actividad_rol", unique = true, nullable = false)
	@GeneratedValue(generator="PROC_ACTIVIDAD_ROL_GENERATOR")
	@SequenceGenerator(name="PROC_ACTIVIDAD_ROL_GENERATOR", sequenceName="proceso.tbl_proc_actividad_rol_id_proc_actividad_rol_seq")
	public long getIdProcActividadRol() {
		return this.idProcActividadRol;
	}

	public void setIdProcActividadRol(long idProcActividadRol) {
		this.idProcActividadRol = idProcActividadRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol", nullable = false)
	@NotNull
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad_proceso", nullable = false)
	@NotNull
	public ActividadProceso getActividadProceso() {
		return this.actividadProceso;
	}

	public void setActividadProceso(ActividadProceso actividadProceso) {
		this.actividadProceso = actividadProceso;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Transient
	public Serializable getId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Transient
	public Properties getProperties() {
		// TODO Auto-generated method stub
		return null;
	}

	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub
		
	}

}
