package py.com.excelsis.sicca.entity;

// Generated 28/10/2011 05:04:36 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.Properties;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.EntityBase;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * PromocionConcursoAgr generated by hbm2java
 */
@Entity
@Table(name = "promocion_concurso_agr", schema = "seleccion")
public class PromocionConcursoAgr extends EntityBase {

	private Long idPromocionConcursoAgr;
	private PromocionSalarial promocionSalarial;
	private ConcursoPuestoAgr concursoPuestoAgr;
	private Integer nroOrden;
	private EstadoDet estadoDet;
	private Boolean activo;
	private String observacion;	
	private Excepcion excepcion;
	private Boolean excepcionado;
	private EmpleadoPuesto empleadoPuesto;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;


	
	
	// Transients
	private Boolean desierto = false;;
	private Boolean excepcionar = false;

	public PromocionConcursoAgr() {
	}

	public PromocionConcursoAgr(
			Long idPromocionConcursoAgr, PromocionSalarial promocionSalarial, EstadoDet estadoDet,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idPromocionConcursoAgr = idPromocionConcursoAgr;
		this.promocionSalarial = promocionSalarial;
		this.estadoDet = estadoDet;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PromocionConcursoAgr(
			Long idPromocionConcursoAgr, PromocionSalarial promocionSalarial,
			ConcursoPuestoAgr concursoPuestoAgr, EstadoDet estadoDet, Integer nroOrden,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idPromocionConcursoAgr = idPromocionConcursoAgr;
		this.promocionSalarial = promocionSalarial;
		this.concursoPuestoAgr = concursoPuestoAgr;
		this.estadoDet = estadoDet;
		this.nroOrden = nroOrden;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "PROMOCION_CONCURSO_AGR_GENERATOR")
	@SequenceGenerator(name = "PROMOCION_CONCURSO_AGR_GENERATOR", sequenceName = "seleccion.promocion_concurso_agr_id_promocion_concurso_agr_seq")
	@Column(name = "id_promocion_concurso_agr", unique = true, nullable = false)
	public Long getIdPromocionConcursoAgr() {
		return this.idPromocionConcursoAgr;
	}

	public void setIdPromocionConcursoAgr(Long idPromocionConcursoAgr) {
		this.idPromocionConcursoAgr = idPromocionConcursoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_promocion_salarial", nullable = false)
	@NotNull
	public PromocionSalarial getPromocionSalarial() {
		return this.promocionSalarial;
	}

	public void setPromocionSalarial(PromocionSalarial promocionSalarial) {
		this.promocionSalarial = promocionSalarial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso_puesto_agr")
	public ConcursoPuestoAgr getConcursoPuestoAgr() {
		return this.concursoPuestoAgr;
	}

	public void setConcursoPuestoAgr(ConcursoPuestoAgr concursoPuestoAgr) {
		this.concursoPuestoAgr = concursoPuestoAgr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_det", nullable = false)
	@NotNull
	public EstadoDet getEstadoDet() {
		return this.estadoDet;
	}

	public void setEstadoDet(EstadoDet estadoDet) {
		this.estadoDet = estadoDet;
	}

	@Column(name = "nro_orden")
	public Integer getNroOrden() {
		return this.nroOrden;
	}

	public void setNroOrden(Integer nroOrden) {
		this.nroOrden = nroOrden;
	}

	@Column(name = "activo", nullable = false)
	public Boolean isActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	

	@Transient
	public Long getId() {
		return idPromocionConcursoAgr;
	}

	/**
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.CONCURSO_PUESTO_DET_ID, getId());

		return properties;
	}

	/**
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}

	
	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Transient
	public Boolean getDesierto() {
		return desierto;
	}

	public void setDesierto(Boolean desierto) {
		this.desierto = desierto;
	}

	@Transient
	public Boolean getExcepcionar() {
		return excepcionar;
	}

	public void setExcepcionar(Boolean excepcionar) {
		this.excepcionar = excepcionar;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_excepcion" )	 
	public Excepcion getExcepcion() {
		return excepcion;
	}

	public void setExcepcion(Excepcion excepcion) {
		this.excepcion = excepcion;
	}

	@Column(name = "excepcionado")
	public Boolean getExcepcionado() {
		return excepcionado;
	}

	public void setExcepcionado(Boolean excepcionado) {
		this.excepcionado = excepcionado;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto")
	public EmpleadoPuesto getEmpleadoPuesto() {
		return empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

	
	
	
}
