package py.com.excelsis.sicca.entity;

// Generated 03-ene-2012 9:17:46 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PublicacionConcurso generated by hbm2java
 */
@Entity
@Table(name = "publicacion_concurso", schema = "seleccion")
public class PublicacionConcurso implements java.io.Serializable {

	private Long idPublicacionConcurso;
	private Concurso concurso;
	private String usuSolicitud;
	private Date fechaSolicitud;
	private Date fechaAprobacion;
	private String usuAprobacion;
	private String usuUltRev;
	private Date fechaUltRev;
	private Set<PublicacionConcursoCab> publicacionConcursoCabs = new HashSet<PublicacionConcursoCab>(
			0);

	public PublicacionConcurso() {
	}

	public PublicacionConcurso(Long idPublicacionConcurso, Concurso concurso,
			String usuSolicitud, Date fechaSolicitud) {
		this.idPublicacionConcurso = idPublicacionConcurso;
		this.concurso = concurso;
		this.usuSolicitud = usuSolicitud;
		this.fechaSolicitud = fechaSolicitud;
	}

	public PublicacionConcurso(Long idPublicacionConcurso, Concurso concurso,
			String usuSolicitud, Date fechaSolicitud, Date fechaAprobacion,
			String usuAprobacion, String usuUltRev, Date fechaUltRev,
			Set<PublicacionConcursoCab> publicacionConcursoCabs) {
		this.idPublicacionConcurso = idPublicacionConcurso;
		this.concurso = concurso;
		this.usuSolicitud = usuSolicitud;
		this.fechaSolicitud = fechaSolicitud;
		this.fechaAprobacion = fechaAprobacion;
		this.usuAprobacion = usuAprobacion;
		this.usuUltRev = usuUltRev;
		this.fechaUltRev = fechaUltRev;
		this.publicacionConcursoCabs = publicacionConcursoCabs;
	}

	@Id
	@GeneratedValue(generator="PUBLICACION_CONCURSO_GENERATOR")
	@SequenceGenerator(name="PUBLICACION_CONCURSO_GENERATOR",sequenceName="seleccion.publicacion_concurso_id_publicacion_concurso_seq")
	@Column(name = "id_publicacion_concurso", unique = true, nullable = false)
	public Long getIdPublicacionConcurso() {
		return this.idPublicacionConcurso;
	}

	public void setIdPublicacionConcurso(Long idPublicacionConcurso) {
		this.idPublicacionConcurso = idPublicacionConcurso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_concurso", nullable = false)
	@NotNull
	public Concurso getConcurso() {
		return this.concurso;
	}

	public void setConcurso(Concurso concurso) {
		this.concurso = concurso;
	}

	@Column(name = "usu_solicitud", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuSolicitud() {
		return this.usuSolicitud;
	}

	public void setUsuSolicitud(String usuSolicitud) {
		this.usuSolicitud = usuSolicitud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_solicitud", nullable = false, length = 29)
	@NotNull
	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_aprobacion", length = 29)
	public Date getFechaAprobacion() {
		return this.fechaAprobacion;
	}

	public void setFechaAprobacion(Date fechaAprobacion) {
		this.fechaAprobacion = fechaAprobacion;
	}

	@Column(name = "usu_aprobacion", length = 50)
	@Length(max = 50)
	public String getUsuAprobacion() {
		return this.usuAprobacion;
	}

	public void setUsuAprobacion(String usuAprobacion) {
		this.usuAprobacion = usuAprobacion;
	}

	@Column(name = "usu_ult_rev", length = 50)
	@Length(max = 50)
	public String getUsuUltRev() {
		return this.usuUltRev;
	}

	public void setUsuUltRev(String usuUltRev) {
		this.usuUltRev = usuUltRev;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_ult_rev", length = 29)
	public Date getFechaUltRev() {
		return this.fechaUltRev;
	}

	public void setFechaUltRev(Date fechaUltRev) {
		this.fechaUltRev = fechaUltRev;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publicacionConcurso")
	public Set<PublicacionConcursoCab> getPublicacionConcursoCabs() {
		return this.publicacionConcursoCabs;
	}

	public void setPublicacionConcursoCabs(
			Set<PublicacionConcursoCab> publicacionConcursoCabs) {
		this.publicacionConcursoCabs = publicacionConcursoCabs;
	}

}
