package py.com.excelsis.sicca.entity;

// Generated 16-nov-2011 8:26:22 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PublicacionConcursoDet generated by hbm2java
 */
@Entity
@Table(name = "publicacion_concurso_det", schema = "seleccion")
public class PublicacionConcursoDet implements java.io.Serializable {

	private Long idPublicacionDet;
	private PublicacionConcursoCab publicacionConcursoCab;
	private DatosEspecificos datosEspecificos;
	private Date fechaDesde;
	private Date fechaHasta;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public PublicacionConcursoDet() {
	}

	public PublicacionConcursoDet(Long idPublicacionDet,
			PublicacionConcursoCab publicacionConcursoCab,
			DatosEspecificos datosEspecificos, Date fechaDesde,
			Date fechaHasta, boolean activo, String usuAlta, Date fechaAlta) {
		this.idPublicacionDet = idPublicacionDet;
		this.publicacionConcursoCab = publicacionConcursoCab;
		this.datosEspecificos = datosEspecificos;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public PublicacionConcursoDet(Long idPublicacionDet,
			PublicacionConcursoCab publicacionConcursoCab,
			DatosEspecificos datosEspecificos, Date fechaDesde,
			Date fechaHasta, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idPublicacionDet = idPublicacionDet;
		this.publicacionConcursoCab = publicacionConcursoCab;
		this.datosEspecificos = datosEspecificos;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="PUBLICACION_CONCURSO_DET_GENERATOR")
	@SequenceGenerator(name="PUBLICACION_CONCURSO_DET_GENERATOR",sequenceName="seleccion.publicacion_concurso_det_id_publicacion_conc_seq")
	@Column(name = "id_publicacion_det", unique = true, nullable = false)
	public Long getIdPublicacionDet() {
		return this.idPublicacionDet;
	}

	public void setIdPublicacionDet(Long idPublicacionDet) {
		this.idPublicacionDet = idPublicacionDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_publicacion_conc", nullable = false)
	@NotNull
	public PublicacionConcursoCab getPublicacionConcursoCab() {
		return this.publicacionConcursoCab;
	}

	public void setPublicacionConcursoCab(
			PublicacionConcursoCab publicacionConcursoCab) {
		this.publicacionConcursoCab = publicacionConcursoCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_desde", nullable = false, length = 29)
	@NotNull
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hasta", nullable = false, length = 29)
	@NotNull
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
