package py.com.excelsis.sicca.entity;

// Generated 03-ene-2012 15:25:17 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PublicacionConcursoRevDet generated by hbm2java
 */
@Entity
@Table(name = "publicacion_concurso_rev_det", schema = "seleccion")
public class PublicacionConcursoRevDet implements java.io.Serializable {

	private Long idPublicacionConcRevDet;
	private PublicacionConcurso publicacionConcurso;
	private String observacion;
	private Date fechaObs;
	private String usuObs;
	private Boolean enviadoSfp;
	private Boolean ajustadoOee;
	private String respuesta;
	private Date fechaRpta;
	private String usuRpta;
	private Boolean activo;
	private String usuMod;
	private Date fechaMod;

	public PublicacionConcursoRevDet() {
	}

	public PublicacionConcursoRevDet(Long idPublicacionConcRevDet,
			PublicacionConcurso publicacionConcurso, String observacion,
			Date fechaObs, String usuObs, boolean enviadoSfp,
			boolean ajustadoOee, boolean activo) {
		this.idPublicacionConcRevDet = idPublicacionConcRevDet;
		this.publicacionConcurso = publicacionConcurso;
		this.observacion = observacion;
		this.fechaObs = fechaObs;
		this.usuObs = usuObs;
		this.enviadoSfp = enviadoSfp;
		this.ajustadoOee = ajustadoOee;
		this.activo = activo;
	}

	public PublicacionConcursoRevDet(Long idPublicacionConcRevDet,
			PublicacionConcurso publicacionConcurso, String observacion,
			Date fechaObs, String usuObs, boolean enviadoSfp,
			boolean ajustadoOee, String respuesta, Date fechaRpta,
			String usuRpta, boolean activo, String usuMod, Date fechaMod) {
		this.idPublicacionConcRevDet = idPublicacionConcRevDet;
		this.publicacionConcurso = publicacionConcurso;
		this.observacion = observacion;
		this.fechaObs = fechaObs;
		this.usuObs = usuObs;
		this.enviadoSfp = enviadoSfp;
		this.ajustadoOee = ajustadoOee;
		this.respuesta = respuesta;
		this.fechaRpta = fechaRpta;
		this.usuRpta = usuRpta;
		this.activo = activo;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="PUBLICACION_CONCURSO__REV_DET_GENERATOR")
	@SequenceGenerator(name="PUBLICACION_CONCURSO__REV_DET_GENERATOR",sequenceName="seleccion.publicacion_concurso_rev_det__id_publicacion_conc_rev_det_seq")
	@Column(name = "id_publicacion_conc_rev_det", unique = true, nullable = false)
	public Long getIdPublicacionConcRevDet() {
		return this.idPublicacionConcRevDet;
	}

	public void setIdPublicacionConcRevDet(Long idPublicacionConcRevDet) {
		this.idPublicacionConcRevDet = idPublicacionConcRevDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_publicacion_concurso", nullable = false)
	@NotNull
	public PublicacionConcurso getPublicacionConcurso() {
		return this.publicacionConcurso;
	}

	public void setPublicacionConcurso(PublicacionConcurso publicacionConcurso) {
		this.publicacionConcurso = publicacionConcurso;
	}

	@Column(name = "observacion", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_obs", nullable = false, length = 29)
	@NotNull
	public Date getFechaObs() {
		return this.fechaObs;
	}

	public void setFechaObs(Date fechaObs) {
		this.fechaObs = fechaObs;
	}

	@Column(name = "usu_obs", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuObs() {
		return this.usuObs;
	}

	public void setUsuObs(String usuObs) {
		this.usuObs = usuObs;
	}

	@Column(name = "enviado_sfp", nullable = false)
	public Boolean getEnviadoSfp() {
		return this.enviadoSfp;
	}

	public void setEnviadoSfp(Boolean enviadoSfp) {
		this.enviadoSfp = enviadoSfp;
	}

	@Column(name = "ajustado_oee", nullable = false)
	public Boolean getAjustadoOee() {
		return this.ajustadoOee;
	}

	public void setAjustadoOee(Boolean ajustadoOee) {
		this.ajustadoOee = ajustadoOee;
	}

	@Column(name = "respuesta", length = 1000)
	@Length(max = 1000)
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_rpta", length = 29)
	public Date getFechaRpta() {
		return this.fechaRpta;
	}

	public void setFechaRpta(Date fechaRpta) {
		this.fechaRpta = fechaRpta;
	}

	@Column(name = "usu_rpta", length = 50)
	@Length(max = 50)
	public String getUsuRpta() {
		return this.usuRpta;
	}

	public void setUsuRpta(String usuRpta) {
		this.usuRpta = usuRpta;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
