package py.com.excelsis.sicca.entity;

// Generated 24/10/2011 09:05:02 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.Properties;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * ReclamoSugerencia generated by hbm2java
 */
@Entity
@Table(name = "reclamo_sugerencia", schema = "seleccion")
public class ReclamoSugerencia implements java.io.Serializable {

	private Long idReclamoSugerencia;
	private String origen;
	private Postulacion postulacion;
	private Long nroReclamo;
	private String asunto;
	private String descripcion;
	private String reclamoSugerencia;
	private Date fechaReclamoSugerencia;
	private Long nroRespuesta;
	private String asuntoRespuesta;
	private String descripcionRespuesta;
	private Date fechaRespuesta;
	private Boolean enviarCorreoPostulante;
	private String estado;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String usuPostulante;
	private String usuRespuesta;
	private Date fechaReclamoRespuesta;
	private ComisionSeleccionDet comisionSeleccionDet;
	private String asuntoSfp;
	private String descripcionSfp;
	private String usuRptaSfp;
	private Boolean enviarPostulante;
	private Date fechaRptaSfp;
	private Integer plazoRptaSfp;
	private Documentos documentos;
	//Nuevo para insertar nombres y apellidos; cédula de identidad; e-mail, en reclamos y sugerencias, sin "logearse" Werner.
	private String noLogginNomApe;
	private String noLogginCi;
	private String noLogginEmail;
	//***********************************************************************************************************************
	public ReclamoSugerencia() {
	}

	public ReclamoSugerencia(Long idReclamoSugerencia, String origen,
			String asunto, String descripcion, String reclamoSugerencia,
			Date fechaReclamoSugerencia) {
		this.idReclamoSugerencia = idReclamoSugerencia;
		this.origen = origen;
		this.asunto = asunto;
		this.descripcion = descripcion;
		this.reclamoSugerencia = reclamoSugerencia;
		this.fechaReclamoSugerencia = fechaReclamoSugerencia;
	}

	public ReclamoSugerencia(Long idReclamoSugerencia, String origen,
			String asunto, String descripcion, String reclamoSugerencia,
			Date fechaReclamoSugerencia, String asuntoRespuesta,
			String descripcionRespuesta, Boolean enviarCorreoPostulante,
			String estado, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, String usuPostulante, String usuRespuesta,
			Date fechaReclamoRespuesta) {
		this.idReclamoSugerencia = idReclamoSugerencia;
		this.origen = origen;
		this.asunto = asunto;
		this.descripcion = descripcion;
		this.reclamoSugerencia = reclamoSugerencia;
		this.fechaReclamoSugerencia = fechaReclamoSugerencia;
		this.asuntoRespuesta = asuntoRespuesta;
		this.descripcionRespuesta = descripcionRespuesta;
		this.enviarCorreoPostulante = enviarCorreoPostulante;
		this.estado = estado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.usuPostulante = usuPostulante;
		this.usuRespuesta = usuRespuesta;
		this.fechaReclamoRespuesta = fechaReclamoRespuesta;
	}

	@Id
	@GeneratedValue(generator="RECLAMO_SUGERENCIA_GENERATOR")
	@SequenceGenerator(name="RECLAMO_SUGERENCIA_GENERATOR",sequenceName="seleccion.reclamo_sugerencia_id_reclamo_sugerencia_seq")
	@Column(name = "id_reclamo_sugerencia", unique = true, nullable = false)
	public Long getIdReclamoSugerencia() {
		return this.idReclamoSugerencia;
	}

	public void setIdReclamoSugerencia(Long idReclamoSugerencia) {
		this.idReclamoSugerencia = idReclamoSugerencia;
	}

	@Column(name = "origen", length = 2)
	@Length(max = 2)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "asunto", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	@Column(name = "descripcion", nullable = false, length = 400)
	@NotNull
	@Length(max = 400)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "reclamo_sugerencia", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getReclamoSugerencia() {
		return this.reclamoSugerencia;
	}

	public void setReclamoSugerencia(String reclamoSugerencia) {
		this.reclamoSugerencia = reclamoSugerencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_reclamo_sugerencia", nullable = false, length = 29)
	@NotNull
	public Date getFechaReclamoSugerencia() {
		return this.fechaReclamoSugerencia;
	}

	public void setFechaReclamoSugerencia(Date fechaReclamoSugerencia) {
		this.fechaReclamoSugerencia = fechaReclamoSugerencia;
	}

	@Column(name = "asunto_respuesta", length = 150)
	@Length(max = 150)
	public String getAsuntoRespuesta() {
		return this.asuntoRespuesta;
	}

	public void setAsuntoRespuesta(String asuntoRespuesta) {
		this.asuntoRespuesta = asuntoRespuesta;
	}

	@Column(name = "descripcion_respuesta", length = 400)
	@Length(max = 400)
	public String getDescripcionRespuesta() {
		return this.descripcionRespuesta;
	}

	public void setDescripcionRespuesta(String descripcionRespuesta) {
		this.descripcionRespuesta = descripcionRespuesta;
	}

	@Column(name = "enviar_correo_postulante")
	public Boolean getEnviarCorreoPostulante() {
		return this.enviarCorreoPostulante;
	}

	public void setEnviarCorreoPostulante(Boolean enviarCorreoPostulante) {
		this.enviarCorreoPostulante = enviarCorreoPostulante;
	}

	@Column(name = "estado", length = 1)
	@Length(max = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usu_alta", length = 50)
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", length = 29)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "usu_postulante", length = 50)
	@Length(max = 50)
	public String getUsuPostulante() {
		return this.usuPostulante;
	}

	public void setUsuPostulante(String usuPostulante) {
		this.usuPostulante = usuPostulante;
	}

	@Column(name = "usu_respuesta", length = 50)
	@Length(max = 50)
	public String getUsuRespuesta() {
		return this.usuRespuesta;
	}

	public void setUsuRespuesta(String usuRespuesta) {
		this.usuRespuesta = usuRespuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_reclamo_respuesta", length = 29)
	public Date getFechaReclamoRespuesta() {
		return this.fechaReclamoRespuesta;
	}

	public void setFechaReclamoRespuesta(Date fechaReclamoRespuesta) {
		this.fechaReclamoRespuesta = fechaReclamoRespuesta;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_postulacion")
	public Postulacion getPostulacion() {
		return postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	@Column(name = "nro_reclamo")
	public Long getNroReclamo() {
		return nroReclamo;
	}

	public void setNroReclamo(Long nroReclamo) {
		this.nroReclamo = nroReclamo;
	}
	
	@Column(name = "nro_respuesta")
	public Long getNroRespuesta() {
		return nroRespuesta;
	}

	public void setNroRespuesta(Long nroRespuesta) {
		this.nroRespuesta = nroRespuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_respuesta", length = 29)
	public Date getFechaRespuesta() {
		return fechaRespuesta;
	}

	public void setFechaRespuesta(Date fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comision_sel_det")
	public ComisionSeleccionDet getComisionSeleccionDet() {
		return comisionSeleccionDet;
	}

	public void setComisionSeleccionDet(ComisionSeleccionDet comisionSeleccionDet) {
		this.comisionSeleccionDet = comisionSeleccionDet;
	}

	@Column(name = "asunto_sfp", length = 150)
	@Length(max = 150)
	public String getAsuntoSfp() {
		return asuntoSfp;
	}

	public void setAsuntoSfp(String asuntoSfp) {
		this.asuntoSfp = asuntoSfp;
	}

	@Column(name = "descripcion_sfp", length = 600)
	@Length(max = 600)
	public String getDescripcionSfp() {
		return descripcionSfp;
	}

	public void setDescripcionSfp(String descripcionSfp) {
		this.descripcionSfp = descripcionSfp;
	}

	@Column(name = "usu_rpta_sfp", length = 50)
	@Length(max = 50)
	public String getUsuRptaSfp() {
		return usuRptaSfp;
	}

	public void setUsuRptaSfp(String usuRptaSfp) {
		this.usuRptaSfp = usuRptaSfp;
	}

	@Column(name = "enviar_postulante")
	public Boolean getEnviarPostulante() {
		return enviarPostulante;
	}

	public void setEnviarPostulante(Boolean enviarPostulante) {
		this.enviarPostulante = enviarPostulante;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_rpta_sfp", length = 29)
	public Date getFechaRptaSfp() {
		return fechaRptaSfp;
	}

	public void setFechaRptaSfp(Date fechaRptaSfp) {
		this.fechaRptaSfp = fechaRptaSfp;
	}

	@Column(name = "plazo_rpta_sfp")
	public Integer getPlazoRptaSfp() {
		return plazoRptaSfp;
	}

	public void setPlazoRptaSfp(Integer plazoRptaSfp) {
		this.plazoRptaSfp = plazoRptaSfp;
	}
	
	@Column(name = "no_loggin_ci", length = 80)
	@Length(max = 80)
	public String getNoLogginCi() {
		return noLogginCi;
	}

	public void setNoLogginCi(String noLogginCi) {
		this.noLogginCi = noLogginCi;
	}

	@Column(name = "no_loggin_nom_ape", length = 120)
	@Length(max = 120)
	public String getNoLogginNomApe() {
		return noLogginNomApe;
	}

	public void setNoLogginNomApe(String noLogginNomApe) {
		this.noLogginNomApe = noLogginNomApe;
	}
	
	@Column(name = "no_loggin_email", length = 80)
	@Length(max = 80)
	public String getNoLogginEmail() {
		return noLogginEmail;
	}

	public void setNoLogginEmail(String noLogginEmail) {
		this.noLogginEmail = noLogginEmail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	@Transient
	public Long getId() {
		return idReclamoSugerencia;
	}

	/**
	 * 
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.RECLAMO_SUGERENCIA_ID, getId());
		properties.put(SICCASessionParameters.RECLAMO_SUGERENCIA_DESCRIPCION,
				descripcion);

		return properties;
	}

	/**
	 * 
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}

}
