package py.com.excelsis.sicca.entity;

// Generated 24/10/2011 09:36:22 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * Recorridooral generated by hbm2java
 */
@Entity
@Table(name = "recorrido_laboral_migrado", schema = "legajo")
public class RecorridoLegajoMigrado implements java.io.Serializable {

	private Long idRecorrido;
	private Persona persona;
	private String oee;
	private String cargo;
	private String observacion;
	private Boolean activo;
	private Legajos legajo;

	
	public RecorridoLegajoMigrado() {
	}

	
	

	@Id
	@Column(name = "id_recorrido", unique = true, nullable = false)
	@GeneratedValue(generator="RECORRIDO_GENERATOR")
	@SequenceGenerator(name="RECORRIDO_GENERATOR",sequenceName="legajo.recorrido_laboral_migrado_id_recorrido_seq")
	public Long getIdRecorrido() {
		return this.idRecorrido;
	}

	public void setIdRecorrido(Long idRecorrido) {
		this.idRecorrido = idRecorrido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_legajo" ) 
	public Legajos getLegajo() {
		return this.legajo;
	}

	public void setLegajo(Legajos legajo) {
		this.legajo = legajo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona" ) 
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}


	
	@Column(name = "oee")
	public String getOee() {
		return this.oee;
	}

	public void setOee(String empresa) {
		this.oee = empresa;
	}

	@Column(name = "cargo")
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}
	
	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	
	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	
	


}
