package py.com.excelsis.sicca.entity;

// Generated 02/07/2012 09:16:17 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * RedCapacitacion generated by hbm2java
 */
@Entity
@Table(name = "red_capacitacion", schema = "capacitacion", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_persona", "id_configuracion_uo" }))
public class RedCapacitacion implements java.io.Serializable {

	private Long idRedCap;
	private Persona persona;
	private ConfiguracionUoCab configuracionUoCab;
	private String cargo;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public RedCapacitacion() {
	}

	public RedCapacitacion(Long idRedCap,
			ConfiguracionUoCab configuracionUoCab, Persona persona,
			String cargo, Boolean activo, String usuAlta, Date fechaAlta) {
		this.idRedCap = idRedCap;
		this.configuracionUoCab = configuracionUoCab;
		this.persona = persona;
		this.cargo = cargo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public RedCapacitacion(Long idRedCap,
			ConfiguracionUoCab configuracionUoCab, Persona persona,
			String cargo, boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idRedCap = idRedCap;
		this.configuracionUoCab = configuracionUoCab;
		this.persona = persona;
		this.cargo = cargo;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_red_cap", unique = true, nullable = false)
	@GeneratedValue(generator="RED_CAPACITACION_GENERATOR")
	@SequenceGenerator(name="RED_CAPACITACION_GENERATOR",sequenceName="capacitacion.red_capacitacion_id_red_cap_seq")
	
	public Long getIdRedCap() {
		return this.idRedCap;
	}

	public void setIdRedCap(Long idRedCap) {
		this.idRedCap = idRedCap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	@NotNull
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	@NotNull
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "cargo", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
