package py.com.excelsis.sicca.entity;

// Generated 29/08/2012 03:05:14 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ReferenciaAdjuntos generated by hbm2java
 */
@Entity
@Table(name = "referencia_adjuntos", schema = "general")
public class ReferenciaAdjuntos implements java.io.Serializable {

	private Long idReferenciaAdjuntos;
	private Documentos documentos;
	private Persona persona;
	private DatosEspecificos datosEspecificosContexto;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Long idRegistroTabla;
	private ActividadProceso actividadProceso;

	public ReferenciaAdjuntos() {
	}

	public ReferenciaAdjuntos(Long idReferenciaAdjuntos, String usuAlta,
			Date fechaAlta) {
		this.idReferenciaAdjuntos = idReferenciaAdjuntos;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ReferenciaAdjuntos(Long idReferenciaAdjuntos, Documentos documentos,
			Persona persona, DatosEspecificos idDatosEspecificosContexto, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod, Long idRegistroTabla,
			ActividadProceso idActividadProceso) {
		this.idReferenciaAdjuntos = idReferenciaAdjuntos;
		this.documentos = documentos;
		this.persona = persona;
		this.datosEspecificosContexto = idDatosEspecificosContexto;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.idRegistroTabla = idRegistroTabla;
		this.actividadProceso = idActividadProceso;
	}

	@Id
	@Column(name = "id_referencia_adjuntos", unique = true, nullable = false)
	@GeneratedValue(generator = "REFERENCIA_ADJUTO_GENERATOR")
	@SequenceGenerator(name = "REFERENCIA_ADJUTO_GENERATOR", sequenceName = "general.referencia_adjuntos_id_referencia_adjuntos_seq")
	public Long getIdReferenciaAdjuntos() {
		return this.idReferenciaAdjuntos;
	}

	public void setIdReferenciaAdjuntos(Long idReferenciaAdjuntos) {
		this.idReferenciaAdjuntos = idReferenciaAdjuntos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_contexto")
	public DatosEspecificos getDatosEspecificosContexto() {
		return datosEspecificosContexto;
	}

	public void setDatosEspecificosContexto(
			DatosEspecificos datosEspecificosContexto) {
		this.datosEspecificosContexto = datosEspecificosContexto;
	}

	
	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 22)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 22)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "id_registro_tabla")
	public Long getIdRegistroTabla() {
		return this.idRegistroTabla;
	}

	public void setIdRegistroTabla(Long idRegistroTabla) {
		this.idRegistroTabla = idRegistroTabla;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_actividad_proceso")
	public ActividadProceso getActividadProceso() {
		return actividadProceso;
	}

	public void setActividadProceso(ActividadProceso actividadProceso) {
		this.actividadProceso = actividadProceso;
	}

	
	

}
