package py.com.excelsis.sicca.entity;

// Generated 05/10/2011 11:41:21 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Referencias generated by hbm2java
 */
@Entity
@Table(name = "referencias", schema = "seleccion")
public class Referencias implements java.io.Serializable {

	private Long idReferencias;
	private String dominio;
	private String descAbrev;
	private String descLarga;
	private String valorAlf;
	private Integer valorNum;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public Referencias() {
	}

	public Referencias(Long idReferencias, String dominio, Boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idReferencias = idReferencias;
		this.dominio = dominio;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public Referencias(Long idReferencias, String dominio, String descAbrev,
			String descLarga, String valorAlf, Integer valorNum,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idReferencias = idReferencias;
		this.dominio = dominio;
		this.descAbrev = descAbrev;
		this.descLarga = descLarga;
		this.valorAlf = valorAlf;
		this.valorNum = valorNum;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_referencias", unique = true, nullable = false)
	@GeneratedValue(generator="REFERENCIA_GENERATOR")
	@SequenceGenerator(name="REFERENCIA_GENERATOR",sequenceName="seleccion.sel_referencias_id_referencias_seq")
	public Long getIdReferencias() {
		return this.idReferencias;
	}

	public void setIdReferencias(Long idReferencias) {
		this.idReferencias = idReferencias;
	}

	@Column(name = "dominio", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getDominio() {
		return this.dominio;
	}

	public void setDominio(String dominio) {
		this.dominio = dominio;
	}

	@Column(name = "desc_abrev", length = 30)
	@Length(max = 30)
	public String getDescAbrev() {
		return this.descAbrev;
	}

	public void setDescAbrev(String descAbrev) {
		this.descAbrev = descAbrev;
	}

	@Column(name = "desc_larga", length = 60)
	@Length(max = 60)
	public String getDescLarga() {
		return this.descLarga;
	}

	public void setDescLarga(String descLarga) {
		this.descLarga = descLarga;
	}

	@Column(name = "valor_alf", length = 6)
	@Length(max = 6)
	public String getValorAlf() {
		return this.valorAlf;
	}

	public void setValorAlf(String valorAlf) {
		this.valorAlf = valorAlf;
	}

	@Column(name = "valor_num")
	public Integer getValorNum() {
		return this.valorNum;
	}

	public void setValorNum(Integer valorNum) {
		this.valorNum = valorNum;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
