package py.com.excelsis.sicca.entity;

// Generated 17-sep-2012 11:18:50 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ReglaCab generated by hbm2java
 */
@Entity
@Table(name = "regla_cab", schema = "seleccion")
public class ReglaCab implements java.io.Serializable {

	private Long idReglaCab;
	private String descripcion;
	private Date fechaVigenciaDesde;
	private Date fechaVigenciaHasta;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<ReglaDet> reglaDets = new HashSet<ReglaDet>(0);

	public ReglaCab() {
	}

	public ReglaCab(Long idReglaCab, String descripcion,
			Date fechaVigenciaDesde, Date fechaVigenciaHasta, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idReglaCab = idReglaCab;
		this.descripcion = descripcion;
		this.fechaVigenciaDesde = fechaVigenciaDesde;
		this.fechaVigenciaHasta = fechaVigenciaHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ReglaCab(Long idReglaCab, String descripcion,
			Date fechaVigenciaDesde, Date fechaVigenciaHasta, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<ReglaDet> reglaDets) {
		this.idReglaCab = idReglaCab;
		this.descripcion = descripcion;
		this.fechaVigenciaDesde = fechaVigenciaDesde;
		this.fechaVigenciaHasta = fechaVigenciaHasta;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.reglaDets = reglaDets;
	}

	@Id
	@Column(name = "id_regla_cab", unique = true, nullable = false)
	@GeneratedValue(generator="REGLA_CAB_GENERATOR")
	@SequenceGenerator(name="REGLA_CAB_GENERATOR",sequenceName="seleccion.regla_cab_id_regla_cab_seq")

	public Long getIdReglaCab() {
		return this.idReglaCab;
	}

	public void setIdReglaCab(Long idReglaCab) {
		this.idReglaCab = idReglaCab;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_vigencia_desde", nullable = false, length = 29)
	@NotNull
	public Date getFechaVigenciaDesde() {
		return this.fechaVigenciaDesde;
	}

	public void setFechaVigenciaDesde(Date fechaVigenciaDesde) {
		this.fechaVigenciaDesde = fechaVigenciaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_vigencia_hasta", nullable = false, length = 29)
	@NotNull
	public Date getFechaVigenciaHasta() {
		return this.fechaVigenciaHasta;
	}

	public void setFechaVigenciaHasta(Date fechaVigenciaHasta) {
		this.fechaVigenciaHasta = fechaVigenciaHasta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reglaCab")
	public Set<ReglaDet> getReglaDets() {
		return this.reglaDets;
	}

	public void setReglaDets(Set<ReglaDet> reglaDets) {
		this.reglaDets = reglaDets;
	}

}
