package py.com.excelsis.sicca.entity;

// Generated 17-sep-2012 11:18:50 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ReglaDet generated by hbm2java
 */
@Entity
@Table(name = "regla_det", schema = "seleccion")
public class ReglaDet implements java.io.Serializable {

	private Long idReglaDet;
	private ReglaCab reglaCab;
	private Integer cantVacancias;
	private Integer cantPostulantes;
	private Integer relacionPuestoVac;
	private String observacion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ReglaDet() {
	}

	public ReglaDet(Long idReglaDet, ReglaCab reglaCab, Integer cantVacancias,
			Integer cantPostulantes, Integer relacionPuestoVac, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idReglaDet = idReglaDet;
		this.reglaCab = reglaCab;
		this.cantVacancias = cantVacancias;
		this.cantPostulantes = cantPostulantes;
		this.relacionPuestoVac = relacionPuestoVac;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ReglaDet(Long idReglaDet, ReglaCab reglaCab, Integer cantVacancias,
			Integer cantPostulantes, Integer relacionPuestoVac, String observacion,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod) {
		this.idReglaDet = idReglaDet;
		this.reglaCab = reglaCab;
		this.cantVacancias = cantVacancias;
		this.cantPostulantes = cantPostulantes;
		this.relacionPuestoVac = relacionPuestoVac;
		this.observacion = observacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_regla_det", unique = true, nullable = false)
	@GeneratedValue(generator="REGLA_DET_GENERATOR")
	@SequenceGenerator(name="REGLA_DET_GENERATOR",sequenceName="seleccion.regla_det_id_regla_det_seq")

	public Long getIdReglaDet() {
		return this.idReglaDet;
	}

	public void setIdReglaDet(Long idReglaDet) {
		this.idReglaDet = idReglaDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_regla_cab", nullable = false)
	@NotNull
	public ReglaCab getReglaCab() {
		return this.reglaCab;
	}

	public void setReglaCab(ReglaCab reglaCab) {
		this.reglaCab = reglaCab;
	}

	@Column(name = "cant_vacancias", nullable = false)
	public Integer getCantVacancias() {
		return this.cantVacancias;
	}

	public void setCantVacancias(Integer cantVacancias) {
		this.cantVacancias = cantVacancias;
	}

	@Column(name = "cant_postulantes", nullable = false)
	public Integer getCantPostulantes() {
		return this.cantPostulantes;
	}

	public void setCantPostulantes(Integer cantPostulantes) {
		this.cantPostulantes = cantPostulantes;
	}

	@Column(name = "relacion_puesto_vac", nullable = false)
	public Integer getRelacionPuestoVac() {
		return this.relacionPuestoVac;
	}

	public void setRelacionPuestoVac(Integer relacionPuestoVac) {
		this.relacionPuestoVac = relacionPuestoVac;
	}

	@Column(name = "observacion", length = 250)
	@Length(max = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
