package py.com.excelsis.sicca.entity;

// Generated 08/11/2012 10:10:53 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * RemunConfig generated by hbm2java
 */
@Entity
@Table(name = "remun_config", schema = "remuneracion")
public class RemunConfig implements java.io.Serializable {

	private Long idRemunConfig;
	private ConfiguracionUoCab configuracionUoCab;
	private String origen;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private String EMail;

	public RemunConfig() {
	}

	public RemunConfig(Long idRemunConfig,
			ConfiguracionUoCab configuracionUoCab, String origen,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idRemunConfig = idRemunConfig;
		this.configuracionUoCab = configuracionUoCab;
		this.origen = origen;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public RemunConfig(Long idRemunConfig,
			ConfiguracionUoCab configuracionUoCab, String origen,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, String EMail) {
		this.idRemunConfig = idRemunConfig;
		this.configuracionUoCab = configuracionUoCab;
		this.origen = origen;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.EMail = EMail;
	}

	@Id
	@GeneratedValue(generator = "REMUN_CONFIG_GENERATOR")
	@SequenceGenerator(name = "REMUN_CONFIG_GENERATOR", sequenceName = "remuneracion.remun_config_id_remun_config_seq")
	@Column(name = "id_remun_config", unique = true, nullable = false)
	public Long getIdRemunConfig() {
		return this.idRemunConfig;
	}

	public void setIdRemunConfig(Long idRemunConfig) {
		this.idRemunConfig = idRemunConfig;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo", nullable = false)
	@NotNull
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return this.configuracionUoCab;
	}

	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Column(name = "origen", nullable = false)
	@NotNull
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "e_mail", length = 500)
	@Length(max = 500)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

}
