package py.com.excelsis.sicca.entity;

// Generated 24-sep-2012 13:57:28 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ResolucionEval generated by hbm2java
 */
@Entity
@Table(name = "resolucion_eval", schema = "eval_desempeno")
public class ResolucionEval implements java.io.Serializable {

	private Long idResolucionEval;
	private PlantillaResolucionEval plantillaResolucionEval;
	private EvaluacionDesempeno evaluacionDesempeno;
	private String titulo;
	private String lugar;
	private Integer nro;
	private Date fecha;
	private String visto;
	private String considerando;
	private String porTanto;
	private String resuelve;
	private String firma;
	private String cargo;
	private String institucion;
	private Documentos documento;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ResolucionEval() {
	}

	public ResolucionEval(Long idResolucionEval,
			PlantillaResolucionEval plantillaResolucionEval,
			EvaluacionDesempeno evaluacionDesempeno, String titulo,
			String lugar, Integer nro, Date fecha, String visto,
			String considerando, String porTanto, String resuelve,
			String firma, String cargo, String institucion, String usuAlta,
			Date fechaAlta) {
		this.idResolucionEval = idResolucionEval;
		this.plantillaResolucionEval = plantillaResolucionEval;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.titulo = titulo;
		this.lugar = lugar;
		this.nro = nro;
		this.fecha = fecha;
		this.visto = visto;
		this.considerando = considerando;
		this.porTanto = porTanto;
		this.resuelve = resuelve;
		this.firma = firma;
		this.cargo = cargo;
		this.institucion = institucion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ResolucionEval(Long idResolucionEval,
			PlantillaResolucionEval plantillaResolucionEval,
			EvaluacionDesempeno evaluacionDesempeno, String titulo,
			String lugar, Integer nro, Date fecha, String visto,
			String considerando, String porTanto, String resuelve,
			String firma, String cargo, String institucion,
			Documentos documento, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idResolucionEval = idResolucionEval;
		this.plantillaResolucionEval = plantillaResolucionEval;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.titulo = titulo;
		this.lugar = lugar;
		this.nro = nro;
		this.fecha = fecha;
		this.visto = visto;
		this.considerando = considerando;
		this.porTanto = porTanto;
		this.resuelve = resuelve;
		this.firma = firma;
		this.cargo = cargo;
		this.institucion = institucion;
		this.documento = documento;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="RESOLUCION_EVAL_GENERATOR")
	@SequenceGenerator(name="RESOLUCION_EVAL_GENERATOR",sequenceName="eval_desempeno.resolucion_eval_id_resolucion_seq")
	@Column(name = "id_resolucion_eval", unique = true, nullable = false)
	public Long getIdResolucionEval() {
		return this.idResolucionEval;
	}

	public void setIdResolucionEval(Long idResolucionEval) {
		this.idResolucionEval = idResolucionEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_resolucion_eval")
	public PlantillaResolucionEval getPlantillaResolucionEval() {
		return this.plantillaResolucionEval;
	}

	public void setPlantillaResolucionEval(
			PlantillaResolucionEval plantillaResolucionEval) {
		this.plantillaResolucionEval = plantillaResolucionEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno")
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return this.evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}

	@Column(name = "titulo", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "lugar", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "nro", nullable = false)
	public Integer getNro() {
		return this.nro;
	}

	public void setNro(Integer nro) {
		this.nro = nro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	@NotNull
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "visto", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getVisto() {
		return this.visto;
	}

	public void setVisto(String visto) {
		this.visto = visto;
	}

	@Column(name = "considerando", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getConsiderando() {
		return this.considerando;
	}

	public void setConsiderando(String considerando) {
		this.considerando = considerando;
	}

	@Column(name = "por_tanto", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getPorTanto() {
		return this.porTanto;
	}

	public void setPorTanto(String porTanto) {
		this.porTanto = porTanto;
	}

	@Column(name = "resuelve", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getResuelve() {
		return this.resuelve;
	}

	public void setResuelve(String resuelve) {
		this.resuelve = resuelve;
	}

	@Column(name = "firma", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	@Column(name = "cargo", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "institucion", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documentos documento) {
		this.documento = documento;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
