package py.com.excelsis.sicca.entity;

// Generated 14/11/2011 04:49:57 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ResolucionHomologacion generated by hbm2java
 */
@Entity
@Table(name = "resolucion", schema = "seleccion")
public class Resolucion implements java.io.Serializable {

	private Long idResolucion;
	private PlantillaResolucion plantillaResolucionHomologacion;
	private String titulo;
	private String lugar;
	private Integer nroResolucion;
	private Date fecha;
	private String visto;
	private String considerando;
	private String porTanto;
	private String resuelve;
	private String firma;
	private String cargo;
	private String institucion;
	private String usuAlta;
	private Date fechaMod;
	private Date fechaAlta;
	private String usuMod;
	private Documentos documentos;

	private Set<ConcursoPuestoAgr> concursoPuestoAgrs = new HashSet<ConcursoPuestoAgr>(
			0);

	public Resolucion() {
	}

	public Resolucion(long idResolucionHomologacion,
			PlantillaResolucion plantillaResolucionHomologacion,
			 String titulo, String lugar, Date fecha,
			String visto, String considerando, String porTanto,
			String resuelve, String firma, String cargo, String institucion,
			String usuAlta, Date fechaAlta) {
		this.idResolucion = idResolucionHomologacion;
		this.plantillaResolucionHomologacion = plantillaResolucionHomologacion;
		this.titulo = titulo;
		this.lugar = lugar;
		this.fecha = fecha;
		this.visto = visto;
		this.considerando = considerando;
		this.porTanto = porTanto;
		this.resuelve = resuelve;
		this.firma = firma;
		this.cargo = cargo;
		this.institucion = institucion;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public Resolucion(long idResolucionHomologacion,
			PlantillaResolucion plantillaResolucionHomologacion,
			 String titulo, String lugar,
			Integer nroResolucion, Date fecha, String visto,
			String considerando, String porTanto, String resuelve,
			String firma, String cargo, String institucion, String usuAlta,
			Date fechaMod, Date fechaAlta, String usuMod,
			Set<ConcursoPuestoAgr> concursoPuestoAgrs) {
		this.idResolucion = idResolucionHomologacion;
		this.plantillaResolucionHomologacion = plantillaResolucionHomologacion;
		
		this.titulo = titulo;
		this.lugar = lugar;
		this.nroResolucion = nroResolucion;
		this.fecha = fecha;
		this.visto = visto;
		this.considerando = considerando;
		this.porTanto = porTanto;
		this.resuelve = resuelve;
		this.firma = firma;
		this.cargo = cargo;
		this.institucion = institucion;
		this.usuAlta = usuAlta;
		this.fechaMod = fechaMod;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.concursoPuestoAgrs = concursoPuestoAgrs;
	}

	@Id
	@Column(name = "id_resolucion", unique = true, nullable = false)
	@GeneratedValue(generator="RESOLUCION_HOMOLOGACION_GENERATOR")
	@SequenceGenerator(name="RESOLUCION_HOMOLOGACION_GENERATOR",sequenceName="seleccion.resolucion_homologacion_id_resolucion_homologacion_seq")
	public Long getIdResolucion() {
		return idResolucion;
	}

	public void setIdResolucion(Long idResolucion) {
		this.idResolucion = idResolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_resolucion_homologacion")
	public PlantillaResolucion getPlantillaResolucionHomologacion() {
		return this.plantillaResolucionHomologacion;
	}

	

	public void setPlantillaResolucionHomologacion(
			PlantillaResolucion plantillaResolucionHomologacion) {
		this.plantillaResolucionHomologacion = plantillaResolucionHomologacion;
	}


	@Column(name = "titulo", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "lugar")
	@Length(max = 150)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "nro_resolucion")
	public Integer getNroResolucion() {
		return this.nroResolucion;
	}

	public void setNroResolucion(Integer nroResolucion) {
		this.nroResolucion = nroResolucion;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "visto", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getVisto() {
		return this.visto;
	}

	

	public void setVisto(String visto) {
		this.visto = visto;
	}

	@Column(name = "considerando", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getConsiderando() {
		return this.considerando;
	}

	public void setConsiderando(String considerando) {
		this.considerando = considerando;
	}

	@Column(name = "por_tanto", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getPorTanto() {
		return this.porTanto;
	}

	public void setPorTanto(String porTanto) {
		this.porTanto = porTanto;
	}

	@Column(name = "resuelve", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getResuelve() {
		return this.resuelve;
	}

	public void setResuelve(String resuelve) {
		this.resuelve = resuelve;
	}

	@Column(name = "firma", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	@Column(name = "cargo", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "institucion", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolucionHomologacion")
	public Set<ConcursoPuestoAgr> getConcursoPuestoAgrs() {
		return this.concursoPuestoAgrs;
	}

	public void setConcursoPuestoAgrs(Set<ConcursoPuestoAgr> concursoPuestoAgrs) {
		this.concursoPuestoAgrs = concursoPuestoAgrs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento")
	public Documentos getDocumentos() {
		return documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	
	
	

}
