package py.com.excelsis.sicca.entity;

// Generated 13/07/2012 08:32:42 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * RespuestaMultipleConfigurada generated by hbm2java
 */
@Entity
@Table(name = "respuesta_multiple_configurada", schema = "capacitacion")
public class RespuestaMultipleConfigurada implements java.io.Serializable {

	private Long idRespuestaMConf;
	private PreguntaConfigurada preguntaConfigurada;
	private String respuestaOpc;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<ResultadoEncuesta> resultadoEncuestas = new HashSet<ResultadoEncuesta>(
			0);

	public RespuestaMultipleConfigurada() {
	}

	public RespuestaMultipleConfigurada(Long idRespuestaMConf,
			PreguntaConfigurada preguntaConfigurada, String respuestaOpc,
			Boolean activo, String usuAlta, Date fechaAlta) {
		this.idRespuestaMConf = idRespuestaMConf;
		this.preguntaConfigurada = preguntaConfigurada;
		this.respuestaOpc = respuestaOpc;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public RespuestaMultipleConfigurada(Long idRespuestaMConf,
			PreguntaConfigurada preguntaConfigurada, String respuestaOpc,
			Boolean activo, String usuAlta, Date fechaAlta, String usuMod,
			Date fechaMod, Set<ResultadoEncuesta> resultadoEncuestas) {
		this.idRespuestaMConf = idRespuestaMConf;
		this.preguntaConfigurada = preguntaConfigurada;
		this.respuestaOpc = respuestaOpc;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.resultadoEncuestas = resultadoEncuestas;
	}

	@Id
	@GeneratedValue(generator = "RPTA_MULTIPLE_CONFIGURADA_GENERATOR")
	@SequenceGenerator(name = "RPTA_MULTIPLE_CONFIGURADA_GENERATOR", sequenceName = "capacitacion.respuesta_multiple_configurada_id_respuesta_m_conf_seq")
	@Column(name = "id_respuesta_m_conf", unique = true, nullable = false)
	public Long getIdRespuestaMConf() {
		return this.idRespuestaMConf;
	}

	public void setIdRespuestaMConf(Long idRespuestaMConf) {
		this.idRespuestaMConf = idRespuestaMConf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pregunta_conf", nullable = false)
	@NotNull
	public PreguntaConfigurada getPreguntaConfigurada() {
		return this.preguntaConfigurada;
	}

	public void setPreguntaConfigurada(PreguntaConfigurada preguntaConfigurada) {
		this.preguntaConfigurada = preguntaConfigurada;
	}

	@Column(name = "respuesta_opc", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getRespuestaOpc() {
		return this.respuestaOpc;
	}

	public void setRespuestaOpc(String respuestaOpc) {
		this.respuestaOpc = respuestaOpc;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "respuestaMultipleConfigurada")
	public Set<ResultadoEncuesta> getResultadoEncuestas() {
		return this.resultadoEncuestas;
	}

	public void setResultadoEncuestas(Set<ResultadoEncuesta> resultadoEncuestas) {
		this.resultadoEncuestas = resultadoEncuestas;
	}

}
