package py.com.excelsis.sicca.entity;

// Generated 17/10/2012 09:32:21 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ResultadoEvalComision generated by hbm2java
 */
@Entity
@Table(name = "resultado_eval_comision", schema = "eval_desempeno")
public class ResultadoEvalComision implements java.io.Serializable {

	private Long idResultadoEvalComision;
	private GrupoMetodologia grupoMetodologia;
	private ComisionCapacEval comisionCapacEval;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ResultadoEvalComision() {
	}

	public ResultadoEvalComision(Long idResultadoEvalComision,
			GrupoMetodologia grupoMetodologia,
			ComisionCapacEval comisionCapacEval, boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idResultadoEvalComision = idResultadoEvalComision;
		this.grupoMetodologia = grupoMetodologia;
		this.comisionCapacEval = comisionCapacEval;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ResultadoEvalComision(Long idResultadoEvalComision,
			GrupoMetodologia grupoMetodologia,
			ComisionCapacEval comisionCapacEval, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idResultadoEvalComision = idResultadoEvalComision;
		this.grupoMetodologia = grupoMetodologia;
		this.comisionCapacEval = comisionCapacEval;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_resultado_eval_comision", unique = true, nullable = false)
	@GeneratedValue(generator="RESULTADO_EVAL_COMISION_GENERATOR")
	@SequenceGenerator(name="RESULTADO_EVAL_COMISION_GENERATOR",sequenceName="eval_desempeno.resultado_eval_comision_id_resultado_eval_comision_seq")
	public Long getIdResultadoEvalComision() {
		return this.idResultadoEvalComision;
	}

	public void setIdResultadoEvalComision(Long idResultadoEvalComision) {
		this.idResultadoEvalComision = idResultadoEvalComision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_metodologia", nullable = false)
	@NotNull
	public GrupoMetodologia getGrupoMetodologia() {
		return this.grupoMetodologia;
	}

	public void setGrupoMetodologia(GrupoMetodologia grupoMetodologia) {
		this.grupoMetodologia = grupoMetodologia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_comision", nullable = false)
	@NotNull
	public ComisionCapacEval getComisionCapacEval() {
		return this.comisionCapacEval;
	}

	public void setComisionCapacEval(ComisionCapacEval comisionCapacEval) {
		this.comisionCapacEval = comisionCapacEval;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
