package py.com.excelsis.sicca.entity;

// Generated 13/07/2012 08:32:42 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ResultadoEncuesta generated by hbm2java
 */
@Entity
@Table(name = "resultado_encuesta", schema = "capacitacion")
public class ResultadoEncuesta implements java.io.Serializable {

	private Long idResultadoEncuesta;
	private PreguntaConfigurada preguntaConfigurada;
	private RespuestaMultipleConfigurada respuestaMultipleConfigurada;
	private String respuestaTexto;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ResultadoEncuesta() {
	}

	public ResultadoEncuesta(Long idResultadoEncuesta,
			PreguntaConfigurada preguntaConfigurada, Boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idResultadoEncuesta = idResultadoEncuesta;
		this.preguntaConfigurada = preguntaConfigurada;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ResultadoEncuesta(Long idResultadoEncuesta,
			PreguntaConfigurada preguntaConfigurada,
			RespuestaMultipleConfigurada respuestaMultipleConfigurada,
			String respuestaTexto, Boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idResultadoEncuesta = idResultadoEncuesta;
		this.preguntaConfigurada = preguntaConfigurada;
		this.respuestaMultipleConfigurada = respuestaMultipleConfigurada;
		this.respuestaTexto = respuestaTexto;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_resultado_encuesta", unique = true, nullable = false)
		@GeneratedValue(generator="RESULTADO_ECUESTA_GENERATOR")
	@SequenceGenerator(name="RESULTADO_ECUESTA_GENERATOR",sequenceName="capacitacion.resultado_encuesta_id_resultado_encuesta_seq")

	public Long getIdResultadoEncuesta() {
		return this.idResultadoEncuesta;
	}

	public void setIdResultadoEncuesta(Long idResultadoEncuesta) {
		this.idResultadoEncuesta = idResultadoEncuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pregunta_conf", nullable = false)
	@NotNull
	public PreguntaConfigurada getPreguntaConfigurada() {
		return this.preguntaConfigurada;
	}

	public void setPreguntaConfigurada(PreguntaConfigurada preguntaConfigurada) {
		this.preguntaConfigurada = preguntaConfigurada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_respuesta_m_conf")
	public RespuestaMultipleConfigurada getRespuestaMultipleConfigurada() {
		return this.respuestaMultipleConfigurada;
	}

	public void setRespuestaMultipleConfigurada(
			RespuestaMultipleConfigurada respuestaMultipleConfigurada) {
		this.respuestaMultipleConfigurada = respuestaMultipleConfigurada;
	}

	@Column(name = "respuesta_texto", length = 500)
	@Length(max = 500)
	public String getRespuestaTexto() {
		return this.respuestaTexto;
	}

	public void setRespuestaTexto(String respuestaTexto) {
		this.respuestaTexto = respuestaTexto;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
