package py.com.excelsis.sicca.entity;

// Generated 15/10/2012 05:24:06 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ResultadoEvalPlan generated by hbm2java
 */
@Entity
@Table(name = "resultado_eval_plan", schema = "eval_desempeno")
public class ResultadoEvalPlan implements java.io.Serializable {

	private Long idResultadoEvalPlan;
	private ResultadoEval resultadoEval;
	private PlantillaEvalPdecCab plantillaEvalPdecCab;
	private PlanMejora planMejora;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public ResultadoEvalPlan() {
	}

	public ResultadoEvalPlan(
			Long idResultadoEvalPlan, PlanMejora planMejora, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idResultadoEvalPlan = idResultadoEvalPlan;
		this.planMejora = planMejora;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ResultadoEvalPlan(
			Long idResultadoEvalPlan, ResultadoEval resultadoEval,
			PlantillaEvalPdecCab plantillaEvalPdecCab, PlanMejora planMejora, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idResultadoEvalPlan = idResultadoEvalPlan;
		this.resultadoEval = resultadoEval;
		this.plantillaEvalPdecCab = plantillaEvalPdecCab;
		this.planMejora = planMejora;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_resultado_eval_plan", unique = true, nullable = false)
	@GeneratedValue(generator = "RESULTADO_EVAL_PLAN_GENERATOR")
	@SequenceGenerator(name = "RESULTADO_EVAL_PLAN_GENERATOR", sequenceName = "eval_desempeno.resultado_eval_plan_id_resultado_eval_plan_seq")
	public Long getIdResultadoEvalPlan() {
		return this.idResultadoEvalPlan;
	}

	public void setIdResultadoEvalPlan(Long idResultadoEvalPlan) {
		this.idResultadoEvalPlan = idResultadoEvalPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resultado_eval")
	public ResultadoEval getResultadoEval() {
		return this.resultadoEval;
	}

	public void setResultadoEval(ResultadoEval resultadoEval) {
		this.resultadoEval = resultadoEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_eval_pdec_cab")
	public PlantillaEvalPdecCab getPlantillaEvalPdecCab() {
		return this.plantillaEvalPdecCab;
	}

	public void setPlantillaEvalPdecCab(PlantillaEvalPdecCab plantillaEvalPdecCab) {
		this.plantillaEvalPdecCab = plantillaEvalPdecCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plan_mejora", nullable = false)
	@NotNull
	public PlanMejora getPlanMejora() {
		return this.planMejora;
	}

	public void setPlanMejora(PlanMejora planMejora) {
		this.planMejora = planMejora;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
