package py.com.excelsis.sicca.entity;

// Generated 15/10/2012 05:24:06 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ResultadoEval generated by hbm2java
 */
@Entity
@Table(name = "resultado_eval", schema = "eval_desempeno")
public class ResultadoEval implements java.io.Serializable {

	private Long idResultadoEval;
	private GruposSujetos gruposSujetos;
	private PlantillaEvalConfDet plantillaEvalConfDet;
	private PlantillaEvalEscala plantillaEvalEscala;
	private GrupoMetodologia grupoMetodologia;
	private String justificacion;
	private String comentario;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Float puntaje;
	private Set<ResultadoEvalPlan> resultadoEvalPlans = new HashSet<ResultadoEvalPlan>(0);
	private List<PlanMejora> lPM;

	public ResultadoEval() {
	}

	public ResultadoEval(Long idResultadoEval, String usuAlta, Date fechaAlta) {
		this.idResultadoEval = idResultadoEval;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public ResultadoEval(
			Long idResultadoEval, GruposSujetos gruposSujetos,
			PlantillaEvalConfDet plantillaEvalConfDet, PlantillaEvalEscala plantillaEvalEscala,
			GrupoMetodologia grupoMetodologia, String justificacion, String comentario,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod, Float puntaje,
			Set<ResultadoEvalPlan> resultadoEvalPlans) {
		this.idResultadoEval = idResultadoEval;
		this.gruposSujetos = gruposSujetos;
		this.plantillaEvalConfDet = plantillaEvalConfDet;
		this.plantillaEvalEscala = plantillaEvalEscala;
		this.grupoMetodologia = grupoMetodologia;
		this.justificacion = justificacion;
		this.comentario = comentario;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.puntaje = puntaje;
		this.resultadoEvalPlans = resultadoEvalPlans;
	}

	@Id
	@Column(name = "id_resultado_eval", unique = true, nullable = false)
	@GeneratedValue(generator = "RESULTADO_EVAL_GENERATOR")
	@SequenceGenerator(name = "RESULTADO_EVAL_GENERATOR", sequenceName = "eval_desempeno.resultado_eval_id_resultado_eval_seq")
	public Long getIdResultadoEval() {
		return this.idResultadoEval;
	}

	public void setIdResultadoEval(Long idResultadoEval) {
		this.idResultadoEval = idResultadoEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_sujeto")
	public GruposSujetos getGruposSujetos() {
		return this.gruposSujetos;
	}

	public void setGruposSujetos(GruposSujetos gruposSujetos) {
		this.gruposSujetos = gruposSujetos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_eval_conf_det")
	public PlantillaEvalConfDet getPlantillaEvalConfDet() {
		return this.plantillaEvalConfDet;
	}

	public void setPlantillaEvalConfDet(PlantillaEvalConfDet plantillaEvalConfDet) {
		this.plantillaEvalConfDet = plantillaEvalConfDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_plantilla_eval_escala")
	public PlantillaEvalEscala getPlantillaEvalEscala() {
		return this.plantillaEvalEscala;
	}

	public void setPlantillaEvalEscala(PlantillaEvalEscala plantillaEvalEscala) {
		this.plantillaEvalEscala = plantillaEvalEscala;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_metodologia")
	public GrupoMetodologia getGrupoMetodologia() {
		return this.grupoMetodologia;
	}

	public void setGrupoMetodologia(GrupoMetodologia grupoMetodologia) {
		this.grupoMetodologia = grupoMetodologia;
	}

	@Column(name = "justificacion", length = 500)
	@Length(max = 500)
	public String getJustificacion() {
		return this.justificacion;
	}

	public void setJustificacion(String justificacion) {
		this.justificacion = justificacion;
	}

	@Column(name = "comentario", length = 500)
	@Length(max = 500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Column(name = "puntaje", precision = 8, scale = 8)
	public Float getPuntaje() {
		return this.puntaje;
	}

	public void setPuntaje(Float puntaje) {
		this.puntaje = puntaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resultadoEval")
	public Set<ResultadoEvalPlan> getResultadoEvalPlans() {
		return this.resultadoEvalPlans;
	}

	public void setResultadoEvalPlans(Set<ResultadoEvalPlan> resultadoEvalPlans) {
		this.resultadoEvalPlans = resultadoEvalPlans;
	}

	@Transient
	public List<PlanMejora> getlPM() {
		return lPM;
	}

	public void setlPM(List<PlanMejora> lPM) {
		this.lPM = lPM;
	}

}
