package py.com.excelsis.sicca.entity;

// Generated 25/09/2012 10:17:38 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * RevisionEvaluacion generated by hbm2java
 */
@Entity
@Table(name = "revision_evaluacion", schema = "eval_desempeno")
public class RevisionEvaluacion implements java.io.Serializable {

	private Long idRevisionEval;
	private EvaluacionDesempeno evaluacionDesempeno;
	private String observacion;
	private String usuObs;
	private Date fechaObs;
	private String respuesta;
	private String usuRpta;
	private Date fechaRpta;

	public RevisionEvaluacion() {
	}

	public RevisionEvaluacion(Long idRevisionEval, EvaluacionDesempeno idEvaluacionDesempeno,
			String observacion, String usuObs, Date fechaObs) {
		this.idRevisionEval = idRevisionEval;
		this.evaluacionDesempeno = idEvaluacionDesempeno;
		this.observacion = observacion;
		this.usuObs = usuObs;
		this.fechaObs = fechaObs;
	}

	public RevisionEvaluacion(Long idRevisionEval, EvaluacionDesempeno idEvaluacionDesempeno,
			String observacion, String usuObs, Date fechaObs, String respuesta,
			String usuRpta, Date fechaRpta) {
		this.idRevisionEval = idRevisionEval;
		this.evaluacionDesempeno = idEvaluacionDesempeno;
		this.observacion = observacion;
		this.usuObs = usuObs;
		this.fechaObs = fechaObs;
		this.respuesta = respuesta;
		this.usuRpta = usuRpta;
		this.fechaRpta = fechaRpta;
	}

	@Id
	@Column(name = "id_revision_eval", unique = true, nullable = false)
	@GeneratedValue(generator = "REVISION_EVALUACION_GENERATOR")
	@SequenceGenerator(name = "REVISION_EVALUACION_GENERATOR", sequenceName = "eval_desempeno.revision_evaluacion_id_revision_eval_seq")
	public Long getIdRevisionEval() {
		return this.idRevisionEval;
	}

	public void setIdRevisionEval(Long idRevisionEval) {
		this.idRevisionEval = idRevisionEval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno")
	@NotNull
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}

	

	@Column(name = "observacion", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "usu_obs", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuObs() {
		return this.usuObs;
	}

	public void setUsuObs(String usuObs) {
		this.usuObs = usuObs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_obs", nullable = false, length = 29)
	@NotNull
	public Date getFechaObs() {
		return this.fechaObs;
	}

	public void setFechaObs(Date fechaObs) {
		this.fechaObs = fechaObs;
	}

	@Column(name = "respuesta", length = 1000)
	@Length(max = 1000)
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Column(name = "usu_rpta", length = 50)
	@Length(max = 50)
	public String getUsuRpta() {
		return this.usuRpta;
	}

	public void setUsuRpta(String usuRpta) {
		this.usuRpta = usuRpta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_rpta", length = 29)
	public Date getFechaRpta() {
		return this.fechaRpta;
	}

	public void setFechaRpta(Date fechaRpta) {
		this.fechaRpta = fechaRpta;
	}

}
