package py.com.excelsis.sicca.entity;

// Generated 20/10/2011 01:43:05 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import py.com.excelsis.sicca.seguridad.entity.Funcion;

/**
 * SelFuncionDatosEsp generated by hbm2java
 */
@Entity
@Table(name = "sel_funcion_datos_esp", schema = "seleccion")
public class SelFuncionDatosEsp implements java.io.Serializable {

	private Long idFuncionDatosEsp;
	private Funcion funcion;
	private DatosEspecificos datosEspecificos;
	private Integer cantidad;
	private boolean obligatorioSN;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public SelFuncionDatosEsp() {
	}

	public SelFuncionDatosEsp(Long idFuncionDatosEsp, 
			DatosEspecificos datosEspecificos, Integer cantidad,
			boolean obligatorioSN, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idFuncionDatosEsp = idFuncionDatosEsp;
		
		this.datosEspecificos = datosEspecificos;
		this.cantidad = cantidad;
		this.obligatorioSN = obligatorioSN;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public SelFuncionDatosEsp(Long idFuncionDatosEsp, 
			DatosEspecificos datosEspecificos, Integer cantidad,
			boolean obligatorioSN, boolean activo, String usuAlta,
			Date fechaAlta, String usuMod, Date fechaMod) {
		this.idFuncionDatosEsp = idFuncionDatosEsp;
		this.datosEspecificos = datosEspecificos;
		this.cantidad = cantidad;
		this.obligatorioSN = obligatorioSN;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="SEL_FUNCION_DATOS_ESP_GENERATOR")
	@SequenceGenerator(name="SEL_FUNCION_DATOS_ESP_GENERATOR",sequenceName="seleccion.funcion_datos_esp_id_funcion_datos_esp_seq")
	@Column(name = "id_funcion_datos_esp", unique = true, nullable = false)
	public Long getIdFuncionDatosEsp() {
		return this.idFuncionDatosEsp;
	}

	public void setIdFuncionDatosEsp(Long idFuncionDatosEsp) {
		this.idFuncionDatosEsp = idFuncionDatosEsp;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_especificos_tipo_doc", nullable = false)
	@NotNull
	public DatosEspecificos getDatosEspecificos() {
		return this.datosEspecificos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_funcion", nullable = false)
	@NotNull
	public Funcion getFuncion() {
		return funcion;
	}

	public void setFuncion(Funcion funcion) {
		this.funcion = funcion;
	}

	public void setDatosEspecificos(DatosEspecificos datosEspecificos) {
		this.datosEspecificos = datosEspecificos;
	}

	@Column(name = "cantidad", nullable = false)
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "obligatorio_s_n", nullable = false)
	public boolean isObligatorioSN() {
		return this.obligatorioSN;
	}

	public void setObligatorioSN(boolean obligatorioSN) {
		this.obligatorioSN = obligatorioSN;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
