package py.com.excelsis.sicca.entity;

// Generated 09-nov-2012 16:40:10 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SinAnxOriginal generated by hbm2java
 */
@Entity
@Table(name = "sin_anx_original", schema = "sinarh")
public class SinAnxOriginal implements java.io.Serializable {

	private Long idAnxOriginal;
	private Integer aniAniopre;
	private Integer nenCodigo;
	private Integer entCodigo;
	private Integer tipCodigo;
	private Integer proCodigo;
	private Integer subCodigo;
	private Integer pryCodigo;
	private Integer objCodigo;
	private Integer fueCodigo;
	private Integer finCodigo;
	private Integer vrsCodigo;
	private String anxLinea;
	private Integer catGrupo;
	private String ctgCodigo;
	private String mdfCodigo;
	private String anxTiporeg;
	private Integer anxMesaplic;
	private Integer anxDurac;
	private Long anxVlran;
	private Integer anxCargos;
	private String anxDescrip;
	private Integer paiCodigo;
	private Integer dptCodigo;
	private String anxJustifica;
	private Date anxFching;
	private String anxUsring;
	private Date anxFchact;
	private String anxUsract;
	private Integer cantDisponible;
	private Date fechaDescarga;
	 

	public SinAnxOriginal() {
	}

	public SinAnxOriginal(Long idAnxOriginal, Integer aniAniopre, Integer nenCodigo,
			Integer entCodigo, Integer tipCodigo, Integer proCodigo, Integer subCodigo,
			Integer pryCodigo, Integer objCodigo, Integer fueCodigo, Integer finCodigo,
			Integer vrsCodigo, String anxLinea, Integer catGrupo, String ctgCodigo,
			String mdfCodigo, String anxTiporeg, Integer anxMesaplic, Integer anxDurac,
			Long anxVlran, Integer anxCargos, String anxDescrip, Integer paiCodigo,
			Integer dptCodigo) {
		this.idAnxOriginal = idAnxOriginal;
		this.aniAniopre = aniAniopre;
		this.nenCodigo = nenCodigo;
		this.entCodigo = entCodigo;
		this.tipCodigo = tipCodigo;
		this.proCodigo = proCodigo;
		this.subCodigo = subCodigo;
		this.pryCodigo = pryCodigo;
		this.objCodigo = objCodigo;
		this.fueCodigo = fueCodigo;
		this.finCodigo = finCodigo;
		this.vrsCodigo = vrsCodigo;
		this.anxLinea = anxLinea;
		this.catGrupo = catGrupo;
		this.ctgCodigo = ctgCodigo;
		this.mdfCodigo = mdfCodigo;
		this.anxTiporeg = anxTiporeg;
		this.anxMesaplic = anxMesaplic;
		this.anxDurac = anxDurac;
		this.anxVlran = anxVlran;
		this.anxCargos = anxCargos;
		this.anxDescrip = anxDescrip;
		this.paiCodigo = paiCodigo;
		this.dptCodigo = dptCodigo;
	}

	public SinAnxOriginal(Long idAnxOriginal, Integer aniAniopre, Integer nenCodigo,
			Integer entCodigo, Integer tipCodigo, Integer proCodigo, Integer subCodigo,
			Integer pryCodigo, Integer objCodigo, Integer fueCodigo, Integer finCodigo,
			Integer vrsCodigo, String anxLinea, Integer catGrupo, String ctgCodigo,
			String mdfCodigo, String anxTiporeg, Integer anxMesaplic, Integer anxDurac,
			Long anxVlran, Integer anxCargos, String anxDescrip, Integer paiCodigo,
			Integer dptCodigo, String anxJustifica, Date anxFching,
			String anxUsring, Date anxFchact, String anxUsract,
			Integer cantDisponible) {
		this.idAnxOriginal = idAnxOriginal;
		this.aniAniopre = aniAniopre;
		this.nenCodigo = nenCodigo;
		this.entCodigo = entCodigo;
		this.tipCodigo = tipCodigo;
		this.proCodigo = proCodigo;
		this.subCodigo = subCodigo;
		this.pryCodigo = pryCodigo;
		this.objCodigo = objCodigo;
		this.fueCodigo = fueCodigo;
		this.finCodigo = finCodigo;
		this.vrsCodigo = vrsCodigo;
		this.anxLinea = anxLinea;
		this.catGrupo = catGrupo;
		this.ctgCodigo = ctgCodigo;
		this.mdfCodigo = mdfCodigo;
		this.anxTiporeg = anxTiporeg;
		this.anxMesaplic = anxMesaplic;
		this.anxDurac = anxDurac;
		this.anxVlran = anxVlran;
		this.anxCargos = anxCargos;
		this.anxDescrip = anxDescrip;
		this.paiCodigo = paiCodigo;
		this.dptCodigo = dptCodigo;
		this.anxJustifica = anxJustifica;
		this.anxFching = anxFching;
		this.anxUsring = anxUsring;
		this.anxFchact = anxFchact;
		this.anxUsract = anxUsract;
		this.cantDisponible = cantDisponible;
	}

	@Id
	@GeneratedValue(generator="SIN_ANX_ORIGINAL_GENERATOR")
	@SequenceGenerator(name="SIN_ANX_ORIGINAL_GENERATOR",sequenceName="sinarh.sin_anx_original_id_anx_original_seq")
	@Column(name = "id_anx_original", unique = true, nullable = false)
	public Long getIdAnxOriginal() {
		return this.idAnxOriginal;
	}

	public void setIdAnxOriginal(Long idAnxOriginal) {
		this.idAnxOriginal = idAnxOriginal;
	}

	@Column(name = "ani_aniopre")
	public Integer getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(Integer aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "nen_codigo")
	public Integer getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(Integer nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo")
	public Integer getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Integer entCodigo) {
		this.entCodigo = entCodigo;
	}

	@Column(name = "tip_codigo")
	public Integer getTipCodigo() {
		return this.tipCodigo;
	}

	public void setTipCodigo(int tipCodigo) {
		this.tipCodigo = tipCodigo;
	}

	@Column(name = "pro_codigo")
	public Integer getProCodigo() {
		return this.proCodigo;
	}

	public void setProCodigo(Integer proCodigo) {
		this.proCodigo = proCodigo;
	}

	@Column(name = "sub_codigo")
	public Integer getSubCodigo() {
		return this.subCodigo;
	}

	public void setSubCodigo(Integer subCodigo) {
		this.subCodigo = subCodigo;
	}

	@Column(name = "pry_codigo")
	public Integer getPryCodigo() {
		return this.pryCodigo;
	}

	public void setPryCodigo(Integer pryCodigo) {
		this.pryCodigo = pryCodigo;
	}

	@Column(name = "obj_codigo")
	public Integer getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(Integer objCodigo) {
		this.objCodigo = objCodigo;
	}

	@Column(name = "fue_codigo")
	public Integer getFueCodigo() {
		return this.fueCodigo;
	}

	public void setFueCodigo(Integer fueCodigo) {
		this.fueCodigo = fueCodigo;
	}

	@Column(name = "fin_codigo")
	public Integer getFinCodigo() {
		return this.finCodigo;
	}

	public void setFinCodigo(Integer finCodigo) {
		this.finCodigo = finCodigo;
	}

	@Column(name = "vrs_codigo")
	public Integer getVrsCodigo() {
		return this.vrsCodigo;
	}

	public void setVrsCodigo(Integer vrsCodigo) {
		this.vrsCodigo = vrsCodigo;
	}

	@Column(name = "anx_linea")
	public String getAnxLinea() {
		return this.anxLinea;
	}

	public void setAnxLinea(String anxLinea) {
		this.anxLinea = anxLinea;
	}

	@Column(name = "cat_grupo")
	public Integer getCatGrupo() {
		return this.catGrupo;
	}

	public void setCatGrupo(Integer catGrupo) {
		this.catGrupo = catGrupo;
	}

	@Column(name = "ctg_codigo", length = 20)
	@NotNull
	@Length(max = 20)
	public String getCtgCodigo() {
		return this.ctgCodigo;
	}

	public void setCtgCodigo(String ctgCodigo) {
		this.ctgCodigo = ctgCodigo;
	}

	@Column(name = "mdf_codigo", length = 20)
	@NotNull
	@Length(max = 20)
	public String getMdfCodigo() {
		return this.mdfCodigo;
	}

	public void setMdfCodigo(String mdfCodigo) {
		this.mdfCodigo = mdfCodigo;
	}

	@Column(name = "anx_tiporeg", length = 10)
	@NotNull
	@Length(max = 10)
	public String getAnxTiporeg() {
		return this.anxTiporeg;
	}

	public void setAnxTiporeg(String anxTiporeg) {
		this.anxTiporeg = anxTiporeg;
	}

	@Column(name = "anx_mesaplic")
	public Integer getAnxMesaplic() {
		return this.anxMesaplic;
	}

	public void setAnxMesaplic(Integer anxMesaplic) {
		this.anxMesaplic = anxMesaplic;
	}

	@Column(name = "anx_durac")
	public Integer getAnxDurac() {
		return this.anxDurac;
	}

	public void setAnxDurac(Integer anxDurac) {
		this.anxDurac = anxDurac;
	}

	@Column(name = "anx_vlran")
	public Long getAnxVlran() {
		return this.anxVlran;
	}

	public void setAnxVlran(Long anxVlran) {
		this.anxVlran = anxVlran;
	}

	@Column(name = "anx_cargos")
	public Integer getAnxCargos() {
		return this.anxCargos;
	}

	public void setAnxCargos(Integer anxCargos) {
		this.anxCargos = anxCargos;
	}

	@Column(name = "anx_descrip", length = 200)
	@NotNull
	@Length(max = 200)
	public String getAnxDescrip() {
		return this.anxDescrip;
	}

	public void setAnxDescrip(String anxDescrip) {
		this.anxDescrip = anxDescrip;
	}

	@Column(name = "pai_codigo")
	public Integer getPaiCodigo() {
		return this.paiCodigo;
	}

	public void setPaiCodigo(Integer paiCodigo) {
		this.paiCodigo = paiCodigo;
	}

	@Column(name = "dpt_codigo")
	public Integer getDptCodigo() {
		return this.dptCodigo;
	}

	public void setDptCodigo(Integer dptCodigo) {
		this.dptCodigo = dptCodigo;
	}

	@Column(name = "anx_justifica", length = 100)
	@Length(max = 100)
	public String getAnxJustifica() {
		return this.anxJustifica;
	}

	public void setAnxJustifica(String anxJustifica) {
		this.anxJustifica = anxJustifica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "anx_fching", length = 29)
	public Date getAnxFching() {
		return this.anxFching;
	}

	public void setAnxFching(Date anxFching) {
		this.anxFching = anxFching;
	}

	@Column(name = "anx_usring", length = 50)
	@Length(max = 50)
	public String getAnxUsring() {
		return this.anxUsring;
	}

	public void setAnxUsring(String anxUsring) {
		this.anxUsring = anxUsring;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "anx_fchact", length = 29)
	public Date getAnxFchact() {
		return this.anxFchact;
	}

	public void setAnxFchact(Date anxFchact) {
		this.anxFchact = anxFchact;
	}

	@Column(name = "anx_usract", length = 50)
	@Length(max = 50)
	public String getAnxUsract() {
		return this.anxUsract;
	}

	public void setAnxUsract(String anxUsract) {
		this.anxUsract = anxUsract;
	}

	@Column(name = "cant_disponible")
	public Integer getCantDisponible() {
		return this.cantDisponible;
	}

	public void setCantDisponible(Integer cantDisponible) {
		this.cantDisponible = cantDisponible;
	}
	@Column(name = "fecha_descarga")
	public Date getFechaDescarga() {
		return fechaDescarga;
	}


	public void setFechaDescarga(Date fecha) {
		this.fechaDescarga = fecha;
	}

}
