package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * SinCategoriaContratados generated by Generality
 */
@Entity
@Table(name = "sin_categoria_contratados", schema = "sinarh")
public class SinCategoriaContratados implements java.io.Serializable {
	private Long idSinCategoriaContratados;
	private BigDecimal aniAniopre;
	private BigDecimal objCodigo;
	private String conCtg;
	private String ctgDescrip;
	private BigDecimal ctgLinea;
	private Date fechaAlta;
	private Date fechaMod;

	public SinCategoriaContratados() {
	}

	public SinCategoriaContratados(Long idSinCategoriaContratados) {
		this.idSinCategoriaContratados = idSinCategoriaContratados;
	}

	@Id
	@GeneratedValue(generator="SIN_CATEGORIA_CONTRATADOS_GENERATOR")
	@SequenceGenerator(name="SIN_CATEGORIA_CONTRATADOS_GENERATOR",sequenceName="sinarh.sin_categoria_contratados_id_sin_categoria_contratados_seq")

	@Column(name = "id_sin_categoria_contratados")
	public Long getIdSinCategoriaContratados() {
		return this.idSinCategoriaContratados;
	}

	public void setIdSinCategoriaContratados(Long idSinCategoriaContratados) {
		this.idSinCategoriaContratados = idSinCategoriaContratados;
	}
	

	@Column(name = "ani_aniopre")
	public BigDecimal getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(BigDecimal aniAniopre) {
		this.aniAniopre = aniAniopre;
	}
	

	@Column(name = "obj_codigo")
	public BigDecimal getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(BigDecimal objCodigo) {
		this.objCodigo = objCodigo;
	}
	

	@Column(name = "con_ctg")
	public String getConCtg() {
		return this.conCtg;
	}

	public void setConCtg(String conCtg) {
		this.conCtg = conCtg;
	}
	

	@Column(name = "ctg_descrip")
	public String getCtgDescrip() {
		return this.ctgDescrip;
	}

	public void setCtgDescrip(String ctgDescrip) {
		this.ctgDescrip = ctgDescrip;
	}
	

	@Column(name = "ctg_linea")
	public BigDecimal getCtgLinea() {
		return this.ctgLinea;
	}

	public void setCtgLinea(BigDecimal ctgLinea) {
		this.ctgLinea = ctgLinea;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idSinCategoriaContratados == null) ? 0 : idSinCategoriaContratados.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SinCategoriaContratados other = (SinCategoriaContratados) obj;
		if (idSinCategoriaContratados == null) {
			if (other.idSinCategoriaContratados != null)
				return false;
		} else if (!idSinCategoriaContratados.equals(other.idSinCategoriaContratados))
			return false;
		return true;
	}
}
