package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * SinCategoria generated by Generality
 */
@Entity
@Table(name = "sin_categoria", schema = "sinarh")
public class SinCategoria implements java.io.Serializable {
	private Long idSinCategoria;
	private BigDecimal aniAniopre;
	private BigDecimal catGrupo;
	private String ctgCodigo;
	private BigDecimal ctgValor1;
	private BigDecimal ctgValor2;
	private BigDecimal ctgValor3;
	private BigDecimal ctgValor4;
	private BigDecimal ctgValor5;
	private BigDecimal ctgValor6;
	private BigDecimal ctgValor7;
	private BigDecimal ctgValor8;
	private BigDecimal ctgValor9;
	private BigDecimal ctgValor10;
	private BigDecimal ctgValor11;
	private BigDecimal ctgValor12;
	private String ctgDenominacion;
	private Date fechaAlta;
	private Date fechaMod;
	private String vrsCodigo;

	public SinCategoria() {
	}

	public SinCategoria(Long idSinCategoria) {
		this.idSinCategoria = idSinCategoria;
	}

	@Id
	@GeneratedValue(generator="SIN_CATEGORIA_GENERATOR")
	@SequenceGenerator(name="SIN_CATEGORIA_GENERATOR",sequenceName="sinarh.sin_categoria_id_sin_categoria_seq")
	@Column(name = "id_sin_categoria")
	public Long getIdSinCategoria() {
		return this.idSinCategoria;
	}

	public void setIdSinCategoria(Long idSinCategoria) {
		this.idSinCategoria = idSinCategoria;
	}
	

	@Column(name = "ani_aniopre")
	public BigDecimal getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(BigDecimal aniAniopre) {
		this.aniAniopre = aniAniopre;
	}
	

	@Column(name = "cat_grupo")
	public BigDecimal getCatGrupo() {
		return this.catGrupo;
	}

	public void setCatGrupo(BigDecimal catGrupo) {
		this.catGrupo = catGrupo;
	}
	

	@Column(name = "ctg_codigo")
	public String getCtgCodigo() {
		return this.ctgCodigo;
	}

	public void setCtgCodigo(String ctgCodigo) {
		this.ctgCodigo = ctgCodigo;
	}
	

	@Column(name = "ctg_valor1")
	public BigDecimal getCtgValor1() {
		return this.ctgValor1;
	}

	public void setCtgValor1(BigDecimal ctgValor1) {
		this.ctgValor1 = ctgValor1;
	}
	

	@Column(name = "ctg_valor2")
	public BigDecimal getCtgValor2() {
		return this.ctgValor2;
	}

	public void setCtgValor2(BigDecimal ctgValor2) {
		this.ctgValor2 = ctgValor2;
	}
	

	@Column(name = "ctg_valor3")
	public BigDecimal getCtgValor3() {
		return this.ctgValor3;
	}

	public void setCtgValor3(BigDecimal ctgValor3) {
		this.ctgValor3 = ctgValor3;
	}
	

	@Column(name = "ctg_valor4")
	public BigDecimal getCtgValor4() {
		return this.ctgValor4;
	}

	public void setCtgValor4(BigDecimal ctgValor4) {
		this.ctgValor4 = ctgValor4;
	}
	

	@Column(name = "ctg_valor5")
	public BigDecimal getCtgValor5() {
		return this.ctgValor5;
	}

	public void setCtgValor5(BigDecimal ctgValor5) {
		this.ctgValor5 = ctgValor5;
	}
	

	@Column(name = "ctg_valor6")
	public BigDecimal getCtgValor6() {
		return this.ctgValor6;
	}

	public void setCtgValor6(BigDecimal ctgValor6) {
		this.ctgValor6 = ctgValor6;
	}
	

	@Column(name = "ctg_valor7")
	public BigDecimal getCtgValor7() {
		return this.ctgValor7;
	}

	public void setCtgValor7(BigDecimal ctgValor7) {
		this.ctgValor7 = ctgValor7;
	}
	

	@Column(name = "ctg_valor8")
	public BigDecimal getCtgValor8() {
		return this.ctgValor8;
	}

	public void setCtgValor8(BigDecimal ctgValor8) {
		this.ctgValor8 = ctgValor8;
	}
	

	@Column(name = "ctg_valor9")
	public BigDecimal getCtgValor9() {
		return this.ctgValor9;
	}

	public void setCtgValor9(BigDecimal ctgValor9) {
		this.ctgValor9 = ctgValor9;
	}
	

	@Column(name = "ctg_valor10")
	public BigDecimal getCtgValor10() {
		return this.ctgValor10;
	}

	public void setCtgValor10(BigDecimal ctgValor10) {
		this.ctgValor10 = ctgValor10;
	}
	

	@Column(name = "ctg_valor11")
	public BigDecimal getCtgValor11() {
		return this.ctgValor11;
	}

	public void setCtgValor11(BigDecimal ctgValor11) {
		this.ctgValor11 = ctgValor11;
	}
	

	@Column(name = "ctg_valor12")
	public BigDecimal getCtgValor12() {
		return this.ctgValor12;
	}

	public void setCtgValor12(BigDecimal ctgValor12) {
		this.ctgValor12 = ctgValor12;
	}
	

	@Column(name = "ctg_denominacion")
	public String getCtgDenominacion() {
		return this.ctgDenominacion;
	}

	public void setCtgDenominacion(String ctgDenominacion) {
		this.ctgDenominacion = ctgDenominacion;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	

	@Column(name = "vrs_codigo")
	public String getVrsCodigo() {
		return this.vrsCodigo;
	}

	public void setVrsCodigo(String vrsCodigo) {
		this.vrsCodigo = vrsCodigo;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idSinCategoria == null) ? 0 : idSinCategoria.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SinCategoria other = (SinCategoria) obj;
		if (idSinCategoria == null) {
			if (other.idSinCategoria != null)
				return false;
		} else if (!idSinCategoria.equals(other.idSinCategoria))
			return false;
		return true;
	}
}
