package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * SinEntidad generated by Generality
 */
@Entity
@Table(name = "sin_entidad", schema = "sinarh")
public class SinEntidad implements java.io.Serializable {
	private BigDecimal aniAniopre;
	private BigDecimal nenCodigo;
	private BigDecimal entCodigo;
	private String entNombre;
	private String entNomabre;
	private String entSigla;
	private String entRuc;
	private BigDecimal cofCodigo;
	private Date fechaAlta;
	private Date fechaMod;
	private Long idSinEntidad;
	private Boolean activo;
	private String usuAlta;
	private String usuMod;

	
	private Set<Entidad> entidads = new HashSet<Entidad>(0);
	

	public SinEntidad() {
	}

	public SinEntidad(Long idSinEntidad) {
		this.idSinEntidad = idSinEntidad;
	}


	@Column(name = "ani_aniopre")
	public BigDecimal getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(BigDecimal aniAniopre) {
		this.aniAniopre = aniAniopre;
	}
	

	@Column(name = "nen_codigo")
	public BigDecimal getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(BigDecimal nenCodigo) {
		this.nenCodigo = nenCodigo;
	}
	

	@Column(name = "ent_codigo")
	public BigDecimal getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(BigDecimal entCodigo) {
		this.entCodigo = entCodigo;
	}
	

	@Column(name = "ent_nombre")
	public String getEntNombre() {
		return this.entNombre;
	}

	public void setEntNombre(String entNombre) {
		this.entNombre = entNombre;
	}
	

	@Column(name = "ent_nomabre")
	public String getEntNomabre() {
		return this.entNomabre;
	}

	public void setEntNomabre(String entNomabre) {
		this.entNomabre = entNomabre;
	}
	

	@Column(name = "ent_sigla")
	public String getEntSigla() {
		return this.entSigla;
	}

	public void setEntSigla(String entSigla) {
		this.entSigla = entSigla;
	}
	

	@Column(name = "ent_ruc")
	public String getEntRuc() {
		return this.entRuc;
	}

	public void setEntRuc(String entRuc) {
		this.entRuc = entRuc;
	}
	

	@Column(name = "cof_codigo")
	public BigDecimal getCofCodigo() {
		return this.cofCodigo;
	}

	public void setCofCodigo(BigDecimal cofCodigo) {
		this.cofCodigo = cofCodigo;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Id
	@GeneratedValue(generator="SIN_ENTIDAD_GENERATOR")
	@SequenceGenerator(name="SIN_ENTIDAD_GENERATOR",sequenceName="sinarh.sin_entidad_id_sin_entidad_seq")

	@Column(name = "id_sin_entidad")
	public Long getIdSinEntidad() {
		return this.idSinEntidad;
	}

	public void setIdSinEntidad(Long idSinEntidad) {
		this.idSinEntidad = idSinEntidad;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinEntidad")
	public Set<Entidad> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad> entidads) {
		this.entidads = entidads;
	}
	
	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	@Column(name = "usu_mod")
	public String getUsuMod() {
		return usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idSinEntidad == null) ? 0 : idSinEntidad.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SinEntidad other = (SinEntidad) obj;
		if (idSinEntidad == null) {
			if (other.idSinEntidad != null)
				return false;
		} else if (!idSinEntidad.equals(other.idSinEntidad))
			return false;
		return true;
	}
}
