package py.com.excelsis.sicca.entity;

// Generated 14/10/2011 09:15:23 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SinFin generated by hbm2java
 */
@Entity
@Table(name = "sin_fin", schema = "sinarh")
public class SinFin implements java.io.Serializable {

	private Integer idFin;
	private Integer aniAniopre;
	private Integer finCodigo;
	private Integer finNivel;
	private String finNombre;

	public SinFin() {
	}

	public SinFin(Integer idFin, Integer aniAniopre, Integer finCodigo, Integer finNivel,
			String finNombre) {
		this.idFin = idFin;
		this.aniAniopre = aniAniopre;
		this.finCodigo = finCodigo;
		this.finNivel = finNivel;
		this.finNombre = finNombre;
	}

	@Id
	@Column(name = "id_fin", unique = true, nullable = false)
	public Integer getIdFin() {
		return this.idFin;
	}

	public void setIdFin(Integer idFin) {
		this.idFin = idFin;
	}

	@Column(name = "ani_aniopre", nullable = false)
	public Integer getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(Integer aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "fin_codigo", nullable = false)
	public Integer getFinCodigo() {
		return this.finCodigo;
	}

	public void setFinCodigo(Integer finCodigo) {
		this.finCodigo = finCodigo;
	}

	@Column(name = "fin_nivel", nullable = false)
	public Integer getFinNivel() {
		return this.finNivel;
	}

	public void setFinNivel(Integer finNivel) {
		this.finNivel = finNivel;
	}

	@Column(name = "fin_nombre", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getFinNombre() {
		return this.finNombre;
	}

	public void setFinNombre(String finNombre) {
		this.finNombre = finNombre;
	}

}
