package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * SinNivelEntidad generated by Generality
 */
@Entity
@Table(name = "sin_nivel_entidad", schema = "sinarh")
public class SinNivelEntidad implements java.io.Serializable {
	private BigDecimal aniAniopre;
	private BigDecimal nenCodigo;
	private String nenNombre;
	private String nenNomabr;
	private String nenImputable;
	private Date fechaAlta;
	private Date fechaMod;
	private Long idSinNivelEntidad;
	private Boolean activo;
	private String usuAlta;
	private String usuMod;

	public SinNivelEntidad() {
	}

	public SinNivelEntidad(Long idSinNivelEntidad) {
		this.idSinNivelEntidad = idSinNivelEntidad;
	}


	@Column(name = "ani_aniopre")
	public BigDecimal getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(BigDecimal aniAniopre) {
		this.aniAniopre = aniAniopre;
	}
	

	@Column(name = "nen_codigo")
	public BigDecimal getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(BigDecimal nenCodigo) {
		this.nenCodigo = nenCodigo;
	}
	

	@Column(name = "nen_nombre")
	public String getNenNombre() {
		return this.nenNombre;
	}

	public void setNenNombre(String nenNombre) {
		this.nenNombre = nenNombre;
	}
	

	@Column(name = "nen_nomabr")
	public String getNenNomabr() {
		return this.nenNomabr;
	}

	public void setNenNomabr(String nenNomabr) {
		this.nenNomabr = nenNomabr;
	}
	

	@Column(name = "nen_imputable")
	public String getNenImputable() {
		return this.nenImputable;
	}

	public void setNenImputable(String nenImputable) {
		this.nenImputable = nenImputable;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Id
	@GeneratedValue(generator="SIN_NIVEL_ENTIDAD_GENERATOR")
	@SequenceGenerator(name="SIN_NIVEL_ENTIDAD_GENERATOR",sequenceName="sinarh.sin_nivel_entidad_id_sin_nivel_entidad_seq")

	@Column(name = "id_sin_nivel_entidad")
	public Long getIdSinNivelEntidad() {
		return this.idSinNivelEntidad;
	}

	public void setIdSinNivelEntidad(Long idSinNivelEntidad) {
		this.idSinNivelEntidad = idSinNivelEntidad;
	}
	
	
	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	
	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	
	@Column(name = "usu_mod")
	public String getUsuMod() {
		return usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idSinNivelEntidad == null) ? 0 : idSinNivelEntidad.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SinNivelEntidad other = (SinNivelEntidad) obj;
		if (idSinNivelEntidad == null) {
			if (other.idSinNivelEntidad != null)
				return false;
		} else if (!idSinNivelEntidad.equals(other.idSinNivelEntidad))
			return false;
		return true;
	}
}
