package py.com.excelsis.sicca.entity;

// Generated 06/10/2011 03:09:44 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SinObj generated by hbm2java
 */
@Entity
@Table(name = "sin_obj", schema = "sinarh")
public class SinObj implements java.io.Serializable {

	private Integer idObj;
	private Integer aniAniopre;
	private Integer objCodigo;
	private String objNombre;

	public SinObj() {
	}

	public SinObj(Integer idObj, Integer aniAniopre, Integer objCodigo, String objNombre) {
		this.idObj = idObj;
		this.aniAniopre = aniAniopre;
		this.objCodigo = objCodigo;
		this.objNombre = objNombre;
	}

	@Id
	@Column(name = "id_obj", unique = true, nullable = false)
	public Integer getIdObj() {
		return this.idObj;
	}

	public void setIdObj(Integer idObj) {
		this.idObj = idObj;
	}

	@Column(name = "ani_aniopre", nullable = false)
	public Integer getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(Integer aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "obj_codigo", nullable = false)
	public Integer getObjCodigo() {
		return this.objCodigo;
	}

	public void setObjCodigo(Integer objCodigo) {
		this.objCodigo = objCodigo;
	}

	@Column(name = "obj_nombre", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getObjNombre() {
		return this.objNombre;
	}

	public void setObjNombre(String objNombre) {
		this.objNombre = objNombre;
	}

}
