package py.com.excelsis.sicca.entity;

// Generated 14/10/2011 09:15:23 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SinPry generated by hbm2java
 */
@Entity
@Table(name = "sin_pry", schema = "sinarh")
public class SinPry implements java.io.Serializable {

	private Integer idPry;
	private Integer aniAniopre;
	private Integer nenCodigo;
	private Integer entCodigo;
	private Integer tipCodigo;
	private Integer proCodigo;
	private Integer subCodigo;
	private Integer pryCodigo;
	private Integer unrCodigo;
	private String pryNombre;
	private String pryNomabr;
	private String pryDescrip;
	private Integer paiCodigo;
	private Integer dptCodigo;
	private Integer ciuCodigo;

	public SinPry() {
	}

	public SinPry(Integer idPry, Integer aniAniopre, Integer nenCodigo, Integer entCodigo,
			Integer tipCodigo, Integer proCodigo, Integer subCodigo, Integer pryCodigo,
			Integer unrCodigo, String pryNombre, String pryNomabr,
			String pryDescrip, Integer paiCodigo, Integer dptCodigo, Integer ciuCodigo) {
		this.idPry = idPry;
		this.aniAniopre = aniAniopre;
		this.nenCodigo = nenCodigo;
		this.entCodigo = entCodigo;
		this.tipCodigo = tipCodigo;
		this.proCodigo = proCodigo;
		this.subCodigo = subCodigo;
		this.pryCodigo = pryCodigo;
		this.unrCodigo = unrCodigo;
		this.pryNombre = pryNombre;
		this.pryNomabr = pryNomabr;
		this.pryDescrip = pryDescrip;
		this.paiCodigo = paiCodigo;
		this.dptCodigo = dptCodigo;
		this.ciuCodigo = ciuCodigo;
	}

	@Id
	@Column(name = "id_pry", unique = true, nullable = false)
	public Integer getIdPry() {
		return this.idPry;
	}

	public void setIdPry(Integer idPry) {
		this.idPry = idPry;
	}

	@Column(name = "ani_aniopre", nullable = false)
	public Integer getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(Integer aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "nen_codigo", nullable = false)
	public Integer getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(Integer nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo", nullable = false)
	public Integer getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Integer entCodigo) {
		this.entCodigo = entCodigo;
	}

	@Column(name = "tip_codigo", nullable = false)
	public Integer getTipCodigo() {
		return this.tipCodigo;
	}

	public void setTipCodigo(Integer tipCodigo) {
		this.tipCodigo = tipCodigo;
	}

	@Column(name = "pro_codigo", nullable = false)
	public Integer getProCodigo() {
		return this.proCodigo;
	}

	public void setProCodigo(Integer proCodigo) {
		this.proCodigo = proCodigo;
	}

	@Column(name = "sub_codigo", nullable = false)
	public Integer getSubCodigo() {
		return this.subCodigo;
	}

	public void setSubCodigo(Integer subCodigo) {
		this.subCodigo = subCodigo;
	}

	@Column(name = "pry_codigo", nullable = false)
	public Integer getPryCodigo() {
		return this.pryCodigo;
	}

	public void setPryCodigo(Integer pryCodigo) {
		this.pryCodigo = pryCodigo;
	}

	@Column(name = "unr_codigo", nullable = false)
	public Integer getUnrCodigo() {
		return this.unrCodigo;
	}

	public void setUnrCodigo(Integer unrCodigo) {
		this.unrCodigo = unrCodigo;
	}

	@Column(name = "pry_nombre", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getPryNombre() {
		return this.pryNombre;
	}

	public void setPryNombre(String pryNombre) {
		this.pryNombre = pryNombre;
	}

	@Column(name = "pry_nomabr", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getPryNomabr() {
		return this.pryNomabr;
	}

	public void setPryNomabr(String pryNomabr) {
		this.pryNomabr = pryNomabr;
	}

	@Column(name = "pry_descrip", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getPryDescrip() {
		return this.pryDescrip;
	}

	public void setPryDescrip(String pryDescrip) {
		this.pryDescrip = pryDescrip;
	}

	@Column(name = "pai_codigo", nullable = false)
	public Integer getPaiCodigo() {
		return this.paiCodigo;
	}

	public void setPaiCodigo(Integer paiCodigo) {
		this.paiCodigo = paiCodigo;
	}

	@Column(name = "dpt_codigo", nullable = false)
	public Integer getDptCodigo() {
		return this.dptCodigo;
	}

	public void setDptCodigo(Integer dptCodigo) {
		this.dptCodigo = dptCodigo;
	}

	@Column(name = "ciu_codigo", nullable = false)
	public Integer getCiuCodigo() {
		return this.ciuCodigo;
	}

	public void setCiuCodigo(Integer ciuCodigo) {
		this.ciuCodigo = ciuCodigo;
	}

}
