package py.com.excelsis.sicca.entity;

// Generated 14/10/2011 09:15:23 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SinPro generated by hbm2java
 */
@Entity
@Table(name = "sin_pro", schema = "sinarh")
public class SinPro implements java.io.Serializable {

	private Integer idPro;
	private Integer aniAniopre;
	private Integer nenCodigo;
	private Integer entCodigo;
	private Integer tipCodigo;
	private Integer proCodigo;
	private String funCodigo;
	private String proNombre;
	private String proNomabr;
	private String proDescrip;

	public SinPro() {
	}

	public SinPro(Integer idPro, Integer aniAniopre, Integer nenCodigo, Integer entCodigo,
			Integer tipCodigo, Integer proCodigo, String funCodigo, String proNombre,
			String proNomabr, String proDescrip) {
		this.idPro = idPro;
		this.aniAniopre = aniAniopre;
		this.nenCodigo = nenCodigo;
		this.entCodigo = entCodigo;
		this.tipCodigo = tipCodigo;
		this.proCodigo = proCodigo;
		this.funCodigo = funCodigo;
		this.proNombre = proNombre;
		this.proNomabr = proNomabr;
		this.proDescrip = proDescrip;
	}

	@Id
	@Column(name = "id_pro", unique = true, nullable = false)
	public Integer getIdPro() {
		return this.idPro;
	}

	public void setIdPro(Integer idPro) {
		this.idPro = idPro;
	}

	@Column(name = "ani_aniopre", nullable = false)
	public Integer getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(Integer aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "nen_codigo", nullable = false)
	public Integer getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(Integer nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo", nullable = false)
	public Integer getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Integer entCodigo) {
		this.entCodigo = entCodigo;
	}

	@Column(name = "tip_codigo", nullable = false)
	public Integer getTipCodigo() {
		return this.tipCodigo;
	}

	public void setTipCodigo(Integer tipCodigo) {
		this.tipCodigo = tipCodigo;
	}

	@Column(name = "pro_codigo", nullable = false)
	public Integer getProCodigo() {
		return this.proCodigo;
	}

	public void setProCodigo(Integer proCodigo) {
		this.proCodigo = proCodigo;
	}

	@Column(name = "fun_codigo", nullable = false)
	@NotNull
	public String getFunCodigo() {
		return this.funCodigo;
	}

	public void setFunCodigo(String funCodigo) {
		this.funCodigo = funCodigo;
	}

	@Column(name = "pro_nombre", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getProNombre() {
		return this.proNombre;
	}

	public void setProNombre(String proNombre) {
		this.proNombre = proNombre;
	}

	@Column(name = "pro_nomabr", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getProNomabr() {
		return this.proNomabr;
	}

	public void setProNomabr(String proNomabr) {
		this.proNomabr = proNomabr;
	}

	@Column(name = "pro_descrip", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getProDescrip() {
		return this.proDescrip;
	}

	public void setProDescrip(String proDescrip) {
		this.proDescrip = proDescrip;
	}

}
