package py.com.excelsis.sicca.entity;

// Generated 14/10/2011 09:15:23 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SinSub generated by hbm2java
 */
@Entity
@Table(name = "sin_sub", schema = "sinarh")
public class SinSub implements java.io.Serializable {

	private Integer idSub;
	private Integer aniAniopre;
	private Integer nenCodigo;
	private Integer entCodigo;
	private Integer tipCodigo;
	private Integer proCodigo;
	private Integer subCodigo;
	private String subNombre;
	private String subNomabr;
	private Integer paiCodigo;
	private Integer dptCodigo;
	private Integer ciuCodigo;

	public SinSub() {
	}

	public SinSub(Integer idSub, Integer aniAniopre, Integer nenCodigo, Integer entCodigo,
			Integer tipCodigo, Integer proCodigo, Integer subCodigo, String subNombre,
			String subNomabr, Integer paiCodigo, Integer dptCodigo, Integer ciuCodigo) {
		this.idSub = idSub;
		this.aniAniopre = aniAniopre;
		this.nenCodigo = nenCodigo;
		this.entCodigo = entCodigo;
		this.tipCodigo = tipCodigo;
		this.proCodigo = proCodigo;
		this.subCodigo = subCodigo;
		this.subNombre = subNombre;
		this.subNomabr = subNomabr;
		this.paiCodigo = paiCodigo;
		this.dptCodigo = dptCodigo;
		this.ciuCodigo = ciuCodigo;
	}

	@Id
	@Column(name = "id_sub", unique = true, nullable = false)
	public Integer getIdSub() {
		return this.idSub;
	}

	public void setIdSub(Integer idSub) {
		this.idSub = idSub;
	}

	@Column(name = "ani_aniopre", nullable = false)
	public Integer getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(Integer aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "nen_codigo", nullable = false)
	public Integer getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(Integer nenCodigo) {
		this.nenCodigo = nenCodigo;
	}

	@Column(name = "ent_codigo", nullable = false)
	public Integer getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Integer entCodigo) {
		this.entCodigo = entCodigo;
	}

	@Column(name = "tip_codigo", nullable = false)
	public Integer getTipCodigo() {
		return this.tipCodigo;
	}

	public void setTipCodigo(Integer tipCodigo) {
		this.tipCodigo = tipCodigo;
	}

	@Column(name = "pro_codigo", nullable = false)
	public Integer getProCodigo() {
		return this.proCodigo;
	}

	public void setProCodigo(Integer proCodigo) {
		this.proCodigo = proCodigo;
	}

	@Column(name = "sub_codigo", nullable = false)
	public Integer getSubCodigo() {
		return this.subCodigo;
	}

	public void setSubCodigo(Integer subCodigo) {
		this.subCodigo = subCodigo;
	}

	@Column(name = "sub_nombre", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getSubNombre() {
		return this.subNombre;
	}

	public void setSubNombre(String subNombre) {
		this.subNombre = subNombre;
	}

	@Column(name = "sub_nomabr", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getSubNomabr() {
		return this.subNomabr;
	}

	public void setSubNomabr(String subNomabr) {
		this.subNomabr = subNomabr;
	}

	@Column(name = "pai_codigo", nullable = false)
	public Integer getPaiCodigo() {
		return this.paiCodigo;
	}

	public void setPaiCodigo(Integer paiCodigo) {
		this.paiCodigo = paiCodigo;
	}

	@Column(name = "dpt_codigo", nullable = false)
	public Integer getDptCodigo() {
		return this.dptCodigo;
	}

	public void setDptCodigo(Integer dptCodigo) {
		this.dptCodigo = dptCodigo;
	}

	@Column(name = "ciu_codigo", nullable = false)
	public Integer getCiuCodigo() {
		return this.ciuCodigo;
	}

	public void setCiuCodigo(Integer ciuCodigo) {
		this.ciuCodigo = ciuCodigo;
	}

}
