package py.com.excelsis.sicca.entity;

// Generated 05-nov-2012 16:44:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.print.Doc;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SolicitudTrasladoCab generated by hbm2java
 */
@Entity
@Table(name = "solicitud_traslado_cab", schema = "movilidad")
public class SolicitudTrasladoCab implements java.io.Serializable {

	private Long idSolicitudTrasladoCab;
	private ConfiguracionUoCab oeeDestino;
	private ConfiguracionUoCab oeeOrigen;
	private DatosEspecificos datosEspEstadoSolicitud;
	private boolean activo;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private Documentos documentoDestino;
	private Documentos documentoOrigen;
	private Documentos documentoSfp;
	private Persona persona;
	private DatosEspecificos datosEspTipoTranslado;
	private String respuestaSFP;
	private Long idProcessInstance;
	private String respuestaOeeOrigen;
	private EmpleadoPuesto empleadoPuesto;
	private PlantaCargoDet plantaCargoDet;
	private String valorObj;
	private String categoria;
	private Long monto;
	private String linea;
	private String descripcion;
	private Integer codObjeto;
	private String codCategoria;
	
	private Set<SolicitudTrasladoDet> solicitudTrasladoDets = new HashSet<SolicitudTrasladoDet>(
			0);

	public SolicitudTrasladoCab() {
	}

	public SolicitudTrasladoCab(Long idSolicitudTrasladoCab, ConfiguracionUoCab oeeDestino,
			ConfiguracionUoCab oeeOrigen, DatosEspecificos datosEspEstadoSolicitud, boolean activo,
			String usuAlta, Date fechaAlta, Persona persona) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
		this.oeeDestino = oeeDestino;
		this.oeeOrigen = oeeOrigen;
		this.datosEspEstadoSolicitud = datosEspEstadoSolicitud;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.persona = persona;
	}

	public SolicitudTrasladoCab(Long idSolicitudTrasladoCab, ConfiguracionUoCab oeeDestino,
			ConfiguracionUoCab oeeOrigen, DatosEspecificos datosEspEstadoSolicitud, boolean activo,
			String usuAlta, String usuMod, Date fechaMod, Date fechaAlta,
			Documentos documentoDestino, Documentos documentoOrigen,
			Documentos documentoSfp, Persona persona,
			Set<SolicitudTrasladoDet> solicitudTrasladoDets, PlantaCargoDet plantaCargoDet,
			String valorObj, String categoria, Long monto, String linea, String descripcion, 
			Integer codObjeto, String codCategoria) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
		this.oeeDestino = oeeDestino;
		this.oeeOrigen = oeeOrigen;
		this.datosEspEstadoSolicitud = datosEspEstadoSolicitud;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.fechaAlta = fechaAlta;
		this.documentoDestino = documentoDestino;
		this.documentoOrigen = documentoOrigen;
		this.documentoSfp = documentoSfp;
		this.persona = persona;
		this.solicitudTrasladoDets = solicitudTrasladoDets;
		this.plantaCargoDet = plantaCargoDet;
		this.valorObj = valorObj;
		this.categoria = categoria;
		this.monto = monto;
		this.linea = linea;
		this.descripcion = descripcion;
		this.codObjeto = codObjeto;
		this.codCategoria = codCategoria;
	}

	@Id
	@GeneratedValue(generator = "SOLICITUD_TRANSLADO_CAB_GENERATOR")
	@SequenceGenerator(name = "SOLICITUD_TRANSLADO_CAB_GENERATOR", sequenceName = "movilidad.solicitud_traslado_cab_id_solicitud_traslado_cab_seq")
	@Column(name = "id_solicitud_traslado_cab", unique = true, nullable = false)
	public Long getIdSolicitudTrasladoCab() {
		return this.idSolicitudTrasladoCab;
	}

	public void setIdSolicitudTrasladoCab(Long idSolicitudTrasladoCab) {
		this.idSolicitudTrasladoCab = idSolicitudTrasladoCab;
	}


	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oee_destino")
	public ConfiguracionUoCab getOeeDestino() {
		return oeeDestino;
	}

	public void setOeeDestino(ConfiguracionUoCab oeeDestino) {
		this.oeeDestino = oeeDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oee_origen")
	public ConfiguracionUoCab getOeeOrigen() {
		return oeeOrigen;
	}

	public void setOeeOrigen(ConfiguracionUoCab oeeOrigen) {
		this.oeeOrigen = oeeOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_estado_solicitud")
	public DatosEspecificos getDatosEspEstadoSolicitud() {
		return datosEspEstadoSolicitud;
	}

	public void setDatosEspEstadoSolicitud(DatosEspecificos datosEspEstadoSolicitud) {
		this.datosEspEstadoSolicitud = datosEspEstadoSolicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento_destino")
	public Documentos getDocumentoDestino() {
		return documentoDestino;
	}

	public void setDocumentoDestino(Documentos documentoDestino) {
		this.documentoDestino = documentoDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento_origen")
	public Documentos getDocumentoOrigen() {
		return documentoOrigen;
	}

	public void setDocumentoOrigen(Documentos documentoOrigen) {
		this.documentoOrigen = documentoOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento_sfp")
	public Documentos getDocumentoSfp() {
		return documentoSfp;
	}

	public void setDocumentoSfp(Documentos documentoSfp) {
		this.documentoSfp = documentoSfp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_tipo_traslado")
	public DatosEspecificos getDatosEspTipoTranslado() {
		return datosEspTipoTranslado;
	}

	public void setDatosEspTipoTranslado(DatosEspecificos datosEspTipoTranslado) {
		this.datosEspTipoTranslado = datosEspTipoTranslado;
	}

	
	@Column(name = "respuesta_sfp", length = 15)
	@Length(max = 15)
	public String getRespuestaSFP() {
		return respuestaSFP;
	}

	public void setRespuestaSFP(String respuestaSFP) {
		this.respuestaSFP = respuestaSFP;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudTrasladoCab")
	public Set<SolicitudTrasladoDet> getSolicitudTrasladoDets() {
		return this.solicitudTrasladoDets;
	}

	public void setSolicitudTrasladoDets(
			Set<SolicitudTrasladoDet> solicitudTrasladoDets) {
		this.solicitudTrasladoDets = solicitudTrasladoDets;
	}
	
	@Column(name = "id_process_instance")
	public Long getIdProcessInstance() {
		return idProcessInstance;
	}

	public void setIdProcessInstance(Long idProcessInstance) {
		this.idProcessInstance = idProcessInstance;
	}

	@Column(name = "respuesta_oee_origen")
	public String getRespuestaOeeOrigen() {
		return respuestaOeeOrigen;
	}

	public void setRespuestaOeeOrigen(String respuestaOeeOrigen) {
		this.respuestaOeeOrigen = respuestaOeeOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto")
	public EmpleadoPuesto getEmpleadoPuesto() {
		return empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_planta_cargo_det")
	public PlantaCargoDet getPlantaCargoDet() {
		return plantaCargoDet;
	}

	public void setPlantaCargoDet(PlantaCargoDet plantaCargoDet) {
		this.plantaCargoDet = plantaCargoDet;
	}
	
	@Column(name = "valor_obj", length = 200)
	@Length(max = 200)
	public String getValorObj() {
		return valorObj;
	}

	public void setValorObj(String valorObj) {
		this.valorObj = valorObj;
	}
	
	@Column(name = "categoria", length = 10)
	@Length(max = 10)
	public String getCategoria() {
		return categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
	
	@Column(name = "monto")
	public Long getMonto() {
		return monto;
	}

	public void setMonto(Long monto) {
		this.monto = monto;
	}
	
	@Column(name = "linea")
	public String getLinea() {
		return linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}
	
	@Column(name = "descripcion")
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "cod_obj")
	public Integer getCodObjeto() {
		return codObjeto;
	}

	public void setCodObjeto(Integer codObjeto) {
		this.codObjeto = codObjeto;
	}
	
	@Column(name = "cod_categ")
	public String getCodCategoria() {
		return codCategoria;
	}

	public void setCodCategoria(String codCategoria) {
		this.codCategoria = codCategoria;
	}

}
