package py.com.excelsis.sicca.entity;

// Generated 12-dic-2011 17:04:12 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SolicProrrogaDet generated by hbm2java
 */
@Entity
@Table(name = "solic_prorroga_det", schema = "seleccion")
public class SolicProrrogaDet implements java.io.Serializable {

	private Long idSolicDet;
	private SolicProrrogaCab solicProrrogaCab;
	private Integer nro;
	private String observacion;
	private String usuObs;
	private Date fechaObs;
	private Boolean aceptaSfp;
	private String respuesta;
	private Boolean enviadoSfp;
	private String usuRpta;
	private Date fechaRpta;
	private String usuAlta;
	private Boolean activo;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public SolicProrrogaDet() {
	}

	@Id
	@GeneratedValue(generator="solic_prorroga_det")
	@SequenceGenerator(name="solic_prorroga_det",sequenceName="seleccion.solic_prorroga_det_id_solic_det_seq")
	@Column(name = "id_solic_det", unique = true, nullable = false)
	public Long getIdSolicDet() {
		return this.idSolicDet;
	}

	public void setIdSolicDet(Long idSolicDet) {
		this.idSolicDet = idSolicDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_solic_cab", nullable = false)
	@NotNull
	public SolicProrrogaCab getSolicProrrogaCab() {
		return this.solicProrrogaCab;
	}

	public void setSolicProrrogaCab(SolicProrrogaCab solicProrrogaCab) {
		this.solicProrrogaCab = solicProrrogaCab;
	}

	@Column(name = "nro")
	public Integer getNro() {
		return this.nro;
	}

	public void setNro(Integer nro) {
		this.nro = nro;
	}

	@Column(name = "observacion", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "usu_obs", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuObs() {
		return this.usuObs;
	}

	public void setUsuObs(String usuObs) {
		this.usuObs = usuObs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_obs", nullable = false, length = 29)
	@NotNull
	public Date getFechaObs() {
		return this.fechaObs;
	}

	public void setFechaObs(Date fechaObs) {
		this.fechaObs = fechaObs;
	}

	@Column(name = "acepta_sfp")
	public Boolean getAceptaSfp() {
		return this.aceptaSfp;
	}

	public void setAceptaSfp(Boolean aceptaSfp) {
		this.aceptaSfp = aceptaSfp;
	}

	@Column(name = "respuesta", length = 1000)
	@Length(max = 1000)
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Column(name = "enviado_sfp")
	public Boolean getEnviadoSfp() {
		return this.enviadoSfp;
	}

	public void setEnviadoSfp(Boolean enviadoSfp) {
		this.enviadoSfp = enviadoSfp;
	}

	@Column(name = "usu_rpta", length = 50)
	@Length(max = 50)
	public String getUsuRpta() {
		return this.usuRpta;
	}

	public void setUsuRpta(String usuRpta) {
		this.usuRpta = usuRpta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_rpta", length = 29)
	public Date getFechaRpta() {
		return this.fechaRpta;
	}

	public void setFechaRpta(Date fechaRpta) {
		this.fechaRpta = fechaRpta;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Column(name = "activo", nullable = false)
	public Boolean isActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
