package py.com.excelsis.sicca.entity;

// Generated 05-nov-2012 16:44:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SolicitudTrasladoDet generated by hbm2java
 */
@Entity
@Table(name = "solicitud_traslado_det", schema = "movilidad")
public class SolicitudTrasladoDet implements java.io.Serializable {

	private Long idSolicitudTrasladoDet;
	private SolicitudTrasladoCab solicitudTrasladoCab;
	private DatosEspecificos datosEspEstadoSolicitud;
	private String observacion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public SolicitudTrasladoDet() {
	}

	public SolicitudTrasladoDet(Long idSolicitudTrasladoDet,
			SolicitudTrasladoCab solicitudTrasladoCab,
			DatosEspecificos datosEspEstadoSolicitud, boolean activo, String usuAlta,
			Date fechaAlta) {
		this.idSolicitudTrasladoDet = idSolicitudTrasladoDet;
		this.solicitudTrasladoCab = solicitudTrasladoCab;
		this.datosEspEstadoSolicitud = datosEspEstadoSolicitud;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public SolicitudTrasladoDet(Long idSolicitudTrasladoDet,
			SolicitudTrasladoCab solicitudTrasladoCab,
			DatosEspecificos datosEspEstadoSolicitud, String observacion, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idSolicitudTrasladoDet = idSolicitudTrasladoDet;
		this.solicitudTrasladoCab = solicitudTrasladoCab;
		this.datosEspEstadoSolicitud = datosEspEstadoSolicitud;
		this.observacion = observacion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator = "SOLICITUD_TRANSLADO_DET_GENERATOR")
	@SequenceGenerator(name = "SOLICITUD_TRANSLADO_DET_GENERATOR", sequenceName = "movilidad.solicitud_traslado_det_id_solicitud_traslado_det_seq")
	@Column(name = "id_solicitud_traslado_det", unique = true, nullable = false)
	public Long getIdSolicitudTrasladoDet() {
		return this.idSolicitudTrasladoDet;
	}

	public void setIdSolicitudTrasladoDet(Long idSolicitudTrasladoDet) {
		this.idSolicitudTrasladoDet = idSolicitudTrasladoDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_solicitud_traslado_cab", nullable = false)
	@NotNull
	public SolicitudTrasladoCab getSolicitudTrasladoCab() {
		return this.solicitudTrasladoCab;
	}

	public void setSolicitudTrasladoCab(
			SolicitudTrasladoCab solicitudTrasladoCab) {
		this.solicitudTrasladoCab = solicitudTrasladoCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_esp_estado_solicitud")
	public DatosEspecificos getDatosEspEstadoSolicitud() {
		return datosEspEstadoSolicitud;
	}

	public void setDatosEspEstadoSolicitud(DatosEspecificos datosEspEstadoSolicitud) {
		this.datosEspEstadoSolicitud = datosEspEstadoSolicitud;
	}


	@Column(name = "observacion", length = 500)
	@Length(max = 500)
	public String getObservacion() {
		return this.observacion;
	}
	
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
