package py.com.excelsis.sicca.entity;

// Generated 12-sep-2012 9:08:43 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Sujetos generated by hbm2java
 */
@Entity
@Table(name = "sujetos", schema = "eval_desempeno")
public class Sujetos implements java.io.Serializable {

	private Long idSujetos;
	private EvaluacionDesempeno evaluacionDesempeno;
	private EmpleadoPuesto empleadoPuesto;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private boolean selecciono;
	private String motivoInactivacion;
	private Set<GruposSujetos> gruposSujetoses = new HashSet<GruposSujetos>(0);

	public Sujetos() {
	}

	public Sujetos(
			Long idSujetos, EvaluacionDesempeno evaluacionDesempeno, EmpleadoPuesto empleadoPuesto,
			boolean activo, String usuAlta, Date fechaAlta) {
		this.idSujetos = idSujetos;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.empleadoPuesto = empleadoPuesto;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public Sujetos(
			Long idSujetos, EvaluacionDesempeno evaluacionDesempeno, EmpleadoPuesto empleadoPuesto,
			boolean activo, String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<GruposSujetos> gruposSujetoses) {
		this.idSujetos = idSujetos;
		this.evaluacionDesempeno = evaluacionDesempeno;
		this.empleadoPuesto = empleadoPuesto;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.gruposSujetoses = gruposSujetoses;

	}

	@Id
	@GeneratedValue(generator = "SUJETOS_GENERATOR")
	@SequenceGenerator(name = "SUJETOS_GENERATOR", sequenceName = "eval_desempeno.sujetos_id_sujetos_seq")
	@Column(name = "id_sujetos", unique = true, nullable = false)
	public Long getIdSujetos() {
		return this.idSujetos;
	}

	public void setIdSujetos(Long idSujetos) {
		this.idSujetos = idSujetos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_evaluacion_desempeno", nullable = false)
	@NotNull
	public EvaluacionDesempeno getEvaluacionDesempeno() {
		return this.evaluacionDesempeno;
	}

	public void setEvaluacionDesempeno(EvaluacionDesempeno evaluacionDesempeno) {
		this.evaluacionDesempeno = evaluacionDesempeno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto")
	public EmpleadoPuesto getEmpleadoPuesto() {
		return empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sujetos")
	public Set<GruposSujetos> getGruposSujetoses() {
		return this.gruposSujetoses;
	}

	public void setGruposSujetoses(Set<GruposSujetos> gruposSujetoses) {
		this.gruposSujetoses = gruposSujetoses;
	}

	@Transient
	public boolean isSelecciono() {
		return selecciono;
	}

	public void setSelecciono(boolean selecciono) {
		this.selecciono = selecciono;
	}

	@Column(name = "motivo_inactivacion", length = 250)
	@Length(max = 250)
	public String getMotivoInactivacion() {
		return motivoInactivacion;
	}

	public void setMotivoInactivacion(String motivoBaja) {
		this.motivoInactivacion = motivoBaja;
	}

}
