package py.com.excelsis.sicca.entity;

// Generated 27-feb-2012 15:54:08 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.Min;
import org.hibernate.validator.NotNull;

/**
 * SumarioCab generated by hbm2java
 */
@Entity
@Table(name = "sumario_cab", schema = "juridicos")
public class SumarioCab implements java.io.Serializable {

	private Long idSumarioCab;
	private EmpleadoPuesto empleadoPuesto;
	private Sancion sancionMai;
	private Sancion sancionJuez;
	private Integer nroExp;
	private Integer anioExp;
	private String estado;
	private String estadoJuez;
	private Integer tiempoJ;
	private String expresadoJ;
	private String obsJ;
	private Integer tiempoM;
	private String expresadoM;
	private String obsM;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Persona persona;
	private ConfiguracionUoCab configuracionUoCab;
	private Date fechaDesde;
	private Inhabilitados inhabilitados;
	private Desvinculacion desvinculacion;
	private Integer nroExpSfp;
	private Integer anioExpSfp;

	private Set<SumarioDet> sumarioDets = new HashSet<SumarioDet>(0);

	public SumarioCab() {
	}

	
	@Id
	@Column(name = "id_sumario_cab", unique = true, nullable = false)
	@GeneratedValue(generator="SUMARIO_CAB_GENERATOR")
	@SequenceGenerator(name="SUMARIO_CAB_GENERATOR",sequenceName="juridicos.sumario_cab_id_sumario_cab_seq")
	public Long getIdSumarioCab() {
		return this.idSumarioCab;
	}

	public void setIdSumarioCab(Long idSumarioCab) {
		this.idSumarioCab = idSumarioCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empleado_puesto", nullable = false)
	@NotNull
	public EmpleadoPuesto getEmpleadoPuesto() {
		return this.empleadoPuesto;
	}

	public void setEmpleadoPuesto(EmpleadoPuesto empleadoPuesto) {
		this.empleadoPuesto = empleadoPuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sancion_m")
	public Sancion getSancionMai() {
		return this.sancionMai;
	}

	public void setSancionMai(Sancion sancionMai) {
		this.sancionMai = sancionMai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sancion_j")
	public Sancion getSancionJuez() {
		return this.sancionJuez;
	}

	public void setSancionJuez(Sancion sancionJuez) {
		this.sancionJuez = sancionJuez;
	}

	@Column(name = "nro_exp", nullable = false)
	public Integer getNroExp() {
		return this.nroExp;
	}

	public void setNroExp(Integer nroExp) {
		this.nroExp = nroExp;
	}

	@Column(name = "anio_exp", nullable = false)
	public Integer getAnioExp() {
		return this.anioExp;
	}

	public void setAnioExp(Integer anioExp) {
		this.anioExp = anioExp;
	}

	@Column(name = "estado", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "estado_juez", length = 2)
	@Length(max = 2)
	public String getEstadoJuez() {
		return this.estadoJuez;
	}

	public void setEstadoJuez(String estadoJuez) {
		this.estadoJuez = estadoJuez;
	}

	@Column(name = "tiempo_j")
	public Integer getTiempoJ() {
		return this.tiempoJ;
	}

	public void setTiempoJ(Integer tiempoJ) {
		this.tiempoJ = tiempoJ;
	}

	@Column(name = "expresado_j", length = 1)
	@Length(max = 1)
	public String getExpresadoJ() {
		return this.expresadoJ;
	}

	public void setExpresadoJ(String expresadoJ) {
		this.expresadoJ = expresadoJ;
	}

	@Column(name = "obs_j", length = 500)
	@Length(max = 500)
	public String getObsJ() {
		return this.obsJ;
	}

	public void setObsJ(String obsJ) {
		this.obsJ = obsJ;
	}

	@Column(name = "tiempo_m")
	public Integer getTiempoM() {
		return this.tiempoM;
	}

	public void setTiempoM(Integer tiempoM) {
		this.tiempoM = tiempoM;
	}

	@Column(name = "expresado_m", length = 1)
	@Length(max = 1)
	public String getExpresadoM() {
		return this.expresadoM;
	}

	public void setExpresadoM(String expresadoM) {
		this.expresadoM = expresadoM;
	}

	@Column(name = "obs_m", length = 500)
	@Length(max = 500)
	public String getObsM() {
		return this.obsM;
	}

	public void setObsM(String obsM) {
		this.obsM = obsM;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return persona;
	}


	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_configuracion_uo")
	public ConfiguracionUoCab getConfiguracionUoCab() {
		return configuracionUoCab;
	}


	public void setConfiguracionUoCab(ConfiguracionUoCab configuracionUoCab) {
		this.configuracionUoCab = configuracionUoCab;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_desde", length = 29)
	public Date getFechaDesde() {
		return fechaDesde;
	}


	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inhabilitado")
	public Inhabilitados getInhabilitados() {
		return inhabilitados;
	}


	public void setInhabilitados(Inhabilitados inhabilitados) {
		this.inhabilitados = inhabilitados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_desvinculacion")
	public Desvinculacion getDesvinculacion() {
		return desvinculacion;
	}


	public void setDesvinculacion(Desvinculacion desvinculacion) {
		this.desvinculacion = desvinculacion;
	}

	@Column(name = "nro_exp_sfp")
	public Integer getNroExpSfp() {
		return nroExpSfp;
	}


	public void setNroExpSfp(Integer nroExpSfp) {
		this.nroExpSfp = nroExpSfp;
	}

	@Column(name = "anio_exp_sfp")
	public Integer getAnioExpSfp() {
		return anioExpSfp;
	}


	public void setAnioExpSfp(Integer anioExpSfp) {
		this.anioExpSfp = anioExpSfp;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sumarioCab")
	public Set<SumarioDet> getSumarioDets() {
		return this.sumarioDets;
	}

	public void setSumarioDets(Set<SumarioDet> sumarioDets) {
		this.sumarioDets = sumarioDets;
	}

}
