package py.com.excelsis.sicca.entity;

// Generated 11-nov-2011 15:32:40 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.hibernate.validator.Pattern;

/**
 * DatosGrupoPuesto generated by hbm2java
 */
@Entity
@Table(name = "tachas_reclamos_modificaciones", schema = "seleccion")
public class TachasReclamosModificaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2231945453601930035L;
	private Long idTachasReclamosModificaciones;
	private Date fechaTrm;
	private EvalDocumentalCab evalDocumentalCab;
	private Boolean modificaEvalDocumental;
	private Boolean modificaEvaluaciones;
	private Documentos documentoPostulante;
	private Documentos documentoComision;
	private String observacion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	

	public TachasReclamosModificaciones() {
	}
	
	
	@Id
	@Column(name = "id_tachas_reclamos_modificaciones", unique = true, nullable = false)
	@GeneratedValue(generator="id_tachas_reclamos_modificaciones")
	@SequenceGenerator(name="id_tachas_reclamos_modificaciones", sequenceName="seleccion.tachas_reclamos_modificacione_id_tachas_reclamos_modificaci_seq")
	public Long getIdTachasReclamosModificaciones() {
		return this.idTachasReclamosModificaciones;
	}

	public void setIdTachasReclamosModificaciones(Long idTachasReclamosModificaciones) {
		this.idTachasReclamosModificaciones = idTachasReclamosModificaciones;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_trm", nullable = false, length = 29)
	@NotNull
	public Date getFechaTrm() {
		return this.fechaTrm;
	}

	public void setFechaTrm(Date fechaTrm) {
		this.fechaTrm = fechaTrm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_eval_documental_cab")
	public EvalDocumentalCab getEvalDocumentalCab() {
		return this.evalDocumentalCab;
	}

	public void setEvalDocumentalCab(EvalDocumentalCab evalDocumentalCab) {
		this.evalDocumentalCab = evalDocumentalCab;
	}

	@Column(name = "modifica_eval_documental")
	public Boolean getModificaEvalDocumental() {
		return this.modificaEvalDocumental;
	}

	public void setModificaEvalDocumental(Boolean modificaEvalDocumental) {
		this.modificaEvalDocumental = modificaEvalDocumental;
	}
	
	
	@Column(name = "modifica_evaluaciones")
	public Boolean getModificaEvaluaciones() {
		return this.modificaEvaluaciones;
	}

	public void setModificaEvaluaciones(Boolean modificaEvaluaciones) {
		this.modificaEvaluaciones = modificaEvaluaciones;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento_postulante")
	public Documentos getDocumentoPostulante() {
		return this.documentoPostulante;
	}

	public void setDocumentoPostulante(Documentos documentoPostulante) {
		this.documentoPostulante = documentoPostulante;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento_comision")
	public Documentos getDocumentoComision() {
		return this.documentoComision;
	}

	public void setDocumentoComision(Documentos documentoComision) {
		this.documentoComision = documentoComision;
	}
	
	
	@Column(name = "observacion", length = 1000)
	@Length(max = 1000)
	public String getObservacion() {
		return observacion;
	}


	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}


	
	
	
	

}
