package py.com.excelsis.sicca.entity;

// Generated 14/11/2011 04:49:57 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", schema = "seleccion")
public class Tags implements java.io.Serializable {

	private long idTag;
	private String tag;
	private String descripcion;
	private String consulta;

	public Tags() {
	}

	public Tags(long idTag, String tag, String descripcion) {
		this.idTag = idTag;
		this.tag = tag;
		this.descripcion = descripcion;
	}

	public Tags(long idTag, String tag, String descripcion, String consulta) {
		this.idTag = idTag;
		this.tag = tag;
		this.descripcion = descripcion;
		this.consulta = consulta;
	}

	@Id
	@Column(name = "id_tag", unique = true, nullable = false)
	public long getIdTag() {
		return this.idTag;
	}

	public void setIdTag(long idTag) {
		this.idTag = idTag;
	}

	@Column(name = "tag", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "consulta", length = 500)
	@Length(max = 500)
	public String getConsulta() {
		return this.consulta;
	}

	public void setConsulta(String consulta) {
		this.consulta = consulta;
	}

}
