package py.com.excelsis.sicca.entity;

// Generated 21/09/2011 04:12:48 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoCce generated by hbm2java
 */
@Entity
@Table(name = "tipo_cce", schema = "planificacion")
public class TipoCce implements java.io.Serializable {

	private Long idTipoCce;
	private String descripcion;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<AgrupamientoCce> agrupamientoCces = new HashSet<AgrupamientoCce>(
			0);

	public TipoCce() {
	}

	public TipoCce(Long idTipoCce, String descripcion, Boolean activo,
			String usuAlta, Date fechaAlta) {
		this.idTipoCce = idTipoCce;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public TipoCce(Long idTipoCce, String descripcion, Boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod,
			Set<AgrupamientoCce> agrupamientoCces) {
		this.idTipoCce = idTipoCce;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.agrupamientoCces = agrupamientoCces;
	}

	@Id
	@Column(name = "id_tipo_cce", unique = true, nullable = false)
	@GeneratedValue(generator="TIPO_CCE_GENERATOR")
	@SequenceGenerator(name="TIPO_CCE_GENERATOR",sequenceName="planificacion.tipo_cce_id_tipo_cce_seq")
	public Long getIdTipoCce() {
		return this.idTipoCce;
	}

	public void setIdTipoCce(Long idTipoCce) {
		this.idTipoCce = idTipoCce;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCce")
	public Set<AgrupamientoCce> getAgrupamientoCces() {
		return agrupamientoCces;
	}

	public void setAgrupamientoCces(Set<AgrupamientoCce> agrupamientoCces) {
		this.agrupamientoCces = agrupamientoCces;
	}

	
	

}
