package py.com.excelsis.sicca.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import py.com.excelsis.sicca.util.EXCProperties;
import py.com.excelsis.sicca.util.EntityBase;
import py.com.excelsis.sicca.util.SICCASessionParameters;

/**
 * TipoNombramiento generated by Generality
 */
@Entity
@Table(name = "tipo_nombramiento", schema = "planificacion")
public class TipoNombramiento extends EntityBase {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4664220564647921873L;
	private Long idTipoNombramiento;
	private String descripcion;
	private Boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private TipoPlanta tipoPlanta;
	private Boolean seleccionado;
	private Set<DetTipoNombramiento> detTipoNombramientos = new HashSet<DetTipoNombramiento>(0);

	public TipoNombramiento() {
	}

	public TipoNombramiento(Long idTipoNombramiento, TipoPlanta tipoPlanta,
			String descripcion, Boolean activo, String usuAlta, Date fechaAlta) {
		this.idTipoNombramiento = idTipoNombramiento;
		this.tipoPlanta = tipoPlanta;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public TipoNombramiento(Long idTipoNombramiento, TipoPlanta tipoPlanta,
			String descripcion, Boolean activo, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod,
			Set<DetTipoNombramiento> detTipoNombramientos) {
		this.idTipoNombramiento = idTipoNombramiento;
		this.tipoPlanta = tipoPlanta;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
		this.detTipoNombramientos = detTipoNombramientos;
	}

	@Id
	@GeneratedValue(generator="TIPO_NOMBRAMIENTO_GENERATOR")
	@SequenceGenerator(name="TIPO_NOMBRAMIENTO_GENERATOR",sequenceName="planificacion.tipo_nombramiento_id_tipo_nombramiento_seq")

	@Column(name = "id_tipo_nombramiento")
	public Long getIdTipoNombramiento() {
		return this.idTipoNombramiento;
	}

	public void setIdTipoNombramiento(Long idTipoNombramiento) {
		this.idTipoNombramiento = idTipoNombramiento;
	}
	

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_planta")
	public TipoPlanta getTipoPlanta() {
		return this.tipoPlanta;
	}

	public void setTipoPlanta(TipoPlanta tipoPlanta) {
		this.tipoPlanta = tipoPlanta;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoNombramiento")
	public Set<DetTipoNombramiento> getDetTipoNombramientos() {
		return this.detTipoNombramientos;
	}

	public void setDetTipoNombramientos(
			Set<DetTipoNombramiento> detTipoNombramientos) {
		this.detTipoNombramientos = detTipoNombramientos;
	}

	
	
	@Transient
	public Boolean getSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(Boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

	@Transient
	public Long getId() {
		return idTipoNombramiento;
	}

	/**
	 * 
	 * @return properties
	 */
	@Transient
	public Properties getProperties() {
		Properties properties = new EXCProperties();
		properties.put(SICCASessionParameters.TIPO_NOMBRAMIENTO_ID, getId());
		properties.put(SICCASessionParameters.TIPO_NOMBRAMIENTO_DESCRIPCION,
				descripcion);

		return properties;
	}

	/**
	 * 
	 * @param properties
	 */
	public void setProperties(Properties properties) {
		// TODO Auto-generated method stub

	}
}
