package py.com.excelsis.sicca.entity;

// Generated 07/10/2011 09:50:02 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TituloAcademico generated by hbm2java
 */
@Entity
@Table(name = "titulo_academico", schema = "seleccion")
public class TituloAcademico implements java.io.Serializable {

	private Long idTituloAcademico;
	private Especialidades especialidades;
	private NivelEstudio nivelEstudio;
	private String descripcion;
	private boolean activo;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;
	private Set<EstudiosRealizados> estudiosRealizados= new HashSet<EstudiosRealizados>(0);
	private Set<EstudiosRealizadosLegajo> estudiosRealizadosLegajo= new HashSet<EstudiosRealizadosLegajo>(0);

	public TituloAcademico() {
	}

	public TituloAcademico(Long idTituloAcademico, NivelEstudio nivelEstudio,
			String descripcion, boolean activo, String usuAlta, Date fechaAlta) {
		this.idTituloAcademico = idTituloAcademico;
		this.nivelEstudio = nivelEstudio;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public TituloAcademico(long idTituloAcademico, Especialidades especialidad,
			NivelEstudio nivelEstudio, String descripcion, boolean activo,
			String usuAlta, Date fechaAlta, String usuMod, Date fechaMod) {
		this.idTituloAcademico = idTituloAcademico;
		this.especialidades = especialidad;
		this.nivelEstudio = nivelEstudio;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@Column(name = "id_titulo_academico", unique = true, nullable = false)
	@GeneratedValue(generator="TITULO_ACADEMICO_GENERATOR")
	@SequenceGenerator(name="TITULO_ACADEMICO_GENERATOR",sequenceName="seleccion.sel_titulo_academico_id_titulo_academico_seq")

	public Long getIdTituloAcademico() {
		return this.idTituloAcademico;
	}

	public void setIdTituloAcademico(Long idTituloAcademico) {
		this.idTituloAcademico = idTituloAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_especialidad")
	public Especialidades getEspecialidades() {
		return especialidades;
	}

	public void setEspecialidades(Especialidades especialidades) {
		this.especialidades = especialidades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nivel_estudio", nullable = false)
	@NotNull
	public NivelEstudio getNivelEstudio() {
		return this.nivelEstudio;
	}

	

	public void setNivelEstudio(NivelEstudio nivelEstudio) {
		this.nivelEstudio = nivelEstudio;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tituloAcademico")
	public Set<EstudiosRealizados> getEstudiosRealizados() {
		return estudiosRealizados;
	}

	public void setEstudiosRealizados(Set<EstudiosRealizados> estudiosRealizados) {
		this.estudiosRealizados = estudiosRealizados;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tituloAcademico")
	public Set<EstudiosRealizadosLegajo> getEstudiosRealizadosLegajo() {
		return estudiosRealizadosLegajo;
	}

	public void setEstudiosRealizadosLegajo(Set<EstudiosRealizadosLegajo> estudiosRealizadosLegajo) {
		this.estudiosRealizadosLegajo = estudiosRealizadosLegajo;
	}

	
	
	

}
