package py.com.excelsis.sicca.entity;

// Generated 28/09/2011 11:21:46 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TransicionEstado generated by hbm2java
 */
@Entity
@Table(name = "transicion_estado", schema = "planificacion")
public class TransicionEstado implements java.io.Serializable {

	private Long idTrancisionEstado;
	private EstadoCab estadoCabByIdEstadoCab;
	private EstadoCab estadoCabByPosibleEstado;
	private String usuAlta;
	private Date fechaAlta;
	private String usuMod;
	private Date fechaMod;

	public TransicionEstado() {
	}

	public TransicionEstado(Long idTrancisionEstado,
			EstadoCab estadoCabByIdEstadoCab,
			EstadoCab estadoCabByPosibleEstado, String usuAlta, Date fechaAlta) {
		this.idTrancisionEstado = idTrancisionEstado;
		this.estadoCabByIdEstadoCab = estadoCabByIdEstadoCab;
		this.estadoCabByPosibleEstado = estadoCabByPosibleEstado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
	}

	public TransicionEstado(Long idTrancisionEstado,
			EstadoCab estadoCabByIdEstadoCab,
			EstadoCab estadoCabByPosibleEstado, String usuAlta, Date fechaAlta,
			String usuMod, Date fechaMod) {
		this.idTrancisionEstado = idTrancisionEstado;
		this.estadoCabByIdEstadoCab = estadoCabByIdEstadoCab;
		this.estadoCabByPosibleEstado = estadoCabByPosibleEstado;
		this.usuAlta = usuAlta;
		this.fechaAlta = fechaAlta;
		this.usuMod = usuMod;
		this.fechaMod = fechaMod;
	}

	@Id
	@GeneratedValue(generator="TRANSICION_ESTADO_GENERATOR")
	@SequenceGenerator(name="TRANSICION_ESTADO_GENERATOR",sequenceName="planificacion.transicion_estado_id_trancision_estado_seq")
	@Column(name = "id_trancision_estado", unique = true, nullable = false)
	public Long getIdTrancisionEstado() {
		return this.idTrancisionEstado;
	}

	public void setIdTrancisionEstado(Long idTrancisionEstado) {
		this.idTrancisionEstado = idTrancisionEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_cab", nullable = false)
	@NotNull
	public EstadoCab getEstadoCabByIdEstadoCab() {
		return this.estadoCabByIdEstadoCab;
	}

	public void setEstadoCabByIdEstadoCab(EstadoCab estadoCabByIdEstadoCab) {
		this.estadoCabByIdEstadoCab = estadoCabByIdEstadoCab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "posible_estado", nullable = false)
	@NotNull
	public EstadoCab getEstadoCabByPosibleEstado() {
		return this.estadoCabByPosibleEstado;
	}

	public void setEstadoCabByPosibleEstado(EstadoCab estadoCabByPosibleEstado) {
		this.estadoCabByPosibleEstado = estadoCabByPosibleEstado;
	}

	@Column(name = "usu_alta", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 29)
	@NotNull
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "usu_mod", length = 50)
	@Length(max = 50)
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod", length = 29)
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}

}
