package py.com.excelsis.sicca.entity;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * ValorNivelOrg generated by Generality
 */
@Entity
@Table(name = "valor_nivel_org", schema = "planificacion")
public class ValorNivelOrg implements java.io.Serializable {
	private Long idValorNivelOrg;
	private String descripcion;
	private Boolean activo;
	private Integer desde;
	private Integer hasta;
	private String usuAlta;
	private String usuMod;
	private Date fechaMod;
	private Date fechaAlta;
	private ContenidoFuncional contenidoFuncional;


	public ValorNivelOrg() {
	}

	public ValorNivelOrg(Long idValorNivelOrg) {
		this.idValorNivelOrg = idValorNivelOrg;
	}

	@Id
	@GeneratedValue(generator="VALOR_NIVEL_ORG_GENERATOR")
	@SequenceGenerator(name="VALOR_NIVEL_ORG_GENERATOR",sequenceName="planificacion.valor_nivel_org_id_valor_nivel_org_seq")

	@Column(name = "id_valor_nivel_org")
	public Long getIdValorNivelOrg() {
		return this.idValorNivelOrg;
	}

	public void setIdValorNivelOrg(Long idValorNivelOrg) {
		this.idValorNivelOrg = idValorNivelOrg;
	}
	

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
	

	@Column(name = "desde")
	public Integer getDesde() {
		return this.desde;
	}

	public void setDesde(Integer desde) {
		this.desde = desde;
	}
	

	@Column(name = "hasta")
	public Integer getHasta() {
		return this.hasta;
	}

	public void setHasta(Integer hasta) {
		this.hasta = hasta;
	}
	

	@Column(name = "usu_alta")
	public String getUsuAlta() {
		return this.usuAlta;
	}

	public void setUsuAlta(String usuAlta) {
		this.usuAlta = usuAlta;
	}
	

	@Column(name = "usu_mod")
	public String getUsuMod() {
		return this.usuMod;
	}

	public void setUsuMod(String usuMod) {
		this.usuMod = usuMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_mod")
	public Date getFechaMod() {
		return this.fechaMod;
	}

	public void setFechaMod(Date fechaMod) {
		this.fechaMod = fechaMod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta")
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contenido_funcional")
	public ContenidoFuncional getContenidoFuncional() {
		return this.contenidoFuncional;
	}

	public void setContenidoFuncional(ContenidoFuncional contenidoFuncional) {
		this.contenidoFuncional = contenidoFuncional;
	}
	
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idValorNivelOrg == null) ? 0 : idValorNivelOrg.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ValorNivelOrg other = (ValorNivelOrg) obj;
		if (idValorNivelOrg == null) {
			if (other.idValorNivelOrg != null)
				return false;
		} else if (!idValorNivelOrg.equals(other.idValorNivelOrg))
			return false;
		return true;
	}
}
