package py.com.excelsis.sicca.entity;

// Generated 02/05/2012 10:03:12 AM by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * VwListaElegible generated by hbm2java
 */
@Entity
@Table(name = "vw_lista_elegible", schema = "seleccion")
public class VwListaElegible implements java.io.Serializable {

	private Long idGrupo;
	private String concurso;
	private String grupo;
	private String field;
	private String estado;
	private Date vencimiento;
	private String oee;
	private BigDecimal nenCodigo;
	private BigDecimal entCodigo;
	private BigDecimal aniAniopre;
	private Long idConfiguracionUoCab;

	public VwListaElegible() {
	}

	public VwListaElegible(String nombre, String grupo, String estado,
			Date fechaVenc, Long idGrupo, String denominacion) {
		this.concurso = nombre;
		this.grupo = grupo;
		this.estado = estado;
		this.vencimiento = fechaVenc;
		this.idGrupo = idGrupo;
		this.oee = denominacion;
	}
	@Column(name = "concurso", length = 100)
	@Length(max = 100)
	public String getConcurso() {
		return concurso;
	}

	public void setConcurso(String concurso) {
		this.concurso = concurso;
	}

	
	@Column(name = "grupo", length = 100)
	@Length(max = 100)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	
	@Column(name = "field")
	public String getField() {
		return field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "estado", length = 60)
	@Length(max = 60)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "vencimiento", length = 29)
	public Date getVencimiento() {
		return vencimiento;
	}

	public void setVencimiento(Date vencimiento) {
		this.vencimiento = vencimiento;
	}

	

	@Id
	@Column(name = "id_concurso_puesto_agr")
	public Long getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(Long idGrupo) {
		this.idGrupo = idGrupo;
	}
	
	@Column(name = "oee", length = 100)
	@Length(max = 100)
	public String getOee() {
		return oee;
	}

	public void setOee(String oee) {
		this.oee = oee;
	}

	
	


	@Column(name = "nen_codigo")
	public BigDecimal getNenCodigo() {
		return this.nenCodigo;
	}

	public void setNenCodigo(BigDecimal nenCodigo) {
		this.nenCodigo = nenCodigo;
	}
	

	@Column(name = "ent_codigo")
	public BigDecimal getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(BigDecimal entCodigo) {
		this.entCodigo = entCodigo;
	}
	@Column(name = "ani_aniopre")
	public BigDecimal getAniAniopre() {
		return this.aniAniopre;
	}

	public void setAniAniopre(BigDecimal aniAniopre) {
		this.aniAniopre = aniAniopre;
	}

	@Column(name = "id_Oee")
	public Long getIdConfiguracionUoCab() {
		return idConfiguracionUoCab;
	}

	public void setIdConfiguracionUoCab(Long idConfiguracionUoCab) {
		this.idConfiguracionUoCab = idConfiguracionUoCab;
	}
	
	

}
